### ISSUE TITLE
TimeoutException when accessing AsyncCacheApi and then blocking on the resulting CompletableFuture

### ISSUE THREAD

**Issue by austinfunraise** [playframework/playframework#10088]
### Play Version

2.8.0

### API

Java

### Operating System

macOS Mojave 10.14.3

### JDK

java version "1.8.0_202-ea"
Java(TM) SE Runtime Environment (build 1.8.0_202-ea-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b03, mixed mode)

### Library Dependencies

n/a

### Expected Behavior

1. Client makes request to controller method that accesses an AsyncCacheApi and blocks on the response
2. Client receives response with value of entry in cache

### Actual Behavior

1. Client receives HTTP 500 in 5 seconds (configured timeout for blocking call)
2. Server displays stack trace
```
! @7f16a125j - Internal server error, for (GET) [/cache/blockingAsync/get/sample_key] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: Could not get value from cache]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:344)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:263)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:443)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:441)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Could not get value from cache
	at controllers.CacheController.blocking(CacheController.java:87)
	at controllers.CacheController.getBlockingAsyncEntry(CacheController.java:56)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$12(Routes.scala:196)
	at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:139)
	at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:138)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:112)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:128)
	at play.mvc.Action.lambda$call$0(Action.java:89)
	at java.util.Optional.map(Optional.java:215)
	at play.mvc.Action.call(Action.java:81)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:33)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:188)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:661)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:77)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:69)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
	at scala.concurrent.impl.Promise$DefaultPromise.map(Promise.scala:146)
	at scala.concurrent.Future$.apply(Future.scala:661)
	at play.core.j.JavaAction.apply(JavaAction.scala:189)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:95)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:181)
	at scala.util.Try$.apply(Try.scala:210)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:181)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:216)
	at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:436)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
	... 11 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at controllers.CacheController.blocking(CacheController.java:81)
	... 45 common frames omitted
```

### Reproducible Test Case

Reproducible at: https://github.com/austinfunraise/sample-play-cache-timeout-error
See specifically: https://github.com/austinfunraise/sample-play-cache-timeout-error/blob/master/app/controllers/CacheController.java#L42

Based on my investigation it seems related to `akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)`

Note that the tests are passing in my sample project, I assume because the tests use a different underlying executor than the app running for real.

To reproduce the issue:
* start the app - `sbt run` 
* In a new shell tab, run the test script - `./test_caches.sh`
* Observe the results. All 4 endpoints **should** return immediately with a status code of 200, but 2/4 actually take 5 seconds and then return an HTTP 500 since the server times out

**Comment by mkurz** [comment]
@austinfunraise I am unable to reproduce the issue you described with the [test project you provided](https://github.com/austinfunraise/sample-play-cache-timeout-error), using following steps:

> To reproduce the issue:
> 
> * start the app - `sbt run`
> * In a new shell tab, run the test script - `./test_caches.sh`
> * Observe the results. All 4 endpoints **should** return immediately with a status code of 200, but 2/4 actually take 5 seconds and then return an HTTP 500 since the server times out

The only difference to your setup: I am using `openjdk version "1.8.0_282"` and Ubuntu 18.04 instead of macOS.

I tried several times, each time everything looks OK:

```
$ ./test_caches.sh 
Testing endpoint: /cache/sync/get/sample_key
status code is 200

real	0m0,018s
user	0m0,007s
sys	0m0,000s

Testing endpoint: /cache/async/get/sample_key
status code is 200

real	0m0,020s
user	0m0,009s
sys	0m0,000s

Testing endpoint: /cache/asyncCompletableFuture/get/sample_key
status code is 200

real	0m0,019s
user	0m0,005s
sys	0m0,003s

Testing endpoint: /cache/asyncBlocking/get/sample_key
status code is 200

real	0m0,018s
user	0m0,007s
sys	0m0,000s
```
