### ISSUE TITLE
Failed: Java doc generation failure on nightly-deploy-2.8.x

### ISSUE THREAD

**Issue by seglo** [playframework/playframework#10111]
```
[info] Play 2.8.1-2020-03-04-b77889c-SNAPSHOT Scala API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1-2020-03-04-b77889c-SNAPSHOT/play-docs_2.12-2.8.1-2020-03-04-b77889c-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1-2020-03-04-b77889c-SNAPSHOT/play-docs_2.12-2.8.1-2020-03-04-b77889c-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1-2020-03-04-b77889c-SNAPSHOT/play-docs_2.12-2.8.1-2020-03-04-b77889c-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1-2020-03-04-b77889c-SNAPSHOT/play-docs_2.12-2.8.1-2020-03-04-b77889c-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1643)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1643)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Play-Exceptions / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 173 s (02:53), completed Mar 5, 2020 4:44:53 AM
```

**Comment by raboof** [comment]
saw it again at Sat, Aug 29

**Comment by raboof** [comment]
```
The full logs for this task have been saved and can be found in /home/play/logs/nightly-deploy-2.8.x-1598672157.log.

The last 100 lines output of this task were:

[warn] /**
[warn] ^
[info] 	published play_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/2.8.2+27-b60beb11-SNAPSHOT/play_2.12-2.8.2+27-b60beb11-SNAPSHOT-playdoc.jar
[info] 	published play_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/2.8.2+27-b60beb11-SNAPSHOT/play_2.12-2.8.2+27-b60beb11-SNAPSHOT-javadoc.jar
[info] 	published play_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.12/2.8.2+27-b60beb11-SNAPSHOT/play_2.12-2.8.2+27-b60beb11-SNAPSHOT-sources.jar
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/http/Writeable.scala:118:3: Could not find any member to link for "TemporaryFile".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/http/HttpErrorHandler.scala:464:3: Could not find any member to link for "Throwable".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/mvc/Session.scala:30:3: Could not find any member to link for "NoSuchElementException".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/mvc/BodyParsers.scala:572:3: Could not find any member to link for "akka.util.ByteString".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/mvc/BodyParsers.scala:563:3: Could not find any member to link for "akka.util.ByteString".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/mvc/Flash.scala:30:3: Could not find any member to link for "NoSuchElementException".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/ActorModule.scala:10:1: Could not find any member to link for "com.google.inject.Provides".
[warn] /**
[warn] ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala:159:3: Could not find any member to link for "Behavior".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala:139:3: Could not find any member to link for "Behavior".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/ActorModule.scala:54:3: Could not find any member to link for "A".
[warn]   /** A convenience to refer to the type of an [[ActorModule]] with the given message type [[A]]. */
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/concurrent/Futures.scala:161:5: Could not find any member to link for "akka.util.Timeout".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/Files.scala:138:5: Could not find any member to link for "java.nio.file.Files.move()".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/Files.scala:115:5: Could not find any member to link for "java.nio.file.Files.move()".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:407:3: Could not find any member to link for "Result".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:432:3: Could not find any member to link for "SameSite".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:402:3: Could not find any member to link for "Result".
[warn]   /**
[warn]   ^
[warn] Could not find any member to link for "SameSite".
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/core/utils/AsciiSet.scala:33:1: Could not find any member to link for "AsciiRange".
[warn] /**
[warn] ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/core/utils/AsciiSet.scala:51:3: Could not find any member to link for "AsciiBitSet".
[warn]   /** Convert into an [[AsciiBitSet]] for fast querying. */
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:116:3: Could not find any member to link for "createAkkaHttpConfig()".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:144:3: Could not find any member to link for "createServerBinding()".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:133:3: Could not find any member to link for "createParserSettings()".
[warn]   /** Play's parser settings for Akka HTTP. Initialized by a call to [[createParserSettings()]]. */
[warn]   ^
[warn] 47 warnings found
[info] Play 2.8.2+27-b60beb11-SNAPSHOT Scala API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+27-b60beb11-SNAPSHOT/play-docs_2.12-2.8.2+27-b60beb11-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+27-b60beb11-SNAPSHOT/play-docs_2.12-2.8.2+27-b60beb11-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+27-b60beb11-SNAPSHOT/play-docs_2.12-2.8.2+27-b60beb11-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.2+27-b60beb11-SNAPSHOT/play-docs_2.12-2.8.2+27-b60beb11-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 164 s (02:44), completed Aug 29, 2020 3:40:42 AM
```

**Comment by raboof** [comment]
Seems like the cause of the error is:

```
[info] Main Java API documentation to /home/play/deploy/playframework/dev-mode/build-link/target/api...
java.lang.AssertionError: duplicate context value
        at com.sun.tools.javac.util.Context.put(Context.java:141)
        at com.sun.tools.javac.util.Context.put(Context.java:197)
        at com.sun.tools.javac.api.BasicJavacTask.<init>(BasicJavacTask.java:70)
        at com.sun.tools.javac.api.BasicJavacTask.instance(BasicJavacTask.java:63)
        at com.sun.tools.javadoc.DocEnv.initDoclint(DocEnv.java:831)
        at com.sun.tools.javadoc.RootDocImpl.initDocLint(RootDocImpl.java:381)
        at com.sun.tools.doclets.formats.html.ConfigurationImpl.setSpecificDocletOptions(ConfigurationImpl.java:312)
        at com.sun.tools.doclets.internal.toolkit.Configuration.setOptions(Configuration.java:560)
        at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.startGeneration(AbstractDoclet.java:134)
        at com.sun.tools.doclets.internal.toolkit.AbstractDoclet.start(AbstractDoclet.java:82)
        at com.sun.tools.doclets.formats.html.HtmlDoclet.start(HtmlDoclet.java:80)
        at com.sun.tools.doclets.standard.Standard.start(Standard.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
        at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
        at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
        at com.sun.tools.javadoc.Start.begin(Start.java:219)
        at com.sun.tools.javadoc.Start.begin(Start.java:205)
        at com.sun.tools.javadoc.Main.execute(Main.java:191)
        at com.sun.tools.javadoc.api.JavadocTool.run(JavadocTool.java:147)
        at sbt.internal.inc.javac.LocalJava$.javadoc(LocalJava.scala:94)
        at sbt.internal.inc.javac.LocalJavadoc.run(LocalJava.scala:142)
        at sbt.inc.Doc$$anon$1.run(Doc.scala:69)
        at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
        at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
        at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
        at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
        at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
        at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
        at sbt.std.Transform$$anon$4.work(Transform.scala:67)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
        at sbt.Execute.work(Execute.scala:290)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[warn] Unexpected javac output: javadoc: error - In doclet class com.sun.tools.doclets.standard.Standard,  method start has thrown an exception java.lang.reflect.InvocationTargetException.
```

Haven't been able to reproduce this locally yet, though.

**Comment by seglo** [comment]
Seen again on `nightly-deploy-master` (vegemite)

```
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ennru** [comment]
And again on nightly-deploy-2.8.x

**Comment by seglo** [comment]
Seen again on `nightly-deploy-2.8.x`

**Comment by seglo** [comment]
Seen again on `nightly-deploy-2.8.x`

**Comment by ignasi35** [comment]
Again in /home/play/logs/nightly-deploy-master-1612929601.log.

**Comment by mkurz** [comment]
Again, vegemite is dead. We will never know what was the problem here.
