### ISSUE TITLE
UnmappableCharacterException instead real exception

### ISSUE THREAD

**Issue by amigossq** [playframework/playframework#10135]
When i try to migrate my project from 2.6.24 to 2.8.1, i found strange bug.

In this example i forgot insert semicolon

```
public class HomeController extends Controller {
     public Result index() {
        return ok(views.html.index.render())
    }
}
```
i get 

`[error] D:\works\projects\tmp\play-samples\play-java-rest-api-example\app\controllers\HomeController.java:14:1: ';' expected`

That's correct message. But if my code contain cyrillic symbol "И" and only it!
```
public class HomeController extends Controller {
     //  My test comment contain cyrillic symbol "И"
     public Result index() {
        return ok(views.html.index.render())
    }
}
```
I receive
```
[error] An input/output error occurred.
[error] Consult the following stack trace for details.
[error] java.nio.charset.UnmappableCharacterException: Input length = 1
[error]         at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
[error]         at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
[error]         at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[error]         at java.io.InputStreamReader.read(InputStreamReader.java:184)
[error]         at java.io.BufferedReader.fill(BufferedReader.java:161)
[error]         at java.io.BufferedReader.readLine(BufferedReader.java:324)
[error]         at java.io.BufferedReader.readLine(BufferedReader.java:389)
[error]         at java.nio.file.Files.readAllLines(Files.java:3205)
[error]         at play.routes.compiler.RoutesCompiler$GeneratedSource$.unapply(RoutesCompiler.scala:42)
[error]         at play.sbt.routes.RoutesCompilerCompat$$anonfun$$nestedInanonfun$routesPositionMapper$1$1.applyOrElse(RoutesCompilerCompat.scala:21)
```

That's useless exception info. 

### Play Version

2.8.1

### Operating System

Win10 x64

### JDK

build 1.8.0_212-b10

**Comment by amigossq** [comment]
I used decision from here https://github.com/playframework/playframework/issues/8449
`-Dfile.encoding=UTF8`
