### ISSUE TITLE
error in sbt run when enable akka  ClusterMetricsExtension in a lib

### ISSUE THREAD

**Issue by thirdteeth** [playframework/playframework#10143]
### Library Dependencies

     "com.typesafe.akka" %% "akka-cluster-metrics" % "2.6.3",
      "com.typesafe.akka" %% "akka-distributed-data" % "2.6.3",
      "com.typesafe.akka" %% "akka-discovery" % "2.6.3",
      "com.typesafe.akka" %% "akka-http-spray-json" % "10.1.11",
      "com.typesafe.akka" %% "akka-http" % "10.1.11",
      "com.lightbend.akka.management" %% "akka-management-cluster-http" % "1.0.5",
      "com.lightbend.akka.management" %% "akka-management" % "1.0.5",
      "com.lightbend.akka.discovery" %% "akka-discovery-kubernetes-api" % "1.0.5",
      "com.lightbend.akka.management" %% "akka-management-cluster-bootstrap" % "1.0.5",
      ws,
      "com.typesafe.akka" %% "akka-cluster-sharding-typed" % "2.6.3"
and a custom lib enable ClusterMetricsExtension in play/reference-overrides.conf

### Expected Behavior

1. run command sbt run 
2. play start in dev mode

### Actual Behavior

--- (Running the application, auto-reloading is enabled) ---
the follow exception promote and play start in dev mode

[error] a.c.m.ClusterMetricsStrategy - ActorSystem [akka://play-dev-mode] needs to have 'akka.actor.provider' set to 'cluster' in the configuration, currently uses [akka.actor.LocalActorRefProvider]
akka.actor.ActorInitializationException: akka://play-dev-mode/system/cluster-metrics/collector-1: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:195)
	at akka.actor.ActorCell.create(ActorCell.scala:657)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:47)
	at akka.actor.NoArgsReflectConstructor.produce(IndirectActorProducer.scala:109)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
	at akka.actor.ActorCell.create(ActorCell.scala:635)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
Caused by: akka.ConfigurationException: ActorSystem [akka://play-dev-mode] needs to have 'akka.actor.provider' set to 'cluster' in the configuration, currently uses [akka.actor.LocalActorRefProvider]
	at akka.cluster.Cluster.<init>(Cluster.scala:83)
	at akka.cluster.Cluster$.createExtension(Cluster.scala:42)
	at akka.cluster.Cluster$.createExtension(Cluster.scala:35)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1159)
	at akka.actor.ExtensionId.apply(Extension.scala:78)
	at akka.actor.ExtensionId.apply$(Extension.scala:77)
	at akka.cluster.Cluster$.apply(Cluster.scala:35)
	at akka.cluster.metrics.ClusterMetricsCollector.<init>(ClusterMetricsCollector.scala:139)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

### Reason
play Akka HTTP server set actor.provider = local in 2.8 release and it doesn't work with the extension, there is not a way to only remove the extension in the config, so I set akka.extensions = [] also in dev mode, hope there is a better solution for this

**Comment by ignasi35** [comment]
Hi @thirdteeth, running play in dev mode for a clustered application is not trivial. The problem is play uses two different `ActorSystem`'s in dev mode and they will compete for a port to start their server-for-clustering.

The two `ActorSystem`'s in play DevMode are used for `Server` and `Application`. When you are clustering you only want the `Application` `ActorSystem` to be clustered which means the `Server`  `ActorSystem`  must be setup to `local`. 

Then, the solution is to setup Akka's  `cluster` implementation on your `application.conf` so `Allpication`'s `ActorSystem` picks it up and you get rid of the issue you copy/pasted in the description. And, at the same time, configure the `Server` `ActorSystem` to use `local`.  To configure the `Server` `ActorSystem` to use `local` you need to use the the [`play.akka.dev-mode`](https://github.com/playframework/playframework/blob/e6693c4ecdaa4eab0d2f88b9ca74048e92d53dff/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala#L81-L89) namespace in the settings.
