### ISSUE TITLE
Failed: Test script error: File(s) did not exist

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10209]
Failed on `master` buiild. 

https://travis-ci.com/github/playframework/playframework/jobs/321927314#L2408

```scala
Caused by: java.lang.RuntimeException: Test script error: File(s) did not exist: [ /tmp/sbt_be28b0bd/shutdown-happy-path/target/slow-request.txt ]
	at scala.sys.package$.error(package.scala:30)
	at sbt.internal.scripted.FileCommands.scriptError(FileCommands.scala:46)
	at sbt.internal.scripted.FileCommands.exists(FileCommands.scala:80)
	at sbt.internal.scripted.FileCommands.$anonfun$commandMap$3(FileCommands.scala:20)
	at sbt.internal.scripted.FileCommands.$anonfun$commandMap$3$adapted(FileCommands.scala:20)
	at sbt.internal.scripted.FileCommands$CommandBuilder.$anonfun$nonEmpty$1(FileCommands.scala:107)
	at sbt.internal.scripted.FileCommands$CommandBuilder.$anonfun$nonEmpty$1$adapted(FileCommands.scala:103)
	at sbt.internal.scripted.FileCommands.$anonfun$apply$1(FileCommands.scala:41)
	at sbt.internal.scripted.FileCommands.$anonfun$apply$1$adapted(FileCommands.scala:41
	at scala.Option.map(Option.scala:230)
```

**Comment by patriknw** [comment]
https://travis-ci.com/github/playframework/playframework/jobs/471606111

**Comment by mkurz** [comment]
Since this might be related to Travis and we use GitHub actions now, I am closing. We can open new issues if something turns up with GHA.
