### ISSUE TITLE
Play 2.8.1 does not work with Jackson 2.11.0

### ISSUE THREAD

**Issue by slisaasquatch** [playframework/playframework#10242]
### Play Version

2.8.1

### API

Java

### Operating System

Windows 10

### JDK

1.8.0_232

### Library Dependencies

Jackson Databind 2.11.0

### Actual Behavior

Including Jackson Databind 2.11.0 will cause the following error:
```
[error] com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.2 requires Jackson Databind version >= 2.10.0 and < 2.11.0
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
[error]         at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
[error]         at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:818)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4(JacksonObjectMapperProvider.scala:215)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.$anonfun$configureObjectMapperModules$4$adapted(JacksonObjectMapperProvider.scala:214)
[error]         at scala.collection.immutable.List.foreach(List.scala:333)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.configureObjectMapperModules(JacksonObjectMapperProvider.scala:214)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider$.createObjectMapper(JacksonObjectMapperProvider.scala:238)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.create(JacksonObjectMapperProvider.scala:325)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.$anonfun$getOrCreate$1(JacksonObjectMapperProvider.scala:283)
[error]         at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[error]         at akka.serialization.jackson.JacksonObjectMapperProvider.getOrCreate(JacksonObjectMapperProvider.scala:283)
[error]         at akka.serialization.jackson.JacksonJsonSerializer.<init>(JacksonSerializer.scala:98)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]         at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)
[error]         at scala.util.Try$.apply(Try.scala:210)
[error]         at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
[error]         at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
[error]         at scala.util.Success.flatMap(Try.scala:258)
[error]         at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:396)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1$$anonfun$applyOrElse$1.applyOrElse(Serialization.scala:392)
[error]         at scala.util.Failure.recoverWith(Try.scala:240)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:392)
[error]         at akka.serialization.Serialization$$anonfun$serializerOf$1.applyOrElse(Serialization.scala:390)
[error]         at scala.util.Failure.recoverWith(Try.scala:240)
[error]         at akka.serialization.Serialization.serializerOf(Serialization.scala:390)
[error]         at akka.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:424)
[error]         at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
[error]         at scala.collection.immutable.HashMapBuilder.addAll(HashMap.scala:2342)
[error]         at scala.collection.immutable.HashMap$.from(HashMap.scala:2164)
[error]         at scala.collection.immutable.HashMap$.from(HashMap.scala:2140)
[error]         at scala.collection.MapOps$WithFilter.map(Map.scala:352)
[error]         at akka.serialization.Serialization.<init>(Serialization.scala:424)
[error]         at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
[error]         at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:14)
[error]         at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1155)
[error]         at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1196)
[error]         at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
[error]         at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1191)
[error]         at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1209)
[error]         at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1036)
[error]         at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1023)
[error]         at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1023)
[error]         at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1046)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:283)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:327)
[error]         at akka.actor.ActorSystem$.apply(ActorSystem.scala:301)
[error]         at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:248)
[error]         at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error]         at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:76)
[error]         at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
[error]         at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error]         at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error]         at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```

### Reproducible Test Case
N/A

**Comment by mkurz** [comment]
Please see #10232

**Comment by raboof** [comment]
> Scala module 2.10.2 requires Jackson Databind version >= 2.10.0 and < 2.11.0

You could of course try also upgrading `com.fasterxml.jackson.module:jackson-module-scala` - but as discussed in #10232, jackson usually has a good reason to update the minor version, so we can't guarantee that this will work.

**Comment by mkurz** [comment]
In #11219 I see how upgrading to latest jackson 2.13 goes. I needed to override `jackson-module-scala` version that `akka-serialization-jackson` pulls in.
