### ISSUE TITLE
Failed: 2.7.x, sbt.inc.Doc$JavadocGenerationFailed

### ISSUE THREAD

**Issue by seglo** [playframework/playframework#10328]
Raised on 2.7.x nightly build from vegemite.

```
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1617)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1617)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] (Play-Exceptions / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
```

**Comment by ignasi35** [comment]
Again, tonight:

```

[info] Generating /home/play/deploy/playframework/dev-mode/play-docs/target/scala-2.12/apidocs/java/allclasses-frame.html...
[info] Generating /home/play/deploy/playframework/dev-mode/play-docs/target/scala-2.12/apidocs/java/allclasses-noframe.html...
[info] Generating /home/play/deploy/playframework/dev-mode/play-docs/target/scala-2.12/apidocs/java/index.html...
[info] Generating /home/play/deploy/playframework/dev-mode/play-docs/target/scala-2.12/apidocs/java/overview-summary.html...
[info] Generating /home/play/deploy/playframework/dev-mode/play-docs/target/scala-2.12/apidocs/java/help-doc.html...
[info] 157 warnings
[info] Play 2.7.6-SNAPSHOT-SNAPSHOT Java API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.12-2.7.6-SNAPSHOT-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.12-2.7.6-SNAPSHOT-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.12-2.7.6-SNAPSHOT-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.12-2.7.6-SNAPSHOT-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1617)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 173 s (02:53), completed Jul 17, 2020 3:20:07 AM
````

**Comment by ennru** [comment]
/home/play/logs/nightly-deploy-2.7.x-1596251773.log

```
[info] Generating /home/play/deploy/playframework/dev-mode/play-docs/target/scala-2.12/apidocs/java/help-doc.html...
[info] 157 warnings
[info] Play 2.7.6-SNAPSHOT-SNAPSHOT Java API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.12-2.7.6-SNAPSHOT-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.12-2.7.6-SNAPSHOT-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.12-2.7.6-SNAPSHOT-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.12-2.7.6-SNAPSHOT-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
```

**Comment by patriknw** [comment]
nightly-deploy-master failed

The full logs for this task have been saved and can be found in /home/play/logs/nightly-deploy-master-1602385201.log.

**Comment by mkurz** [comment]
vegemite does not exist anymore. We will never know what was the problem here. Also the 2.7.x branch is outdated anyway.
