### ISSUE TITLE
Failed: Sonatype upload failed (502: Bad Gateway)

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#10337]
The nightly build task nightly-deploy-2.7.x failed.

The full logs for this task have been saved and can be found in /home/play/logs/nightly-deploy-2.7.x-1592104503.log.

```
...
[info] 157 warnings
[info] Play 2.7.6-SNAPSHOT-SNAPSHOT Java API documentation successful.
[info] 	published play-docs_2.11 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.11/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.11-2.7.6-SNAPSHOT-SNAPSHOT.pom
[info] 	published play-docs_2.11 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.11/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.11-2.7.6-SNAPSHOT-SNAPSHOT.jar
[info] 	published play-docs_2.11 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.11/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.11-2.7.6-SNAPSHOT-SNAPSHOT-sources.jar
[info] 	published play-docs_2.11 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.11/2.7.6-SNAPSHOT-SNAPSHOT/play-docs_2.11-2.7.6-SNAPSHOT-SNAPSHOT-javadoc.jar
[error] java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-logback_2.11/2.7.6-SNAPSHOT-SNAPSHOT/play-logback_2.11-2.7.6-SNAPSHOT-SNAPSHOT.jar failed with status code 502: Bad Gateway
[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:82)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:264)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:368)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
[error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:501)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:500)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:792)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
```

**Comment by ignasi35** [comment]
Again in `/home/play/logs/nightly-deploy-2.7.x-1595474138.log`

**Comment by mkurz** [comment]
Many moons have passed since this error. We are not even deploying Play 2.7 anymore.
Also we switched to GHA now and use sbt-ci-release now.
