### ISSUE TITLE
Failed: shutdown-happy-path sbt task

### ISSUE THREAD

**Issue by seglo** [playframework/playframework#10334]
On master cron build

https://travis-ci.com/github/playframework/playframework/jobs/346905060#L5012

Didn't see a more informative error.  Not sure if it has something to do with `routes-compiler-no-package-declaration-in-routes-file`

```
[info] + play-sbt-plugin / routes-compiler-no-package-declaration-in-routes-file 
[error] java.lang.RuntimeException: Failed tests:
[error] 	play-sbt-plugin / shutdown-happy-path
[error] 
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.scriptedtest.ScriptedRunner.reportErrors(ScriptedTests.scala:565)
[error] 	at sbt.scriptedtest.ScriptedRunner.runAll(ScriptedTests.scala:568)
[error] 	at sbt.scriptedtest.ScriptedRunner.run(ScriptedTests.scala:513)
[error] 	at sbt.scriptedtest.ScriptedRunner.run(ScriptedTests.scala:477)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] 	at sbt.ScriptedPlugin$.$anonfun$scriptedTask$3(ScriptedPlugin.scala:193)
[error] 	at sbt.ScriptedPlugin$.$anonfun$scriptedTask$3$adapted(ScriptedPlugin.scala:178)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (scripted) Failed tests:
[error] 	play-sbt-plugin / shutdown-happy-path
```

**Comment by mkurz** [comment]
This has nothing to do with `routes-compiler-no-package-declaration-in-routes-file`. Why should it? Just because that's the previous test before the failing one? `routes-compiler-no-package-declaration-in-routes-file` ran totally fine.

**Comment by mkurz** [comment]
Anyway, todays' cron build are all green, can we close this issue?

**Comment by seglo** [comment]
I agree it probably has nothing to do with `routes-compiler-no-package-declaration-in-routes-file`. I'm on surface this week and one of the responsibilities is to flag build failures, transient or otherwise. I think we should keep it open for awhile to see if it occurs again.

**Comment by raboof** [comment]
saw this failure again at https://travis-ci.com/github/playframework/playframework/jobs/457952029 (for the 2.8.x branch), indeed seems flakey. The actual error seems to be:

```
Test script error: File(s) did not exist: [ /tmp/sbt_50cf8ab9/shutdown-happy-path/target/slow-request.txt ]
```

We never see the 'Resource at /slow returned HTTP ...'. Perhaps we were unlucky and the request was not accepted yet within 500ms?
