### ISSUE TITLE
NoClassDefFoundError: akka/protobufv3/internal/MessageLite

### ISSUE THREAD

**Issue by raboof** [playframework/playframework#10470]
https://travis-ci.com/github/playframework/playframework/jobs/396668130
```
java.lang.NoClassDefFoundError: akka/protobufv3/internal/MessageLite
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:38)
	at scala.util.Try$.apply(Try.scala:213)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
	at scala.util.Success.flatMap(Try.scala:251)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.serialization.Serialization.serializerOf(Serialization.scala:390)
	at akka.serialization.Serialization.$anonfun$serializers$2(Serialization.scala:424)
```

**Comment by raboof** [comment]
Interestingly we're seeing the same error in akka-http nightlies (https://github.com/akka/akka-http/issues/3510), looking into that

**Comment by raboof** [comment]
should be fixed by https://github.com/akka/akka/pull/29719
