### ISSUE TITLE
Problem serializing to JSON when upgrading from 2.8.2 to 2.8.3

### ISSUE THREAD

**Issue by tomp4l** [playframework/playframework#10505]
### Play Version

2.8.3 

### API

Java API

### Operating System

Linux NBSL1380 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

### Expected Behavior

`play.libs.Json.toJson` is able to serialise a Jackson serializable object as it was in 2.8.2

### Actual Behavior

Our tests now fail with stack trace provided below: 
```
      java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: We should have been reading an object, something got wrong
        at controllers.DecisionStrategyController.lambda$getDecisionStrategy$0(DecisionStrategyController.java:50) Test / executeTests 19s
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at ✽.I should have a strategy with proxy settings attached(file:///home/tom/deko-docker/src/decisioning/test/cucumber/features/ProxySettings.feature:13)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: We should have been reading an object, something got wrong
	at play.libs.Json.toJson(Json.java:94)
	at controllers.DecisionStrategyController.lambda$getDecisionStrategy$0(DecisionStrategyController.java:48)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: We should have been reading an object, something got wrong
	at play.utils.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.scala:166)
	at play.utils.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.scala:57)
	at play.utils.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.scala:53)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4497)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2840)
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3229)
	at play.libs.Json.toJson(Json.java:92)
	... 11 more
```

Maybe a downstream issue with https://github.com/playframework/play-json?

### Reproducible Test Case

I'm unable to provide a reproducible test case at this time, I will try and spend some time later if possible and work out where the issue is.

**Comment by octonato** [comment]
@tomp4l, thanks for reporting it. This is certainly a regression. We did change how the parsing is done for Play Java API. We had a bunch of tests, but we probably missed an edge case. 

I hope this is an edge case and is not affecting most users. It will be super helpful if you can provides us an example of json your are trying to read. 

I will start to investigate it right now, but if it's an edge case it may be harder to reproduce.

**Comment by tomp4l** [comment]
I'm looking to see if I can pin down the root cause, the strange part is we're trying to serialise an object to respond with, but clearly, it's hitting some deserialization code here.

Does seem to be an edge case only affecting one of our endpoints.

**Comment by tomp4l** [comment]
I've managed to track down the error to something annotated with `@JsonRawValue` which is either a string containing a JSON object `"{...}"` or the string `"null"`

**Comment by jrudolph** [comment]
It seems Jackson does a chain of conversion to implement `toJson`: `Object` -> json -> JsonNode. That explains why the deserializer comes into play. In that particular case, the new deserializer fails here:

https://github.com/playframework/playframework/blob/585590673fa55f0d8218b18a00be7ca9370538d0/core/play/src/main/scala/play/utils/JsonNodeDeserializer.scala#L164-L166

The error message seems wrong in the first place. It seems the new deserializer just does not support `ID_EMBEDDED_OBJECT` tokens right now (which are probably the ones produced by `@JsonRawValue`).

**Comment by jrudolph** [comment]
Here's the original JsonNodeDeserializer code dealing with those embedded objects:

https://github.com/FasterXML/jackson-databind/blob/57482db32f4490f17615e0540a9fdf1c7784abb0/src/main/java/com/fasterxml/jackson/databind/deser/std/JsonNodeDeserializer.java#L679-L700

Should be easy enough to support (once you know that those have to be supported...).

Another possibility could be, to fallback to the default Jackson JsonNodeDeserializer in `Json.toJson` based on the reasoning that the object already comes from the application and not from the wire.

**Comment by octonato** [comment]
Fixing in #10508
