### ISSUE TITLE
Failed: Nightly task nightly-deploy-2.8.x failed

### ISSUE THREAD

**Issue by jrudolph** [playframework/playframework#10533]
With two different error messages, failed at least three times in the last few days:

```
[error] (Sbt-Routes-Compiler / publish) java.io.IOException: PUT operation failed because the destination file exists and overwriting is disabled:
[error]     source     : /home/play/deploy/playframework/dev-mode/routes-compiler/target/sbt-routes-compiler/scala-2.10/sbt-routes-compiler_2.10-2.8.5-SNAPSHOT.pom
```

and

```
[error] (Play-Docs-Sbt-Plugin / publish) error uploading to com.typesafe.play/play-docs-sbt-plugin/scala_2.10/sbt_0.13/2.8.5-SNAPSHOT/jars/play-docs-sbt-plugin.jar: {"message":"Failed to create version, invalid version name: 2.8.5-SNAPSHOT"}
```

<details>
<summary>Details</summary>

```
The full logs for this task have been saved and can be found in /home/play/logs/nightly-deploy-2.8.x-1605155968.log.

[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:87)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:209)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:250)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:132)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2814)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2814)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.io.IOException: destination file exists and overwrite == false
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:368)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
[error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:501)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:500)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:500)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:142)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:156)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:149)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:142)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:132)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:251)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:215)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:87)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:87)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:209)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:250)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:132)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2814)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2814)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Run-Support / publish) java.io.IOException: PUT operation failed because the destination file exists and overwriting is disabled:
[error]     source     : /home/play/deploy/playframework/dev-mode/run-support/target/run-support/scala-2.10/run-support_2.10-2.8.5-SNAPSHOT.pom
[error]     destination: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/run-support_2.10/2.8.5-SNAPSHOT/run-support_2.10-2.8.5-SNAPSHOT.pom
[error] If you have a staging repository that has failed, drop it and start over.
[error] Otherwise fix the double publishing, or relax the setting as follows:
[error]     publishConfiguration := publishConfiguration.value.withOverwrite(true)
[error]     publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
[error] (Play-Docs-Sbt-Plugin / publish) error uploading to com.typesafe.play/play-docs-sbt-plugin/scala_2.10/sbt_0.13/2.8.5-SNAPSHOT/jars/play-docs-sbt-plugin.jar: {"message":"Failed to create version, invalid version name: 2.8.5-SNAPSHOT"}
[error] (Sbt-Plugin / publish) error uploading to com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.8.5-SNAPSHOT/jars/sbt-plugin.jar: {"message":"Failed to create version, invalid version name: 2.8.5-SNAPSHOT"}
[error] (Sbt-Routes-Compiler / publish) java.io.IOException: PUT operation failed because the destination file exists and overwriting is disabled:
[error]     source     : /home/play/deploy/playframework/dev-mode/routes-compiler/target/sbt-routes-compiler/scala-2.10/sbt-routes-compiler_2.10-2.8.5-SNAPSHOT.pom
[error]     destination: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/sbt-routes-compiler_2.10/2.8.5-SNAPSHOT/sbt-routes-compiler_2.10-2.8.5-SNAPSHOT.pom
[error] If you have a staging repository that has failed, drop it and start over.
[error] Otherwise fix the double publishing, or relax the setting as follows:
[error]     publishConfiguration := publishConfiguration.value.withOverwrite(true)
[error]     publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
[error] Total time: 41 s, completed Nov 12, 2020 4:41:25 AM
```
</details>

**Comment by ennru** [comment]
Again in /home/play/logs/nightly-deploy-2.8.x-1605242192.log

**Comment by mkurz** [comment]
Since this might be related to Travis and we use GitHub actions now, I am closing. We can open new issues if something turns up with GHA.
