### ISSUE TITLE
Failed: Error accessing netty jar

### ISSUE THREAD

**Issue by chbatey** [playframework/playframework#10554]
Happened a few times in a row:

```
[info] 	published ivy to /home/travis/.ivy2/local/com.typesafe.play/play-java-jpa_2.12/2.8.1+758-c478f944/ivys/ivy.xml
[error] scala.reflect.internal.FatalError: Error accessing /home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/io/netty/netty-transport/4.1.54.Final/netty-transport-4.1.54.Final.jar
[error] 	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$list$3(AggregateClassPath.scala:99)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.tools.nsc.classpath.AggregateClassPath.list(AggregateClassPath.scala:87)
[error] 	at scala.tools.nsc.util.ClassPath.list(ClassPath.scala:36)
[error] 	at scala.tools.nsc.util.ClassPath.list$(ClassPath.scala:36)
[error] 	at scala.tools.nsc.classpath.AggregateClassPath.list(AggregateClassPath.scala:30)
[error] 	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:284)
[error] 	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:230)
[error] 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
[error] 	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:257)
[error] 	at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:74)
```

https://travis-ci.com/github/playframework/playframework/jobs/450386317

**Comment by raboof** [comment]
in https://github.com/playframework/playframework/pull/10553 it went away after removing the cache (which worked this time :tada: !)
