### ISSUE TITLE
Failed: Nightly task nightly-deploy-master failed

### ISSUE THREAD

**Issue by jrudolph** [playframework/playframework#10583]
Probably related to #10111 and #10328 (but for the master branch).

`The full logs for this task have been saved and can be found in /home/play/logs/nightly-deploy-master-1607227201.log.`

```
[info] Play 2.8.1+781-467c50b0-SNAPSHOT Scala API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1+781-467c50b0-SNAPSHOT/play-docs_2.12-2.8.1+781-467c50b0-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1+781-467c50b0-SNAPSHOT/play-docs_2.12-2.8.1+781-467c50b0-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1+781-467c50b0-SNAPSHOT/play-docs_2.12-2.8.1+781-467c50b0-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1+781-467c50b0-SNAPSHOT/play-docs_2.12-2.8.1+781-467c50b0-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cachedJavadoc$1(Doc.scala:51)
[error] 	at sbt.inc.Doc$$anonfun$cachedJavadoc$2.run(Doc.scala:41)
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$prepare$1(Doc.scala:62)
[error] 	at sbt.inc.Doc$$anonfun$prepare$5.run(Doc.scala:57)
[error] 	at sbt.inc.Doc$.go$1(Doc.scala:73)
[error] 	at sbt.inc.Doc$.$anonfun$cached$5(Doc.scala:82)
[error] 	at sbt.inc.Doc$.$anonfun$cached$5$adapted(Doc.scala:81)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cached$1(Doc.scala:85)
[error] 	at sbt.inc.Doc$$anonfun$cached$7.run(Doc.scala:68)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1993)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cachedJavadoc$1(Doc.scala:51)
[error] 	at sbt.inc.Doc$$anonfun$cachedJavadoc$2.run(Doc.scala:41)
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$prepare$1(Doc.scala:62)
[error] 	at sbt.inc.Doc$$anonfun$prepare$5.run(Doc.scala:57)
[error] 	at sbt.inc.Doc$.go$1(Doc.scala:73)
[error] 	at sbt.inc.Doc$.$anonfun$cached$5(Doc.scala:82)
[error] 	at sbt.inc.Doc$.$anonfun$cached$5$adapted(Doc.scala:81)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cached$1(Doc.scala:85)
[error] 	at sbt.inc.Doc$$anonfun$cached$7.run(Doc.scala:68)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1993)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Play-Exceptions / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 164 s (02:44), completed Dec 6, 2020 4:04:08 AM
```

**Comment by patriknw** [comment]
Many build failures of nightly-deploy-master and nightly-deploy-2.8.x this week.

**Comment by mkurz** [comment]
@patriknw What was the error?

**Comment by patriknw** [comment]
I see now that there might be different errors for 2.8 and master. Sorry if I pinged wrong ticket.

**nightly-deploy-2.8.x**
```
The nightly build task nightly-deploy-2.8.x failed.

The full logs for this task have been saved and can be found in /home/play/logs/nightly-deploy-2.8.x-1620529259.log.

The last 100 lines output of this task were:

[warn] /**
[warn] ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala:159:3: Could not find any member to link for "Behavior".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala:139:3: Could not find any member to link for "Behavior".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/ActorModule.scala:54:3: Could not find any member to link for "A".
[warn]   /** A convenience to refer to the type of an [[ActorModule]] with the given message type [[A]]. */
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/concurrent/Futures.scala:161:5: Could not find any member to link for "akka.util.Timeout".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/Files.scala:138:5: Could not find any member to link for "java.nio.file.Files.move()".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/Files.scala:115:5: Could not find any member to link for "java.nio.file.Files.move()".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:407:3: Could not find any member to link for "Result".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:432:3: Could not find any member to link for "SameSite".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:402:3: Could not find any member to link for "Result".
[warn]   /**
[warn]   ^
[warn] Could not find any member to link for "SameSite".
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/core/utils/AsciiSet.scala:33:1: Could not find any member to link for "AsciiRange".
[warn] /**
[warn] ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/core/utils/AsciiSet.scala:51:3: Could not find any member to link for "AsciiBitSet".
[warn]   /** Convert into an [[AsciiBitSet]] for fast querying. */
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:116:3: Could not find any member to link for "createAkkaHttpConfig()".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:144:3: Could not find any member to link for "createServerBinding()".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:133:3: Could not find any member to link for "createParserSettings()".
[warn]   /** Play's parser settings for Akka HTTP. Initialized by a call to [[createParserSettings()]]. */
[warn]   ^
[warn] 46 warnings found
[info] Play 2.8.8+27-fd6fa29b-SNAPSHOT Scala API documentation successful.
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.8+27-fd6fa29b-SNAPSHOT/play-docs_2.12-2.8.8+27-fd6fa29b-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.8+27-fd6fa29b-SNAPSHOT/play-docs_2.12-2.8.8+27-fd6fa29b-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.8+27-fd6fa29b-SNAPSHOT/play-docs_2.12-2.8.8+27-fd6fa29b-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.8+27-fd6fa29b-SNAPSHOT/play-docs_2.12-2.8.8+27-fd6fa29b-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$$anon$1.run(Doc.scala:72)
[error] 	at sbt.inc.Doc$$anon$2.run(Doc.scala:91)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5(Doc.scala:118)
[error] 	at sbt.inc.Doc$$anon$3.$anonfun$run$5$adapted(Doc.scala:114)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.inc.Doc$$anon$3.run(Doc.scala:122)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1646)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Play-Exceptions / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 158 s (02:38), completed May 9, 2021 3:05:34 AM
```

**nightly-deploy-master**
```
The nightly build task nightly-deploy-master failed.

The full logs for this task have been saved and can be found in /home/play/logs/nightly-deploy-master-1620874801.log.

The last 100 lines output of this task were:

Wed May 12 20:00:01 PDT 2021 - nightly-deploy-master started
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
Checking out branches and extracting versions...
Checking out /home/play/deploy/playframework (master)
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at 06e85e2 Merge pull request #10841 from mkurz/remove_bintray
Removing cache/play-cache/target/
Removing cache/play-caffeine-cache/target/
Removing cache/play-ehcache/target/
Removing cache/play-jcache/target/
Removing cluster/play-cluster-sharding/target/
Removing cluster/play-java-cluster-sharding/target/
Removing core/play-exceptions/target/
Removing core/play-guice/target/
Removing core/play-integration-test/target/
Removing core/play-java/target/
Removing core/play-logback/target/
Removing core/play-microbenchmark/target/
Removing core/play-streams/target/
Removing core/play/target/
Removing dev-mode/bill-of-materials/
Removing dev-mode/build-link/target/
Removing dev-mode/play-docs-sbt-plugin/target/
Removing dev-mode/play-docs/target/
Removing dev-mode/routes-compiler/target/
Removing dev-mode/run-support/target/
Removing dev-mode/sbt-plugin/target/
Removing persistence/play-java-jdbc/target/
Removing persistence/play-java-jpa/target/
Removing persistence/play-jdbc-api/target/
Removing persistence/play-jdbc-evolutions/target/
Removing persistence/play-jdbc/target/
Removing project/project/project/
Removing project/project/target/
Removing project/target/
Removing target/
Removing testkit/play-specs2/target/
Removing testkit/play-test/target/
Removing transport/client/play-ahc-ws/target/
Removing transport/client/play-ws/target/
Removing transport/server/play-akka-http-server/target/
Removing transport/server/play-akka-http2-support/target/
Removing transport/server/play-netty-server/target/
Removing transport/server/play-server/target/
Removing web/play-filters-helpers/target/
Removing web/play-java-forms/target/
Removing web/play-joda-forms/target/
Removing web/play-openid/target/
Checking out /home/play/deploy/scalatestplus-play (master)
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at 3e9cf74 htmlunit-driver 2.43.1 (was 2.39.0) (#285)
Checking out /home/play/deploy/play-slick (master)
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at ea32e32 Merge pull request #589 from scala-steward/update/interplay-3.0.3
-:1: parser error : Start tag expected, '<' not found
Forbidden!
```

**Comment by mkurz** [comment]
@patriknw Looking at
```
...
#Checking out /home/play/deploy/play-slick (master)
Already on 'master'
Your branch is up-to-date with 'origin/master'.
HEAD is now at ea32e32 Merge pull request #589 from scala-steward/update/interplay-3.0.3
-:1: parser error : Start tag expected, '<' not found
Forbidden!
...
the problem probably is that play-slick still tries to access the bintray repos,I think https://github.com/playframework/play-slick/pull/593 should fix that.

**Comment by mkurz** [comment]
@patriknw About the 2.8.x nightly I am not sure what's going on, but it looks like the docs get generated with Java 11?

**Comment by mkurz** [comment]
@patriknw It seems the nightly snapshots are still broken for the master branch, latest is `2.8.1+1148-091b4871-SNAPSHOT` from May 2nd: https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/sbt-plugin_2.12_1.0/
Can you please post the latest log?

**Comment by raboof** [comment]
`nightly-deploy-master` now seems to fail in much the same way as the 2.8 failure pasted above:

```
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/http/HttpErrorHandler.scala:488:3: Could not find any member to link for "Throwable".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/mvc/Session.scala:30:3: Could not find any member to link for "NoSuchElementException".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/mvc/BodyParsers.scala:584:3: Could not find any member to link for "akka.util.ByteString".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/mvc/BodyParsers.scala:575:3: Could not find any member to link for "akka.util.ByteString".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/mvc/Flash.scala:30:3: Could not find any member to link for "NoSuchElementException".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/ActorModule.scala:10:1: Could not find any member to link for "com.google.inject.Provides".
[warn] /**
[warn] ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala:159:3: Could not find any member to link for "Behavior".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala:139:3: Could not find any member to link for "Behavior".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play-guice/src/main/scala/play/api/libs/concurrent/ActorModule.scala:54:3: Could not find any member to link for "A".
[warn]   /** A convenience to refer to the type of an [[ActorModule]] with the given message type [[A]]. */
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/concurrent/Futures.scala:161:5: Could not find any member to link for "akka.util.Timeout".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/Files.scala:138:5: Could not find any member to link for "java.nio.file.Files.move()".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/libs/Files.scala:115:5: Could not find any member to link for "java.nio.file.Files.move()".
[warn]     /**
[warn]     ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:407:3: Could not find any member to link for "Result".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:432:3: Could not find any member to link for "SameSite".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/api/i18n/Messages.scala:402:3: Could not find any member to link for "Result".
[warn]   /**
[warn]   ^
[warn] Could not find any member to link for "SameSite".
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/core/utils/AsciiSet.scala:33:1: Could not find any member to link for "AsciiRange".
[warn] /**
[warn] ^
[warn] /home/play/deploy/playframework/core/play/src/main/scala/play/core/utils/AsciiSet.scala:51:3: Could not find any member to link for "AsciiBitSet".
[warn]   /** Convert into an [[AsciiBitSet]] for fast querying. */
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:112:3: Could not find any member to link for "createAkkaHttpConfig()".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:139:3: Could not find any member to link for "createServerBinding()".
[warn]   /**
[warn]   ^
[warn] /home/play/deploy/playframework/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala:128:3: Could not find any member to link for "createParserSettings()".
[warn]   /** Play's parser settings for Akka HTTP. Initialized by a call to [[createParserSettings()]]. */
[warn]   ^
[warn] 61 warnings found
[info] Play 2.8.1+1232-2464d6bc-SNAPSHOT Scala API documentation successful.
[warn] versionScheme setting is empty; set `ThisBuild / versionScheme := Some("early-semver")`, `Some("semver-spec")` or `Some("pvp")`
[warn] so tooling can use it for eviction errors etc - https://www.scala-sbt.org/1.x/docs/Publishing.html
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1+1232-2464d6bc-SNAPSHOT/play-docs_2.12-2.8.1+1232-2464d6bc-SNAPSHOT.pom
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1+1232-2464d6bc-SNAPSHOT/play-docs_2.12-2.8.1+1232-2464d6bc-SNAPSHOT.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1+1232-2464d6bc-SNAPSHOT/play-docs_2.12-2.8.1+1232-2464d6bc-SNAPSHOT-sources.jar
[info] 	published play-docs_2.12 to https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-docs_2.12/2.8.1+1232-2464d6bc-SNAPSHOT/play-docs_2.12-2.8.1+1232-2464d6bc-SNAPSHOT-javadoc.jar
[error] sbt.inc.Doc$JavadocGenerationFailed
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cachedJavadoc$1(Doc.scala:51)
[error] 	at sbt.inc.Doc$$anonfun$cachedJavadoc$2.run(Doc.scala:41)
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$prepare$1(Doc.scala:62)
[error] 	at sbt.inc.Doc$$anonfun$prepare$5.run(Doc.scala:57)
[error] 	at sbt.inc.Doc$.go$1(Doc.scala:73)
[error] 	at sbt.inc.Doc$.$anonfun$cached$5(Doc.scala:82)
[error] 	at sbt.inc.Doc$.$anonfun$cached$5$adapted(Doc.scala:81)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cached$1(Doc.scala:85)
[error] 	at sbt.inc.Doc$$anonfun$cached$7.run(Doc.scala:68)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2179)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Build-Link / Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 168 s (02:48), completed Jul 12, 2021 3:04:17 AM
```

**Comment by mkurz** [comment]
Not sure what was going on here. The last month the nightly job under Travis was working fine, also now with GHA I can not see a problem anymore. Therefore I am closing this issue. We can open new issues if something turns up with GHA.
