### ISSUE TITLE
Problem between system property and sub project

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [playframework/playframework#10619]
### Play Version
Play version : 2.8.7

### API
Project use Java

### Operating System
Windows 10

### JDK
Version : jdk1.8.0_221

### Library Dependencies
Play Ebean version : 6.0.0

### Expected Behavior

1. sbt run of the project
2. Go to localhost:9000
3. Project successfully compile

### Actual Behavior

1. sbt run of the project
2. Go to localhost:9000
3. Project crashed on compile

Here is the stack trace : 

```
`[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[error] java.lang.RuntimeException: com.typesafe.config.ConfigException$IO: application.dev.conf: java.io.IOException: resource not found on classpath: application.dev.conf
[error]         at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:190)
[error]         at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error]         at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
[error]         at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:1058)
[error]         at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:986)
[error]         at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
[error]         at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:529)
[error]         at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:261)
[error]         at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:258)
[error]         at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:66)
[error]         at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:93)
[error]         at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:258)
[error]         at play.db.ebean.ModelsConfigLoader.apply(ModelsConfigLoader.java:28)
[error]         at play.db.ebean.ModelsConfigLoader.apply(ModelsConfigLoader.java:22)
[error]         at play.ebean.sbt.PlayEbean$.$anonfun$configuredEbeanModels$4(PlayEbean.scala:149)
[error]         at play.ebean.sbt.PlayEbean$.withClassLoader$1(PlayEbean.scala:126)
[error]         at play.ebean.sbt.PlayEbean$.$anonfun$configuredEbeanModels$1(PlayEbean.scala:146)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.RuntimeException: java.io.IOException: resource not found on classpath: application.dev.conf
[error]         at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:726)
[error]         at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:701)
[error]         at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
[error]         at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error]         at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
[error]         at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:1058)
[error]         at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:986)
[error]         at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
[error]         at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:529)
[error]         at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:261)
[error]         at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:258)
[error]         at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:66)
[error]         at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:93)
[error]         at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:258)
[error]         at play.db.ebean.ModelsConfigLoader.apply(ModelsConfigLoader.java:28)
[error]         at play.db.ebean.ModelsConfigLoader.apply(ModelsConfigLoader.java:22)
[error]         at play.ebean.sbt.PlayEbean$.$anonfun$configuredEbeanModels$4(PlayEbean.scala:149)
[error]         at play.ebean.sbt.PlayEbean$.withClassLoader$1(PlayEbean.scala:126)
[error]         at play.ebean.sbt.PlayEbean$.$anonfun$configuredEbeanModels$1(PlayEbean.scala:146)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (business / Compile / playEbeanModels) com.typesafe.config.ConfigException$IO: application.dev.conf: java.io.IOException: resource not found on classpath: application.dev.conf
[error] p.a.h.DefaultHttpErrorHandler -

! @7ib0i9mb1 - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[RuntimeException: com.typesafe.config.ConfigException$IO: application.dev.conf: java.io.IOException: resource not found on classpath: application.dev.conf]
        at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$1(PlayReload.scala:44)
        at scala.Option.map(Option.scala:230)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:37)
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:30)
        at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:65)
        at scala.util.Either$LeftProjection.map(Either.scala:573)
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:65)
        at play.sbt.run.PlayRun$.$anonfun$playRunTask$4(PlayRun.scala:78)
        at play.runsupport.Reloader.$anonfun$reload$1(Reloader.scala:496)
        at play.runsupport.Reloader$$anon$1.run(Reloader.scala:57)
Caused by: java.lang.RuntimeException: com.typesafe.config.ConfigException$IO: application.dev.conf: java.io.IOException: resource not found on classpath: application.dev.conf
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:190)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
        at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:1058)
        at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:986)
        at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
        at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:529)
        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:261)
        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:258)
        at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:66)
Caused by: java.lang.RuntimeException: java.io.IOException: resource not found on classpath: application.dev.conf
        at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:726)
        at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:701)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
        at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:1058)
        at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:986)
        at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
        at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:529)
        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:261)
```

### Reproducible Test Case

Here is my build.sbt : 
```
lazy val business = (project in file("modules/business"))
  .enablePlugins(PlayJava).enablePlugins(SbtWeb).enablePlugins(PlayEbean)

lazy val root = (project in file("."))
  .settings(
    Common.settings(Common.appName),
    javaOptions += s"-Dconfig.resource=application.dev.conf"
  )
  .enablePlugins(PlayJava)
  .aggregate(business)
  .dependsOn(business)
```

Here is a complete simple project which is buggy : 
https://github.com/LeComptoirDesPharmacies/IssuePlayMultiProject

What is strange is that it was working in Play 2.6 with play-ebean 4.1.4.
See this branch : 
https://github.com/LeComptoirDesPharmacies/IssuePlayMultiProject/tree/workingIn2.6

Any idea about the problem or any workaround ?
Yours faithfully,
LCDP

**Comment by LeComptoirDesPharmacies** [comment]
Mhhh, after some analysis, it may come from Play Ebean itself and the way they did the migration from Configuration to Config.

I created the following issue on their side : https://github.com/playframework/play-ebean/issues/209

**Comment by mkurz** [comment]
Issue moved to the play-ebean repo.
