### ISSUE TITLE
[failed] java.lang.OutOfMemoryError: Metaspace when running sbt scripted test

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10676]
https://travis-ci.com/github/playframework/playframework/jobs/478802860#L2350

```scala
'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play-dev-mode]
[error] java.lang.OutOfMemoryError: Metaspace
[error] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[error] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error] 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.apply(BuiltinModule.scala:77)
[error] 	at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.apply(BuiltinModule.scala:42)
[error] 	at play.api.inject.SimpleModule.bindings(Module.scala:94)
[error] 	at play.api.inject.guice.GuiceableModuleConversions.guice(GuiceInjectorBuilder.scala:365)
[error] 	at play.api.inject.guice.GuiceableModuleConversions.guice$(GuiceInjectorBuilder.scala:364)
[error] 	at play.api.inject.guice.GuiceableModule$.guice(GuiceInjectorBuilder.scala:297)
[error] 	at play.api.inject.guice.GuiceableModuleConversions$$anon$2.$anonfun$guiced$2(GuiceInjectorBuilder.scala:344)
[error] 	at play.api.inject.guice.GuiceableModuleConversions$$anon$2$$Lambda$15962/0x0000000102af6840.apply(Unknown Source)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike$$Lambda$4521/0x0000000101595840.apply(Unknown Source)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at play.api.inject.guice.GuiceableModuleConversions$$anon$2.guiced(GuiceInjectorBuilder.scala:344)
[error] 	at play.api.inject.guice.GuiceableModule$.$anonfun$guiced$1(GuiceInjectorBuilder.scala:322)
[error] 	at play.api.inject.guice.GuiceableModule$$$Lambda$15961/0x0000000102af7840.apply(Unknown Source)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
[error] 	at scala.collection.TraversableLike$$Lambda$4549/0x00000001015eb840.apply(Unknown Source)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
[error] Exception in thread "play-dev-mode-shutdown-hook-1" java.lang.OutOfMemoryError: Metaspace
[error] x play-sbt-plugin / dev-mode 
```

**Comment by jtjeferreira** [comment]
maybe related to #10500, or some leak that was introduced meanwhile... I can try to have a look in the weekend

**Comment by jtjeferreira** [comment]
I could not reproduce locally this neither in a3cf50fa0 or cbbc97e759e4edb708f3ccd675502239cd29022c

**Comment by mkurz** [comment]
Todays master cron job [failed again](https://travis-ci.com/github/playframework/playframework/jobs/506279272#L1904):
```
[info] java.lang.OutOfMemoryError: Metaspace
[info] Dumping heap to /tmp/java_pid6448.hprof ...
[info] Heap dump file created [169897617 bytes in 0.925 secs]
[error] Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-6]: Metaspace, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play-dev-mode]
[error] java.lang.OutOfMemoryError: Metaspace
[error] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[error] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error] 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error] 	at play.api.libs.crypto.CookieSignerProvider.get$lzycompute(CookieSigner.scala:58)
[error] 	at play.api.libs.crypto.CookieSignerProvider.get(CookieSigner.scala:58)
[error] 	at play.api.libs.crypto.CookieSignerProvider.get(CookieSigner.scala:57)
[error] 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86)
[error] 	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
[error] 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60)
[error] 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:59)
[error] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
[error] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
[error] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
[error] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[error] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
[error] 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
[error] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
[error] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
[error] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
[error] 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
[error] 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
[error] 	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
[error] 	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
[error] 	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
[error] 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
[error] Exception in thread "play-dev-mode-shutdown-hook-1" java.lang.OutOfMemoryError: Metaspace
[error] x play-sbt-plugin/dev-mode 
```

**Comment by mkurz** [comment]
Even tough the heapdump gets stored on disk, we can't just simpy download that file. We would need to use somethink like https://github.com/travis-ci/artifacts

**Comment by mkurz** [comment]
Once more. Like the above reports, the scripted test `play-sbt-plugin / dev-mode` runs out of memory... (but not every day, just every now and then...)
https://travis-ci.com/github/playframework/playframework/jobs/507767891#L1579

```java
java.lang.OutOfMemoryError: Metaspace
Dumping heap to /tmp/java_pid7124.hprof ...
Heap dump file created [182657019 bytes in 0.878 secs]
[error] java.lang.BootstrapMethodError: call site initialization exception
[error] 	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
[error] 	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
[error] 	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
[error] 	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$$less$tilde$1(Parsers.scala:294)
[error] 	at scala.util.parsing.combinator.Parsers$Success.flatMapWithNext(Parsers.scala:146)
[error] 	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$flatMap$1(Parsers.scala:232)
[error] 	at scala.util.parsing.combinator.Parsers$$anon$1.apply(Parsers.scala:215)
[error] 	at scala.util.parsing.combinator.Parsers$$anon$5.apply(Parsers.scala:919)
[error] 	at scala.util.parsing.combinator.RegexParsers.parse(RegexParsers.scala:161)
[error] 	at scala.util.parsing.combinator.RegexParsers.parse$(RegexParsers.scala:160)
[error] 	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.parse(Algorithms.scala:232)
[error] 	at scala.util.parsing.combinator.RegexParsers.parseAll(RegexParsers.scala:177)
[error] 	at scala.util.parsing.combinator.RegexParsers.parseAll$(RegexParsers.scala:176)
[error] 	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.parseAll(Algorithms.scala:232)
[error] 	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.apply(Algorithms.scala:236)
[error] 	at com.typesafe.sslconfig.ssl.ConfigSSLContextBuilder.$anonfun$build$1(SSLContextBuilder.scala:110)
[error] 	at scala.collection.immutable.Vector1.map(Vector.scala:1872)
[error] 	at scala.collection.immutable.Vector1.map(Vector.scala:375)
[error] 	at com.typesafe.sslconfig.ssl.ConfigSSLContextBuilder.build(SSLContextBuilder.scala:110)
[error] 	at com.typesafe.sslconfig.akka.AkkaSSLConfig.<init>(AkkaSSLConfig.scala:93)
[error] 	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:32)
[error] 	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:21)
[error] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
[error] 	at akka.actor.ExtensionId.apply(Extension.scala:78)
[error] 	at akka.actor.ExtensionId.apply$(Extension.scala:77)
[error] 	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:27)
[error] 	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.apply(AkkaSSLConfig.scala:21)
[error] 	at akka.http.scaladsl.HttpExt.<init>(Http.scala:82)
[error] 	at akka.http.scaladsl.Http$.createExtension(Http.scala:1132)
[error] 	at akka.http.scaladsl.Http$.createExtension(Http.scala:901)
[error] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
[error] 	at akka.actor.ExtensionId.apply(Extension.scala:78)
[error] 	at akka.actor.ExtensionId.apply$(Extension.scala:77)
[error] 	at akka.http.scaladsl.Http$.apply(Http.scala:1127)
[error] 	at play.core.server.AkkaHttpServer.createServerBinding(AkkaHttpServer.scala:222)
[error] 	at play.core.server.AkkaHttpServer.$anonfun$httpServerBinding$1(AkkaHttpServer.scala:251)
[error] 	at play.core.server.AkkaHttpServer.$anonfun$httpServerBinding$1$adapted(AkkaHttpServer.scala:247)
[error] 	at scala.Option.map(Option.scala:242)
[error] 	at play.core.server.AkkaHttpServer.<init>(AkkaHttpServer.scala:247)
[error] 	at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:665)
[error] 	at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:663)
[error] 	at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:311)
[error] 	at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error] 	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:76)
[error] 	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
[error] 	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:100)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:83)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$12(PlayRun.scala:105)
[error] 	at play.sbt.StaticPlayNonBlockingInteractionMode$.start(PlayInteractionMode.scala:144)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] Caused by: java.lang.OutOfMemoryError: Metaspace
[error] 	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
[error] 	at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:326)
[error] 	at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:194)
[error] 	at java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:474)
[error] 	at java.lang.invoke.LambdaForm$DMH/668210649.invokeStatic_L4_L(LambdaForm$DMH)
[error] 	at java.lang.invoke.LambdaForm$BMH/1190703722.reinvoke(LambdaForm$BMH)
[error] 	at java.lang.invoke.LambdaForm$MH/1322060587.invoke_MT(LambdaForm$MH)
[error] 	at java.lang.invoke.CallSite.makeSite(CallSite.java:306)
[error] 	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
[error] 	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
[error] 	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$$less$tilde$1(Parsers.scala:294)
[error] 	at scala.util.parsing.combinator.Parsers$Parser$$Lambda$10818/1644257752.apply(Unknown Source)
[error] 	at scala.util.parsing.combinator.Parsers$Success.flatMapWithNext(Parsers.scala:146)
[error] 	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$flatMap$1(Parsers.scala:232)
[error] 	at scala.util.parsing.combinator.Parsers$Parser$$Lambda$10815/418584305.apply(Unknown Source)
[error] 	at scala.util.parsing.combinator.Parsers$$anon$1.apply(Parsers.scala:215)
[error] 	at scala.util.parsing.combinator.Parsers$$anon$5.apply(Parsers.scala:919)
[error] 	at scala.util.parsing.combinator.RegexParsers.parse(RegexParsers.scala:161)
[error] 	at scala.util.parsing.combinator.RegexParsers.parse$(RegexParsers.scala:160)
[error] 	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.parse(Algorithms.scala:232)
[error] 	at scala.util.parsing.combinator.RegexParsers.parseAll(RegexParsers.scala:177)
[error] 	at scala.util.parsing.combinator.RegexParsers.parseAll$(RegexParsers.scala:176)
[error] 	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.parseAll(Algorithms.scala:232)
[error] 	at com.typesafe.sslconfig.ssl.AlgorithmConstraintsParser$.apply(Algorithms.scala:236)
[error] 	at com.typesafe.sslconfig.ssl.ConfigSSLContextBuilder.$anonfun$build$1(SSLContextBuilder.scala:110)
[error] 	at com.typesafe.sslconfig.ssl.ConfigSSLContextBuilder$$Lambda$10810/464024343.apply(Unknown Source)
[error] 	at scala.collection.immutable.Vector1.map(Vector.scala:1872)
[error] 	at scala.collection.immutable.Vector1.map(Vector.scala:375)
[error] 	at com.typesafe.sslconfig.ssl.ConfigSSLContextBuilder.build(SSLContextBuilder.scala:110)
[error] 	at com.typesafe.sslconfig.akka.AkkaSSLConfig.<init>(AkkaSSLConfig.scala:93)
[error] 	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:32)
[error] 	at com.typesafe.sslconfig.akka.AkkaSSLConfig$.createExtension(AkkaSSLConfig.scala:21)
[error] stack trace is suppressed; run 'last Compile / run' for the full output
[error] (Compile / run) java.lang.reflect.InvocationTargetException
[error] Total time: 6 s, completed May 25, 2021 3:15:22 PM
[error] java.lang.BootstrapMethodError: call site initialization exception
[error] Use 'last' for the full log.
[error] x play-sbt-plugin / dev-mode 
```

**Comment by mkurz** [comment]
I will increase the metaspace size to 512m again, like it was before: #10877

**Comment by mkurz** [comment]
Once more: https://app.travis-ci.com/github/playframework/playframework/jobs/527317158#L2086-L2093

```
[info] java.lang.OutOfMemoryError: Metaspace
[info] Dumping heap to /tmp/java_pid6482.hprof ...
[info] Heap dump file created [164507469 bytes in 0.869 secs]
[error] Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-7]: Metaspace, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play-dev-mode]
[error] java.lang.OutOfMemoryError: Metaspace
[error] Exception in thread "play-dev-mode-shutdown-hook-1" java.lang.OutOfMemoryError: Metaspace
[error] x play-sbt-plugin/dev-mode 
[error]  Cause of test exception: {line 68}  Command failed
```

Looking at this thread here it looks like the OOM exception always happens in the `play-sbt-plugin/dev-mode` scripted test, nowhere else.
I fixed a potential memory leak in https://github.com/playframework/playframework/pull/10939, maybe that helps. It would even make sense if the `play-sbt-plugin/dev-mode` scripted test was effected by this memory leak, because this test reloads the app in dev mode a couple of times
