### ISSUE TITLE
[failed] script tests: play-sbt-plugin / dev-mode

### ISSUE THREAD

**Issue by octonato** [playframework/playframework#10677]
https://travis-ci.com/github/playframework/playframework/jobs/479981496#L1900-L1928

```scala
[error] Exception in thread "play-watch-service" java.nio.file.NoSuchFileException: /tmp/sbt_410f3bc2/dev-mode/public/css/some.css
[error] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error] 	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[error] 	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
[error] 	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[error] 	at java.nio.file.Files.readAttributes(Files.java:1737)
[error] 	at java.nio.file.Files.getLastModifiedTime(Files.java:2266)
[error] 	at better.files.File.lastModifiedTime(File.scala:608)
[error] 	at play.dev.filewatch.SourceModificationWatch$$anonfun$3.apply(PollingFileWatchService.scala:50)
[error] 	at play.dev.filewatch.SourceModificationWatch$$anonfun$3.apply(PollingFileWatchService.scala:50)
[error] 	at scala.collection.TraversableOnce$$anonfun$maxBy$1.apply(TraversableOnce.scala:225)
[error] 	at scala.collection.TraversableOnce$$anonfun$reduceLeft$1.apply(TraversableOnce.scala:177)
[error] 	at scala.collection.TraversableOnce$$anonfun$reduceLeft$1.apply(TraversableOnce.scala:172)
[error] 	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:153)
[error] 	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
[error] 	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:172)
[error] 	at scala.collection.AbstractTraversable.reduceLeft(Traversable.scala:105)
[error] 	at scala.collection.TraversableOnce$class.maxBy(TraversableOnce.scala:225)
[error] 	at scala.collection.AbstractTraversable.maxBy(Traversable.scala:105)
[error] 	at play.dev.filewatch.SourceModificationWatch$.findLastModifiedTime(PollingFileWatchService.scala:50)
[error] 	at play.dev.filewatch.SourceModificationWatch$.watch(PollingFileWatchService.scala:62)
[error] 	at play.dev.filewatch.PollingFileWatchService$$anon$1.run(PollingFileWatchService.scala:24)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mkurz** [comment]
Since this might be related to Travis and we use GitHub actions now, I am closing. We can open new issues if something turns up with GHA.
