### ISSUE TITLE
Unhandled error in sbt-plugin

### ISSUE THREAD

**Issue by kiritsuku** [playframework/playframework#10792]
### Play Version

`addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.7")`

### Problem

After starting the play server with `sbt run`, the play plugin crashes with the following error:
```
[error] p.a.h.DefaultHttpErrorHandler - Error while handling error
java.lang.ClassCastException: sbt.internal.inc.MappedVirtualFile cannot be cast to java.io.File
        at play.sbt.run.PlayReload$.$anonfun$sourceMap$1(PlayReload.scala:71)
        at scala.collection.MapLike$MappedValues.get(MapLike.scala:260)
        at play.runsupport.Reloader.$anonfun$findSource$1(Reloader.scala:547)
        at scala.Option.flatMap(Option.scala:271)
        at play.runsupport.Reloader.findSource(Reloader.scala:546)
        at play.core.server.DevServerStart$$anon$1$$anon$2.sourceOf(DevServerStart.scala:171)
        at play.core.SourceMapper.$anonfun$sourceFor$1(ApplicationProvider.scala:21)
        at play.core.SourceMapper.$anonfun$sourceFor$1$adapted(ApplicationProvider.scala:21)
        at scala.collection.ArrayOps$.find$extension(ArrayOps.scala:684)
        at play.core.SourceMapper.sourceFor(ApplicationProvider.scala:21)
```

My Scala application threw an exception, which should be shown in the error output.

I can try to work on a reproducible test case if this would help fixing the issue.

**Comment by mkurz** [comment]
That's because you use sbt 1.4+ (check your `project/build.properties` file). Play 2.8.8, which should be released soon, will finally have support for sbt 1.4/1.5.
For now please just use sbt 1.3.13 until Play 2.8.8 is out.
