### ISSUE TITLE
Can't use 2.8.11 with Java 8

### ISSUE THREAD

**Issue by maxcom** [playframework/playframework#11033]
Binaries was build on Java 11 and can't be used on Java 8:

```
2021-12-02T16:06:14+0300 ovm156 run[7033]: Uncaught error from thread [application-akka.actor.default-dispatcher-6]: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;,
shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
2021-12-02T16:06:14+0300 ovm156 run[7033]: java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at play.core.formatters.Multipart$CustomCharsetByteStringFormatter.flushCharBuffer(Multipart.scala:103)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at play.core.formatters.Multipart$CustomCharsetByteStringFormatter.$tilde$tilde(Multipart.scala:89)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at play.core.formatters.Multipart$CustomCharsetByteStringFormatter.$tilde$tilde(Multipart.scala:78)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at play.core.formatters.Multipart$.play$core$formatters$Multipart$$renderDisposition(Multipart.scala:209)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at play.core.formatters.Multipart$$anon$1$$anon$2.onPush(Multipart.scala:165)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:61)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:57)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.ActorGraphInterpreter$RequestMore.execute(ActorGraphInterpreter.scala:289)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorG
raphInterpreter.scala:800)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.actor.Actor.aroundReceive(Actor.scala:537)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.actor.Actor.aroundReceive$(Actor.scala:535)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.actor.ActorCell.invoke(ActorCell.scala:548)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.dispatch.Mailbox.run(Mailbox.scala:231)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
2021-12-02T16:06:14+0300 ovm156 run[7033]:         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

This is well know problem (see https://www.morling.dev/blog/bytebuffer-and-the-dreaded-nosuchmethoderror/ for explanaition). Please rebuild them under Java 8 so they will be compatible with 8 and any modern version of JDK.

**Comment by octonato** [comment]
@maxcom, can you double check it? Play 2.8.10 was wrongly build, but not 2.8.11. 

I just unzipped the sbt plugin jar from 2.8.11 and picked one of the class to check, here is the output:

```
file play/core/PlayVersion.class
play/core/PlayVersion.class: compiled Java class data, version 52.0 (Java 1.8)
```

So I'm pretty sure the JDK version is correct. Of course, we can't exclude that we introduced a regression, but we will need to be able to reproduce this in order to dig deeper.

**Comment by maxcom** [comment]
I'll recheck this. Class file version is not enough.

**Comment by maxcom** [comment]
Test failed on 2.6.10 + play ws 2.1.6. It passes on 2.6.11. I'm sorry for disturbing you.

**Comment by octonato** [comment]
Uff, you scared me! 😄
