### ISSUE TITLE
Play 2.8 in JDK 17 get assets error.

### ISSUE THREAD

**Issue by counter2015** [playframework/playframework#11037]
### Play Version

```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.8")
```

### API

Scala 2.13.6

### Operating System

```
Darwin counters-MacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```

### JDK

```
openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment Corretto-17.0.0.35.2 (build 17+35-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.0.35.2 (build 17+35-LTS, mixed mode, sharing)
```
### Library Dependencies

https://github.com/iheartradio/play-swagger
```
# plugins.sbt
addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.10.6-PLAY2.8")
```

in route
```
### NoDocs ###
GET   /api/docs/swagger-ui/*file        controllers.Assets.at(path:String="/public/lib/swagger-ui", file:String)

### NoDocs ###
GET   /api/assets/*file                 controllers.Assets.versioned(path="/public", file: Asset)
```

### Expected Behavior

It should render swagger ui.

### Actual Behavior

```

! @7m1cf6ji5 - Internal server error, for (GET) [/api/docs/swagger-ui/index.html?url=/assets/swagger.json] ->
 
play.api.PlayException: Execution exception[[RuntimeException: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x1aaca7e0) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x1aaca7e0]]
	at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$3(HttpErrorHandler.scala:388)
	at scala.Option.getOrElse(Option.scala:201)
	at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:388)
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:373)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
	at handle.ErrorHandler.onServerError(ErrorHandler.scala:36)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:430)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:422)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:454)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x1aaca7e0) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x1aaca7e0
	at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:384)
	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
	at scala.util.Try$.apply(Try.scala:210)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:199)
	at play.api.libs.streams.FlattenedAccumulator.$anonfun$run$2(Accumulator.scala:216)
	Suppressed: zio.Cause$FiberTrace: Fiber failed.
A checked error was not handled.
java.lang.RuntimeException: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x1aaca7e0) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x1aaca7e0

```

In JDK 11, it works well.

**Comment by PromanSEW** [comment]
https://github.com/playframework/playframework/pull/10819

**Comment by counter2015** [comment]
> #10819
Thanks your reply.
Is that mean Play does not supoort JDK 17 in 2.8.x, and the 2.9.x will fix it ?

**Comment by mkurz** [comment]
I am closing this, even though Java 17 support is not released yet, however this specific issue described here was fixed in the master branch already.
