### ISSUE TITLE
Cannot build Play application with SBT 1.6.1

### ISSUE THREAD

**Issue by MikeEngUSA** [playframework/playframework#11087]
I recently attempted to update _SBT_ to v1.6.1, from v1.5.8. The _Play_ application used to build without problem on the earlier version of _SBT_, but fails with a very peculiar error with the latest release.
### Play Version

2.8.12

### API

Scala

### Operating System

Windows 10 Pro 64-bit (21H1)

### JDK

openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)

### Expected Behavior

1. Typing `sbt run` should result in a successful compile and run of the application.

### Actual Behavior

1. The application fails as soon as the browser is used to visit a URL on the site.

Output from `sbt run` (a URL was visited once the web-server was running):
```plain
[info] welcome to sbt 1.6.1 (Azul Systems, Inc. Java 11.0.13)
[info] loading global plugins from C:\Users\Me\.sbt\1.0\plugins
[info] loading settings for project mywebapp-build from CoffeeScript.sbt,Play.sbt,Release.sbt ...
[info] loading project definition from C:\Users\Me\src\MyWebApp\project
[info] loading settings for project root from build.sbt,version.sbt ...
[info]   __              __
[info]   \ \     ____   / /____ _ __  __
[info]    \ \   / __ \ / // __ `// / / /
[info]    / /  / /_/ // // /_/ // /_/ /
[info]   /_/  / .___//_/ \__,_/ \__, /
[info]       /_/               /____/
[info]
[info] Version 2.8.12 running Java 11.0.13
[info]
[info] Play is run entirely by the community. If you want to keep using it please consider donating:
[info] https://www.playframework.com/sponsors
[info]

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /127.0.0.1:9000

(Server started, use Enter to stop and go back to the console...)

[error] java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/Me/src/MyWebApp/public/javascripts/
[error]         at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[error]         at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[error]         at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[error]         at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
[error]         at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
[error]         at java.base/java.nio.file.Path.of(Path.java:147)
[error]         at java.base/java.nio.file.Paths.get(Paths.java:69)
[error]         at sbt.internal.inc.MappedVirtualFile$.toPath(MappedVirtualFile.scala:36)
[error]         at sbt.internal.inc.MappedFileConverter.toPath(MappedVirtualFile.scala:53)
[error]         at sbt.Sync$.$anonfun$convertFromVirtual$1(Sync.scala:175)
[error]         at sbt.internal.util.Relation$.$anonfun$switch$1(Relation.scala:58)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at sbt.internal.util.Relation$.switch(Relation.scala:56)
[error]         at sbt.Sync$.convertFromVirtual(Sync.scala:175)
[error]         at sbt.Sync$.readInfoWrapped(Sync.scala:168)
[error]         at sbt.Sync$.$anonfun$sync$1(Sync.scala:67)
[error]         at com.typesafe.sbt.web.SbtWeb$.syncMappings(SbtWeb.scala:537)
[error]         at com.typesafe.sbt.web.SbtWeb$.$anonfun$unscopedAssetSettings$40(SbtWeb.scala:293)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (Web-assets / assets) java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/Me/src/MyWebApp/public/javascripts/
[error] p.a.h.DefaultHttpErrorHandler -

! @7m9jjji8m - Internal server error, for (GET) [/] ->

play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/Me/src/MyWebApp/public/javascripts/]
        at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$8(PlayReload.scala:133)
        at scala.Option.map(Option.scala:230)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:104)
        at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:38)
        at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:156)
        at scala.util.Either$LeftProjection.map(Either.scala:573)
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:156)
        at play.sbt.run.PlayRun$.$anonfun$playRunTask$4(PlayRun.scala:80)
        at play.runsupport.Reloader.$anonfun$reload$1(Reloader.scala:496)
        at play.runsupport.Reloader$$anon$1.run(Reloader.scala:57)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/Me/src/MyWebApp/public/javascripts/
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at sbt.internal.inc.MappedVirtualFile$.toPath(MappedVirtualFile.scala:36)
        at sbt.internal.inc.MappedFileConverter.toPath(MappedVirtualFile.scala:53)
        at sbt.Sync$.$anonfun$convertFromVirtual$1(Sync.scala:175)
```
To be clear, _SBT_ appears to be treating the standard `public\javascripts` directory as though it is a URL, and is objecting to the `:` in the `file:` prefix.

Any clues as to what is happening here? Is this an issue with the `PlayScala` _SBT_ plugin with v1.6.1 of _SBT_?

**Comment by MikeEngUSA** [comment]
This could be an issue in _SBT_, rather than _Play_: https://github.com/sbt/sbt/issues/6774

**Comment by mkurz** [comment]
Seems like an probem in sbt, however I keep this ticket open and track it for the 2.8.13 release.

**Comment by mkurz** [comment]
I am pretty sure this is a Windows specific sbt bug, so https://github.com/sbt/sbt/issues/6774 is the issue to follow here.
