### ISSUE TITLE
JDK 17 support

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#11127]
### Play Version

2.8.13

### API

Scala

### Operating System

MacOS

### JDK

```
➜  ~ java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

### Expected Behavior

Running play on JDK 17 works fine

### Actual Behavior

```
[info]   __              __
[info]   \ \     ____   / /____ _ __  __
[info]    \ \   / __ \ / // __ `// / / /
[info]    / /  / /_/ // // /_/ // /_/ /
[info]   /_/  / .___//_/ \__,_/ \__, /
[info]       /_/               /____/
[info]
[info] Version 2.8.13 running Java 17.0.1
[info]
[info] Play is run entirely by the community. If you want to keep using it please consider donating:
[info] https://www.playframework.com/sponsors
[info]
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[info]   Java version is 17. Play supports only 8 and 11.
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[info]
```

Some issues we see during tests:

```
[info] RedirectFilterSpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: Could not initialize class com.typesafe.sslconfig.ssl.FakeKeyStore$KeystoreSettings$
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$.generateKeyStore(FakeKeyStore.scala:71)
[info]   at play.core.server.SelfSigned$.x$1$lzycompute(SelfSigned.scala:24)

[info] PlayCacheSpec
[info] the play cache
[info] - should correctly update an existing entry *** FAILED ***
[info]   java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @647c3190
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
[info]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[info]   at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
[info]   at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
[info]   at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getAllFields(ObjectGraphWalker.java:271)
[info]   at net.sf.ehcache.pool.sizeof.ObjectGraphWalker.getFilteredFields(ObjectGraphWalker.java:229)

[info] ServerErrorHandlingSpec *** ABORTED ***
[info]   java.lang.IllegalAccessError: class com.typesafe.sslconfig.ssl.FakeKeyStore$KeystoreSettings$ (in unnamed module @0x647c3190) cannot access class sun.security.x509.AlgorithmId (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x647c3190
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$KeystoreSettings$.<clinit>(FakeKeyStore.scala:55)
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$.generateKeyStore(FakeKeyStore.scala:71)
[info]   at play.core.server.SelfSigned$.x$1$lzycompute(SelfSigned.scala:24)
```

**Comment by arixmkii** [comment]
It is a known issue and JDK 17 support is being worked on, but only for Play 2.9 future releases https://github.com/playframework/playframework/pull/10819

**Comment by mkurz** [comment]
Like mentioned by @arixmkii we will add Java 17 support in Play 2.9. Closing because we already have #10819
