### ISSUE TITLE
Incompatibility with Heroku (Java 11, GraalVM)

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#11137]
### Play Version

2.8.13

### JDK

Java 11.0.14 (GraalVM)

### Library Dependencies

Scala 2.13.5, SBT 1.6.1

### Expected Behavior

Successfully deploy on Heroku with Java 11

### Actual Behavior

Errors while deploying and "Application Error" when opening site

Build log:

```
-----> Building on the Heroku-20 stack
-----> Deleting 4 files matching .slugignore patterns.
-----> Using buildpack: heroku/scala
-----> Play 2.x - Java app detected
-----> Installing JDK 11... done
-----> Running: sbt clean compile stage
       [info] welcome to sbt 1.6.1 (Oracle Corporation Java 11.0.14)
       Thread[JVMCI CompilerThread0,9,system]: Compilation of java.io.DataInputStream.readUTF(DataInput) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
       Failed dependency of type leaf_type
         context = java.io.ByteArrayInputStream
         witness = sun.security.util.DerInputBuffer

       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
       To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
       To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
       Retrying compilation of java.io.DataInputStream.readUTF(DataInput)

       [info] loading global plugins from /tmp/scala_buildpack_build_dir/.sbt_home/plugins
       [info] compiling 1 Scala source to /tmp/scala_buildpack_build_dir/.sbt_home/plugins/target/scala-2.12/sbt-1.0/classes ...
       [info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.15. Compiling...
       Thread[JVMCI CompilerThread0,9,system]: Compilation of scala.collection.mutable.FlatHashTable.addEntry(Object) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
       Failed dependency of type abstract_with_unique_concrete_subtype
         context = *scala.collection.mutable.FlatHashTable
         class   = scala.collection.mutable.HashSet
         witness = *scala.collection.mutable.FlatHashTable

       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
       To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
       To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
       Retrying compilation of scala.collection.mutable.FlatHashTable.addEntry(Object)

       Warning: adjusting CompilationFailureAction from Diagnose to Print after MaxCompilationProblemsPerAction (2) failed compilations
       Thread[JVMCI CompilerThread0,9,system]: Compilation of scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(Types$Type) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
       Failed dependency of type unique_concrete_method
         context = *scala.reflect.internal.tpe.TypeMaps$SubstMap
         method  = {method} {0x00007fd9c40fb9c8} 'mapOver' '(Lscala/reflect/internal/Types$Type;)Lscala/reflect/internal/Types$Type;' in 'scala/reflect/internal/tpe/TypeMaps$TypeMap'
         witness = scala.tools.nsc.transform.SpecializeTypes$FullTypeMap$1

       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
       To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
       To capture more information for diagnosing or reporting a compilation failure, set CompilationFailureAction to Diagnose or ExitVM (e.g., -Dgraal.CompilationFailureAction=Diagnose).

       [info]   Compilation completed in 17.115s.
       [warn] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin.scala:6:20: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     sources in doc in Compile := List(),
       [warn]                    ^
       [warn] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin.scala:6:13: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     sources in doc in Compile := List(),
       [warn]             ^
       [warn] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin.scala:7:21: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     publishArtifact in packageDoc := false,
       [warn]                     ^
       [warn] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin.scala:8:21: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     publishArtifact in packageSrc := false
       [warn]                     ^
       [warn] four warnings found
       [info] done compiling
       Thread[JVMCI CompilerThread0,9,system]: Compilation of scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(Types$Type) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
       Failed dependency of type unique_concrete_method
         context = *scala.reflect.internal.tpe.TypeMaps$TypeMap
         method  = {method} {0x00007fd9cad92678} 'mapOver' '(Lscala/reflect/internal/Scopes$Scope;)Lscala/reflect/internal/Scopes$Scope;' in 'scala/reflect/internal/tpe/TypeMaps$TypeMap'
         witness = scala.reflect.internal.Variances$VarianceValidator$ValidateVarianceMap$

       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
       To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
       To capture more information for diagnosing or reporting a compilation failure, set CompilationFailureAction to Diagnose or ExitVM (e.g., -Dgraal.CompilationFailureAction=Diagnose).

       [info] loading settings for project scala_buildpack_build_dir-build from plugins.sbt ...
       [info] loading project definition from /tmp/scala_buildpack_build_dir/project
       [info] loading settings for project root from build.sbt ...
       [info]   __              __
       [info]   \ \     ____   / /____ _ __  __
       [info]    \ \   / __ \ / // __ `// / / /
       [info]    / /  / /_/ // // /_/ // /_/ /
       [info]   /_/  / .___//_/ \__,_/ \__, /
       [info]       /_/               /____/
       [info] 
       [info] Version 2.8.13 running Java 11.0.14
       [info] 
       [info] Play is run entirely by the community. If you want to keep using it please consider donating:
       [info] https://www.playframework.com/sponsors
       [info] 
       [info] Executing in batch mode. For better performance use sbt's shell
       [success] Total time: 0 s, completed Jan 31, 2022, 1:22:28 PM
       [info] compiling 17 Scala sources and 13 Java sources to /tmp/scala_buildpack_build_dir/target/scala-2.13/classes ...
       [info] Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.5. Compiling...
       [info]   Compilation completed in 15.091s.
       Warning: adjusting CompilationFailureAction from Print to Silent after MaxCompilationProblemsPerAction (2) failed compilations
       [info] done compiling
       [success] Total time: 27 s, completed Jan 31, 2022, 1:22:55 PM
       [info] Wrote /tmp/scala_buildpack_build_dir/target/scala-2.13/truefishing-server-records_2.13-release.pom
       [success] Total time: 2 s, completed Jan 31, 2022, 1:22:58 PM
       Graal diagnostic output saved in /tmp/scala_buildpack_build_dir/dumps/1643635310817/graal_diagnostics_358.zip
       ....
```

**Comment by mkurz** [comment]
Please try again with latest Scala 2.13.8

**Comment by PromanSEW** [comment]
@mkurz other errors:
```
-----> Building on the Heroku-20 stack
-----> Deleting 4 files matching .slugignore patterns.
-----> Using buildpack: heroku/scala
-----> Play 2.x - Java app detected
-----> Installing JDK 11... done
-----> Running: sbt clean compile stage
       [info] welcome to sbt 1.6.1 (Oracle Corporation Java 11.0.14)
       [info] loading global plugins from /tmp/scala_buildpack_build_dir/.sbt_home/plugins
       [info] compiling 1 Scala source to /tmp/scala_buildpack_build_dir/.sbt_home/plugins/target/scala-2.12/sbt-1.0/classes ...
       Thread[JVMCI CompilerThread0,9,system]: Compilation of java.util.zip.ZipUtils.dosToJavaTime(long) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
       Failed dependency of type abstract_with_unique_concrete_subtype
         context = *java.util.TimeZone
         class   = sun.util.calendar.ZoneInfo
         witness = java.util.SimpleTimeZone

       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
       To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
       To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
       Retrying compilation of java.util.zip.ZipUtils.dosToJavaTime(long)


       [warn] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin.scala:6:20: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     sources in doc in Compile := List(),
       [warn]                    ^
       [warn] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin.scala:6:13: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     sources in doc in Compile := List(),
       [warn]             ^
       [warn] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin.scala:7:21: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     publishArtifact in packageDoc := false,
       [warn]                     ^
       [warn] /tmp/scala_buildpack_build_dir/.sbt_home/plugins/HerokuBuildpackPlugin.scala:8:21: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
       [warn]     publishArtifact in packageSrc := false
       [warn]                     ^
       Thread[JVMCI CompilerThread0,9,system]: Compilation of scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(Types$Type) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
       Failed dependency of type unique_concrete_method
         context = *scala.reflect.internal.tpe.TypeMaps$SubstMap
         method  = {method} {0x00007fca1bf01c50} 'mapOver' '(Lscala/reflect/internal/Types$Type;)Lscala/reflect/internal/Types$Type;' in 'scala/reflect/internal/tpe/TypeMaps$TypeMap'
         witness = scala.tools.nsc.transform.SpecializeTypes$FullTypeMap$1

       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
       To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
       To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
       Retrying compilation of scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(Types$Type)

       [warn] four warnings found
       [info] done compiling
       [info] loading settings for project scala_buildpack_build_dir-build from plugins.sbt ...
       [info] loading project definition from /tmp/scala_buildpack_build_dir/project
       [info] loading settings for project root from build.sbt ...
       [info]   __              __
       [info]   \ \     ____   / /____ _ __  __
       [info]    \ \   / __ \ / // __ `// / / /
       [info]    / /  / /_/ // // /_/ // /_/ /
       [info]   /_/  / .___//_/ \__,_/ \__, /
       [info]       /_/               /____/
       [info] 
       [info] Version 2.8.13 running Java 11.0.14
       [info] 
       [info] Play is run entirely by the community. If you want to keep using it please consider donating:
       [info] https://www.playframework.com/sponsors
       [info] 
       [info] Executing in batch mode. For better performance use sbt's shell
       [success] Total time: 0 s, completed Jan 31, 2022, 2:11:58 PM
       [info] compiling 17 Scala sources and 13 Java sources to /tmp/scala_buildpack_build_dir/target/scala-2.13/classes ...
       [info] Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.8. Compiling...
       [info]   Compilation completed in 15.934s.
       Warning: adjusting CompilationFailureAction from Diagnose to Print after MaxCompilationProblemsPerAction (2) failed compilations
       Thread[JVMCI CompilerThread0,9,system]: Compilation of scala.tools.nsc.backend.jvm.BTypesFromSymbols.primitiveOrClassToBType$1(Symbols$Symbol) failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
       Failed dependency of type leaf_type
         context = scala.tools.nsc.Global
         witness = *xsbt.CallbackGlobal

       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
       To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
       To capture more information for diagnosing or reporting a compilation failure, set CompilationFailureAction to Diagnose or ExitVM (e.g., -Dgraal.CompilationFailureAction=Diagnose).

       Thread[JVMCI CompilerThread0,9,system]: Compilation of scala.tools.nsc.ast.parser.Scanners$Scanner.nextToken() failed: java.lang.AssertionError: dependencies invalid Code installation failed: dependencies invalid
       Failed dependency of type leaf_type
         context = scala.tools.nsc.ast.parser.Scanners$UnitScanner
         witness = scala.tools.nsc.ast.parser.Scanners$ParensAnalyzer

       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotCodeCacheProvider.installCode(HotSpotCodeCacheProvider.java:130)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.target.Backend.createInstalledCode(Backend.java:214)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.installMethod(CompilationTask.java:370)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:191)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:98)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:330)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:144)
       	at jdk.internal.vm.compiler@11.0.14/org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:111)
       	at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:524)
       To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
       To capture more information for diagnosing or reporting a compilation failure, set CompilationFailureAction to Diagnose or ExitVM (e.g., -Dgraal.CompilationFailureAction=Diagnose).

       [info] done compiling
       [success] Total time: 31 s, completed Jan 31, 2022, 2:12:28 PM
       [info] Wrote /tmp/scala_buildpack_build_dir/target/scala-2.13/truefishing-server-records_2.13-release.pom
       [success] Total time: 2 s, completed Jan 31, 2022, 2:12:31 PM
       Graal diagnostic output saved in /tmp/scala_buildpack_build_dir/dumps/1643638298906/graal_diagnostics_357.zip
```

**Comment by mkurz** [comment]
I never used GraalVM, maybe this helps: https://www.playframework.com/blog/play-on-graal

**Comment by rbueker** [comment]
I had the same issue.

The problem occurs when using (Oracle Corporation Java 11.0.14). This is the current default JDK11 on Heroku.

Setting the system.properties file to:
`java.runtime.version=11.0.13`

Allows the build to proceed using (Oracle Corporation Java 11.0.13) without the various graalvm errors.

**Comment by PromanSEW** [comment]
@rbueker I tried this but got Application Error anyway. While using 11.0.13 locally there are no errors, at least in dev mode. I will try to run in production...

**Comment by PromanSEW** [comment]
I crteated new app with the same codebase, and it does not crash... LOL
I swap apps, and all works. Thanks @rbueker

**Comment by rbueker** [comment]
Heroku support should release an updated scala buildpack this week that should fix the graalvm compiler warnings.

**Comment by mkurz** [comment]
Good this is resolved!
