### ISSUE TITLE
Truncated POST request leads to error in the logging

### ISSUE THREAD

**Issue by raboof** [playframework/playframework#11194]
### Play Version

2.8.8

### API

Scala

### Operating System

Linux rigter 5.16.5 #1-NixOS SMP PREEMPT Tue Feb 1 16:29:20 UTC 2022 x86_64 GNU/Linux

### JDK

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Expected Behavior

1. A client performs an HTTP POST requests, but due to some kind of problem the request is truncated
2. Play should respond by either closing the connection or producing a HTTP 4xx status code

### Actual Behavior

The `EntityStreamException` thrown by Akka HTTP in this situation is logged as an error in the logging:

```
play.api.PlayException: Execution exception[[EntityStreamException: Entity stream truncation. The HTTP parser was receiving an entity when the underlying connection was closed unexpectedly.]]
	at play.api.http.HttpErrorHandlerExceptions$.$anonfun$convertToPlayException$3(HttpErrorHandler.scala:388)
	at scala.Option.getOrElse(Option.scala:201)
	at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:388)
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:373)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:430)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:422)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:454)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
Caused by: akka.http.scaladsl.model.EntityStreamException: Entity stream truncation. The HTTP parser was receiving an entity when the underlying connection was closed unexpectedly.
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$1.applyOrElse(HttpMessageParser.scala:351)
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$1.applyOrElse(HttpMessageParser.scala:349)
	at akka.stream.impl.fusing.Collect$$anon$6.$anonfun$wrappedPf$1(Ops.scala:243)
	at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:202)
	at akka.stream.impl.fusing.Collect$$anon$6.onPush(Ops.scala:245)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:495)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
```

... and the request is responded to with a HTTP 500 status code.

### Reproducible Test Case

(stay tuned, will add shortly)

**Comment by jrudolph** [comment]
Isn't the problem only triggered by aborting the connection? In that case, there's no good way to report an error back to the client.

I guess the most important thing would be to avoid the error log in that case.

**Comment by raboof** [comment]
> Isn't the problem only triggered by aborting the connection? In that case, there's no good way to report an error back to the client.

It's also triggered by closing the request side normally before finishing writing all the bytes you promised in the `Content-length` header.

> I guess the most important thing would be to avoid the error log in that case.

Agreed

**Comment by jrudolph** [comment]
> It's also triggered by closing the request side normally before finishing writing all the bytes you promised in the `Content-length` header (e.g. [raboof/play-reproduce-truncated-request-11194@`main`/Main.scala#L13](https://github.com/raboof/play-reproduce-truncated-request-11194/blob/main/Main.scala#L13))

You mean making use of half-closed connections? Ok, in that case, a client might be able to read the result, though, there's a lot that can go wrong if not the whole pipeline makes it work.

Probably it would be enough to add a new case at 

https://github.com/playframework/playframework/blob/6e3403ec43ff3f633668ef147172e8c541bacd5e/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L430

to handle that particular error as a client error instead of a server error. Unfortunately, it doesn't seem to be easily possible to distinguish client and server errors more generally. Maybe, it would be possible to add another `recoverWith` directly to the request entity source and rethrow the exception to flag it as a client exception? Not sure, it's worth it just for this case.

**Comment by gheine** [comment]
We came across the same issue and were able to convert the EntityStreamException from a 500 back into a 400 by adding this to the `play.filters.enabled`:

```
class StreamTruncationFilter @Inject() (
)(implicit
  val mat: Materializer,
  ec: ExecutionContext,
) extends Filter {
  private val logger = Logger(classOf[StreamTruncationFilter])
  override def apply(nextFilter: RequestHeader => Future[Result])(requestHeader: RequestHeader): Future[Result] =
    nextFilter(requestHeader).recoverWith { case e: EntityStreamException =>
      logger.info("Converting EntityStreamException to 400 status code", e)
      Future.successful(Results.Status(400): Result)
    }
}
```

**Comment by mkurz** [comment]
@gheine Any chance you can come up with a pull request to get this fixed in Play itself?
