### ISSUE TITLE
JDK 17 IllegalAccessError because Play listens to https port in tests

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#11209]
### Play Version

2.8.14

### API

Scala

### Operating System

Darwin hostname.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

### JDK

```
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)
```

### Expected Behavior

We can run tests using OneServerPerSuiteWithComponents/GuiceOneServerPerTest

### Actual Behavior

We get his error during test startup

```
[info] filters.shared.RedirectFilterSpec *** ABORTED ***
[info]   java.lang.IllegalAccessError: class com.typesafe.sslconfig.ssl.FakeKeyStore$ (in unnamed module @0x59505b48) cannot access class sun.security.x509.X509CertInfo (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x59505b48
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$.createSelfSignedCertificate(FakeKeyStore.scala:89)
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$.generateKeyStore(FakeKeyStore.scala:79)
[info]   at play.core.server.SelfSigned$.x$1$lzycompute(SelfSigned.scala:24)
[info]   at play.core.server.SelfSigned$.x$1(SelfSigned.scala:23)
[info]   at play.core.server.SelfSigned$.sslContext$lzycompute(SelfSigned.scala:23)
[info]   at play.core.server.SelfSigned$.sslContext(SelfSigned.scala:23)
[info]   at play.core.server.SelfSignedSSLEngineProvider.sslContext(SelfSigned.scala:36)
[info]   at play.core.server.AkkaHttpServer.sslContext$lzycompute(AkkaHttpServer.scala:245)
[info]   at play.core.server.AkkaHttpServer.sslContext(AkkaHttpServer.scala:244)
[info]   at play.core.server.AkkaHttpServer.$anonfun$httpsServerBinding$1(AkkaHttpServer.scala:260)
```

### Reproducible Test Case

```scala
class RedirectFilterSpec extends PlaySpec with OneServerPerSuiteWithComponents with WsTestClient { 

  override lazy val components = new BuiltInComponentsFromContext(context) with RedirectHttpsComponents {
    ...
  }

  ...
}
```

**Comment by mkurz** [comment]
Will look into this today, thanks!

**Comment by francisdb** [comment]
@mkurz let me know if you need more info or if you can't reproduce this

**Comment by mkurz** [comment]
@francisdb Even though you are not touching anything with certificates yourself probably, this fails because Play binds to both http and https ports when using `OneServerPerTestWithComponents` or `GuiceOneServerPerTest`. I am not going to change that right now in Play 2.8.x but will think about what to do about that in Play 2.9. As a workaround you have to add

```sbt
Test / javaOptions ++= Seq(
  "--add-exports=java.base/sun.security.x509=ALL-UNNAMED",
  //"--add-opens=java.base/sun.security.ssl=ALL-UNNAMED" // Could be needed as well in some cases
)
// Test / fork := true // This is the default anyway, just a reminder in case you changed that to false
```
to your `build.sbt` (of course just remove the comments if you don't need that stuff).

---

Notes for 2.9:
The "problem" here is that `DefaultTestServerFactory` binds to both ports [here](https://github.com/playframework/playframework/blob/0f2d75a8fd62681592e50a4ad40c03c10c2d9193/testkit/play-test/src/main/scala/play/api/test/TestServerFactory.scala#L64). Based on [these comments](https://github.com/playframework/playframework/blob/0f2d75a8fd62681592e50a4ad40c03c10c2d9193/testkit/play-test/src/main/scala/play/api/test/TestServerFactory.scala#L25-L26) that is intentional. `DefaultTestServerFactory` was introduced in #8689. If you look closer in that PR you will see that `DefaultTestServerFactory` is used
- in `ForServer`, which is a replacement for `WithServer`. But if you look at `WithServer` you will see it only binds on the http port, but not the https port, but `ForServer` binds on both... 
- and in the ServerEndpoints, however there the ports are [overriden anyway](https://github.com/playframework/playframework/pull/8689/files#diff-cddba9b5d4c5d1548fe3ac3c3ee469fe846d2a99a63e3f1a154377af87f1925fR151-R154).

scalatestplus-play then made use of `DefaultTestServerFactory` as well in [BaseOneServerPerTest](https://github.com/playframework/scalatestplus-play/blob/096e1cfab69165969e1f276fbdc1b5641d69e903/module/src/main/scala/org/scalatestplus/play/BaseOneServerPerTest.scala#L109) and [BaseOneServerPerSuite](https://github.com/playframework/scalatestplus-play/blob/096e1cfab69165969e1f276fbdc1b5641d69e903/module/src/main/scala/org/scalatestplus/play/BaseOneServerPerSuite.scala#L145), again always bindig to both ports. Now if we look the diff when [that got introduced](https://github.com/playframework/scalatestplus-play/commit/9302e4b4eb70acda1f9f83cd3ca9202608045951) we see that before a test server was created by using `TestServer(port, app)`, which, again, did _not_ bind the https port...

So the question is should we just remove the http binding of `DefaultTestServerFactory`, like it was before? Why is it even necessary to bind on both ports in test?
What speaks for removal as well is that the `GuiceOneServerPerTest` (=`BaseOneServerPerTest`) only [provides a `port/portNumber` field](https://github.com/playframework/scalatestplus-play/blob/096e1cfab69165969e1f276fbdc1b5641d69e903/module/src/main/scala/org/scalatestplus/play/ServerProvider.scala#L48-L61) (however it is still possible to access the https port via `runningServer.endpoints.httpsEndpoint`). The question is how likely someon makes use of that https port?

As an alternative we could keep the https binding and either just document that java flags are needed on Java 17 (which I don't think is a good idea because a lot of people will run into that problem), or to add just the the `--add-exports/--add-opens` to the `Test / javaOptions` by default (then it would be nice if we drop Java 8 before :wink:) BTW: Adding [`Add-Exports:...` in manifest](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B) is probably not an option, see http://mail.openjdk.java.net/pipermail/core-libs-dev/2017-August/048830.html

**Comment by mkurz** [comment]
Also now that #11173 got merged, and in keys we keep the https binding for `DefaultTestServerFactory`, we might want to introduce `Helpers.testServerHttpsPort`... See https://github.com/playframework/playframework/pull/11173#issuecomment-1081109412

**Comment by francisdb** [comment]
Maybe the https part could be optional so by default everything works as expected without extra config?

**Comment by francisdb** [comment]
Thanks for looking into this, put some money in the sponsor jar.

**Comment by pk044** [comment]
FYI - I receive a similar error when running Play on prod mode:

```java
[2022-08-17 09:18:18.653] ERROR - play.core.server.AkkaHttpServer -  - Cannot load SSL context
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:116)
	at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:39)
	at play.core.server.AkkaHttpServer.sslContext$lzycompute(AkkaHttpServer.scala:246)
	at play.core.server.AkkaHttpServer.sslContext(AkkaHttpServer.scala:245)
	at play.core.server.AkkaHttpServer.$anonfun$httpsServerBinding$1(AkkaHttpServer.scala:261)
	at play.core.server.AkkaHttpServer.$anonfun$httpsServerBinding$1$adapted(AkkaHttpServer.scala:256)
	at scala.Option.map(Option.scala:242)
	at play.core.server.AkkaHttpServer.<init>(AkkaHttpServer.scala:256)
	at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:671)
	at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:669)
	at play.core.server.ServerProvider.createServer(ServerProvider.scala:29)
	at play.core.server.ServerProvider.createServer$(ServerProvider.scala:26)
	at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:669)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:59)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.IllegalAccessError: class com.typesafe.sslconfig.ssl.FakeKeyStore$ (in unnamed module @0x2cfb4a64) cannot access class sun.security.x509.X509CertInfo (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x2cfb4a64
	at com.typesafe.sslconfig.ssl.FakeKeyStore$.createSelfSignedCertificate(FakeKeyStore.scala:89)
	at com.typesafe.sslconfig.ssl.FakeKeyStore$.generateKeyStore(FakeKeyStore.scala:79)
	at com.typesafe.sslconfig.ssl.FakeKeyStore.createKeyStore(FakeKeyStore.scala:182)
	at com.typesafe.sslconfig.ssl.FakeKeyStore.keyManagerFactory(FakeKeyStore.scala:218)
	at play.core.server.ssl.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:65)
	at play.core.server.ssl.DefaultSSLEngineProvider.<init>(DefaultSSLEngineProvider.scala:30)
	... 21 common frames omitted
```

**Comment by mkurz** [comment]
@pk044 Like explained above you need to add the `--add-exports` argument.

**Comment by xuwei-k** [comment]
`NoSuchMethodError` with JDK 20 😭 

https://github.com/openjdk/jdk/commit/671f84bd8625ea7e06fa8272ae629309df06e9ca#diff-e2fdd59bc2993aaf489f089d6b2df20d3661d4a65e3a42c23664a824acd5bf67L342

```
[info]   java.lang.NoSuchMethodError: 'void sun.security.x509.X509CertInfo.set(java.lang.String, java.lang.Object)'
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$.createSelfSignedCertificate(FakeKeyStore.scala:92)
[info]   at com.typesafe.sslconfig.ssl.FakeKeyStore$.generateKeyStore(FakeKeyStore.scala:79)
[info]   at play.core.server.SelfSigned$.$1$$lzyINIT1(SelfSigned.scala:24)
[info]   at play.core.server.SelfSigned$.$1$(SelfSigned.scala:23)
[info]   at play.core.server.SelfSigned$.sslContext(SelfSigned.scala:23)
[info]   at play.core.server.SelfSignedSSLEngineProvider.sslContext(SelfSigned.scala:36)
[info]   at play.core.server.AkkaHttpServer.sslContext$lzyINIT1(AkkaHttpServer.scala:240)
[info]   at play.core.server.AkkaHttpServer.sslContext(AkkaHttpServer.scala:240)
[info]   at play.core.server.AkkaHttpServer.$init$$$anonfun$5(AkkaHttpServer.scala:255)
[info]   at play.core.server.AkkaHttpServer.$init$$$anonfun$adapted$2(AkkaHttpServer.scala:263)
```

**Comment by mkurz** [comment]
@xuwei-k That sucks. Did that happen while running tests?

**Comment by mkurz** [comment]
This issue definitely needs to be addressed before 2.9 final.

**Comment by xuwei-k** [comment]
> happen while running tests?

yes

**Comment by xuwei-k** [comment]
- https://github.com/lightbend/ssl-config/issues/367

**Comment by xuwei-k** [comment]
another workaround with scalatestplus-play

```scala
  protected override implicit lazy val runningServer: RunningServer =
    new DefaultTestServerFactory() {
      protected override def serverConfig(app: Application) =
        super.serverConfig(app).copy(
          port = Some(0),
          sslPort = None // disable ssl port due to https://github.com/playframework/playframework/issues/11209
        )
    }.start(app)
```

**Comment by xuwei-k** [comment]
- https://github.com/playframework/scalatestplus-play/pull/410 🤔

**Comment by mkurz** [comment]
Not sure I mentioned that here already but I added following to the play-examples: https://github.com/playframework/play-samples/blob/2e35a5f9a01a6c7358f631b2916dbe6ff7315b51/play-scala-grpc-example/test/test/HelloSpecs2Spec.scala#L25-L29
Need to take a look at this as well.

**Comment by mkurz** [comment]
Looking at this now, this is bascially the last thing blocking us before cutting a RC for Play 2.9

**Comment by xuwei-k** [comment]
Thanks! 👍
