### ISSUE TITLE
[2.4.0]Threads are not getting release in play Framework

### ISSUE THREAD

**Issue by amitkumaryadav2** [playframework/playframework#11218]
We are sending an http request to remote server(Where we are using flask framework) which return stream of data. So when all the data is transferred as a stream from using play framework, the threads are not getting released. Is there a way to release threads. We are just streaming the data from the remote server to the end customer, not reading the data at any place.

### Play Version

2.4.0

### API

Java 

### Operating System

ubuntu

### JDK

Java8

### Expected Behavior

1. After the full data is passed through play framework, all the threads should get released, for all the status codes i.e 200, 400s or 500s.

### Actual Behavior

1. After the full data is passed through play  framework, the threads are getting released only when the status code is not 200 i.e threads are getting released for 400s or 500s but not for 200 status code.

### Stack Trace

application-akka.actor.default-dispatcher-116
PRIORITY : 5

THREAD ID : 0X00007FD5D4003000

NATIVE ID : 0X1A1

NATIVE ID (DECIMAL) : 417

STATE : RUNNABLE

stackTrace:
```
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
at java.net.SocketInputStream.read(SocketInputStream.java:171)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:161)
at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:276)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:294)
at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)
at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:207)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:679)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:481)
at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.mindtickle.selfserve.controllers.mtapi.MTAPIAnalyticsV2Controller.odata(MTAPIAnalyticsV2Controller.java:83)
at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$62$$anonfun$apply$62.apply(Routes.scala:1845)
at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$62$$anonfun$apply$62.apply(Routes.scala:1845)
at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:65)
at com.mindtickle.selfserve.RequestHandler$1.call(RequestHandler.java:26)
```

**Comment by PromanSEW** [comment]
2.4.x is EOL many time ago, and does not get updates

**Comment by amitkumaryadav2** [comment]
> 2.4.x is EOL many time ago, and does not get updates

@PromanSEW Will this issue is resolved if we update our version

**Comment by PromanSEW** [comment]
@amitkumaryadav2 sorry I don't know. 2.4 is too old, You need to follow migration guides for correct update to latest 2.8.x version
Your code won't compile without changes, I sure

**Comment by mkurz** [comment]
Like said by @PromanSEW already, Play 2.4.x is very out of date, there is no support for it anymore. You should upgrade to latest Play 2.8 as soon as possible, however that will be quite some work. Best thing is to upgrade version after version, so from 2.4 -> 2.5, then from 2.5 -> 2.6, and so on until 2.8.x. You always have to follow the migration guides for each migration step:
* https://www.playframework.com/documentation/latest/Migration25
* https://www.playframework.com/documentation/latest/Migration26
* https://www.playframework.com/documentation/latest/Migration27
* https://www.playframework.com/documentation/latest/Migration28

Also its good to look at the highlights of each release:
* https://www.playframework.com/documentation/latest/Highlights25
* https://www.playframework.com/documentation/latest/Highlights26
* https://www.playframework.com/documentation/latest/Highlights27
* https://www.playframework.com/documentation/latest/Highlights28

Unfortunately I don't think I can help you here. I only see you use Apache HttpClient, so maybe you do something wrong there and it isn't even a problem with Play? Not sure however.

**Comment by jilen** [comment]
Seems you are makeing blocking http call inside default thread pool, that could be very dangerous.

**Comment by PromanSEW** [comment]
Can be closed. `2.4.x` won't get updates

**Comment by raja-anbazhagan** [comment]
Is there proper documentation of when each version was EOL'ed?
