### ISSUE TITLE
com.google.inject.ProvisionException: Unable to provision, see the following errors: Error in custom provider, java.lang.RuntimeException: Failed to build Android Driver.

### ISSUE THREAD

**Issue by vishalsoni89** [playframework/playframework#11254]
**I am trying to run the automation tests but constantly getting below errors. Any help would be highly appreciated. Thanks in advance.**

```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: Failed to build Android Driver.
  while locating com.firstdirect.bankingonthego.switcher.fd.appiumdriver.AppiumDriverProvider
  while locating io.appium.java_client.AppiumDriver
    for the 1st parameter of com.firstdirect.bankingonthego.switcher.fd.screens.android.helppages.HelpCardsScreen.<init>(HelpCardsScreen.java:82)
  while locating com.firstdirect.bankingonthego.switcher.fd.screens.android.helppages.HelpCardsScreen
  while locating com.firstdirect.bankingonthego.switcher.fd.interfaces.help.HelpCards
    for the 1st parameter of com.firstdirect.bankingonthego.switcher.fd.steps.HelpSteps.HelpCardsStep.<init>(HelpCardsStep.java:17)
  while locating com.firstdirect.bankingonthego.switcher.fd.steps.HelpSteps.HelpCardsStep
Caused by: java.lang.RuntimeException: Failed to build Android Driver.
	at com.firstdirect.bankingonthego.switcher.fd.appiumdriver.drivers.MobileAndroidDriver.buildAndroidDriver(MobileAndroidDriver.java:67)
	at com.firstdirect.bankingonthego.switcher.fd.appiumdriver.AppiumDriverProvider.get(AppiumDriverProvider.java:61)
	at com.firstdirect.bankingonthego.switcher.fd.appiumdriver.AppiumDriverProvider.get(AppiumDriverProvider.java:22)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at cucumber.runtime.java.guice.impl.GuiceFactory.getInstance(GuiceFactory.java:42)
	at cucumber.runtime.java.ObjectFactoryLoader$ObjectFactoryAdapter.getInstance(ObjectFactoryLoader.java:157)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:150)
	at cucumber.runner.Runner.buildBackendWorlds(Runner.java:130)
	at cucumber.runner.Runner.runPickle(Runner.java:48)
	at io.cucumber.junit.PickleRunners$WithStepDescriptions.run(PickleRunners.java:97)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:144)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:65)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:174)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:63)
Caused by: java.lang.RuntimeException: Failed to generate Android capabilities
	at com.firstdirect.bankingonthego.switcher.fd.appiumdriver.drivers.MobileAndroidDriver.getCapabilities(MobileAndroidDriver.java:48)
	at com.firstdirect.bankingonthego.switcher.fd.appiumdriver.drivers.MobileAndroidDriver.buildAndroidDriver(MobileAndroidDriver.java:64)
	... 54 more
Caused by: java.io.IOException: Cannot run program "adb": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.firstdirect.bankingonthego.switcher.fd.configuration.MyAndroidModule.execCommand(MyAndroidModule.java:58)
	at com.firstdirect.bankingonthego.switcher.fd.configuration.MyAndroidModule.osVersion(MyAndroidModule.java:36)
	at com.firstdirect.bankingonthego.switcher.fd.appiumdriver.drivers.MobileAndroidDriver.getCapabilities(MobileAndroidDriver.java:30)
	... 55 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 61 more
```

**Comment by mkurz** [comment]
This has nothing to do with Play. Your project in general is not set up correctly.
```
Caused by: java.io.IOException: Cannot run program "adb": error=2, No such file or directory
```
So the project tries to run `adb` (Android Debug Bridge), but it isn't available... So that is a starting point. adb has absolutly nothing to do with Play.

I am closing this, if you need (Play related) help freel free to comment.
