### ISSUE TITLE
Fails to convert error to PlayException/UsefulException

### ISSUE THREAD

**Issue by philipwhiuk** [playframework/playframework#11303]
### Play Version

2.8.15

### API

Scala

### Operating System

Windows 10

### JDK

sbt 1.6.2 (Oracle Corporation Java 1.8.0_191-1-redhat)

### Library Dependencies

N/A

### Expected Behavior

Server should either load the page or provide an actual error stack trace

### Actual Behavior

Server fails to convert error:

{code}
2022-06-01 17:12:44 ERROR p.api.http.DefaultHttpErrorHandler  Error while handling error
java.lang.NullPointerException: null
	at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:377)
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:367)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:109)
	at play.core.server.Server$$anonfun$handleErrors$1$1.applyOrElse(Server.scala:105)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at play.core.server.Server$.getHandlerFor(Server.scala:129)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:317)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:224)
	at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1307)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

{code}

**Comment by philipwhiuk** [comment]
One way to reproduce this error is to have a custom Guice Module fail to bind a required property due to an NPE.

Finally found in my project by improving testing on the GuiceModule.

**Comment by gmethvin** [comment]
My guess is that `getCause` here is returning null: https://github.com/playframework/playframework/blob/a898ec0f88246f1d20f5af698d7d0b6df7c1b366/core/play/src/main/scala/play/api./http/HttpErrorHandler.scala#L365. So maybe in that case we fall back to the original exception.

**Comment by mkurz** [comment]
Yeah, most likely `getCause` is `null` here.
@philipwhiuk can you share a code snippet that shows how to enforce this problem, saves me time, thanks!
