### ISSUE TITLE
Upgrade slf4j to 2.0.0

### ISSUE THREAD

**Issue by mrooneytrimble** [playframework/playframework#11400]
slf4j has recently been upgraded by a major version, in order to use current versions of dependent libraries (logback-core, logback-classic) we need playframework to upgrade the version of slf4j to 2.0.0 as well.

### Play Version

2.8.16

### API

scala

### Operating System

Mac

### Library Dependencies

logback-classic, logback-core 1.4.0

### Expected Behavior

The server is able to initialise

### Actual Behavior

The server cannot startup because the version of slf4j is incompatible

```
[error] java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.loggerFactory(LogbackLoggerConfigurator.scala:21)
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:84)
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.init(LogbackLoggerConfigurator.scala:31)
[error] 	at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:106)
[error] 	at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error] 	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:76)
[error] 	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
[error] 	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:100)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:83)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:107)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.loggerFactory(LogbackLoggerConfigurator.scala:21)
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:84)
[error] 	at play.api.libs.logback.LogbackLoggerConfigurator.init(LogbackLoggerConfigurator.scala:31)
[error] 	at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:106)
[error] 	at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
[error] 	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:76)
[error] 	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
[error] 	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:100)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:83)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:107)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
```

**Comment by PromanSEW** [comment]
See https://github.com/playframework/playframework/discussions/11399

**Comment by mkurz** [comment]
Let's assign 2.9.0. @jfsoul @mrooneytrimble Do you have time to work on this and provide a pull request?
BTW: I would not upgrade in the 2.8.x branch, to not break anything, but maybe it would be possible to adjust code so at least it would be possible to upgrade by hand when using Play 2.8. Not sure though if that works.

**Comment by benthecarman** [comment]
is there a way to resolve this?

**Comment by jfsoul** [comment]
@mkurz I had a quick look and I'm wondering whether we can resolve on `2.8.x` fairly simply after all.

In https://github.com/playframework/playframework/compare/2.8.x...jfsoul:playframework:2.8.x if we replace the direct reference to `StaticLoggerBinder` with call to the factory method, then we should be able to work with SLF4J 1 or 2 because the factory finds the logging backend for us.

It looks like that used to be the way it was done until [this change](https://github.com/playframework/playframework/pull/6025/files?diff=split&w=1) although I don't understand the reason for changing to use `StaticLoggerBinder` directly, so I'm a little hesitant.

I can spend a bit more time on it and PR, if this sounds reasonable.

**Comment by wsargent** [comment]
The StaticLoggerBinder isn't significant -- a reference to `LoggerFactory.getILoggerFactory()` will work just as well.

**Comment by mkurz** [comment]
Thanks @jfsoul, can you provide a pull request with your change?

**Comment by mkurz** [comment]
Unfortunately two tests are failing when upgrading to slf4j v2, someone wants to help and take a look? For details see: https://github.com/playframework/playframework/pull/11419#issuecomment-1252108130
