### ISSUE TITLE
[play-samples-play-scala-hello-world-tutorial] Some unresolved dependencies have extra attributes.

### ISSUE THREAD

**Issue by XingLiu0923** [playframework/playframework#11596]
### Discussed in https://github.com/orgs/playframework/discussions/11595

<div type='discussions-op-text'>

<sup>Originally posted by **XingLiu0923** January  3, 2023</sup>
I used dockerfile below to build [play-samples-play-scala-hello-world-tutorial](https://github.com/playframework/play-samples/tree/2.8.x/play-scala-hello-world-tutorial)

```
FROM openjdk:11

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV HULU_ENV=staging

ADD . /play-samples-play-scala-hello-world-tutorial
WORKDIR /play-samples-play-scala-hello-world-tutorial
RUN curl -L https://github.com/sbt/sbt/releases/download/v1.5.2/sbt-1.5.2.tgz -o sbt.tgz
RUN tar xf sbt.tgz

RUN ./sbt/bin/sbt clean stage
```

but got error below and failed to build

```
docker build . -f Dockerfile

#11 0.595 copying runtime jar...                                                                                             
#11 7.202 [info] [launcher] getting org.scala-sbt sbt 1.7.2  (this may take some time)...                                    
#11 37.07 [info] [launcher] getting Scala 2.12.16 (for sbt)...                                                               
#11 40.32 [info] welcome to sbt 1.7.2 (Oracle Corporation Java 11.0.16)                                                      
#11 42.57 [info] loading settings for project serengeti-build from plugins.sbt,scaffold.sbt ...
#11 43.22 [info] loading project definition from /serengeti/project
#11 69.16 [warn] 
#11 69.16 [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
#11 69.16 [warn] 		com.typesafe.sbt:sbt-js-engine:1.2.3 (scalaVersion=2.12, sbtVersion=1.0)
#11 69.16 [warn] 		org.foundweekends.giter8:sbt-giter8-scaffold:0.11.0 (sbtVersion=1.0, scalaVersion=2.12)
#11 69.16 [warn] 		com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0)
#11 69.16 [warn] 		com.lightbend.sbt:sbt-javaagent:0.1.5 (scalaVersion=2.12, sbtVersion=1.0)
#11 69.16 [warn] 		com.typesafe.sbt:sbt-twirl:1.5.1 (scalaVersion=2.12, sbtVersion=1.0)
#11 69.16 [warn] 		com.typesafe.sbt:sbt-web:1.4.4 (scalaVersion=2.12, sbtVersion=1.0)
#11 69.16 [warn] 
#11 69.16 [warn] 	Note: Unresolved dependencies path:
#11 69.25 [error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-js-engine;sbtVersion=1.0;scalaVersion=2.12:1.2.3
#11 69.25 [error]   Not found
#11 69.25 [error]   Not found
#11 69.25 [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-js-engine_2.12_1.0/1.2.3/sbt-js-engine-1.2.3.pom
#11 69.25 [error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
#11 69.25 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
#11 69.25 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
#11 69.25 [error] Error downloading org.foundweekends.giter8:sbt-giter8-scaffold;sbtVersion=1.0;scalaVersion=2.12:0.11.0
#11 69.25 [error]   Not found
#11 69.25 [error]   Not found
#11 69.25 [error]   not found: https://repo1.maven.org/maven2/org/foundweekends/giter8/sbt-giter8-scaffold_2.12_1.0/0.11.0/sbt-giter8-scaffold-0.11.0.pom
#11 69.25 [error]   not found: /root/.ivy2/localorg.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml
#11 69.25 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml
#11 69.25 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml
#11 69.25 [error] Error downloading com.typesafe.sbt:sbt-native-packager;sbtVersion=1.0;scalaVersion=2.12:1.5.2
#11 69.25 [error]   Not found
#11 69.25 [error]   Not found
#11 69.25 [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.5.2/sbt-native-packager-1.5.2.pom
#11 69.25 [error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
#11 69.25 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
#11 69.25 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
#11 69.25 [error] Error downloading com.lightbend.sbt:sbt-javaagent;sbtVersion=1.0;scalaVersion=2.12:0.1.5
#11 69.25 [error]   Not found
#11 69.25 [error]   Not found
#11 69.25 [error]   not found: https://repo1.maven.org/maven2/com/lightbend/sbt/sbt-javaagent_2.12_1.0/0.1.5/sbt-javaagent-0.1.5.pom
#11 69.25 [error]   not found: /root/.ivy2/localcom.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml
#11 69.25 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml
#11 69.25 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml
#11 69.25 [error] Error downloading com.typesafe.sbt:sbt-twirl;sbtVersion=1.0;scalaVersion=2.12:1.5.1
#11 69.25 [error]   Not found
#11 69.26 [error]   Not found
#11 69.26 [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-twirl_2.12_1.0/1.5.1/sbt-twirl-1.5.1.pom
#11 69.26 [error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml
#11 69.26 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml
#11 69.26 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml
#11 69.26 [error] Error downloading com.typesafe.sbt:sbt-web;sbtVersion=1.0;scalaVersion=2.12:1.4.4
#11 69.26 [error]   Not found
#11 69.26 [error]   Not found
#11 69.26 [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.4/sbt-web-1.4.4.pom
#11 69.26 [error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
#11 69.26 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
#11 69.26 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
#11 69.26 [error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
#11 69.26 [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
#11 69.26 [error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
#11 69.26 [error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:314)
#11 69.26 [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
#11 69.26 [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
#11 69.26 [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
#11 69.26 [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
#11 69.26 [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
#11 69.26 [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
#11 69.26 [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
#11 69.26 [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
#11 69.26 [error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
#11 69.26 [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
#11 69.26 [error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
#11 69.26 [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
#11 69.26 [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
#11 69.26 [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
#11 69.26 [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
#11 69.26 [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
#11 69.26 [error] 	at sbt.Execute.work(Execute.scala:291)
#11 69.26 [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
#11 69.26 [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
#11 69.26 [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
#11 69.26 [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#11 69.26 [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
#11 69.26 [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#11 69.26 [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
#11 69.26 [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
#11 69.26 [error] 	at java.base/java.lang.Thread.run(Thread.java:829)
#11 69.27 [error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-js-engine;sbtVersion=1.0;scalaVersion=2.12:1.2.3
#11 69.27 [error]   Not found
#11 69.27 [error]   Not found
#11 69.27 [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-js-engine_2.12_1.0/1.2.3/sbt-js-engine-1.2.3.pom
#11 69.27 [error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
#11 69.27 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
#11 69.27 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
#11 69.27 [error] Error downloading org.foundweekends.giter8:sbt-giter8-scaffold;sbtVersion=1.0;scalaVersion=2.12:0.11.0
#11 69.27 [error]   Not found
#11 69.27 [error]   Not found
#11 69.28 [error]   not found: https://repo1.maven.org/maven2/org/foundweekends/giter8/sbt-giter8-scaffold_2.12_1.0/0.11.0/sbt-giter8-scaffold-0.11.0.pom
#11 69.28 [error]   not found: /root/.ivy2/localorg.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml
#11 69.28 [error] Error downloading com.typesafe.sbt:sbt-native-packager;sbtVersion=1.0;scalaVersion=2.12:1.5.2
#11 69.28 [error]   Not found
#11 69.28 [error]   Not found
#11 69.28 [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.5.2/sbt-native-packager-1.5.2.pom
#11 69.28 [error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml
#11 69.28 [error] Error downloading com.lightbend.sbt:sbt-javaagent;sbtVersion=1.0;scalaVersion=2.12:0.1.5
#11 69.28 [error]   Not found
#11 69.28 [error]   Not found
#11 69.28 [error]   not found: https://repo1.maven.org/maven2/com/lightbend/sbt/sbt-javaagent_2.12_1.0/0.1.5/sbt-javaagent-0.1.5.pom
#11 69.28 [error]   not found: /root/.ivy2/localcom.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml
#11 69.28 [error] Error downloading com.typesafe.sbt:sbt-twirl;sbtVersion=1.0;scalaVersion=2.12:1.5.1
#11 69.28 [error]   Not found
#11 69.28 [error]   Not found
#11 69.28 [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-twirl_2.12_1.0/1.5.1/sbt-twirl-1.5.1.pom
#11 69.28 [error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml
#11 69.28 [error] Error downloading com.typesafe.sbt:sbt-web;sbtVersion=1.0;scalaVersion=2.12:1.4.4
#11 69.28 [error]   Not found
#11 69.28 [error]   Not found
#11 69.28 [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.4/sbt-web-1.4.4.pom
#11 69.28 [error]   not found: /root/.ivy2/localcom.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
#11 69.28 [error]   download error: Caught javax.net.ssl.SSLHandshakeException (Remote host terminated the handshake) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
#11 69.30 [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
------
executor failed running [/bin/sh -c ./sbt/bin/sbt clean stage]: exit code: 1
```

Any help is appreciated!</div>

**Comment by ugputu18** [comment]
That problem breaks app build now. Also I see this error on the new play project, created by the instruction here: https://www.playframework.com/documentation/2.8.x/NewApplication

Yesterday everything worked fine.

**Comment by mkurz** [comment]
@ugputu18 Seems the repository hosting those libraries are down currently: https://github.com/sbt/sbt/issues/7202 There is nothing we can do from Play's side. You probably just need to have some patients. With next Play release hopefully all Play dependencies will be hosted on Maven central so that should hopefully not happen again.
