### ISSUE TITLE
com.google.inject.ProvisionException: Unable to provision

### ISSUE THREAD

**Issue by nc-jeni** [playframework/playframework#11786]
### API

Java

### Operating System

Windows 11 - WSL Ubuntu

### JDK

1.8

### Expected Behavior

Listening to broadcasts and connect to them

### Actual Behavior

Fatal error during startup, aborted
com.google.inject.ProvisionException: Unable to provision, see the following errors:
  while locating XXX
  while locating XXX annotated with @com.google.inject.internal.Element(setName=,uniqueId=19, type=MULTIBINDER, keyType=)

1) Error injecting constructor, java.net.SocketException: Invalid argument
Caused by: java.net.SocketException: Invalid argument
        at java.net.PlainDatagramSocketImpl.join(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
        at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
        at javax.jmdns.impl.JmDNSImpl.openMulticastSocket(JmDNSImpl.java:463)
        at javax.jmdns.impl.JmDNSImpl.<init>(JmDNSImpl.java:420)
        at javax.jmdns.JmDNS.create(JmDNS.java:81)

**Comment by nc-jeni** [comment]
Moved to https://github.com/jmdns/jmdns/issues/250
