### ISSUE TITLE
`AkkaHttpServer` fails to run on scala 3 with 2.9 milestones

### ISSUE THREAD

**Issue by mrdziuban** [playframework/playframework#11846]
### Play Version

2.9.0-M6

### API

Scala

### Operating System

macOS 13.3.1

### JDK

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### Expected Behavior

Running an application using play-akka-http-server v2.9.0-M6 should start successfully.

### Actual Behavior

The application crashes immediately with an error coming from akka-http.

I believe the root cause of this is that play is using [akka-http v10.2.10](https://github.com/playframework/playframework/blob/2.9.0-M6/project/Dependencies.scala#L27) which doesn't support scala 3, so is calling [`.cross(CrossVersion.for3Use2_13)`](https://github.com/playframework/playframework/blob/2.9.0-M6/project/Dependencies.scala#L199) on the dependency. This issue is relevant: https://github.com/akka/akka-http/issues/4118

Are there plans to update the play 2.9 milestones to use [akka-http v10.5.0](https://github.com/akka/akka-http/releases/tag/v10.5.0) (which does support scala 3) or later?

### Reproducible Test Case

1. Clone this repository: https://github.com/mrdziuban/play-akka-http-scala-3
2. `cd play-akka-http-scala-3`
3. `sbt run`
4. See that the app crashes immediately with an error:
    ```
    java.lang.NoSuchMethodError: 'void akka.actor.ExtensionId.$init$(akka.actor.ExtensionId)'
      at akka.http.scaladsl.Http$.<clinit>(Http.scala:845)
      at play.core.server.AkkaHttpServer.createServerBinding(AkkaHttpServer.scala:215)
      at play.core.server.AkkaHttpServer.$init$$$anonfun$4(AkkaHttpServer.scala:248)
      at play.core.server.AkkaHttpServer.$init$$$anonfun$adapted$1(AkkaHttpServer.scala:249)
      at scala.Option.map(Option.scala:242)
      at play.core.server.AkkaHttpServer.<init>(AkkaHttpServer.scala:249)
      at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:722)
      at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:721)
      at play.core.server.ServerProvider.createServer(ServerProvider.scala:30)
      at play.core.server.ServerProvider.createServer$(ServerProvider.scala:21)
      at play.core.server.AkkaHttpServerProvider.createServer(AkkaHttpServer.scala:720)
      at play.core.server.ProdServerStart$.start(ProdServerStart.scala:58)
      at play.core.server.ProdServerStart$.main(ProdServerStart.scala:28)
      at play.core.server.ProdServerStart.main(ProdServerStart.scala)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      at sbt.Run.invokeMain(Run.scala:143)
      at sbt.Run.execute$1(Run.scala:93)
      at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
      at sbt.Run$.executeSuccess(Run.scala:186)
      at sbt.Run.runWithLoader(Run.scala:120)
      at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)
      at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)
      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
      at scala.util.Try$.apply(Try.scala:213)
      at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:366)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.base/java.lang.Thread.run(Thread.java:833)
    ```

**Comment by mrdziuban** [comment]
Oooh I see that akka-http v10.5.0 requires at least akka v2.7.0 -- does that make upgrading a non-starter because of the akka license changes??

**Comment by mkurz** [comment]
> does that make upgrading a non-starter because of the akka license changes??

Yes. I was thinking about this intensively the last couple of days and more and more problems come up regarding akka. Give me some time I will see what I can do about your problem.

**Comment by mrdziuban** [comment]
👍 thanks @mkurz, for now I've switched to using the netty server so this isn't blocking me, but it does feel like something that would block a final 2.9 release

Does [the additional use grant in akka's license](https://github.com/akka/akka/blob/main/LICENSE#L8-L16) mean that play could update to later versions of akka and put the burden on downstream users to respect the license otherwise?

**Comment by mkurz** [comment]
I opened a pull request against your reproducer repo: https://github.com/mrdziuban/play-akka-http-scala-3/pull/1
Copy pasting the PR comment (in case you ever delete that repo):

The pull request I posted is more or less a copy of the workaround in https://github.com/playframework/playframework/commit/78c5bfdb885fab3d82938ddbc38f73c094a6d7ed#diff-9ed9f10e75f274f487467172a335403bc184a1933657912746ad94444ed59dab

That workaround would get applied if you would add the Play sbt plugin to your `project/plugins.sbt` and activate it in your `build.sbt` via `lazy val root = (project in file(".")).enablePlugins(PlayScala)` (or `PlayJava`). This would automatically activate the `PlayAkkaHttpServer` sbt plugin as well which would then apply the above linked workaround automatically.

Since you don't do that that way, but directly depend on `"com.typesafe.play" %% "play-akka-http-server" % "2.9.0-M6"` in your `libraryDependencies` you need to make sure to not bring in any `akka`, `ssl-config-core` and `jackson-module-scala` Scala 3 artifacts, but instead their Scala 2 artifacts, otherwise you will end up with the exception you got. So you basically switch some dependencies to Scala 2 even when using Scala 3 (There is no sane way in sbt to do that, so we have to first exclude any Scala 3 artifacts and then include the Scala 2 ones).

That does work for me, the akka-http-server now starts.

This should be documented as part of #11739.

Also what I will do is check if Play is compatible with akka 2.8 and latest akka-http 10.5.x. Not that we are going to ship with that versions, but people should be able to use that versions in their app if they want to pull that dependencies in.

**Comment by mkurz** [comment]
Added a note in #11804
