### ISSUE TITLE
2.9 upgrade: exception in Play java async actions that return CompleteableFuture.completedStage

### ISSUE THREAD

**Issue by bion** [playframework/playframework#11991]
When upgrading to Play 2.9, returning a `CompletableFuture.completedStage()` in Java controller action causes the framework to throw an exception. Changing the code to return a `CompletableFuture.completedFuture()` avoids the exception.

### Play Version

2.9-RC2

### API

Java

### Operating System

Alpine Linux, [eclipse-temurin:11.0.20_8-jdk-alpine](https://github.com/civiform/civiform/blob/main/Dockerfile#L7)

### JDK

Java 11.0.20_8

Scala 2.13.12

### Library Dependencies

Libraries listed here: https://github.com/civiform/civiform/blob/main/server/build.sbt

### Expected Behavior

1. upgrade to Play 2.9-RC2
2. make a request to controllers with dependencies that return a `CompletableFuture.completedStage`
3. request succeeds normally

### Actual Behavior

Play Framework throws an exception:

```
Caused by: java.lang.UnsupportedOperationException: null
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.isDone(CompletableFuture.java:2844)
	at scala.jdk.javaapi.FutureConverters$.asScala(FutureConverters.scala:73)
	at scala.jdk.FutureConverters$CompletionStageOps$.asScala$extension(FutureConverters.scala:41)
	at play.core.j.JavaAction$$anon$1.$anonfun$call$1(JavaAction.scala:127)
	at play.api.mvc.BodyParser$.$anonfun$parseBody$4(Action.scala:241)
	at scala.Option.getOrElse(Option.scala:201)
	at play.api.mvc.BodyParser$.parseBody(Action.scala:239)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:128)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
	at org.pac4j.play.java.SecureAction.lambda$internalCall$1(SecureAction.java:100)
	at org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:141)
	at org.pac4j.play.java.SecureAction.internalCall(SecureAction.java:94)
	at org.pac4j.play.java.SecureAction.call(SecureAction.java:77)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:184)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at play.core.j.ClassLoaderExecutionContext.$anonfun$execute$1(ClassLoaderExecutionContext.scala:64)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:104)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:66)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
```

### Reproducible Test Case

The code changes to `QuestionService.java` in this commit fixed the issue: https://github.com/civiform/civiform/pull/5648/commits/46ed43981901cc8c3dc6a6367a83192871e7468e

Previously in [the associated PR](https://github.com/civiform/civiform/pull/5648) we worked around this by making the action synchronous. Changing `completedStage` to `completedFuture` allowed us to change it back to being async.

**Comment by mkurz** [comment]
I will take a look at this the next minutes, thanks for the report.

**Comment by mkurz** [comment]
Fix is here: #11993 I will publish this as RC3 but will not announce it just so you can test if this fixes your problem.

**Comment by mkurz** [comment]
@bion Would you be able to test a RC3 today (your time)?

**Comment by mkurz** [comment]
@bion @gwendolyngoetz I tagged RC3 a couple of minutes ago. Can you please test (if possible today/tomorrow friday)?
Usually it takes some time until the artifacts are available from Maven central, you can try in like 30 minutes to an hour.
Thanks!

**Comment by gwendolyngoetz** [comment]
Sure thing!

**Comment by gwendolyngoetz** [comment]
Our tests passed and running it manually worked too on Java 11. I'm getting `BeanNotEnhancedException`s when trying on Java 17, but I don't think that's related.

**Comment by mkurz** [comment]
@gwendolyngoetz Thanks! The `BeanNotEnhancedException` most likely is caused by the fact that play-ebean removed the play-enhancer, so you have to manually write getter/setters now. See
* https://github.com/playframework/play-enhancer/issues/23
* https://github.com/playframework/play-ebean/issues/201
* https://github.com/playframework/play-ebean/pull/203
