### ISSUE TITLE
sbt.inc.Doc$JavadocGenerationFailed

### ISSUE THREAD

**Issue by rajithpalavalli** [playframework/playframework#11999]
SBT: 1.6.2
Java : 8
Scala : 2.12.15

Previously we are using 1.2.6 sbt version due to Log4j vulnerable we are upgrading sbt version to 1.6.2.
This version upgrade we need in one of the module, it is not a service its kind of connector.

"publishLocal" command executed we are getting this error : 

[error] sbt.inc.Doc$JavadocGenerationFailed
[error]         at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cachedJavadoc$1(Doc.scala:51)
[error]         at sbt.inc.Doc$$anonfun$cachedJavadoc$2.run(Doc.scala:41)
[error]         at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$prepare$1(Doc.scala:62)
[error]         at sbt.inc.Doc$$anonfun$prepare$5.run(Doc.scala:57)
[error]         at sbt.inc.Doc$.go$1(Doc.scala:73)
[error]         at sbt.inc.Doc$.$anonfun$cached$5(Doc.scala:82)
[error]         at sbt.inc.Doc$.$anonfun$cached$5$adapted(Doc.scala:81)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.inc.Doc$.sbt$inc$Doc$$$anonfun$cached$1(Doc.scala:85)
[error]         at sbt.inc.Doc$$anonfun$cached$7.run(Doc.scala:68)
[error]         at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2175)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / doc) sbt.inc.Doc$JavadocGenerationFailed
[error] Total time: 4 s, completed Oct 3, 2023 7:05:43 PM

Please help!!

**Comment by mkurz** [comment]
Please try sbt 1.7.2, and latest Scala 2.12.18.
I am pretty sure this is not caused by Play. This is some problem with the Java version used, maybe in compination with the sbt version you are using. Maybe you also have a syntax error in you javadoc somewhere.
I recommend searching for `sbt.inc.Doc$JavadocGenerationFailed` in this repo's issues and in
* https://github.com/sbt/sbt
* https://github.com/sbt/zinc/

Maybe you will find some hint how to fix that. Also you could try to use Java 11.
