### ISSUE TITLE
No Persistence provider for EntityManager in play 2.9.0-RC2

### ISSUE THREAD

**Issue by Harish247** [playframework/playframework#12030]
### Discussed in https://github.com/orgs/playframework/discussions/11985

<div type='discussions-op-text'>

<sup>Originally posted by **Harish247** September 25, 2023</sup>
Play version - 2.9.0-RC2
Java version - 11.0.1
Scala version - 2.13.12
sbt - 1.9.6
MySQL - 8.0

The application JPA was working well with older versions of play. But I am doing trials with 2.9.0-RC2 and It was not able to find the persistence provider. I have updated the javax.persistence imports with jakarta.persistence and updated the persistence.xml file as well. 

I have followed the migration guide and some stack over flow threads as well with not much help. Please suggest where I should be looking to resolve this one. Thanks

Here is my xml file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="https://jakarta.ee/xml/ns/persistence"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
  version="3.0">

  <persistence-unit name="applicationPersistenceUnit" transaction-type="RESOURCE_LOCAL">
    <provider>org.hibernate.ejb.HibernatePersistence</provider>
    <properties>
      <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL8Dialect"/>
      <property name="hibernate.dialect.storage_engine" value="innodb"/>
    </properties>
  </persistence-unit>
</persistence>
```

Here is the error I have been seeing.
```
Caused by: jakarta.persistence.PersistenceException: No Persistence provider for EntityManager named applicationPersistenceUnit
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:86)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at play.db.jpa.DefaultJPAApi.lambda$start$0(DefaultJPAApi.java:74)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at play.db.jpa.DefaultJPAApi.start(DefaultJPAApi.java:70)
	at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:57)
	at play.db.jpa.DefaultJPAApi$JPAApiProvider$$FastClassByGuice$$4a5c759.GUICE$TRAMPOLINE(<generated>)
	at play.db.jpa.DefaultJPAApi$JPAApiProvider$$FastClassByGuice$$4a5c759.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:58)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
	... 68 more
```</div>

**Comment by Harish247** [comment]
Followed suggestions provided by @mkurz and still having the same issue. https://github.com/orgs/playframework/discussions/11985

**Comment by mkurz** [comment]
@Harish247 Please post `persistence.xml´ and the relevant parts of your `application.conf` **after** you applied my suggestions, just to make sure we are not missing something here.

**Comment by ihostage** [comment]
> I get the error dataSource or dataSourceClassName or jdbcUrl is required

I don't see in your _application.conf_ the related settings. Are you sure you set the next settings like in [example](https://github.com/playframework/play-samples/blob/2d6ce37f611d0157d51587d2cbd282c811a90e19/play-java-jpa-example/conf/application.conf#L5-L6) that @mkurz mentioned in discussion?

```HOCON
db {
  default.driver = org.h2.Driver
  default.url = "jdbc:h2:mem:play"
}
```

**Comment by Harish247** [comment]
The issue is fixed with the suggestions from https://github.com/orgs/playframework/discussions/11985
