### ISSUE TITLE
UnsupportedOperationException building/running Play 2.9 project using Webjars on Windows NTFS due to POSIX permissions

### ISSUE THREAD

**Issue by inigo** [playframework/playframework#12187]
UnsupportedOperationException building/running Play 2.9 project using Webjars on Windows NTFS due to POSIX permissions.

`last` shows the stack trace to be:

```
[error] java.lang.UnsupportedOperationException
[error]         at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2168)
[error]         at org.webjars.WebJarExtractor.extractResource(WebJarExtractor.java:147)
```

### Play Version

2.9

### Operating System

Windows using NTFS. Non-POSIX filesystems (such as exFAT / FAT32) on Linux/MacOS are also likely be affected, but I haven't checked that and that's less common in practice.

### JDK

Tested on Java 11, Java 17, Java 21.

### Library Dependencies

This is not a bug in Play code. It is a bug in webjars-locator-core 0.54, raised at https://github.com/webjars/webjars-locator-core/issues/123. Once that bug is fixed, Play's dependencies can be updated.

**Comment by inigo** [comment]
webjars-locator-core is now updated to 0.55, and I can confirm that it fixes the problem for me.

I have tested by adding:

```
dependencyOverrides += "org.webjars" % "webjars-locator-core" % "0.55"
```

to my plugins.sbt.

**Comment by PromanSEW** [comment]
@mkurz please help how to fix this error before Play 2.9.1 will be released
```scala
dependencyOverrides += "org.webjars" % "webjars-locator-core" % "0.55"
```
gives me another error:
```
[error] (Web-assets / typescript) java.lang.NoSuchMethodError: 'java.lang.Object com.typesafe.sbt.web.SbtWeb$.withActorRefFactory(sbt.State, java.lang.String, scala.Function1)'
ERROR a.a.ActorSystemImpl - Internal server error, sending 500 response
scala.MatchError: java.lang.NoSuchMethodError: 'java.lang.Object com.typesafe.sbt.web.SbtWeb$.withActorRefFactory(sbt.State, java.lang.String, scala.Function1)' (of class java.lang.NoSuchMethodError)
        at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$8(PlayReload.scala:92)
        at scala.Option.map(Option.scala:230)
        at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:92)
        at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:144)
        at scala.util.Either$LeftProjection.map(Either.scala:573)
        at play.sbt.run.PlayReload$.compile(PlayReload.scala:144)
        at sbt.PlayRun$.$anonfun$playRunTask$5(PlayRun.scala:99)
        at play.runsupport.Reloader.$anonfun$reload$1(Reloader.scala:493)
        at play.runsupport.Reloader$$anon$1.run(Reloader.scala:58)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
```

**Comment by inigo** [comment]
@PromanSEW the `webjars-locator-core` upgrade on its own fixed it for me, but judging by the second PR - https://github.com/playframework/playframework/pull/12197/files - you might also need to add dependency overrides for these?

```
"com.github.sbt"    % "sbt-web"             % "1.5.3"
"com.github.sbt"    % "sbt-js-engine"       % "1.3.4"
```

**Comment by PromanSEW** [comment]
@mkurz no luck...
```scala
dependencyOverrides ++= Seq(
  "com.github.sbt" % "sbt-web" % "1.5.3",
  "com.github.sbt" % "sbt-js-engine" % "1.3.4",
  "org.webjars" % "webjars-locator-core" % "0.55"
)
```
in `plugins.sbt` does nothing, also in `build.sbt`. IDEA shows old library, and error is still here.
```
libraryDependencies ++= Seq(
  "com.github.sbt" % "sbt-web" % "1.5.3",
  "com.github.sbt" % "sbt-js-engine" % "1.3.4",
  "org.webjars" % "webjars-locator-core" % "0.55"
)
```
in `plugins.sbt` raises error:
```
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.sbt:sbt-js-engine:1.3.4
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/sbt/sbt-js-engine/1.3.4/sbt-js-engine-1.3.4.pom
[error]   not found: C:\Users\proma\.ivy2\localcom.github.sbt\sbt-js-engine\1.3.4\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.sbt/sbt-js-engine/1.3.4/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.sbt/sbt-js-engine/1.3.4/ivys/ivy.xml
[error] Error downloading com.github.sbt:sbt-web:1.5.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/sbt/sbt-web/1.5.3/sbt-web-1.5.3.pom
[error]   not found: C:\Users\proma\.ivy2\localcom.github.sbt\sbt-web\1.5.3\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.sbt/sbt-web/1.5.3/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.sbt/sbt-web/1.5.3/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
...
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.sbt:sbt-js-engine:1.3.4
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/sbt/sbt-js-engine/1.3.4/sbt-js-engine-1.3.4.pom
[error]   not found: C:\Users\proma\.ivy2\localcom.github.sbt\sbt-js-engine\1.3.4\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.sbt/sbt-js-engine/1.3.4/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.sbt/sbt-js-engine/1.3.4/ivys/ivy.xml
[error] Error downloading com.github.sbt:sbt-web:1.5.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/sbt/sbt-web/1.5.3/sbt-web-1.5.3.pom
[error]   not found: C:\Users\proma\.ivy2\localcom.github.sbt\sbt-web\1.5.3\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.sbt/sbt-web/1.5.3/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.sbt/sbt-web/1.5.3/ivys/ivy.xml
```

also here I see strange path...
```
[error]   not found: C:\Users\proma\.ivy2\localcom.github.sbt\sbt-web\1.5.3\ivys\ivy.xml
```
Where is slash after `local`?

**Comment by mkurz** [comment]
@PromanSEW Let's start again:
Please _only_ add
``sbt
dependencyOverrides += "org.webjars" % "webjars-locator-core" % "0.55"
```
to your `project/plugins.sbt`, nothing else. shutdown sbt. Remove your `target` and `project/target` folder and then start sbt.
Same error? If so please run in sbt:
```sbt
reload plugins
show fullClasspath
```
and please check if `webjars-locator-core-0.55.jar` is on the classpath.

**Comment by PromanSEW** [comment]
@mkurz Error is still here :(
```
[info] * Attributed(C:\Users\proma\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\com\github\sbt\sbt-web_2.12_1.0\1.5.2\sbt-web_2.12_1.0-1.5.2.jar)
[info] * Attributed(C:\Users\proma\AppData\Local\Coursier\Cache\v1\https\repo.scala-sbt.org\scalasbt\sbt-plugin-releases\com.typesafe.sbt\sbt-web\scala_2.12\sbt_1.0\1.4.4\jars\sbt-web.jar)
[info] * Attributed(C:\Users\proma\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\com\github\sbt\sbt-js-engine_2.12_1.0\1.3.3\sbt-js-engine_2.12_1.0-1.3.3.jar)
[info] * Attributed(C:\Users\proma\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\webjars\webjars-locator-core\0.55\webjars-locator-core-0.55.jar)
```
`webjars-locator-core-0.55.jar`, but `sbt-web` and `sbt-js-engine` are old

**Comment by PromanSEW** [comment]
@mkurz I found, where is the trouble
```scala
addSbtPlugin("com.github.platypii" % "sbt-typescript" % "4.6.4")
```
This plugin is incompatible now

**Comment by mkurz** [comment]
Ah ok.
Seems like the author [is active in GitHub](https://github.com/platypii), maybe just open a pull request in [the repo](https://github.com/platypii/sbt-typescript) to upgrade to sbt-web 1.5.x?
