### ISSUE TITLE
`DependencyInjectedRoutingDslTest` and other tests are failed by `LoggerContext`

### ISSUE THREAD

**Issue by ihostage** [playframework/playframework#12204]
https://github.com/playframework/playframework/actions/runs/6845514122/job/18610965468#step:10:23923

```
[error] Test play.routing.DependencyInjectedRoutingDslTest failed: java.util.NoSuchElementException: null, took 0.0 sec
[error]     at java.util.ArrayList$Itr.next(ArrayList.java:1000)
[error]     at ch.qos.logback.classic.LoggerContext.fireOnReset(LoggerContext.java:317)
[error]     at ch.qos.logback.classic.LoggerContext.reset(LoggerContext.java:366)
[error]     at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:95)
[error]     at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:75)
[error]     at play.api.inject.guice.GuiceApplicationBuilder.$anonfun$configureLoggerFactory$1(GuiceApplicationBuilder.scala:158)
[error]     at scala.Option.map(Option.scala:242)
[error]     at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:157)
[error]     at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:116)
[error]     at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
[error]     at play.inject.guice.GuiceBuilder.injector(GuiceBuilder.java:210)
[error]     at play.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.java:116)
[error]     at play.routing.DependencyInjectedRoutingDslTest.startApp(DependencyInjectedRoutingDslTest.java:19)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
[error] Test play.routing.DependencyInjectedRoutingDslTest failed: java.lang.NullPointerException: null, took 0.0 sec
[error]     at play.test.Helpers.stop(Helpers.java:436)
[error]     at play.routing.DependencyInjectedRoutingDslTest.stopApp(DependencyInjectedRoutingDslTest.java:35)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
```

**Comment by mkurz** [comment]
Yes, this happens sometimes. I think this is related to
- 10939

So after fixing #10939f we will see if this still occurs.

**Comment by mkurz** [comment]
Fixed by 
- #12667

Since that PR got merged the errors disappeared.
