### ISSUE TITLE
POST request fails with java.lang.IllegalStateException: Sink.asPublisher(fanout = false) only supports one subscriber

### ISSUE THREAD

**Issue by daniel-yb** [playframework/playframework#12251]
### Play Version

`2.8.19`

### API

Java

### Operating System

```
# uname -a
Linux platform-yugaware-0 5.15.107+ #1 SMP Thu Jun 15 09:51:46 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### JDK

```
# java -version
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)
```

### Library Dependencies

Akka 2.8.3, not the default `2.6.21` for this version of the Play Framework. (Maybe this is just the reason for the issue?)

### Expected Behavior

1. Make a POST request
2. It succeeds in being processed (i.e. returns a 2xx or 4xx based on the specific request)

### Actual Behavior

The POST request returns a 500 with the following stacktrace:
```
! @83lgdh7mf - Internal server error, for (POST) [/api/v1/customers/<SOME_UUID>/universes/<SOME_UUID>/create_db_credentials] ->

play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.IllegalStateException: Sink.asPublisher(fanout = false) only supports one subscriber (which is allowed, see reactive-streams specification, rule 1.11)]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:246)
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:182)
	at com.yugabyte.yw.common.YWErrorHandler.onServerError(YWErrorHandler.java:68)
	at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:32)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:441)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:433)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
	at com.yugabyte.yw.common.logging.MDCPropagatingDispatcher$1.run(MDCPropagatingDispatcher.java:71)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:64)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:101)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:101)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Sink.asPublisher(fanout = false) only supports one subscriber (which is allowed, see reactive-streams specification, rule 1.11)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.Promise.failure(Promise.scala:104)
	at scala.concurrent.Promise.failure$(Promise.scala:104)
	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:187)
	at play.api.mvc.BodyParsers$TakeUpTo$$anon$1$$anon$3.onUpstreamFailure(BodyParsers.scala:1153)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:539)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:402)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:61)
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:57)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnError.execute(ActorGraphInterpreter.scala:82)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	... 5 common frames omitted
Caused by: java.lang.IllegalStateException: Sink.asPublisher(fanout = false) only supports one subscriber (which is allowed, see reactive-streams specification, rule 1.11)
	at akka.stream.impl.ReactiveStreamsCompliance$.rejectAdditionalSubscriber(ReactiveStreamsCompliance.scala:62)
	at akka.stream.impl.VirtualPublisher.rec$6(StreamLayout.scala:481)
	at akka.stream.impl.VirtualPublisher.subscribe(StreamLayout.scala:486)
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary.preStart(ActorGraphInterpreter.scala:148)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:309)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:619)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:727)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:776)
	at akka.actor.Actor.aroundPreStart(Actor.scala:548)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:548)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.create(ActorCell.scala:643)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	... 6 common frames omitted
```

Note: We are not directly interacting with Akka, this seems to be an issue with the play framework's interaction with the library.

### Reproducible Test Case

We are not sure what reproduces this issue. It seems to happen randomly on numerous of our PUT/POST APIs with no discernible pattern. Importantly, we only started seeing this after upgrading play framework from v`2.7.9` -> v`2.8.19`.

**Comment by mkurz** [comment]
@daniel-yb Does this still happen? Can you provide more details on how to reproduce maybe already?

**Comment by mkurz** [comment]
@daniel-yb I am closing this isse for now, if the problem still occurs and you have more details to share of course please comment below, thanks!

**Comment by BillOTei** [comment]
we are facing the exact same issue [here](https://stackoverflow.com/questions/78522466/java-lang-illegalstateexception-sink-aspublisherfanout-false-only-supports-o)
random requests not sure if there is a precise one to identify.
Play 2.8.19 with the akka coming with.

**Comment by iwanek9ld** [comment]
If anyone yet interested. I have hit the same issue. Some random POST requests are failing in the web application.

After some investigation, I have found out that I can reliably reproduced by adding 10s `Thread.sleep` in custom filter, before this filter passes execution to the next filter.

```
class CustomLaggyFilter @Inject() ()(ec: ExecutionContext) extends Filter {
  override def apply(nextFilter: RequestHeader => Future[Result])(request: RequestHeader): Future[Result] = {
    for {
      _ <- Future { Thread.sleep(10000) }
      result <- nextFilter(request)
    } yield result
  }
}
```

On the other hand, it works: 
 - for GET requests, and 
 - works if the sleep time is added after filter calling next filter in chain. 

Therefore, I think it might be somewhat related to the way Play constructs the body parsers (and that there is a request body).


For akka doc, subscription is canceled after 5 seconds by default: https://doc.akka.io/libraries/akka-core/current/general/stream/stream-configuration.html

```
      # Cleanup leaked publishers and subscribers when they are not used within a given
      # deadline
      subscription-timeout {
        # when the subscription timeout is reached one of the following strategies on
        # the "stale" publisher:
        # cancel - cancel it (via `onError` or subscribing to the publisher and
        #          `cancel()`ing the subscription right away
        # warn   - log a warning statement about the stale element (then drop the
        #          reference to it)
        # noop   - do nothing (not recommended)
        mode = cancel

        # time after which a subscriber / publisher is considered stale and eligible
        # for cancelation (see `akka.stream.subscription-timeout.mode`)
        timeout = 5s
      }
```

Here is post that suggests that it might be a some operation delay issue: https://discuss.akka.io/t/java-lang-illegalstateexception-sink-aspublisher-fanout-false-only-supports-one-subscriber/10789

**Comment by BillOTei** [comment]
> If anyone yet interested. I have hit the same issue. Some random POST requests are failing in the web application.
> 
> After some investigation, I have found out that I can reliably reproduce it by adding 10s `Thread.sleep` in custom filter, before this filter passes execution to the next filter.
> 
> ```
> class CustomLaggyFilter @Inject() ()(ec: ExecutionContext) extends Filter {
>   override def apply(nextFilter: RequestHeader => Future[Result])(request: RequestHeader): Future[Result] = {
>     for {
>       _ <- Future { Thread.sleep(10000) }
>       result <- nextFilter(request)
>     } yield result
>   }
> }
> ```
> 
> On the other hand, it works:
> 
> * for GET requests, and
> * works if the sleep time is added after filter calling next filter in chain.
> 
> Therefore, I think it might be somewhat related to the way Play constructs the body parsers (and that there is a request body).
> 
> From akka docs, subscription is canceled after 5 seconds by default: https://doc.akka.io/libraries/akka-core/current/general/stream/stream-configuration.html
> 
> ```
>       # Cleanup leaked publishers and subscribers when they are not used within a given
>       # deadline
>       subscription-timeout {
>         # when the subscription timeout is reached one of the following strategies on
>         # the "stale" publisher:
>         # cancel - cancel it (via `onError` or subscribing to the publisher and
>         #          `cancel()`ing the subscription right away
>         # warn   - log a warning statement about the stale element (then drop the
>         #          reference to it)
>         # noop   - do nothing (not recommended)
>         mode = cancel
> 
>         # time after which a subscriber / publisher is considered stale and eligible
>         # for cancelation (see `akka.stream.subscription-timeout.mode`)
>         timeout = 5s
>       }
> ```
> 
> Here is post that suggests that it might be a some operation delay issue: https://discuss.akka.io/t/java-lang-illegalstateexception-sink-aspublisher-fanout-false-only-supports-one-subscriber/10789

do you have long running IO happening in the POST action?

**Comment by iwanek9ld** [comment]
> do you have long running IO happening in the POST action?

Yes, I have long running IO operation. But for the purpose of the reproduction of the issue, adding `Thread.sleep` is enough. 

The high IO load, on the machine where application is running, is not needed.

**Comment by BillOTei** [comment]
that suggests to me that there's a timeout on asynchrone operations which
shouldn't happen?



Le mar. 28 janv. 2025 à 10:24, Tomasz Iwanek ***@***.***> a
écrit :

**Comment by mkurz** [comment]
Can you provide a simple reproducer project?

**Comment by iwanek9ld** [comment]
I have tried to create simple play application for reproduction, but adding sleep of 10s in custom filter, does not reproduce the issue as I was convinced before. I think that there must be other condition on which this occurs then.
