### ISSUE TITLE
InjectedController trait not working with scala 3

### ISSUE THREAD

**Issue by ThomasGrt** [playframework/playframework#12272]
### Play Version

Play 3.0.0

### API

Scala 3

### Operating System

Fedora 38

### JDK

openjdk version "17.0.9" 2023-10-17
openjdk version "11.0.21" 2023-10-17

### Library Dependencies

None

### Expected Behavior

1. Controller inheriting from InjectedController should serve result

### Actual Behavior

1. when calling route to controller via browser or test we get an error
```
ERROR p.a.h.DefaultHttpErrorHandler - 

! @83p3df7p7 - Internal server error, for (GET) [/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NoSuchElementException: ControllerComponents not set! Call setControllerComponents or create the instance with dependency injection.]]
        at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException$$anonfun$2(HttpErrorHandler.scala:405)
        at scala.Option.map(Option.scala:242)
        at play.api.http.HttpErrorHandlerExceptions$.convertToPlayException(HttpErrorHandler.scala:406)
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:390)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:267)
        at play.core.server.Server$$anon$1.applyOrElse(Server.scala:116)
        at play.core.server.Server$$anon$1.applyOrElse(Server.scala:112)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
        at play.core.server.Server$.getHandlerFor(Server.scala:137)
        at play.core.server.PekkoHttpServer.handleRequest(PekkoHttpServer.scala:355)
Caused by: java.util.NoSuchElementException: ControllerComponents not set! Call setControllerComponents or create the instance with dependency injection.
        at play.api.mvc.InjectedController.fallbackControllerComponents(Controller.scala:202)
        at play.api.mvc.InjectedController.fallbackControllerComponents$(Controller.scala:182)
        at controllers.HomeController.fallbackControllerComponents(HomeController.scala:13)
        at play.api.mvc.InjectedController.controllerComponents(Controller.scala:186)
        at play.api.mvc.InjectedController.controllerComponents$(Controller.scala:182)
        at controllers.HomeController.controllerComponents(HomeController.scala:13)
        at play.api.mvc.BaseController.Action(Controller.scala:171)
        at play.api.mvc.BaseController.Action$(Controller.scala:158)
        at controllers.HomeController.Action(HomeController.scala:13)
        at controllers.HomeController.index(HomeController.scala:22)
```

### Reproducible Test Case

I reproduced this bug with some minor tweaks to  [play-samples/play-scala-hello-world-tutorial](https://github.com/playframework/play-samples/tree/3.0.x/play-scala-hello-world-tutorial) code.

1.  In HomeController replace AbstractController with InjectedController
```
-class HomeController @Inject()(cc: ControllerComponents) extends AbstractController(cc) {
+class HomeController @Inject()() extends InjectedController {
```
2. Force use of scala 3 (by default project user scala 2.13)
```
     crossScalaVersions := Seq("2.13.12", "3.3.1"),
-    scalaVersion := crossScalaVersions.value.head,
+    scalaVersion := "3.3.1",
```
3. Launch app with `sbt run`
4. Access `http://localhost:9000/` to get the error (this is the one listed in the previous step)

Note: exact same code works if you switch back to scala "2.13.12" and Play serves the "Play Hello World Web Tutorial" page

**Comment by mkurz** [comment]
Can confirm, taking a look already. Thanks a lot for the report!

**Comment by mkurz** [comment]
Pretty sure I nailed it down:
When decompiling `HomeController.class` (using `javap -v`) the method signature for `setControllerComponents` is different for Scala 2.13 and Scala 3.

Scala 2.13:
```
  public void setControllerComponents(play.api.mvc.ControllerComponents);
    descriptor: (Lplay/api/mvc/ControllerComponents;)V
    flags: (0x0001) ACC_PUBLIC
```

Scala 3:
```
  public void setControllerComponents(play.api.mvc.ControllerComponents);
    descriptor: (Lplay/api/mvc/ControllerComponents;)V
    flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
```

So you see Scala 3 marks the method as synthetic bridge method (`ACC_BRIDGE` and `ACC_SYNTHETIC`).

Guice however ignores such methods:
https://github.com/google/guice/blob/f095cad8aa7b59abafacc4d4461ddfc77be83667/core/src/com/google/inject/spi/InjectionPoint.java#L819-L841

Need to find a workaround...

**Comment by ThomasGrt** [comment]
Thanks for the quick feedback and for your work on Play! 👏🏻 

Seems pretty low level stuff (scala compiler...), I don't know why they changed this in scala 3.
Hope that, as you said, you can find a workaround.

One can still use AbstractController instead of InjectedController but if there's a way to make it work that would be better.

**Comment by PromanSEW** [comment]
This is definitely regression / breaking change in Scala 3 compiler

**Comment by mkurz** [comment]
So I tried lots of stuff, but couldn't make it work, and at this point I also believe this is a bug in the Scala 3 compiler, but I am not 100% sure, so I leave the judgment to the experts:

- https://github.com/lampepfl/dotty/issues/19270

**Comment by mkurz** [comment]
So according to https://github.com/lampepfl/dotty/issues/19270#issuecomment-1860132129 this is a problem in the Scala 3 compiler. Let's leave the things how they are currently and let's hope they fix it with Scala 3.3.3 (3.3.2 is in RC phase already, so no chance anymore)

**Comment by ThomasGrt** [comment]
Thanks for the follow up!
Let's wait for the fix.

**Comment by mkurz** [comment]
> If there's interest I would open a doc pull-request to add a short warning

@aumann Yes sure, please go for it, thanks!

**Comment by jausmann-wc** [comment]
I can confirm this is still an issue with Scala 3.5.1 and Play 2.9.4
```
ControllerComponents not set! Call setControllerComponents or create the instance with dependency injection.
```
