### ISSUE TITLE
Less compilation fails when using the !important keyword with a mixin

### ISSUE THREAD

**Issue by jrabbe** [playframework/playframework#1286]
I have run into a specific issue with the play compilation in 2.1.1. If you have a mixin and you use the `!important` keyword it can get really messed up.

Specifically, I'm importing the [retina.js](https://github.com/imulus/retinajs/blob/master/src/retina.less) mixin to support retina images in our stylesheet (I have also tried copying it into the source).

The example that breaks is when I use the `.at2x` mixin with the `!important` keyword.

``` Less
.at2x('/assets/images/list_icon.png') !important;
background: no-repeat 0 0 !important;
```

I get the following compilation error in play, but when I run the 1.3.3 less compiler on the code it works.

```
[error] /Users/jonas/repo/RadiusIntelligence/radius/app/assets/stylesheets/app.less:606: Compilation error[Cannot call method "charAt" of undefined]
[error]   background: no-repeat 0 0 !important;
[error]   ^
[error] (*:play-copy-assets) @6enmnkgmk: Compilation error in /Users/jonas/repo/RadiusIntelligence/radius/app/assets/stylesheets/app.less:606
[error] application -

! @6enmnkgmk - Internal server error, for (GET) [/] ->

sbt.PlayExceptions$AssetCompilationException: Compilation error[Cannot call method "charAt" of undefined]
    at play.core.less.LessCompiler$.compile(LessCompiler.scala:139) ~[na:na]
    at sbt.PlayAssetsCompiler$$anonfun$6.apply(PlayAssetsCompiler.scala:88) ~[na:na]
    at sbt.PlayAssetsCompiler$$anonfun$6.apply(PlayAssetsCompiler.scala:88) ~[na:na]
    at sbt.PlayAssetsCompiler$$anonfun$AssetsCompiler$1$$anonfun$3.apply(PlayAssetsCompiler.scala:52) ~[na:na]
    at sbt.PlayAssetsCompiler$$anonfun$AssetsCompiler$1$$anonfun$3.apply(PlayAssetsCompiler.scala:48) ~[na:na]
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:239) ~[scala-library.jar:na]
```

**Comment by manoj-kumar-vishwakarma** [comment]
Hi,

In my project I am getting below error while I updated jars ("lesscss-engine" and "lesscss-servlet") to version 1.4.2 but same issue -
org.mozilla.javascript.EcmaError: TypeError: Cannot call method "charAt" of undefined (/D:/jboss-5.1.0.GA-BCBSNC-LG/server/default/deploy/bcbsnc.ear/bcbsn
c-web.war/WEB-INF/lib/lesscss-engine-1.5.1.jar/META-INF/less.js#308)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
        at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3693)
        at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3712)
        at org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:3731)c
        at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2258)
        at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2251)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1317)
        at script.getLocation(/D:/jboss-5.1.0.GA-BCBSNC-LG/server/default/deploy/bcbsnc.ear/bcbsnc-web.war/WEB-INF/lib/lesscss-engine-1.5.1.jar/META-INF/l
ess.js:308)
        at script.LessError(/D:/jboss-5.1.0.GA-BCBSNC-LG/server/default/deploy/bcbsnc.ear/bcbsnc-web.war/WEB-INF/lib/lesscss-engine-1.5.1.jar/META-INF/les
s.js:335)
