### ISSUE TITLE
Canceled file uploads raise ClosedChannelExceptions caught in RequestBodyHandler

### ISSUE THREAD

**Issue by MarcelBruse** [playframework/playframework#1842]
Thanks to the wonderful Play! Framework v2.2.0 my application enables users to upload large files to a server. On the client side I utilize Javascript and a XMLHttpRequest() object to monitor the progress of the uploads. The corresponding controller on the server side looks like this

``` scala
def upload = isAuthenticated(parse.multipartFormData) { user => implicit request =>
    request.body.file("file").map { file =>
        import java.io.File
        val filepath = "/tmp/" + file.filename
        file.ref.moveTo(new File(filepath), true)
        Ok("Success")
    }.getOrElse {
        Logger.warn("A file upload has been canceled by the user or it failed.")    
        Redirect(routes.Application.userPanel)
    }
}
```

The upload works as expected if the user does not interrupt the upload process (e.g. by navigating to another website or by aborting the transfer through request.abort()), but if the upload is purposely canceled by the user (or somehow interrupted) my console gets cluttered with ClosedChannelExceptions caught in RequestBodyHandler:

```
[warn] application - A file upload has been canceled by the user or it failed.
[error] play - Exception caught in RequestBodyHandler
java.nio.channels.ClosedChannelException: null
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:434) ~[netty.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:129) ~[netty.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99) ~[netty.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36) ~[netty.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:725) ~[netty.jar:na]
    at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71) ~[netty.jar:na]
```

I had a look at the sources of the RequestBodyHandler and it seams like you suppress NPEs in v2.1.x like this:

```
  override def exceptionCaught(ctx: ChannelHandlerContext, e: ExceptionEvent) = {
    e.getCause match {
      case e: NullPointerException => Play.logger.debug("NPE thrown in RequestBodyHandler, parsing probably ended early", e)
      case other => Play.logger.error("Error in request body handler", e.getCause)
    }
    e.getChannel.close() /*really? */
  }
```

But I could not find such a measure in v.2.2.x. Wouldn't it be good to suppress the netty exceptions in the new version too? Since a canceled file upload is a very common thing and happens frequently, there should be a way to get rid of such logs.

Thank you very much for your effort.

**Comment by joeboyscout04** [comment]
Thank you so much for this workaround!  We have also been getting partial files uploaded due to a closed connection, and Play doesn't seem to have any way to detect the error.

**Comment by AlexITC** [comment]
@cchantep  your solution worked for me thanks, I wonder why this is not already provided by play? is there any reason to not include this custom parser? @gmethvin

**Comment by gmethvin** [comment]
As @cchantep explained, his custom body parser is a workaround and does not support chunked responses. Now that we've moved to Akka streams, we can pass the error through as a failed `Accumulator`.

If you are still seeing an issue like this in Play 2.5 or 2.6, it may be best to open a new issue to discuss, since much has changed in Play since this bug was created.

**Comment by joeboyscout04** [comment]
This is what I'm using now for Play 2.5.  I don't think we ever tested without this in Play 2.5 because we also changed some of the client-side code to reduce the size of files being uploaded, so maybe it's not necessary, but it works. 

```
  //Check for partial files.
  def cleanup() = Logger.trace("fileCheckBodyParser: Do anything to do clean partial data from target.")

  // Does not support chunked request
  def fileCheckBodyParser()(implicit ec: ExecutionContext): BodyParser[MultipartFormData[TemporaryFile]] = {
    val underlying = BodyParsers.parse.multipartFormData

    BodyParser { req =>
      req.headers.get(HeaderNames.CONTENT_LENGTH) match {
        case Some(l) => try {
          val expectedContentLength = l.toLong

          val lengthFlow = Flow.fromGraph(new LengthCount)

          // Apply the request
          val parserSink = underlying(req).toSink

          Accumulator(lengthFlow.toMat(parserSink) { (statusFuture, resultFuture) =>
            statusFuture.flatMap {

              case `expectedContentLength` => {
                Logger.debug("fileCheckBodyParser: Expected content length "+expectedContentLength+" was found")
                resultFuture.map {
                  case Left(result) => {
                    Logger.warn("fileCheckBodyParser: Multipart file parsing failed.")
                    cleanup()
                    Left(result)
                  }
                  case Right(a) => Right(a)
                }
              }
              case transferred => {
                val msg = s"fileCheckBodyParser: Unexpected request size; expected: $expectedContentLength; found: $transferred"
                Logger.warn(msg)
                resultFuture.map {

                  case Left(leftRes) => {
                    Logger.warn("fileCheckBodyParser: Multipart file parsing failed.")
                    cleanup()
                    Left(leftRes)
                  }
                                     
                  case Right(rightRes) =>{
                    //instead of throwing an exception here, let's just send the successful future with the rest of the data, but remove the files.
                    cleanup()
                    Right(MultipartFormData(rightRes.dataParts,Seq(),rightRes.badParts))
                  }
                }
              }
            }
          })
        } catch {
          case err: Exception =>
            // invalid content length
            Logger.warn("fileCheckBodyParser: Exception: Invalid content length.")
            underlying(req)
        }
        case _ => {
          Logger.warn("fileCheckBodyParser: No content length found ")
          underlying(req)
        }
      }
    }
  }

  //Mostly lifted from play.api.mvc.ContentTypes.BodyParsers.TakeUpTo
  class LengthCount extends GraphStageWithMaterializedValue[FlowShape[ByteString, ByteString], Future[Long]] {

    private val in = Inlet[ByteString]("LengthCount.in")
    private val out = Outlet[ByteString]("LengthCount.out")

    override def shape: FlowShape[ByteString, ByteString] = FlowShape.of(in, out)

    override def createLogicAndMaterializedValue(inheritedAttributes: Attributes): (GraphStageLogic, Future[Long]) = {
      val status = Promise[Long]()
      var pushedBytes: Long = 0

      val logic = new GraphStageLogic(shape) {
        setHandler(out, new OutHandler {
          override def onPull(): Unit = {
            pull(in)
          }
          override def onDownstreamFinish(): Unit = {
            status.success(pushedBytes)
            completeStage()
          }
        })
        setHandler(in, new InHandler {
          override def onPush(): Unit = {
            val chunk = grab(in)
            pushedBytes += chunk.size
            push(out, chunk)
          }
          override def onUpstreamFinish(): Unit = {
            status.success(pushedBytes)
            completeStage()
          }
          override def onUpstreamFailure(ex: Throwable): Unit = {
            status.failure(ex)
            failStage(ex)
          }
        })
      }

      (logic, status.future)
    }
  }
```
