### ISSUE TITLE
Json macros fail with extra apply()

### ISSUE THREAD

**Issue by havocp** [playframework/playframework#2031]
If you add a custom `apply()` to a case class companion object then Json.reads and Json.writes fail, like this:

```
[error] exception during macro expansion: 
[error] scala.ScalaReflectionException: value apply encapsulates multiple overloaded alternatives and cannot be treated as a method. Consider invoking `<offending symbol>.asTerm.alternatives` and manually picking the required method
[error] 	at scala.reflect.api.Symbols$SymbolApi$class.asMethod(Symbols.scala:279)
[error] 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:73)
[error] 	at play.api.libs.json.JsMacroImpl$.readsImpl(JsMacroImpl.scala:51)
```
```
[error] exception during macro expansion: 
[error] scala.ScalaReflectionException: value apply encapsulates multiple overloaded alternatives and cannot be treated as a method. Consider invoking `<offending symbol>.asTerm.alternatives` and manually picking the required method
[error] 	at scala.reflect.api.Symbols$SymbolApi$class.asMethod(Symbols.scala:279)
[error] 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:73)
[error] 	at play.api.libs.json.JsMacroImpl$.writesImpl(JsMacroImpl.scala:333)
```

For example if you did something like this:
```scala
case class Foo(a: Int, b: String)
object Foo {
  def apply(): Foo = Foo(10, "foo")
  implicit val reads = Json.reads[Foo]
  implicit val writes = Json.writes[Foo]
}
```

**Comment by zbeckman** [comment]
Was this ever addressed (is there an easier way that hand-coding the Writes)?
