### ISSUE TITLE
Poor SSL configuration error handling

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#2091]
Do "play run" without providing any special arguments to setup SSL or anything and then visit https://localhost:9000/

The screen will be filled with non-obvious errors:

    [error] p.nettyException - Exception caught in Netty
    java.lang.IllegalArgumentException: empty text
    	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:97) ~[netty-3.7.0.Final.jar:na]
    	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[netty-3.7.0.Final.jar:na]
    	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75) ~[netty-3.7.0.Final.jar:na]
    	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:189) ~[netty-3.7.0.Final.jar:na]
    	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:101) ~[netty-3.7.0.Final.jar:na]
    	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[netty-3.7.0.Final.jar:na]

**Comment by rmmeans** [comment]
I believe this issue can be closed now with Play 2.4 as there is well document host of configuration options and debugging options built into Play now for SSL issues.

**Comment by wsargent** [comment]
@rmmeans We have SSLEngineProvider at least.  The non-obvious error is what happens when you give HTTP to something configured for HTTPS, but this is both hard to figure out from above Netty, and completely obvious once you start logging packets with Wireshark.  Closing.
