### ISSUE TITLE
Log exceptions thrown in Global.onStart(...)

### ISSUE THREAD

**Issue by martinburger** [playframework/playframework#2118]
Currently, when an exception is thrown in `Global.onStart(...)`, Play silently fails to start without printing and logging, respectively, that exception.

It would make deployment easier if Play would log exceptions thrown in that method.

**Comment by recastrodiaz** [comment]
Hi @jroper, @martinburger 
I've just hit this issue and there is an easy way to replicate it:

``` SH
# 1. Create a sample app
activator new my-first-app play-scala
# 2. Edit the file application.conf and add the following Guice Module
play.modules.enabled += "app.inject.DoesNotExistModule"
# 3. Replace logback.xml contents by https://www.playframework.com/documentation/2.4.x/SettingsLogger#Default-configuration
# 4. Compile it for prod mode
activator clean compile stage
# 5. Run the app and see that the exception is not logged in application.log
target/universal/stage/bin/my-first-app
``` 

The console shows:
``` LOG
[...]
10:50:28,747 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebeaninternal.server.core.XmlConfigLoader] to OFF
10:50:28,747 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebeaninternal.server.lib.BackgroundThread] to OFF
10:50:28,747 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.gargoylesoftware.htmlunit.javascript] to OFF
10:50:28,747 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
10:50:28,747 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCFILE] to Logger[ROOT]
10:50:28,747 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCSTDOUT] to Logger[ROOT]
10:50:28,747 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:50:28,747 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@37858383 - Registering current configuration as safe fallback point

Oops, cannot start the server.
@6p22o1b6c: Cannot load module
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:131)
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:103)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at play.api.inject.Modules$.locate(Module.scala:103)
        at play.api.inject.guice.GuiceableModule$.loadModules(GuiceInjectorBuilder.scala:203)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:22)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:22)
        at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:79)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: app.controllers.DevModule
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:105)
        ... 20 more
``` 

But the application.log file is empty. Whenever I hit this is usually because I've messed up the dependency injection graph. (I either forgot to Inject a dependency or did it in the wrong order, thus these wouldn't be catch by the compiler.) Not having any info in the logs, make it really hard to debug what's wrong, specially when the injection module is different in dev than the one in prod.

I don't know enough about the internals of play to create a fix for this. But let me know if there's anything else I can do to help, or if I should open a new issue.

Thanks,

Rodrigo
