### ISSUE TITLE
Native library support in development mode(play run)

### ISSUE THREAD

**Issue by lnxmnx** [playframework/playframework#2212]
Hi all!
Play version: 2.2.1.
Scala version: 2.10
OpenCV version: 2.4.7. I actually don't think that this error is connected with OpenCV. OpenCV is just where I got the following error.

OpenCV comes in two files:
- java jar file(opencv-247.jar)
- native library(libopencv_java247.so)

Description:
I've loaded the openCV library this way:

class Global  extends GlobalSettings {
    override def beforeStart(app: Application) {
        super.beforeStart(app);
        System.loadLibrary("opencv_java247")
    }
}

Then, in my code I call for opencv functions:

val m  = Mat.eye(3, 3, CvType.CV_8UC1)

If I start this program  with "play start" no error occurs. I get the matrix, program works as expected.

But if I start with "play run" this error occurs:
play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_eye(III)J]]

StackTrace:

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_eye(III)J]]
    at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.1]
    at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.1]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10.jar:2.2.1]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10.jar:2.2.1]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_eye(III)J
    at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:314) ~[play_2.10.jar:2.2.1]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:109) ~[play_2.10.jar:2.2.1]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:109) ~[play_2.10.jar:2.2.1]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:18) ~[play_2.10.jar:2.2.1]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:108) ~[play_2.10.jar:2.2.1]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:107) ~[play_2.10.jar:2.2.1]
Caused by: java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_eye(III)J
    at org.opencv.core.Mat.n_eye(Native Method) ~[opencv-247.jar:na]
    at org.opencv.core.Mat.eye(Mat.java:1467) ~[opencv-247.jar:na]
    at controllers.Application$$anonfun$getMatrix$1.apply(Application.scala:47) ~[classes/:na]
    at controllers.Application$$anonfun$getMatrix$1.apply(Application.scala:45) ~[classes/:na]
    at play.api.mvc.ActionBuilder$$anonfun$apply$11.apply(Action.scala:255) ~[play_2.10.jar:2.2.1]
    at play.api.mvc.ActionBuilder$$anonfun$apply$11.apply(Action.scala:255) ~[play_2.10.jar:2.2.1]

**Comment by CharlesLovely** [comment]
@katzelad @shkhln Could you share a working gist of that solution?  In my own testing, I couldn't get this approach to work.

Also, :+1: on getting this working correctly in Play in the first place.  Would be great to see this issue permanently resolved.

**Comment by shkhln** [comment]
@CharlesLovely 

> Could you share a working gist of that solution?

PlayNativeLibHack.java:

```
public final class PlayNativeLibHack {

  public static void load(String name) {
    // http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/lang/System.java#l1083
    // http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/lang/Runtime.java#l809
    System.load(name); // -> ClassLoader.loadLibrary(PlayNativeLibHack.class, name, true);
  }
}
```

```
$ javac PlayNativeLibHack.java
$ jar cf play-native-lib-loader.jar PlayNativeLibHack.class
$ cp play-native-lib-loader.jar ~/project-dir/lib
```

Global.scala
```
import play._

class Global extends GlobalSettings {

  override def beforeStart(app: Application) {
    PlayNativeLibHack.load(app.getFile("./lib/libopencv_java247.so").getPath)
  }
}
```

> Also, :+1: on getting this working correctly in Play in the first place. Would be great to see this issue permanently resolved.

I believe it (eventually) might be possible with fork run support. See "Possible TO DOs" section @ https://github.com/playframework/playframework/pull/3591#issue-47418922.

**Comment by CharlesLovely** [comment]
@shkhln Awesome - that approach works for me!  :)

**Comment by jroper** [comment]
As for what to do about this, perhaps it should simply be documented how to do this in Play, I don't think there's any straight forward way that we can fix this in Play itself.

**Comment by sergmor** [comment]
Maybe (not) an update, this becomes rather simple as DI is implemented and you want to use JNA, since the DI FW will take care of the classloaders.

**Comment by shkhln** [comment]
DI has nothing to do with the issue.

JNA avoids the problem by calling [System.loadLibrary](https://github.com/java-native-access/jna/blob/4ba3c1d9e85caf837ba3d524dca9de1dba0d6a38/src/com/sun/jna/Native.java#L860) by itself, this is a *caller sensitive* method and it will use the classloader of the calling class. As long as that call is placed somewhere outside of reloadable code managed by Play sbt plugin, everything works as expected.

**Comment by akashkharade** [comment]
Hi shkhln ,

I am getting the same error mentioned above.

When I execute "activator run" command. I have attached screenshot of the same.

Can you please help with this?

I tried solution given by you many times. I did't get  from where "libopencv_java247.so" will load.

Is ".so" extension supported by windows.?



![test](https://cloud.githubusercontent.com/assets/14108278/19518756/6f83b95e-9626-11e6-81c2-ec627168cbd4.png)

**Comment by shkhln** [comment]
> Is ".so" extension supported by windows.?
No, of course not. For windows you need a dll.

**Comment by akashkharade** [comment]
Hi shkhln ,
Thanks  for the quick response, but still I didn't get the solution
Steps I followed are:

1. first I created PlayNativeLibHack.java file then,
a.  javac PlayNativeLibHack.java
b. jar cf play-native-lib-loader.jar PlayNativeLibHack.class
c. copy play-native-lib-loader.jar ~/project-dir/lib

2. In Global.scala file in before start method 

PlayNativeLibraryLoader.load(Play.application().getFile("/lib/libopencv_java247.dll").getPath());


![error](https://cloud.githubusercontent.com/assets/14108278/19559388/3f25433c-96ed-11e6-9f6e-426129cd6f0f.png)

**Comment by shkhln** [comment]
@akashkharade Please, next time ask your questions on the mailing list: https://groups.google.com/forum/#!forum/play-framework. Did you miss [opencv download link for windows](https://sourceforge.net/projects/opencvlibrary/files/opencv-win/2.4.13/opencv-2.4.13.exe/download) somehow? _Renaming .so to .dll will not work either._

**Comment by akashkharade** [comment]
Issue has been resolved,

No need to download any library for jnotify or opencv.

Initially in plugins.sbt version was 2.3.0,

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.0")

I changed it to,

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.2")

Thanks for all your support.

**Comment by syedihuda** [comment]
Hi All, I'm having an issue similar to the one @akashkharade had with jnotify.  

`Error loading library, java.library.path=C:\Program Files\Java\jdk1.8.0_111\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\cygwin64\usr\local\bin;C:\cygwin64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Program Files\PostgreSQL\9.6\bin;C:\Program Files\Git\cmd;C:\dev\utils\activator-1.3.5-minimal;C:\Users\shuda\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Heroku\bin;.;C:\dev\projects\energywatch-portal-bk\target\native_libraries\64bits

Cannot load the JNotify native library (no jnotify_64bit in java.library.path)
Play will check file changes for each request, so expect degraded reloading performace.

--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[success] Compiled in 1s
`

I've tried many things with no success.  I've tried changing from:

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.2")

to 

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.3.2")

and I get another error:
```

java.lang.NoClassDefFoundError: play/Project$
        at com.typesafe.sbt.SbtEchoPlay$.tracePlaySettings(SbtEchoPlay.scala:19)
        at com.typesafe.sbt.SbtEchoPlay$.echoPlaySettings$lzycompute(SbtEchoPlay.scala:16)
        at com.typesafe.sbt.SbtEchoPlay$.echoPlaySettings(SbtEchoPlay.scala:16)
...
Caused by: java.lang.ClassNotFoundException: play.Project$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.typesafe.sbt.SbtEchoPlay$.tracePlaySettings(SbtEchoPlay.scala:19)
        at com.typesafe.sbt.SbtEchoPlay$.echoPlaySettings$lzycompute(SbtEchoPlay.scala:16)
        at com.typesafe.sbt.SbtEchoPlay$.echoPlaySettings(SbtEchoPlay.scala:16)
       ...

```

So, here's my environment setup currently:

scalaVersion := "2.10.3"   -> from build.sbt
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.2")   ->  from plugins.sbt
sbt.version=0.13.1  -> from build.properties

Also, I'm on Win 10 (64bit)

Really need some assistance here, been stuck for a few days.

**Comment by marcospereira** [comment]
I'm closing this since there is already workarounds and they are not related to Play itself.
