### ISSUE TITLE
Adding externalPom causes NoSuchElementException on play-docs classpath

### ISSUE THREAD

**Issue by JAlexoid** [playframework/playframework#2381]
If I add externalPom(baseDirectory(_ / "pom.xml")) to build.sbt I get when I try to do play run or sbt run. The contents of the pom.xml file have no effect, if can be a barebones pom.xml with only the artifact definition.

```
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:337)
	at scala.collection.immutable.Nil$.head(List.scala:334)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:220)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:91)
	at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:35)
	at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

```scala
        val docsLoader = new URLClassLoader(urls(docsAppClasspath), applicationLoader)
        val docsJarFile = {
           // The following line causes the error
          val f = docsAppClasspath.map(_.data).filter(_.getName.startsWith("play-docs")).head
          new JarFile(f)
        }
```

**Comment by wsargent** [comment]
Closing for lack of activity
