### ISSUE TITLE
Exception Logged After Refusing "Expect: continue" request

### ISSUE THREAD

**Issue by SattaiLanfear** [playframework/playframework#2485]
This might be related to #1842 but as the circumstances are a little different (I chose to close the connection instead of the connection being closed by the user) I thought it sufficiently distinct.

After using an EssentialAction to refuse a request using "Expect: continue", like below:

``` scala
  def receiveFile = EssentialAction { rh =>
    Done(Forbidden)
  }
```

I see error messages like so:

```
[error] play - Exception caught in RequestBodyHandler
java.nio.channels.ClosedChannelException: null
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:434) ~[netty.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:374) ~[netty.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:81) ~[netty.jar:na]
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36) ~[netty.jar:na]
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54) ~[netty.jar:na]
```

Importantly - it's not the _first_ refused continuation that seems to cause this exception, but the second and all subsequent.

**Comment by wsargent** [comment]
Possible this might be fixed by using Streams instead of iteratees...

**Comment by marcospereira** [comment]
Fixed. The following action does not log any errors:

```scala
  def upload = EssentialAction { rh =>
    Accumulator.done(Ok)
  }
```

I've tested both Akka HTTP and Netty server backends.
