### ISSUE TITLE
integration tests do not work by default in intellij

### ISSUE THREAD

**Issue by qwe99** [playframework/playframework#2507]
When creating a new play project and using the intellij sbt import functionality the integration tests do not run and fail with the following error:

```
org.specs2.execute.Error$ThrowableException: VerifyError: Cannot inherit from final class
                at play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:57)
                at play.api.test.WithBrowser$$anonfun$around$3.apply(Specs.scala:57)
                at play.api.test.PlayRunners$class.running(Helpers.scala:60)
                at play.api.test.Helpers$.running(Helpers.scala:364)
                at play.api.test.WithBrowser.around(Specs.scala:57)
                at play.api.test.WithBrowser.delayedInit(Specs.scala:45)
                at IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1.<init>(IntegrationSpec.scala:17)
                at IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
                at IntegrationSpec$$anonfun$1$$anonfun$apply$1.apply(IntegrationSpec.scala:17)
Caused by: java.lang.VerifyError: Cannot inherit from final class
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
                at com.gargoylesoftware.htmlunit.HttpWebConnection.createHttpClient(HttpWebConnection.java:554)
                at com.gargoylesoftware.htmlunit.HttpWebConnection.getHttpClient(HttpWebConnection.java:518)
                at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:155)
                at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1486)
                at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1403)
                at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:305)
                at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:374)
                at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:359)
                at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:346)
                at org.fluentlenium.core.Fluent.goTo(Fluent.java:228)
                at IntegrationSpec$$anonfun$1$$anonfun$apply$1$$anon$1$delayedInit$body.apply(IntegrationSpec.scala:19)
                ... 9 more
```

Running the tests from the play console works correctly.  

It appears that there are multiple versions of some libraries that intellij is picking up.   In this case removing org.apache.httpcomponents.httpclient:4.0.1 and leaving org.apache.httpcomponents.httpclient:4.2.1 fixes the error.

I was seeing this error with play 2.2.2 and intellij 13.1.

**Comment by qabbasi** [comment]
+1 merci

**Comment by fedelopez** [comment]
+1

**Comment by atifmansoor** [comment]
+1 (Using Play 2.4.3 and IntelliJ 14.1.5 Community Ed.)
In my case, in order to get the test running in IntelliJ, I had to remove httpclient:4.01.jar from the Module libraries, run `activator test`, and add this line to my build.sbt:
`unmanagedResourceDirectories in Test <+=  baseDirectory ( _ /"target/web/public/test" )`

**Comment by wsargent** [comment]
This is an Intellij bug -- in any event, there are no reports since IntelliJ 15, so it looks like they fixed it.
