### ISSUE TITLE
Test fails after upgrading to latest jQuery

### ISSUE THREAD

**Issue by amosjyng** [playframework/playframework#2607]
I have the same problem as this guy: http://stackoverflow.com/questions/21945824/error-running-selenium-test-with-jquery-v2-0-2-and-play-framework

My error output:

```
[error] Test IntegrationTest.test failed: org.openqa.selenium.WebDriverException: com.gargoylesoftware.htmlunit.ScriptException: TypeError: Cannot find function addEventListener in object [object HTMLDocument]. (http://localhost:3333/assets/javascripts/jquery-2.0.3.min.js#4)
[error] Build info: version: '2.32.0', revision: '6c40c187d01409a5dc3b7f8251859150c8af0bcb', time: '2013-04-09 10:39:28'
[error] System info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-23-generic', java.version: '1.6.0_30'
[error] Driver info: driver.version: HtmlUnitDriver
[error]     at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:367)
...
```

Funny thing is, when I change `main.scala.html` to point to a non-existent Javascript file:

```
[error] c.g.h.h.HtmlPage - Error loading JavaScript from [http://localhost:3333/assets/javascripts/jquery-nonexistent.min.js].
java.io.IOException: Unable to download JavaScript from 'http://localhost:3333/assets/javascripts/jquery-nonexistent.min.js' (status 404).
        at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1125) ~[htmlunit.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1059) ~[htmlunit.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:399) ~[htmlunit.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:260) ~[htmlunit.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:276) ~[htmlunit.jar:2.12]
        at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:676) ~[htmlunit.jar:2.12]
[info] IntegrationTest
[info] + test
[info]
[info]
[info] Total for test IntegrationTest
[info] Finished in 0.009 seconds
[info] 1 tests, 0 failures, 0 errors
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 44 s, completed Apr 5, 2014 4:17:51 PM
```

Everything passes, as it should, because the only assertion made in `IntegrationTest` is this:

```
assertThat(browser.pageSource()).contains("Your new application is ready.");
```

Any idea what I might do to resolve this test error?

**Comment by nafg** [comment]
FWIW I'm still getting this with jquery 2.1.4 and htmlunit 2.19

**Comment by nafg** [comment]
It seems the issue is that htmlunit (and therefore play) default to IE8 mode. If you write `new WithBrowser(webDriver = new HtmlUnitDriver(BrowserVersion.CHROME, true))`, it works (haven't tried IE11).

This is as spec'ed, because jquery 2 is not meant to work with older IEs. I don't know why htmlunit defaults to IE8, but does that mean Play should?

**Comment by rowanl** [comment]
Still getting this error on play 2.5, the HTMLUnitDriver inside WithBrowser is protected.

Please can you fix this?

**Comment by wsargent** [comment]
@rowanl can you provide a sample github test project so we can reproduce this?
