### ISSUE TITLE
JsTaskFailure while less compilation

### ISSUE THREAD

**Issue by afrischk** [playframework/playframework#2662]
Hello,

I just upgraded from play 2.2.2 to play 2.3-M1 and followed the migration guide and looked at the sample hello world example in typesafe activator. I use bootstrap for style. Everything is working fine except one thing. When I add my own less files based on bootstrap in assets.stylesheets I get an error. It says:

! @6hpl0h7bh - Internal server error, for (GET) [/] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[JsTaskFailure: ]
    at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:293) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$play$PlayReloader$$anon$$taskFailureHandler$1.apply(PlayReloader.scala:285) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library-2.10.4-RC2.jar:na]
    at play.PlayReloader$$anon$1.play$PlayReloader$$anon$$taskFailureHandler(PlayReloader.scala:285) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2.apply(PlayReloader.scala:318) ~[na:na]
Caused by: com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: 
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:204) ~[na:na]
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:176) ~[na:na]
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[scala-library-2.10.4-RC2.jar:na]
    at scala.util.Try$.apply(Try.scala:161) ~[scala-library-2.10.4-RC2.jar:na]
    at scala.util.Success.map(Try.scala:206) ~[scala-library-2.10.4-RC2.jar:na]

When I remove my own less files or add own css files, everything works again.

**Comment by meherbenahmed07** [comment]
install node and all is good
