### ISSUE TITLE
play 2.2.2 throws trace exception but keep working just fine

### ISSUE THREAD

**Issue by reviyou** [playframework/playframework#2766]
Hello, 
I thought I'd share some weird exception we are getting in logs. We make a simple GET call which gets returned no problem. However during tailing logs we found this exception persis happening after each request:

ET /api/1.0/rest/testServiceGet?foo=A&bar=100 HTTP/1.0
X-Real-IP: 96.224.4.24
X-Forwarded-For: 96.224.4.24
Host: api.reviyou.com
Connection: close
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6
494695 [New I/O worker #1] TRACE play - Serving this request with: <function1>
494695 [play-akka.actor.default-dispatcher-14] TRACE play - Parsing AnyContent as empty
494696 [play-akka.actor.default-dispatcher-14] TRACE play - Invoking action with request: GET /api/1.0/rest/testServiceGet?foo=A&bar=100
494703 [New I/O worker #1] TRACE play.nettyException - Benign IO exception caught in Netty
java.nio.channels.ClosedChannelException: null
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:434) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:374) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:81) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54) ~[io.netty.netty-3.7.0.Final.jar:na]
    at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:88) ~[com.typesafe.netty.netty-http-pipelining-1.1.2.jar:na]
    at play.core.server.netty.NettyResultStreamer$$anonfun$sendResult$1.apply(NettyResultStreamer.scala:69) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
    at play.core.server.netty.NettyResultStreamer$$anonfun$sendResult$1.apply(NettyResultStreamer.scala:61) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[org.scala-lang.scala-library-2.10.3.jar:na]
    at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) ~[com.typesafe.play.play-iteratees_2.10-2.2.2.jar:2.2.2]
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) ~[org.scala-lang.scala-library-2.10.3.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) ~[org.scala-lang.scala-library-2.10.3.jar:na]
    at scala.concurrent.Promise$class.complete(Promise.scala:55) ~[org.scala-lang.scala-library-2.10.3.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) ~[org.scala-lang.scala-library-2.10.3.jar:na]
    at scala.concurrent.Promise$class.success(Promise.scala:89) ~[org.scala-lang.scala-library-2.10.3.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:153) ~[org.scala-lang.scala-library-2.10.3.jar:na]
    at play.core.server.netty.NettyPromise$$anon$1.operationComplete(NettyPromise.scala:22) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:413) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:221) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromTaskLoop(AbstractNioWorker.java:152) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioChannel$WriteTask.run(AbstractNioChannel.java:335) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:366) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:290) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90) ~[io.netty.netty-3.7.0.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[io.netty.netty-3.7.0.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
    at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
500587 [New I/O worker #2] TRACE play - Http request received by netty: DefaultHttpRequest(chunked: false)
GET /api/1.0/rest/testServiceGet?foo=A&bar=100 HTTP/1.0
X-Real-IP: 96.224.4.24
X-Forwarded-For: 96.224.4.24
Host: api.reviyou.com
Connection: close
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6
500589 [New I/O worker #2] TRACE play - Serving this request with: <function1>
500590 [play-akka.actor.default-dispatcher-12] TRACE play - Parsing AnyContent as empty
500590 [play-akka.actor.default-dispatcher-12] TRACE play - Invoking action with request: GET /api/1.0/rest/testServiceGet?foo=A&bar=100
500597 [New I/O worker #2] TRACE play.nettyException - Benign IO exception caught in Netty
java.nio.channels.ClosedChannelException: null
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:434) ~[io.netty.netty-3.7.0.Final.jar:na]

**Comment by giuseppegreco** [comment]
I'm using Play 2.3.8 but this error is logged as ERROR:

2015-11-15 21:09:12 +0100 - [ERROR] - from play.nettyException in New I/O worker #9 
Exception caught in Netty
