### ISSUE TITLE
2.3.0-RC1 not readable compilation error in template

### ISSUE THREAD

**Issue by ajozwik** [playframework/playframework#2865]
Code in https://github.com/ajozwik/play-scala-preview/tree/2.3-RC1-twirl_problem

In index.scala.html the code contains error:

If statement `@if(None!=None){` is not correctly closed and is duplicated. It is just very simple example, but in real code unclosed statements is hard to find.
See https://github.com/ajozwik/play-scala-preview/blob/2.3-RC1-twirl_problem/app/views/index.scala.html

```
@(message: String)

@main("Welcome to Play") {

@if(None!=None){
@if(None!=None){
<h1>Hello world</h1>
}

}
```

When you compile this class you receive just `java.lang.IndexOutOfBoundsException`:

```
[trace] Stack trace suppressed: run last compile:twirlCompileTemplates for the full output.
[error] (compile:twirlCompileTemplates) java.lang.IndexOutOfBoundsException: 10
[error] Total time: 0 s, completed May 16, 2014 10:23:36 AM
```

When you want see details the error is still not readable:

```
[play-scala-preview] $ last compile:twirlCompileTemplates
java.lang.IndexOutOfBoundsException: 10
        at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:52)
        at scala.collection.immutable.List.apply(List.scala:84)
        at play.twirl.sbt.TemplateProblem$TemplatePosition$.apply(TemplateProblem.scala:37)
        at play.twirl.sbt.TemplateProblem$.exception(TemplateProblem.scala:19)
        at play.twirl.sbt.TemplateCompiler$$anonfun$handleError$1.applyOrElse(TemplateCompiler.scala:57)
        at play.twirl.sbt.TemplateCompiler$$anonfun$handleError$1.applyOrElse(TemplateCompiler.scala:55)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at play.twirl.sbt.TemplateCompiler$.compile(TemplateCompiler.scala:28)
        at play.twirl.sbt.SbtTwirl$$anonfun$compileTemplatesTask$1.apply(SbtTwirl.scala:77)
        at play.twirl.sbt.SbtTwirl$$anonfun$compileTemplatesTask$1.apply(SbtTwirl.scala:76)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
...
[error] (compile:twirlCompileTemplates) java.lang.IndexOutOfBoundsException: 10
```

**Comment by yangmingsen** [comment]
```
[error] java.lang.ExceptionInInitializerError
[error]         at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$.getFunctionMapping(TwirlCompiler.scala:425)
[error]         at play.twirl.compiler.TwirlCompiler$.generateCode(TwirlCompiler.scala:326)
[error]         at play.twirl.compiler.TwirlCompiler$.generateFinalTemplate(TwirlCompiler.scala:377)
[error]         at play.twirl.compiler.TwirlCompiler$.parseAndGenerateCode(TwirlCompiler.scala:206)
[error]         at play.twirl.compiler.TwirlCompiler$.compile(TwirlCompiler.scala:174)
[error]         at play.twirl.sbt.TemplateCompiler$.$anonfun$compile$2(TemplateCompiler.scala:42)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:788)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:787)
[error]         at play.twirl.sbt.TemplateCompiler$.compile(TemplateCompiler.scala:39)
[error]         at play.twirl.sbt.SbtTwirl$.$anonfun$compileTemplatesTask$1(SbtTwirl.scala:108)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.NullPointerException
[error]         at java.util.Arrays.sort(Arrays.java:1438)
[error]         at scala.tools.nsc.classpath.JFileDirectoryLookup.listChildren(DirectoryClassPath.scala:116)
[error]         at scala.tools.nsc.classpath.JFileDirectoryLookup.listChildren$(DirectoryClassPath.scala:100)
[error]         at scala.tools.nsc.classpath.DirectoryClassPath.listChildren(DirectoryClassPath.scala:283)
[error]         at scala.tools.nsc.classpath.DirectoryClassPath.listChildren(DirectoryClassPath.scala:283)
[error]         at scala.tools.nsc.classpath.DirectoryLookup.list(DirectoryClassPath.scala:76)
[error]         at scala.tools.nsc.classpath.DirectoryLookup.list$(DirectoryClassPath.scala:72)
[error]         at scala.tools.nsc.classpath.DirectoryClassPath.list(DirectoryClassPath.scala:283)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$list$1(AggregateClassPath.scala:76)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.list(AggregateClassPath.scala:74)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:271)
[error]         at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
[error]         at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[error]         at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:225)
[error]         at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:65)
[error]         at scala.tools.nsc.Global.rootMirror(Global.scala:63)
[error]         at scala.tools.nsc.Global.rootMirror(Global.scala:36)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:287)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:287)
[error]         at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1454)
[error]         at scala.tools.nsc.Global$Run.<init>(Global.scala:1179)
[error]         at scala.tools.nsc.interactive.Global$TyperRun.<init>(Global.scala:1314)
[error]         at scala.tools.nsc.interactive.Global.newTyperRun(Global.scala:1337)
[error]         at scala.tools.nsc.interactive.Global.<init>(Global.scala:286)
[error]         at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$CompilerInstance.compiler$lzycompute(TwirlCompiler.scala:507)
[error]         at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$CompilerInstance.compiler(TwirlCompiler.scala:481)
[error]         at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$PresentationCompiler$.<init>(TwirlCompiler.scala:549)
[error]         at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$PresentationCompiler$.<clinit>(TwirlCompiler.scala)
[error]         at play.twirl.compiler.TwirlCompiler$TemplateAsFunctionCompiler$.getFunctionMapping(TwirlCompiler.scala:425)
[error]         at play.twirl.compiler.TwirlCompiler$.generateCode(TwirlCompiler.scala:326)
[error]         at play.twirl.compiler.TwirlCompiler$.generateFinalTemplate(TwirlCompiler.scala:377)
[error]         at play.twirl.compiler.TwirlCompiler$.parseAndGenerateCode(TwirlCompiler.scala:206)
[error]         at play.twirl.compiler.TwirlCompiler$.compile(TwirlCompiler.scala:174)
[error]         at play.twirl.sbt.TemplateCompiler$.$anonfun$compile$2(TemplateCompiler.scala:42)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:788)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:787)
[error]         at play.twirl.sbt.TemplateCompiler$.compile(TemplateCompiler.scala:39)
[error]         at play.twirl.sbt.SbtTwirl$.$anonfun$compileTemplatesTask$1(SbtTwirl.scala:108)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / twirlCompileTemplates) java.lang.ExceptionInInitializerError
[error] Total time: 4 s, completed 2019-2-17 10:33:39
```

**Comment by yangmingsen** [comment]
What is the problem?
