### ISSUE TITLE
PlayReloader -> JNotifyException_linux: Error removing watch 132

### ISSUE THREAD

**Issue by slorber** [playframework/playframework#2946]
**Updated**:

The problem seems to be due to a filesystem filename limit.
See edit here: https://github.com/playframework/playframework/issues/2946#issuecomment-44276454

---

At work we have someone with Ubuntu 12.04 which can't start play at all because of a JNotify errors during the compilation.

```
uncaught exception during compilation: java.io.IOException]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library-2.10.3.jar:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library-2.10.3.jar:na]
[warn] play - No application found at invoker init
net.contentobjects.jnotify.linux.JNotifyException_linux: Error removing watch 132
    at net.contentobjects.jnotify.linux.JNotify_linux.removeWatch(Unknown Source)
    at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.unwatch(Unknown Source)
    at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.removeWatch(Unknown Source)
    at net.contentobjects.jnotify.JNotify.removeWatch(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayReloader$$anon$1$$anon$6.removeWatch(PlayReloader.scala:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayReloader$$anon$1$$anonfun$clean$1.apply$mcVI$sp(PlayReloader.scala:162)
    at play.PlayReloader$$anon$1$$anonfun$clean$1.apply(PlayReloader.scala:162)
    at play.PlayReloader$$anon$1$$anonfun$clean$1.apply(PlayReloader.scala:162)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at play.PlayReloader$$anon$1.clean(PlayReloader.scala:162)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:320)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:91)
    at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:35)
    at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
net.contentobjects.jnotify.linux.JNotifyException_linux: Error removing watch 134
    at net.contentobjects.jnotify.linux.JNotify_linux.removeWatch(Unknown Source)
    at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.unwatch(Unknown Source)
    at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.removeWatch(Unknown Source)
    at net.contentobjects.jnotify.JNotify.removeWatch(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayReloader$$anon$1$$anon$6.removeWatch(PlayReloader.scala:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayReloader$$anon$1$$anonfun$clean$1.apply$mcVI$sp(PlayReloader.scala:162)
    at play.PlayReloader$$anon$1$$anonfun$clean$1.apply(PlayReloader.scala:162)
    at play.PlayReloader$$anon$1$$anonfun$clean$1.apply(PlayReloader.scala:162)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at play.PlayReloader$$anon$1.clean(PlayReloader.scala:162)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:320)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:91)
    at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:35)
    at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
net.contentobjects.jnotify.linux.JNotifyException_linux: Error removing watch 134
    at net.contentobjects.jnotify.linux.JNotify_linux.removeWatch(Unknown Source)
    at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.unwatch(Unknown Source)
    at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.removeWatch(Unknown Source)
    at net.contentobjects.jnotify.JNotify.removeWatch(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayReloader$$anon$1$$anon$6.removeWatch(PlayReloader.scala:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayReloader$$anon$1$$anonfun$clean$1.apply$mcVI$sp(PlayReloader.scala:162)
    at play.PlayReloader$$anon$1$$anonfun$clean$1.
```

Notice that He's not the only one according to this topic, but didn't find any bug open yet:
https://groups.google.com/forum/#!topic/play-framework/UXjYQ_1u7xs

I've noticed these commits in Play 2.3-RCx which handle some JNotify problems, but it does only seem to cover initialization problems and not a problem during the removing of watches.
https://github.com/playframework/playframework/issues/2831
https://github.com/playframework/playframework/commit/07b070b498e488a55c7fa9d5dc9174029f82c498

Maybe on this kind of watch removal error, the strategy could go to the fallback method.
Or at least it would be cool to be able to disable the JNotify system with a system property or an SBT setting?

Note that we are both using Ubuntu 12.04 with an 3.5.0-49-generic kernel, and for me it works fine

**Comment by ranaraj** [comment]
Hi,
I am using 2.3.8 version in linux system and getting same error, tried to do crtl+D multiple time and restared system but still same issue, localhost:9000 is not working, please suggest

 $ run

--- (Running the application, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

net.contentobjects.jnotify.linux.JNotifyException_linux: Error removing watch 2
	at net.contentobjects.jnotify.linux.JNotify_linux.removeWatch(Unknown Source)
	at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.unwatch(Unknown Source)
	at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.removeWatch(Unknown Source)
	at net.contentobjects.jnotify.JNotify.removeWatch(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at play.runsupport.JNotifyPlayWatchService$JNotifyDelegate.removeWatch(PlayWatchService.scala:148)
	at play.runsupport.JNotifyPlayWatchService$$anon$4$$anonfun$stop$1.apply$mcVI$sp(PlayWatchService.scala:126)
	at play.runsupport.JNotifyPlayWatchService$$anon$4$$anonfun$stop$1.apply(PlayWatchService.scala:126)
	at play.runsupport.JNotifyPlayWatchService$$anon$4$$anonfun$stop$1.apply(PlayWatchService.scala:126)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.runsupport.JNotifyPlayWatchService$$anon$4.stop(PlayWatchService.scala:126)
	at play.runsupport.Reloader.close(Reloader.scala:354)
	at play.runsupport.Reloader$$anon$4.close(Reloader.scala:213)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:123)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:54)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)

[success] Total time: 10 s, completed May 5, 2015 11:22:41 PM
