### ISSUE TITLE
activator new failure

### ISSUE THREAD

**Issue by zoyaforever** [playframework/playframework#2960]
After I run the command: "activator new myapp play-java",  i get the following error:
(I use play 2.3.0)

```
Fetching the latest list of templates...

五月 30, 2014 10:02:00 下午 com.amazonaws.http.AmazonHttpClient executeHelper
信息: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.c
om/54.231.1.176 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.ama
zonaws.com/54.231.1.176 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFact
ory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnect
ion(DefaultClientConnectionOperator.java:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.ja
va:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPool
edConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(Default
RequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultReq
uestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.ja
va:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165
)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2
951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.jav
a:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.jav
a:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFr
omS3(UriRemoteTemplateRepository.scala:104)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTr
yingS3First(UriRemoteTemplateRepository.scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveInd
exProperties(UriRemoteTemplateRepository.scala:208)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$h
asNewIndex$1.apply(UriRemoteTemplateRepository.scala:175)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$h
asNewIndex$1.apply(UriRemoteTemplateRepository.scala:173)
        at sbt.IO$.withTemporaryDirectory(IO.scala:285)
        at activator.templates.repository.UriRemoteTemplateRepository.hasNewInde
x(UriRemoteTemplateRepository.scala:173)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:
130)
        at akka.actor.ActorCell.create(ActorCell.scala:562)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:425)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
        at akka.dispatch.Mailbox.run(Mailbox.scala:218)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
ractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)


Could not fetch the updated list of templates.  Using the local cache.
Check your proxy settings or increase the timeout.  For more details see:
http://typesafe.com/activator/docs

[ERROR] [05/30/2014 22:02:05.719] [fallback-akka.actor.default-dispatcher-4] [ak
ka://fallback/user/template-cache] null
akka.actor.ActorInitializationException: exception during creation
        at akka.actor.ActorInitializationException$.apply(Actor.scala:218)
        at akka.actor.ActorCell.create(ActorCell.scala:578)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:425)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
        at akka.dispatch.Mailbox.run(Mailbox.scala:218)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
ractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)
Caused by: java.lang.NullPointerException
        at org.apache.lucene.codecs.BlockTreeTermsReader.<init>(BlockTreeTermsRe
ader.java:162)
        at org.apache.lucene.codecs.lucene41.Lucene41PostingsFormat.fieldsProduc
er(Lucene41PostingsFormat.java:437)
        at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader
.<init>(PerFieldPostingsFormat.java:194)
        at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat.fieldsProduc
er(PerFieldPostingsFormat.java:233)
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.
java:127)
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:56)
        at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDire
ctoryReader.java:62)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfo
s.java:783)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirector
yReader.java:52)
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:66)

        at activator.cache.LuceneIndex.<init>(LuceneIndex.scala:170)
        at activator.cache.LuceneIndexProvider$$anonfun$open$1.apply(LuceneIndex
.scala:24)
        at activator.cache.LuceneIndexProvider$$anonfun$open$1.apply(LuceneIndex
.scala:22)
        at activator.cache.LuceneIndexProvider$.withLuceneClassLoader(LuceneInde
x.scala:35)
        at activator.cache.LuceneIndexProvider$.open(LuceneIndex.scala:22)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:
140)
        at akka.actor.ActorCell.create(ActorCell.scala:562)
        ... 9 more

五月 30, 2014 10:02:06 下午 com.amazonaws.http.AmazonHttpClient executeHelper
信息: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.c
om/54.231.1.176 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.ama
zonaws.com/54.231.1.176 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFact
ory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnect
ion(DefaultClientConnectionOperator.java:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.ja
va:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPool
edConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(Default
RequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultReq
uestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.ja
va:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165
)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2
951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.jav
a:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.jav
a:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFr
omS3(UriRemoteTemplateRepository.scala:104)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTr
yingS3First(UriRemoteTemplateRepository.scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveInd
exProperties(UriRemoteTemplateRepository.scala:208)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$h
asNewIndex$1.apply(UriRemoteTemplateRepository.scala:175)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$h
asNewIndex$1.apply(UriRemoteTemplateRepository.scala:173)
        at sbt.IO$.withTemporaryDirectory(IO.scala:285)
        at activator.templates.repository.UriRemoteTemplateRepository.hasNewInde
x(UriRemoteTemplateRepository.scala:173)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:
130)
        at akka.actor.ActorCell.create(ActorCell.scala:562)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:425)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
        at akka.dispatch.Mailbox.run(Mailbox.scala:218)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
ractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)

五月 30, 2014 10:02:12 下午 com.amazonaws.http.AmazonHttpClient executeHelper
信息: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.c
om/54.231.1.176 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.ama
zonaws.com/54.231.1.176 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFact
ory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnect
ion(DefaultClientConnectionOperator.java:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.ja
va:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPool
edConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(Default
RequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultReq
uestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpCl
ient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.ja
va:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165
)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2
951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.jav
a:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.jav
a:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFr
omS3(UriRemoteTemplateRepository.scala:104)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTr
yingS3First(UriRemoteTemplateRepository.scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveInd
exProperties(UriRemoteTemplateRepository.scala:208)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$h
asNewIndex$1.apply(UriRemoteTemplateRepository.scala:175)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$h
asNewIndex$1.apply(UriRemoteTemplateRepository.scala:173)
        at sbt.IO$.withTemporaryDirectory(IO.scala:285)
        at activator.templates.repository.UriRemoteTemplateRepository.hasNewInde
x(UriRemoteTemplateRepository.scala:173)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:
130)
        at akka.actor.ActorCell.create(ActorCell.scala:562)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:425)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:447)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:262)
        at akka.dispatch.Mailbox.run(Mailbox.scala:218)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
ractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)

java.util.concurrent.TimeoutException: Futures timed out after [10000 millisecon
ds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:96)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:100
)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockConte
xt.scala:53)
        at scala.concurrent.Await$.result(package.scala:107)
        at activator.TemplateHandler$.downloadTemplates(TemplateHandler.scala:38
)
        at activator.ActivatorCli$$anonfun$apply$1.apply$mcI$sp(ActivatorCli.sca
la:22)
        at activator.ActivatorCli$$anonfun$apply$1.apply(ActivatorCli.scala:19)
        at activator.ActivatorCli$$anonfun$apply$1.apply(ActivatorCli.scala:19)
        at activator.ActivatorCli$.withContextClassloader(ActivatorCli.scala:174
)
        at activator.ActivatorCli$.apply(ActivatorCli.scala:19)
        at activator.ActivatorLauncher.run(ActivatorLauncher.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by zarinfam** [comment]
I think Amazon S3 is blocked in Iran too because i have this problem with activator 1.3.

**Comment by qianghuang84** [comment]
I met the same problem, anyone can give a solution for this issue?

**Comment by lvheyang** [comment]
I met the same problem. Is there any other places we can download the templates?
