### ISSUE TITLE
[2.3.2] Play server fails to start with HTTPS enabled

### ISSUE THREAD

**Issue by prabhath** [playframework/playframework#3335]
I am using Play 2.3 with typesafe activator 1.2.2 in a linux enviorenment. I tried start play server with HTTPS using following command. 
````
activator start -Dhttps.port=9443
`````
Then it gives following error
`````
Oops, cannot start the server.java.lang.NumberFormatException: For input string: ""9443" "

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at play.core.server.NettyServer$$anonfun$16.apply(NettyServer.scala:209)
	at play.core.server.NettyServer$$anonfun$16.apply(NettyServer.scala:209)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:209)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:243)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:238)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:238)
	at play.core.server.NettyServer.main(NettyServer.scala)
```````
But if I give 
`````
activator run -Dhttps.port=9443
```````
it works fine.

**Comment by wsargent** [comment]
start deprecated now for testProd, closing.
