### ISSUE TITLE
CI testTemplates failures

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#3468]
We're getting CI failures when running `testTemplates`.

Example failure from PR #3342 ([console](https://playframework2.ci.cloudbees.com/job/play2-PRs/3058/consoleFull)):
```
[info] Preparing templates...
[info] Preparing templates for Play 2.4-SNAPSHOT
[info] Testing template: play-scala
[info] Testing template: play-java
[info] Testing template: play-scala-intro
Exception in thread "Thread-5" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2553)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1296)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
	at sbt.React.react(ForkTests.scala:117)
	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:76)
	at java.lang.Thread.run(Thread.java:662)
[info] Loading project definition from /scratch/jenkins/workspace/play2-PRs/templates/target/template-tests/play-scala-intro/project
[info] Updating {file:/scratch/jenkins/workspace/play2-PRs/templates/target/template-tests/play-scala-intro/project/}play-scala-intro-build...
[info] Resolving com.typesafe.play#sbt-plugin;2.4-SNAPSHOT ...
[info] Resolving com.typesafe.play#build-link;2.4-SNAPSHOT ...
...
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error] 	Running java with options -classpath ... sbt.ForkMain 49037 failed with exit code 255
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 43 s, completed Oct 1, 2014 5:18:47 PM
[error] Template play-scala-intro failed to build
[error] (*:testTemplates) play.sbt.activator.Templates$TemplateBuildFailed: play-scala-intro
[error] Total time: 159 s, completed Oct 1, 2014 5:18:48 PM
Build step 'Execute shell' marked build as failure
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE
```

**Comment by marcospereira** [comment]
@jroper and @richdougherty,

I'm closing this issue since we have a pretty stable ci. Feel free to reopen if necessary. :-)
