### ISSUE TITLE
Adding JVM params on activator command line does not work as expected

### ISSUE THREAD

**Issue by slimandslam** [playframework/playframework#3688]
When you type   "activator -help" it says:

```
 # jvm options and output control
  -Dkey=val          Pass -Dkey=val directly to the java runtime
  -J-X               Pass option -X directly to the java runtime
                     (-J is stripped)
```

When I type:

```
./activator -J-Xms1024m -J-Xmx3084m -J-XX:MaxPermSize=1024m
```

I'm expecting that activator will start with those settings. Instead,
I see:

```
/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/bin/java -Dactivator.home=/MYAPP -Xms1024m -Xmx1024m -XX:PermSize=64m -XX:MaxPermSize=256m -Xms1048m -Xmx3084m -XX:MaxPermSize=1024m -jar /MYAPP/activator-launch-1.2.10.jar
```

It appears that activator just added (but did not replace) my command line arguments to its defaults (?)

**Comment by gkarthik21** [comment]
@richdougherty is this issue resolved

**Comment by richdougherty** [comment]
@gkarthik21, I don't think it is resolved. In the meantime you'll need to edit the script yourself or use `JAVA_OPTS`. In the next version of Play I believe we're using vanilla sbt instead of Activator to run Play.

**Comment by shreya7816** [comment]
@richdougherty these commands are not working in windows. Can you suggest something else?
I am getting following error and to solve it I want to increase the heap size but activator -help and activator -J are not working in windows.

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PrivilegedActionException: null]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191)
        at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50)
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:59)
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at play.core.server.Server$class.getHandlerFor(Server.scala:57)
        at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:37)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:143)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:143)
Caused by: java.security.PrivilegedActionException: null
        at java.security.AccessController.doPrivileged(Native Method)
        at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:40)
        at play.runsupport.Reloader.reload(Reloader.scala:322)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:113)
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
        at sbt.Execute.next$1(Execute.scala:83)
        at sbt.Execute.processAll(Execute.scala:86)
        at sbt.Execute.runKeep(Execute.scala:66)
        at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:342)
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:341)
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:361)
        at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:258)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at scala.tools.nsc.typechecker.Contexts$Context.make(Contexts.scala:467)
        at scala.tools.nsc.typechecker.Contexts$Context.make(Contexts.scala:506)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1891)
        at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1762)
        at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5309)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
