### ISSUE TITLE
Discovery is incorrect for OpenID Provider driven identifier selection (identifier select) - Play 2.2.x, 2.3.x

### ISSUE THREAD

**Issue by dpmeyer** [playframework/playframework#3740]
When performing OpenID Authentication with a _**non-unique**_ OpenID Provider Identifier such as http://steamcommunity.com/openid, the following code:

```
String redirectUrl = OpenID.redirectURL("http://steamcommunity.com/openid",
     controllers.routes.Application.verifyLinkedAccount().absoluteURL(request()), 
     attributes1, attributes2, "http://www.mydomain.com").get();
```

generates a redirect URL in the format:

```
https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
     &openid.mode=checkid_setup
     &openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid
     &openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid
     &openid.return_to=http%3A%2F%2Fwww.mydomain.com%2Flogin%2Fverify
     &openid.realm=http%3A%2F%2Fwww.mydomain.com
```

This is incorrect per the OpenID 2.0 spec, specifically at http://openid.net/specs/openid-authentication-2_0.html#discovered_info: 

>If the end user entered an OpenID Provider (OP) Identifier, there is no Claimed Identifier. For the purposes of making OpenID Authentication requests, the value "http://specs.openid.net/auth/2.0/identifier_select" MUST be used as both the Claimed Identifier and the OP-Local Identifier when an OP Identifier is entered.

As a result, after a user authenticates with the provider, the "return to" URL becomes:

```
http://www.mydomain.com/login/verify?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
     &openid.mode=error
     &openid.error=Invalid+claimed_id+or+identity
```

and the code:

```
GET         /login/verify        controllers.Application.verifyLinkedAccount()
```

```
public static F.Promise<Result> verifyLinkedAccount() {
     return OpenID.verifiedId().map(new F.Function<OpenID.UserInfo, Result>() {
          public Result apply(OpenID.UserInfo userInfo) {
               return ok(Json.toJson(userInfo));
          }
      });
}
```

results in the following exception:

```
play.api.Application$$anon$1: Execution exception[[BAD_RESPONSE$: null]]
	at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.4]
	at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.4]
	at scala.Option.map(Option.scala:145) [scala-library.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:264) [play_2.10.jar:2.2.4]
Caused by: play.api.libs.openid.Errors$BAD_RESPONSE$: null
	at play.api.libs.openid.Errors$BAD_RESPONSE$.<clinit>(OpenIDError.scala) ~[play_2.10.jar:2.2.4]
	at play.api.libs.openid.OpenIDClient.verifiedId(OpenID.scala:111) ~[play_2.10.jar:2.2.4]
	at play.api.libs.openid.OpenIDClient.verifiedId(OpenID.scala:99) ~[play_2.10.jar:2.2.4]
	at play.api.libs.openid.OpenID.verifiedId(OpenID.scala) ~[play_2.10.jar:2.2.4]
	at play.libs.OpenID.verifiedId(OpenID.java:68) ~[play-java_2.10.jar:2.2.4]
	at controllers.Application.verifyLinkedAccount(Application.java:88) ~[classes/:na]
```

Looking at the Play Framework code (OpenIdClient.scala in 2.3.x and OpenId.scala in 2.2.x) I see the following:

```
  /**
   * Retrieve the URL where the user should be redirected to start the OpenID authentication process
   */
  def redirectURL(openID: String,
    callbackURL: String,
    axRequired: Seq[(String, String)] = Seq.empty,
    axOptional: Seq[(String, String)] = Seq.empty,
    realm: Option[String] = None): Future[String] = {

    val claimedId = discovery.normalizeIdentifier(openID)
    discovery.discoverServer(openID).map({ server =>
      val parameters = Seq(
        "openid.ns" -> "http://specs.openid.net/auth/2.0",
        "openid.mode" -> "checkid_setup",
        "openid.claimed_id" -> claimedId,
        "openid.identity" -> server.delegate.getOrElse(claimedId),
        "openid.return_to" -> callbackURL
      ) ++ axParameters(axRequired, axOptional) ++ realm.map("openid.realm" -> _).toList
      val separator = if (server.url.contains("?")) "&" else "?"
      server.url + separator + parameters.map(pair => pair._1 + "=" + URLEncoder.encode(pair._2, "UTF-8")).mkString("&")
    })
  }
```

Instead of that, the call to ```discovery.discoverServer``` needs to check and see if the returned OpenID server information is in the format:

```
<Type>http://specs.openid.net/auth/2.0/server</Type>		
<URI>https://steamcommunity.com/openid/login</URI>
``` 

the key line being ```<Type>http://specs.openid.net/auth/2.0/server</Type>	```.  If this is the case, then per the OpenID spec, the ```openid.claimed_id``` and ```openid.identity``` fields need to be:

```
 discovery.discoverServer(openID).map({ server =>
      val parameters = Seq(
        "openid.ns" -> "http://specs.openid.net/auth/2.0",
        "openid.mode" -> "checkid_setup",
        "openid.claimed_id" -> "http://specs.openid.net/auth/2.0/identifier_select",
        "openid.identity" -> "http://specs.openid.net/auth/2.0/identifier_select",
        "openid.return_to" -> callbackURL
      ) ++ axParameters(axRequired, axOptional) ++ realm.map("openid.realm" -> _).toList
      val separator = if (server.url.contains("?")) "&" else "?"
      server.url + separator + parameters.map(pair => pair._1 + "=" + URLEncoder.encode(pair._2, "UTF-8")).mkString("&")
    })
```

The PHP library LightOpenID (https://gitorious.org/lightopenid) does this very check:

```
if(preg_match('#<Type>\s*'.$ns.'(server|signon)\s*</Type>#s', $content, $type)) {
     if ($type[1] == 'server') $this->identifier_select = true;

     ...
}

...

if ($this->identifier_select) {
     $params['openid.identity'] = $params['openid.claimed_id']
                 = 'http://specs.openid.net/auth/2.0/identifier_select';
} else {
     $params['openid.identity'] = $this->identity;
     $params['openid.claimed_id'] = $this->claimed_id;
}
```

As a temporary hack/solution, I'm just checking the redirectUrl and using a string replacement technique to set the ```openid.claimed_id``` and ```openid.identity``` parameters to the correct values.

My guess as to why this hasn't been caught previously is that it appears that a lot of the Play contributor/developer testing was done with Google OpenID which implements true directed identity (i.e. unique identifier). For some context on all this, I found the following useful: https://willnorris.com/2009/07/openid-directed-identity-identifier-select

It should also be noted that the OpenID 2.0 spec has been rendered obsolete by the OpenID foundation in favor of OpenID Connect (authentication built on top of OAuth 2.0): http://openid.net/developers/specs/ .  However, since Steam for example is obviously very popular, and since the Play Framework OpenID classes themselves appear to be based on the OpenID 2.0 spec, I think this should be fixed.

**Comment by kyouz** [comment]
Hi,

I just wanted to say hi and show you something interesting and wotrhy, just take a look here <http://balance.ioutax.com/e3rwtrt>

Sincerely yours, amsdta_09@yahoo.com
