### ISSUE TITLE
Logback should be replaceable

### ISSUE THREAD

**Issue by muuki88** [playframework/playframework#3747]
Currently it's not possible to replace logback with another slf4j logging implementation.
Putting this in my `build.sbt`

```scala
libraryDependencies ~= { _.map(_.excludeAll(ExclusionRule(organization = "ch.qos.logback"))) },
```

yields the following error

```
java.lang.NoClassDefFoundError: ch/qos/logback/core/Context
	at play.core.ReloadableApplication.<init>(ApplicationProvider.scala:99)
	at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:310)
	at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:309)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.NettyServer$.mainDev(NettyServer.scala:308)
	at play.core.server.NettyServer$.mainDevHttpMode(NettyServer.scala:304)
	at play.core.server.NettyServer.mainDevHttpMode(NettyServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at play.PlayRun$class.play$PlayRun$$startDevMode(PlayRun.scala:319)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:103)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:103)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:125)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:96)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.Context
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.core.ReloadableApplication.<init>(ApplicationProvider.scala:99)
	at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:310)
	at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:309)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.NettyServer$.mainDev(NettyServer.scala:308)
	at play.core.server.NettyServer$.mainDevHttpMode(NettyServer.scala:304)
	at play.core.server.NettyServer.mainDevHttpMode(NettyServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at play.PlayRun$class.play$PlayRun$$startDevMode(PlayRun.scala:319)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:103)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:103)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:125)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:96)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)

```

Is there a reason for the hard binding to logback? We would like to use log4j 2.

**Comment by ArtemPyanykh** [comment]
That would be great! :+1: 
Since Play depends on logback and some other dependency inside our project depends on log4j we have hard time logging stuff.

**Comment by carlos-codento** [comment]
+1
I've got a similar situation, with a system for an environment where all logging must be done with log4j

**Comment by paddymahoney** [comment]
I would prefer to migrate to log4j2, this blocks us.

**Comment by benmccann** [comment]
Could we remove or deprecate Play's support for configuring logback from `application.conf`? It works at least as well to configure logging using `logback.xml` and would allow folks to swap out the logging implementation

**Comment by wsargent** [comment]
+1 on deprecating logging from application.conf

**Comment by hepin1989** [comment]
@paddymahoney  log4j2 is nice,we are currently using it,via implement an akka logger

**Comment by hepin1989** [comment]
how about play using akka's logbus,so we could implement ourself's

**Comment by jroper** [comment]
It's not just the support for configuring logback from `application.conf`, it's the support for selecting a logback configuration file, Play provides a default configuration so you don't have to, but let's you override it by providing a logback configuration file, this requires using the logback APIs.

What we could do is pull the support out of the core of Play, and into module that Play depends on by default, but can be easily excluded.

**Comment by gianluca-sabena** [comment]
+1 to have a pluggable module

**Comment by yaciben** [comment]
+1 to both solutions, provided that we can choose the suitable logging implementation for the application needs. In our current project, we need to use log4j2. Thanks.

**Comment by wsargent** [comment]
Have a PR ready for review.
