### ISSUE TITLE
Activator can't start simple app

### ISSUE THREAD

**Issue by pedrorijo91** [playframework/playframework#3820]
just typed 'activator new products play-scala' and then 'activator run' one the project dir and getting the above error. I've downloaded activator from the site some minutes ago.

    $ activator --version
    sbt launcher version 0.13.5

    $ sbt --version
    Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
sbt launcher version 0.13.6

Error:

    $ activator run
    [info] Loading global plugins from /Users/pedrorijo/.sbt/0.13/plugins
    [info] Loading project definition from /Users/pedrorijo/Desktop/git/products/project
    [info] Updating {file:/Users/pedrorijo/Desktop/git/products/project/}products-build...
    [info] Resolving org.fusesource.jansi#jansi;1.4 ...
    [info] Done updating.
    java.lang.NoClassDefFoundError: org/sbtidea/SbtIdeaPlugin$
      at play.PlayCommands$class.intellijCommandSettings(PlayCommands.scala:60)
      at play.Play$.intellijCommandSettings(Project.scala:17)
      at play.Play$.projectSettings(Project.scala:35)
      at sbt.Load$$anonfun$autoPluginSettings$1$1.apply(Load.scala:517)
      at sbt.Load$$anonfun$autoPluginSettings$1$1.apply(Load.scala:517)
      at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
      at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
      at scala.collection.immutable.List.foreach(List.scala:318)
      at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
      at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
      at sbt.Load$.autoPluginSettings$1(Load.scala:517)
      at sbt.Load$.sbt$Load$$expand$1(Load.scala:525)
      at sbt.Load$$anonfun$sbt$Load$$expand$1$2.apply(Load.scala:526)
      at sbt.Load$$anonfun$sbt$Load$$expand$1$2.apply(Load.scala:526)
      at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
      at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
      at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
      at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
      at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
      at sbt.Load$.sbt$Load$$expand$1(Load.scala:526)
      at sbt.Load$.loadSettings(Load.scala:528)
      at sbt.Load$.sbt$Load$$loadSbtFiles$1(Load.scala:464)
      at sbt.Load$$anonfun$loadForProjects$1$1.apply(Load.scala:470)
      at sbt.Load$$anonfun$loadForProjects$1$1.apply(Load.scala:465)
      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
      at scala.collection.immutable.List.foreach(List.scala:318)
      at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
      at scala.collection.AbstractTraversable.map(Traversable.scala:105)
      at sbt.Load$.loadForProjects$1(Load.scala:465)
      at sbt.Load$.loadTransitive(Load.scala:480)
      at sbt.Load$.loadProjects$1(Load.scala:418)
      at sbt.Load$.loadUnit(Load.scala:419)
      at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
      at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
      at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
      at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:92)
      at sbt.BuildLoader.apply(BuildLoader.scala:143)
      at sbt.Load$.loadAll(Load.scala:312)
      at sbt.Load$.loadURI(Load.scala:264)
      at sbt.Load$.load(Load.scala:260)
      at sbt.Load$.load(Load.scala:251)
      at sbt.Load$.apply(Load.scala:134)
      at sbt.Load$.defaultLoad(Load.scala:37)
      at sbt.BuiltinCommands$.doLoadProject(Main.scala:473)
      at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
      at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
      at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
      at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
      at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
      at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
      at sbt.Command$.process(Command.scala:95)
      at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
      at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
      at sbt.State$$anon$1.process(State.scala:179)
      at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
      at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
      at sbt.MainLoop$.next(MainLoop.scala:100)
      at sbt.MainLoop$.run(MainLoop.scala:93)
      at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
      at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
      at sbt.Using.apply(Using.scala:25)
      at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
      at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
      at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
      at sbt.MainLoop$.runLogged(MainLoop.scala:25)
      at sbt.StandardMain$.runManaged(Main.scala:57)
      at sbt.xMain.run(Main.scala:29)
      at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
      at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
      at xsbt.boot.Launch$.run(Launch.scala:109)
      at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
      at xsbt.boot.Launch$.launch(Launch.scala:117)
      at xsbt.boot.Launch$.apply(Launch.scala:19)
      at xsbt.boot.Boot$.runImpl(Boot.scala:44)
      at xsbt.boot.Boot$.main(Boot.scala:20)
      at xsbt.boot.Boot.main(Boot.scala)
    Caused by: java.lang.ClassNotFoundException: org.sbtidea.SbtIdeaPlugin$
      at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
      at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
      at play.PlayCommands$class.intellijCommandSettings(PlayCommands.scala:60)
      at play.Play$.intellijCommandSettings(Project.scala:17)
      at play.Play$.projectSettings(Project.scala:35)
      at sbt.Load$$anonfun$autoPluginSettings$1$1.apply(Load.scala:517)
      at sbt.Load$$anonfun$autoPluginSettings$1$1.apply(Load.scala:517)
      at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
      at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
      at scala.collection.immutable.List.foreach(List.scala:318)
      at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
      at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
      at sbt.Load$.autoPluginSettings$1(Load.scala:517)
      at sbt.Load$.sbt$Load$$expand$1(Load.scala:525)
      at sbt.Load$$anonfun$sbt$Load$$expand$1$2.apply(Load.scala:526)
      at sbt.Load$$anonfun$sbt$Load$$expand$1$2.apply(Load.scala:526)
      at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
      at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
      at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
      at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
      at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
      at sbt.Load$.sbt$Load$$expand$1(Load.scala:526)
      at sbt.Load$.loadSettings(Load.scala:528)
      at sbt.Load$.sbt$Load$$loadSbtFiles$1(Load.scala:464)
      at sbt.Load$$anonfun$loadForProjects$1$1.apply(Load.scala:470)
      at sbt.Load$$anonfun$loadForProjects$1$1.apply(Load.scala:465)
      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
      at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
      at scala.collection.immutable.List.foreach(List.scala:318)
      at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
      at scala.collection.AbstractTraversable.map(Traversable.scala:105)
      at sbt.Load$.loadForProjects$1(Load.scala:465)
      at sbt.Load$.loadTransitive(Load.scala:480)
      at sbt.Load$.loadProjects$1(Load.scala:418)
      at sbt.Load$.loadUnit(Load.scala:419)
      at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
      at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:256)
      at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
      at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:92)
      at sbt.BuildLoader.apply(BuildLoader.scala:143)
      at sbt.Load$.loadAll(Load.scala:312)
      at sbt.Load$.loadURI(Load.scala:264)
      at sbt.Load$.load(Load.scala:260)
      at sbt.Load$.load(Load.scala:251)
      at sbt.Load$.apply(Load.scala:134)
      at sbt.Load$.defaultLoad(Load.scala:37)
      at sbt.BuiltinCommands$.doLoadProject(Main.scala:473)
      at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
      at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
      at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
      at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
      at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
      at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
      at sbt.Command$.process(Command.scala:95)
      at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
      at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
      at sbt.State$$anon$1.process(State.scala:179)
      at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
      at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
      at sbt.MainLoop$.next(MainLoop.scala:100)
      at sbt.MainLoop$.run(MainLoop.scala:93)
      at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
      at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
      at sbt.Using.apply(Using.scala:25)
      at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
      at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
      at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
      at sbt.MainLoop$.runLogged(MainLoop.scala:25)
      at sbt.StandardMain$.runManaged(Main.scala:57)
      at sbt.xMain.run(Main.scala:29)
      at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
      at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
      at xsbt.boot.Launch$.run(Launch.scala:109)
      at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
      at xsbt.boot.Launch$.launch(Launch.scala:117)
      at xsbt.boot.Launch$.apply(Launch.scala:19)
      at xsbt.boot.Boot$.runImpl(Boot.scala:44)
      at xsbt.boot.Boot$.main(Boot.scala:20)
      at xsbt.boot.Boot.main(Boot.scala)
    [error] java.lang.NoClassDefFoundError: org/sbtidea/SbtIdeaPlugin$
    [error] Use 'last' for the full log.
    Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

What is wrong?

**Comment by cchantep** [comment]
Hi, please ask first on [Play Google Group](https://groups.google.com/forum/m/#!forum/play-framework) before filing an issue there.

**Comment by tomislavmitic2012** [comment]
This is an actual issue which effects migrating from play 2.3.x to 2.4.x, can you please look at it before being dismissive about it

US-C02M22BBFD58:sal-service tmitic$ activator
[info] Loading project definition from /Users/tmitic/workspace/development/sal/work/sal-service/project
java.lang.NoClassDefFoundError: play/PlayCommands
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
	at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
	at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.force(Stream.scala:249)
	at scala.collection.immutable.Stream.mkString(Stream.scala:702)
	at sbt.BuildUtil$.importNames(BuildUtil.scala:83)
	at sbt.BuildUtil$.importAll(BuildUtil.scala:88)
	at sbt.BuildUtil$.importAllRoot(BuildUtil.scala:89)
	at sbt.BuildUtil$.getImports(BuildUtil.scala:80)
	at sbt.DetectedPlugins.imports$lzycompute(BuildStructure.scala:125)
	at sbt.DetectedPlugins.imports(BuildStructure.scala:125)
	at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:712)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:717)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:716)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:58)
	at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:716)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Load$.loadFiles$1(Load.scala:723)
	at sbt.Load$.discoverProjects(Load.scala:734)
	at sbt.Load$.discover$1(Load.scala:545)
	at sbt.Load$.loadTransitive(Load.scala:574)
	at sbt.Load$.loadProjects$1(Load.scala:442)
	at sbt.Load$.loadUnit(Load.scala:446)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: play.PlayCommands
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
	at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
	at scala.collection.immutable.Stream$$anonfun$$plus$plus$1.apply(Stream.scala:330)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.force(Stream.scala:249)
	at scala.collection.immutable.Stream.mkString(Stream.scala:702)
	at sbt.BuildUtil$.importNames(BuildUtil.scala:83)
	at sbt.BuildUtil$.importAll(BuildUtil.scala:88)
	at sbt.BuildUtil$.importAllRoot(BuildUtil.scala:89)
	at sbt.BuildUtil$.getImports(BuildUtil.scala:80)
	at sbt.DetectedPlugins.imports$lzycompute(BuildStructure.scala:125)
	at sbt.DetectedPlugins.imports(BuildStructure.scala:125)
	at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:712)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:717)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:716)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:58)
	at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:716)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Load$.loadFiles$1(Load.scala:723)
	at sbt.Load$.discoverProjects(Load.scala:734)
	at sbt.Load$.discover$1(Load.scala:545)
	at sbt.Load$.loadTransitive(Load.scala:574)
	at sbt.Load$.loadProjects$1(Load.scala:442)
	at sbt.Load$.loadUnit(Load.scala:446)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoClassDefFoundError: play/PlayCommands
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?


Thanks
