### ISSUE TITLE
[2.4-M2] JSON NullPointerException on {}

### ISSUE THREAD

**Issue by helllamer** [playframework/playframework#3825]
Hi. I'm getting `NPE` on pretty simple JSON with functional parser.
My parser is pretty bad and makes no sense, but if such convertion is impossible, i thinking no NPE should occur in play.json deeps.
```
$ sbt console
import play.api.libs.json._
val wsMsg = Json.parse("""{"ctx2":{}}""")
implicit val contextReads = (JsPath \ "ctx2").read[JsObject]
contextReads.reads(wsMsg)

java.lang.NullPointerException
        at play.api.libs.json.PathReads$$anonfun$at$1$$anonfun$apply$2.apply(JsConstraints.scala:32)
        at play.api.libs.json.PathReads$$anonfun$at$1$$anonfun$apply$2.apply(JsConstraints.scala:32)
        at play.api.libs.json.JsResult$class.flatMap(JsResult.scala:111)
        at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:9)
        at play.api.libs.json.PathReads$$anonfun$at$1.apply(JsConstraints.scala:32)
        at play.api.libs.json.PathReads$$anonfun$at$1.apply(JsConstraints.scala:32)
        at play.api.libs.json.Reads$$anon$8.reads(Reads.scala:104)
        at play.api.libs.json.Reads$$anon$3$$anon$4.reads(Reads.scala:84)
        at play.api.libs.json.Reads$$anonfun$map$1.apply(Reads.scala:31)
        at play.api.libs.json.Reads$$anonfun$map$1.apply(Reads.scala:31)
        at play.api.libs.json.Reads$$anon$8.reads(Reads.scala:104)
        ... 43 elided
```

**Comment by helllamer** [comment]
Sorry, looks like this error is possibly due conflicting dependencies near jackson.
I'm closing issue, but write source of problem when find and fix it.

**Comment by helllamer** [comment]
Ok, the problem is quite stupid:
```
implicit val contextReads = (JsPath \ "ctx2").read[JsObject]
```
`contextReads` has type Reads[JsObject], and `.read[JsObject]` implicitly calls `implicit contextReads()`. So,endless loop here. `val` silently hides StackOverflowError in itself with `null` value.
