### ISSUE TITLE
[2.4.0-M2] JsValue Websocket parseException handling issue

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#3869]
I have a Websocket set up like this

```scala
WebSocket.tryAcceptWithActor[JsValue, JsValue] { request =>
  ...
}
```

When this receives an invalid json frame the connection closes and a stack trace is logged to System.out

I would expect the connection to stay open and the frame to be dropped, stack traces sent to the play logger
Even better would be a way to handle the the invalid frame.

```java
com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: {; line: 1, column: 0])
 at [Source: {; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:445)
	at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:450)
	at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:458)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:1856)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:571)
	at play.api.libs.json.JsValueDeserializer.deserialize(JsValue.scala:409)
	at play.api.libs.json.JsValueDeserializer.deserialize(JsValue.scala:361)
	at play.api.libs.json.JsValueDeserializer.deserialize(JsValue.scala:356)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3038)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1652)
	at play.api.libs.json.JacksonJson$.parseJsValue(JsValue.scala:488)
	at play.api.libs.json.Json$.parse(Json.scala:20)
	at play.api.mvc.WebSocket$FrameFormatter$$anonfun$2.apply(WebSocket.scala:80)
	at play.api.mvc.WebSocket$FrameFormatter$$anonfun$2.apply(WebSocket.scala:80)
	at play.core.websocket.BasicFrameFormatter$$anon$1.fromFrame(BasicFrameFormatter.scala:29)
	at play.core.server.netty.WebSocketHandler$class.fromNettyFrame$1(WebSocketHandler.scala:47)
	at play.core.server.netty.WebSocketHandler$$anon$1.messageReceived(WebSocketHandler.scala:103)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:64)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:138)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jroper** [comment]
One thing you could do is use String frames and parse them yourself.

**Comment by francisdb** [comment]
Yes, currently going there as a workaround.

**Comment by nafg** [comment]
+1

**Comment by francisdb** [comment]
This is what I currently use:

```scala
// in the actor companion object
case class IncomingWebSocketMessage(maybeJson: Try[JsValue])

// only one way
implicit val tryJsonFrame: FrameFormatter[IncomingWebSocketMessage] =
    FrameFormatter.stringFrame.transform(tj => ???, s => IncomingWebSocketMessage(Try(Json.parse(s))))

def index = WebSocket.tryAcceptWithActor[IncomingWebSocketMessage, JsValue] { implicit request =>
  ...
}


```
