### ISSUE TITLE
Defining helpers in html package object leads to NoSuchMethodError

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#3876]
When defining a helper method in app/views/package.scala

```
package views

package object html {
  case class PresentationElement(first: String, index: Int, second: String)

  def helperMethod(list: Seq[String], stringMap: Map[String, String]): Seq[PresentationElement] = {
    val listBuffer = scala.collection.mutable.ListBuffer[PresentationElement]()
    for ((el, index) <- list.view.zipWithIndex) {
      listBuffer += PresentationElement(el, index, stringMap(el))
    }
    listBuffer.toSeq
  }
}
```

And calling it in a page with:

```
  @defining(List("one", "two", "three")) { list =>
    @defining(Map("one" -> "uno", "two" -> "deux", "three" -> "tres")) { stringMap =>
      @for(el:PresentationElement <- helperMethod(list, stringMap)) {
        <p>element @{el.first}, index @{el.index}, second el @{el.second}</p>
      }
    }
  }
```

The code will compile fine... but then when running will show the following error message:

```
play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.NoSuchMethodError: views.html.package$.helperMethod(Lscala/collection/Seq;Lscala/collection/immutable/Map;)Lscala/collection/Seq;]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.7.jar:2.3.7]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: views.html.package$.helperMethod(Lscala/collection/Seq;Lscala/collection/immutable/Map;)Lscala/collection/Seq;
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:523) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[play_2.11-2.3.7.jar:2.3.7]
Caused by: java.lang.NoSuchMethodError: views.html.package$.helperMethod(Lscala/collection/Seq;Lscala/collection/immutable/Map;)Lscala/collection/Seq;
	at views.html.index$$anonfun$apply$1$$anonfun$apply$2.apply(index.template.scala:28) ~[classes/:na]
	at views.html.index$$anonfun$apply$1$$anonfun$apply$2.apply(index.template.scala:27) ~[classes/:na]
	at play.twirl.api.TemplateMagic$.defining(TemplateMagic.scala:13) ~[twirl-api_2.11-1.0.2.jar:1.0.2]
	at views.html.index$$anonfun$apply$1.apply(index.template.scala:27) ~[classes/:na]
	at views.html.index$$anonfun$apply$1.apply(index.template.scala:26) ~[classes/:na]
```

**Comment by jroper** [comment]
The reason for this - it's already defined here:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/views/package.scala#L16

It's not a compile error because it's perfectly legal according to the Scala compiler to implement a class that already exists on the classpath.  And at runtime, you're dependent on classpath ordering (parent first, ie, you get Play's version) as to which one you get.

The reason these exist is because the the template imports that Play defines includes:

    views.%format%._

These package objects therefore exist to ensure that import is valid.  But the `html` one is actually not needed since we already have stuff in the `html` package.  I'm not sure if there's any other good reason for us to provide it, perhaps we want to reserve it for future use?  We're going to want to add a few new implicit conversions I think in Play 3.0, it would be useful to have somewhere to put them.

**Comment by wsargent** [comment]
Well, that's the same problem I (as the user) have -- package objects are very useful places to put implicit conversions and methods.  You don't have to do any explicit @import statement from the template -- it's just there, local to the package.

If Play has any implicit conversions, then I'd want that to be added to TwirlKeys.templatesImports in its own Implicits._ class.  I don't see how importing views.html._ is useful for Play, especially since it doesn't do anything currently.

**Comment by wsargent** [comment]
play-bootstrap3, for example https://github.com/adrianhurt/play-bootstrap3/blob/master/module/app/views/b3/package.scala

**Comment by mslinn** [comment]
+1 for leaving the `views.html` package object free so app programmers can use it
