### ISSUE TITLE
Play framework SSL error in bouncycastle

### ISSUE THREAD

**Issue by RockyRx** [playframework/playframework#4010]
Hi all,

We get this strange error when we are fetching a SSL based URL for some data extraction in our Play application. We are doing this using Play's WS class. Here's the code snippet:-

```
Promise<WS.Response> promise = WS.url("https://examplewscall.com").setHeader("Content-Type", "application/json").get();
```

This happens at random time thus making it difficult to provide a solution. We only know that it happens after the WS call. 

Additionally we tried to override the Play's core bouncycastle library with a later version of it (based on our findings that this issue is fixed in bouncycastle version for jdk5). Here's how we did it

```
"com.typesafe.play" % "play_2.10" % "2.2.0" exclude("bouncycastle", "bcprov-jdk14"),
"org.bouncycastle" % "bcprov-jdk15" % "1.45"

resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
```
However when it hits the error we can see that Play is still using the older version on bouncycastle. We are using Play 2.2.0

```
Caused by: java.lang.RuntimeException: Could not generate DH keypair
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:80) ~[na:1.7.0_67]
        at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:632) ~[na:1.7.0_67]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:218) ~[na:1.7.0_67]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868) ~[na:1.7.0_67]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:808) ~[na:1.7.0_67]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:806) ~[na:1.7.0_67]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_67]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1227) ~[na:1.7.0_67]
        at org.jboss.netty.handler.ssl.SslHandler$4.run(SslHandler.java:1365) ~[io.netty.netty-3.7.0.Final.jar:na]
        at org.jboss.netty.handler.ssl.ImmediateExecutor.execute(ImmediateExecutor.java:31) ~[io.netty.netty-3.7.0.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1362) ~[io.netty.netty-3.7.0.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1249) ~[io.netty.netty-3.7.0.Final.jar:na]
        ... 13 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: parameter object not a ECParameterSpec
        at org.bouncycastle.jce.provider.JDKKeyPairGenerator$EC.initialize(Unknown Source) ~[bouncycastle.bcprov-jdk14-138.jar:1.38.0]
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:75) ~[na:1.7.0_67]
        ... 24 common frames omitted
```

**Comment by cchantep** [comment]
Hi @RockyRx , please first ask on the [MailingList](https://groups.google.com/forum/#!forum/play-framework).
