### ISSUE TITLE
Compilation error: java.lang.ArrayIndexOutOfBoundsException. - Java 8 issue.

### ISSUE THREAD

**Issue by maolc** [playframework/playframework#4040]
Compilation fails for Enity beans with Java 8 lambda expressions.

Attempting to compile the class below fails with an java.lang.ArrayIndexOutOfBoundsException.
----------------------------------------
```java
import javax.persistence.Entity;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

@Entity
public class Test {
    public static List<?> test() {
        List<String> fields = Collections.emptyList();

        return fields
                .stream()
                .map(String::intern)
                .collect(Collectors.toList());
    }
}
```

It seems to be the lambda expression ".map(String::intern)" that causes the issue. Uncommenting that lambda expression makes the class compile.

Stacktrace:
--------------
java.lang.ArrayIndexOutOfBoundsException: 9578
        at com.avaje.ebean.enhance.asm.ClassReader.readClass(ClassReader.java:1976)
        at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:464)
        at com.avaje.ebean.enhance.asm.ClassReader.accept(ClassReader.java:420)
        at com.avaje.ebean.enhance.agent.Transformer.detect(Transformer.java:252)
        at com.avaje.ebean.enhance.agent.Transformer.transform(Transformer.java:106)
        at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:55)
        at com.avaje.ebean.enhance.agent.InputStreamTransform.transform(InputStreamTransform.java:39)
        at com.avaje.ebean.enhance.ant.OfflineFileTransform.transformFile(OfflineFileTransform.java:141)
        at com.avaje.ebean.enhance.ant.OfflineFileTransform.processPackage(OfflineFileTransform.java:124)
        at com.avaje.ebean.enhance.ant.OfflineFileTransform.process(OfflineFileTransform.java:90)
        at play.PlayCommands$$anonfun$PostCompile$1.apply(PlayCommands.scala:142)
        at play.PlayCommands$$anonfun$PostCompile$1.apply(PlayCommands.scala:75)
        at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:35)
        at scala.Function8$$anonfun$tupled$1.apply(Function8.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I have ben able to produce this error on Play framework 2.3.7 with Java 8, 1.8.37 and Play framework 2.3.8 and Java 8, 1.8.40, under Linux (Ubuntu 14.10).

**Comment by cchantep** [comment]
It seems related on Ebean (not Play specific code in the class).

**Comment by maolc** [comment]
Ok, in that case I'm closing the issue.
Thanks.
