### ISSUE TITLE
AlgorithmConstraintsParser Bug

### ISSUE THREAD

**Issue by jamesward** [playframework/playframework#4043]
When using a standalone WS client on Heroku I get the following error:
```
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.ObjectRef.zero()Lscala/runtime/ObjectRef;
	at scala.util.parsing.combinator.Parsers$Parser.$tilde(Parsers.scala)
	at play.api.libs.ws.ssl.AlgorithmConstraintsParser$.expression(Algorithms.scala:259)
	at play.api.libs.ws.ssl.AlgorithmConstraintsParser$$anonfun$line$1.apply(Algorithms.scala:257)
	at play.api.libs.ws.ssl.AlgorithmConstraintsParser$$anonfun$line$1.apply(Algorithms.scala:257)
	at scala.util.parsing.combinator.Parsers$class.rep1sep(Parsers.scala:771)
	at play.api.libs.ws.ssl.AlgorithmConstraintsParser$.rep1sep(Algorithms.scala:246)
	at scala.util.parsing.combinator.Parsers$class.repsep(Parsers.scala:687)
	at play.api.libs.ws.ssl.AlgorithmConstraintsParser$.repsep(Algorithms.scala:246)
	at play.api.libs.ws.ssl.AlgorithmConstraintsParser$.line(Algorithms.scala:257)
	at play.api.libs.ws.ssl.AlgorithmConstraintsParser$.apply(Algorithms.scala:250)
	at play.api.libs.ws.ssl.ConfigSSLContextBuilder.build(SSLContextBuilder.scala:108)
	at play.api.libs.ws.ning.NingAsyncHttpClientConfigBuilder.configureSSL(NingAsyncHttpClientConfigBuilder.scala:119)
	at play.api.libs.ws.ning.NingAsyncHttpClientConfigBuilder.build(NingAsyncHttpClientConfigBuilder.scala:35)
	at utils.StandaloneWS.ningWsClient$lzycompute(StandaloneWS.scala:12)
	at utils.StandaloneWS.ningWsClient(StandaloneWS.scala:12)
	at utils.StandaloneWS.client(StandaloneWS.scala:13)
	at utils.StandaloneWS.url(StandaloneWS.scala:14)
	at utils.Bower.info(Bower.scala:22)
	at utils.BowerWebJar$$anonfun$release$1.apply(BowerWebJar.scala:45)
	at utils.BowerWebJar$$anonfun$release$1.apply(BowerWebJar.scala:40)
	at utils.StandaloneWS$.withWs(StandaloneWS.scala:24)
	at utils.BowerWebJar$.release(BowerWebJar.scala:40)
	at utils.BowerWebJar$.delayedEndpoint$utils$BowerWebJar$1(BowerWebJar.scala:83)
	at utils.BowerWebJar$delayedInit$body.apply(BowerWebJar.scala:11)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at utils.BowerWebJar$.main(BowerWebJar.scala:11)
	at utils.BowerWebJar.main(BowerWebJar.scala)
```

Not sure what to do when I encounter errors deep in the bowels of SSL stuff.

**Comment by jamesward** [comment]
Env:

> Play 2.3.8
> OpenJDK Runtime Environment (build 1.8.0_40-cedar14-b25)
> Linux ee97c438-de32-48a3-aa15-68ba1ca38ed7 3.13.0-40-generic #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jroper** [comment]
According to your stack trace, the [scala parser combinators library](https://github.com/scala/scala-parser-combinators):

    scala.util.parsing.combinator.Parsers$Parser.$tilde(Parsers.scala)

Is trying to invoke a method on the [scala standard library](https://github.com/scala/scala):

    scala.runtime.ObjectRef.zero()Lscala/runtime/ObjectRef;

And that method doesn't exist.  Either you have mismatched your Scala versions, or there is a binary compatibility breakage in Scala, which should be reported there.

**Comment by jroper** [comment]
What version of Scala are you using, and what version of `scala-parser-combinators` is on your classpath?

**Comment by jamesward** [comment]
Thanks James for helping me unravel this.  The error (and other weird ones) have been happening randomly.  You question led me to discover:
```
~ $ ls target/universal/stage/lib/ |grep scala
org.scala-lang.modules.scala-parser-combinators_2.11-1.0.1.jar
org.scala-lang.modules.scala-xml_2.11-1.0.1.jar
org.scala-lang.scala-library-2.10.4.jar
org.scala-lang.scala-library-2.11.6.jar
org.scala-lang.scala-reflect-2.10.4.jar
org.scala-lang.scala-reflect-2.11.1.jar
org.scala-stm.scala-stm_2.10-0.7.jar
org.scala-stm.scala-stm_2.11-0.7.jar
```

Difference versions of Scala...  Fun.  I'm sure that once I get the `2.10` stuff removed, my random errors will go away.

Thank you!  Sorry for the noise.
