### ISSUE TITLE
bonecp fail to show error when not default value in a column

### ISSUE THREAD

**Issue by martinvasapollo** [playframework/playframework#4112]
When try insert into a table that not have a default value in the primary key ( and not defined in the query) , play fail to show the correct error: 

[error] c.j.b.ConnectionHandle - Database access problem. Killing off this connection and all remaining connections in the connection pool. SQL State = HY000
[error] application - 

! @6lh5c87f0 - Internal server error, for (GET) [/new-deploy] ->

play.api.Application$$anon$1: Execution exception[[SQLException: Connection is closed!]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.8.jar:2.3.8]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.1.jar:na]
Caused by: java.sql.SQLException: Connection is closed!
	at com.jolbox.bonecp.ConnectionHandle.checkClosed(ConnectionHandle.java:459) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1270) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.AutoCleanConnection.rollback(DB.scala:518) ~[play-jdbc_2.11-2.3.8.jar:2.3.8]
	at play.api.db.DBApi$$anonfun$withTransaction$1.apply(DB.scala:105) ~[play-jdbc_2.11-2.3.8.jar:2.3.8]
	at play.api.db.DBApi$$anonfun$withTransaction$1.apply(DB.scala:96) ~[play-jdbc_2.11-2.3.8.jar:2.3.8]
[error] application -

**Comment by martinvasapollo** [comment]
Just define the primary as auto incremental solve the problem
