### ISSUE TITLE
remove query parameter from error log

### ISSUE THREAD

**Issue by khannedy** [playframework/playframework#4158]
In some code, I see play framework display the error with request.uri information

```scala
Logger.error(
        """
        |
        |! %sInternal server error, for (%s) [%s] ->
        |""".stripMargin.format(e match {
          case p: PlayException => "@" + p.id + " - "
          case _ => ""
        }, request.method, request.uri),
        e)
```

It's good because user can see the uri detail. 

but in my company (financial), we can not log the query parameter because there are so many sensitive data there.

for example : 

```
! @6ljn8i18a - Internal server error, for (GET) [/token?card_number=4111111111111111&card_exp_month=12&card_exp_year=2020&card_cvv=123&public_key=e21279f6-d539-11e4-9dae-6476baad9bec] ->

play.api.Application$$anon$1: Execution exception[[JedisConnectionException: Unexpected end of stream.]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
    at 
```

so I recommended to not display query param in error log

**Comment by benmccann** [comment]
I would guess most people would want the query parameters logged. But you can change the log level for that logger so that this log statement gets skipped for you

**Comment by jroper** [comment]
In Play 2.4 the place where this error gets logged has been moved to `DefaultHttpErrorHandler`, and can be overridden by supplying a custom `onServerError` method that doesn't log the query parameters.
