### ISSUE TITLE
NingAsyncHttpClientConfigBuilder fails on 2.4.0-M3

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#4227]
When using `2.4.0-M3` on a `2.3.8` Play library to establish a `wsClient` I receive a `NoSuchMethodError`. Here's the `2.3.8` code I use to establish the `wsClient` (which is based off the `2.3.8` documentation:

```scala
    implicit val wsClient = {
      val ningClientConfig = 
        new NingAsyncHttpClientConfigBuilder(new DefaultWSClientConfig()).build() // <-- error line
      val clientConfig = new AsyncHttpClientConfig.Builder(ningClientConfig)
        .setCompressionEnabled(true)
        .build()
      new NingWSClient(clientConfig)
    }
```

Using `2.4.0-M1` is fine.

Full stack trace:

```
play.api.UnexpectedException: Unexpected exception[NoSuchMethodError: play.api.libs.ws.ning.NingAsyncHttpClientConfigBuilder$.$lessinit$greater$default$2()Lcom/ning/http/client/AsyncHttpClientConfig$Builder;]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:198) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:148) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:148) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:146) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.6.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:146) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:138) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.6.jar:na]
Caused by: java.lang.NoSuchMethodError: play.api.libs.ws.ning.NingAsyncHttpClientConfigBuilder$.$lessinit$greater$default$2()Lcom/ning/http/client/AsyncHttpClientConfig$Builder;
	at com.typesafe.conductr.bundlelib.play.ConnectionContext$Implicits$.<init>(ConnectionHandler.scala:31) ~[play-conductr-bundle-lib_2.11-0.7.0.jar:0.7.0]
	at com.typesafe.conductr.bundlelib.play.ConnectionContext$Implicits$.<clinit>(ConnectionHandler.scala) ~[play-conductr-bundle-lib_2.11-0.7.0.jar:0.7.0]
	at plugins.ConductrPlugin.onStart(ConductrPlugin.scala:12) ~[na:na]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at scala.collection.Iterator$class.foreach(Iterator.scala:750) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202) ~[scala-library-2.11.6.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.6.jar:na]
	at play.api.Plugins.foreach(Plugins.scala:57) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.4.0-M3.jar:2.4.0-M3]
```

**Comment by huntc** [comment]
Closing, as binary compat isn't supported across different versions of Play.
