### ISSUE TITLE
2.4.0-RC1: Anorm has problems with comments

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#4319]
Following code does not work anymore in play 2.4.0-RC1

```scala
       val checkSql =
          """
            | SELECT
            |        -- secret_member.secret_id, secret_member.uuid, secret_member.custom_name,
            |        -- secret.serial,
            |        -- secret_group.id, secret_group.serial,
            |        -- secret_group_function.id, secret_group_function.name,
            |        -- secret_group_function_property.id, secret_group_function_property.name,
            |
            | secret_group_function_property.name,
            | secret_group_function_property_data.id,
            | secret_group_function_property_data.type
            |
            | FROM secret_member
            | JOIN secret ON (secret_member.member_id = {memberId} AND secret_member.uuid = {uuid} AND secret.id = secret_member.secret_id)
            | JOIN secret_to_group ON (secret_to_group.secret_id = secret.id AND secret_to_group.group_id = {groupId})
            | JOIN secret_group ON (secret_group.id = secret_to_group.group_id)
            | JOIN secret_group_function ON (secret_group_function.group_id = secret_group.id AND secret_group_function.id = {functionId})
            | JOIN secret_group_function_property ON (secret_group_function_property.function_id = secret_group_function.id)
            | JOIN secret_group_function_property_data ON (secret_group_function_property_data.property_id = secret_group_function_property.id)
            | ORDER BY secret_member.custom_name, secret_member.secret_id, secret.serial, secret_group.serial, secret_group_function.id, secret_group_function_property.id
          """.stripMargin

        println(checkSql
          .replace("{groupId}", secretGroupId)
          .replace("{memberId}", request.member.uid.toString)
          .replace("{uuid}", "'"+secretMemberUuid+"'")
          .replace("{functionId}", secretFunctionId)
        )

            val properties : Seq[(String,Int,String)] = SQL(checkSql).
              on(
                "memberId" -> request.member.uid,
                "uuid" -> secretMemberUuid,
                "groupId" -> secretGroupId.toInt,
                "functionId" -> secretFunctionId.toInt
              ).
              as(
//                (str("secret_group_function_property.name") ~ int("secret_group_function_property_data.id") ~ str("secret_group_function_property_data.type"))
                (str("name") ~ int("id") ~ str("type"))
                  .map {
              case n ~ i ~ t => (n, i, t)
            }.*)
```

It throws the exception given below.

However, when I remove the comments from the query, like this:
```scala
      val checkSql =
          """
            | SELECT
            | secret_group_function_property.name,
            | secret_group_function_property_data.id,
            | secret_group_function_property_data.type
            |
            | FROM secret_member
            | JOIN secret ON (secret_member.member_id = {memberId} AND secret_member.uuid = {uuid} AND secret.id = secret_member.secret_id)
            | JOIN secret_to_group ON (secret_to_group.secret_id = secret.id AND secret_to_group.group_id = {groupId})
            | JOIN secret_group ON (secret_group.id = secret_to_group.group_id)
            | JOIN secret_group_function ON (secret_group_function.group_id = secret_group.id AND secret_group_function.id = {functionId})
            | JOIN secret_group_function_property ON (secret_group_function_property.function_id = secret_group_function.id)
            | JOIN secret_group_function_property_data ON (secret_group_function_property_data.property_id = secret_group_function_property.id)
            | ORDER BY secret_member.custom_name, secret_member.secret_id, secret.serial, secret_group.serial, secret_group_function.id, secret_group_function_property.id
          """.stripMargin

```
it works as in 2.3.x

The exception is this:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PSQLException: The column index is out of range: 1, number of columns: 0.]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:180) [play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at Global$.onError(Global.scala:11) [classes/:na]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:159) [play-netty-server_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:156) [play-netty-server_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.5.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library-2.11.5.jar:na]
	at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.5.jar:na]
	at scala.util.Failure.recover(Try.scala:215) [scala-library-2.11.5.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.5.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.5.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.5.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [play-iteratees_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.5.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.5.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.5.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.5.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [akka-actor_2.11-2.3.7.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401) [akka-actor_2.11-2.3.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.5.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.5.jar:na]
Caused by: org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:56) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.core.v3.SimpleParameterList.setBinaryParameter(SimpleParameterList.java:122) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.bindBytes(AbstractJdbc2Statement.java:2312) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setInt(AbstractJdbc2Statement.java:1288) ~[postgresql-9.4-1201-jdbc41.jar:9.4]
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.setInt(PreparedStatementJavassistProxy.java) ~[HikariCP-2.3.5.jar:na]
	at anorm.ToStatement$intToStatement$.set(ToStatement.scala:172) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.ToStatement$intToStatement$.set(ToStatement.scala:171) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.ParameterValue$$anon$1.set(ParameterValue.scala:64) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.SimpleSql$$anonfun$getFilledStatement$2.apply(SimpleSql.scala:67) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.SimpleSql$$anonfun$getFilledStatement$2.apply(SimpleSql.scala:65) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.5.jar:na]
	at anorm.SimpleSql.getFilledStatement(SimpleSql.scala:65) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.SimpleSql$$anonfun$preparedStatement$1.apply(SimpleSql.scala:73) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.SimpleSql$$anonfun$preparedStatement$1.apply(SimpleSql.scala:73) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at resource.DefaultManagedResource.open(AbstractManagedResource.scala:106) ~[scala-arm_2.11-1.4.jar:1.4]
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:85) ~[scala-arm_2.11-1.4.jar:1.4]
	at resource.ManagedResourceOperations$$anon$2.acquireFor(ManagedResourceOperations.scala:40) ~[scala-arm_2.11-1.4.jar:1.4]
	at resource.DeferredExtractableManagedResource.acquireFor(AbstractManagedResource.scala:27) ~[scala-arm_2.11-1.4.jar:1.4]
	at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25) ~[scala-arm_2.11-1.4.jar:1.4]
	at resource.DeferredExtractableManagedResource.acquireAndGet(AbstractManagedResource.scala:24) ~[scala-arm_2.11-1.4.jar:1.4]
	at anorm.Sql$$anonfun$asTry$1.apply(Anorm.scala:302) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.Sql$$anonfun$asTry$1.apply(Anorm.scala:302) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.5.jar:na]
	at anorm.Sql$.asTry(Anorm.scala:301) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.WithResult$class.as(SqlResult.scala:120) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at anorm.SimpleSql.as(SimpleSql.scala:6) ~[anorm_2.11-2.4.0-M3.jar:2.4.0-M3]
	at controllers.SensorView$$anonfun$showSensorData$1$$anonfun$apply$1.apply(SensorView.scala:85) ~[classes/:2.4.0-RC1]
	at controllers.SensorView$$anonfun$showSensorData$1$$anonfun$apply$1.apply(SensorView.scala:45) ~[classes/:2.4.0-RC1]
	at play.api.db.DefaultDatabase.withConnection(Database.scala:232) ~[play-jdbc_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.db.DefaultDatabase.withConnection(Database.scala:226) ~[play-jdbc_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.db.DB$.withConnection(DB.scala:61) ~[play-jdbc_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at controllers.SensorView$$anonfun$showSensorData$1.apply(SensorView.scala:44) ~[classes/:2.4.0-RC1]
	at controllers.SensorView$$anonfun$showSensorData$1.apply(SensorView.scala:24) ~[classes/:2.4.0-RC1]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at controllers.UserAction$class.invokeBlock(UserRequest.scala:17) ~[classes/:2.4.0-RC1]
	at controllers.UserAction$.invokeBlock(UserRequest.scala:30) ~[classes/:2.4.0-RC1]
	at controllers.UserAction$.invokeBlock(UserRequest.scala:30) ~[classes/:2.4.0-RC1]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.5.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[play_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[play-iteratees_2.11-2.4.0-RC1.jar:2.4.0-RC1]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.5.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.5.jar:na]
	... 7 common frames omitted
```

**Comment by cchantep** [comment]
Hi @domdorn , thanks for reporting this regression. The fix [#28](https://github.com/playframework/anorm/pull/28) will be applied on master.

> Please note that you can ask question about Anorm on [StackOverflow](http://stackoverflow.com/questions/tagged/anorm).
> If you need to file a confirmed issue about Anorm, please do it on its own [issue tracker](https://github.com/playframework/anorm/issues).
