### ISSUE TITLE
[2.4.0] java.lang.IllegalArgumentException at scala.Predef$.require(Predef.scala:207)

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#4372]
I'm using the latest nightly (2.4.0-2015-05-04-b54affc-SNAPSHOT) and am getting exceptions when I run my server or integration tests:

    java.lang.IllegalArgumentException: requirement failed
    	at scala.Predef$.require(Predef.scala:207)
    	at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:105)
    	at scala.concurrent.package$.blocking(package.scala:123)
    	at play.api.libs.iteratee.Enumerator$$anonfun$fromStream$2.apply(Enumerator.scala:562)
    	at play.api.libs.iteratee.Enumerator$$anonfun$fromStream$2.apply(Enumerator.scala:560)
    	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
    	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
    	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
    	at scala.concurrent.Promise$class.complete(Promise.scala:55)
    	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
    	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
    	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
    	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:90)
    	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:88)
    	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:88)
    	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:88)
    	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
    	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
    	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by wsargent** [comment]
Looks like your parent block context is null.  Could be https://github.com/akka/akka/issues/16327

**Comment by marcospereira** [comment]
@benmccann Akka was upgraded here: playframework/playframework#4358. Could you revert to Akka 2.3.7 and see if it works?

**Comment by benmccann** [comment]
Hmm, yeah. And I see Play 2.3.8 has:

    "com.typesafe.akka" %% "akka-actor" % "2.3.4",
    "com.typesafe.akka" %% "akka-slf4j" % "2.3.4",

**Comment by marcospereira** [comment]
Closing after #4381 merge.

**Comment by rkuhn** [comment]
Which Scala version was used in these tests? AFAICS `BlockContext.current` cannot have returned `null` (in the sources I see for Scala 2.11.4), and with the stack trace this adds up to that the requirement should have been true and not false. /cc @jroper

**Comment by rkuhn** [comment]
Also checked that the BlockContext.current implementation did not change in a long while (so 2.10.4 and 2.11.5 are fine as well). @viktorklang?

**Comment by rkuhn** [comment]
Forget it: I found the bug in Akka.

**Comment by rkuhn** [comment]
see akka/akka#17390

**Comment by dotta** [comment]
@benmccann Could you try upgrading to akka 2.3.11 and check if the problem you have experienced with 2.3.10 is fixed. If 2.3.1 fixes it, I believe it's in our best interest to upgrade before 2.4 final is out.

**Comment by rkuhn** [comment]
The 2.3.11 release has not yet been published, it is staged [here](https://oss.sonatype.org/content/repositories/comtypesafe-1298/).

**Comment by benmccann** [comment]
@dotta why do you say we should upgrade to 2.3.11? I'm not sure I love the idea of upgrading libraries after we've entered the RC phase unless there's a compelling reason to

**Comment by viktorklang** [comment]
@benmccann The upgrade is required to get the bugfix.

**Comment by benmccann** [comment]
We downgraded to Akka 2.3.9 before Play 2.4.0-RC2 was released, so it doesn't have the bug, right? I believe the bug is only in 2.3.10

**Comment by viktorklang** [comment]
@benmccann 2.3.10 and 2.3.11 has other important bugfixes as well

**Comment by richdougherty** [comment]
I think the 2.3.11 release was mainly so Play could have the latest release minus the bug in 2.3.10, so it would be good if we could use it. Currently the Akka release is staged waiting on us to confirm that it works in Play.

**Comment by dotta** [comment]
@benmccann It's important we upgrade because I'd prefer that we don't inflict the same pain you have experienced to other Play users :-) Basically, by upgrading to akka 2.3.11, users will really need to go the extra mile too be able to use 2.3.10 in their project (because 2.3.11 > 2.3.10). The same won't be true if we keep using 2.3.9.

**Comment by rkuhn** [comment]
We are discussing two separate issues here, with vastly different urgency: independent of which version Play will depend on, would you (@benmccann) please verify that the to-be-released Akka version does indeed fix the issue? You found a flaw and reported it, for which I am deeply grateful, and I fixed the flaw for the benefit of everyone else; now from one hakker to the other, please let me know whether the fix works or not.

**Comment by benmccann** [comment]
@rkuhn I'm not sure how to test it since it's not released yet. Do I have to add another repository to my build?

**Comment by rkuhn** [comment]
Thanks for helping out! To simplify this process we have actually shipped the artifacts now—let’s hope that we don’t have to release 2.3.12 this week as well ;-)

**Comment by benmccann** [comment]
Ok, I tested 2.3.11 and I'm not seeing the problem that I was with 2.3.10

**Comment by rkuhn** [comment]
Thanks a lot for the confirmation!

**Comment by benmccann** [comment]
Sent  a PR to upgrade Play here: https://github.com/playframework/playframework/pull/4441
