### ISSUE TITLE
 net.contentobjects.jnotify.linux.JNotifyException_linux: Error removing watch 2 V2.3.8

### ISSUE THREAD

**Issue by ranaraj** [playframework/playframework#4392]
Hi,
I am using 2.3.8 version in linux system and getting same error, tried to do crtl+D multiple time and restared system but still same issue, localhost:9000 is not working, please suggest

$ run

--- (Running the application, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

net.contentobjects.jnotify.linux.JNotifyException_linux: Error removing watch 2
at net.contentobjects.jnotify.linux.JNotify_linux.removeWatch(Unknown Source)
at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.unwatch(Unknown Source)
at net.contentobjects.jnotify.linux.JNotifyAdapterLinux.removeWatch(Unknown Source)
at net.contentobjects.jnotify.JNotify.removeWatch(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:622)
at play.runsupport.JNotifyPlayWatchService$JNotifyDelegate.removeWatch(PlayWatchService.scala:148)
at play.runsupport.JNotifyPlayWatchService$$anon$4$$anonfun$stop$1.apply$mcVI$sp(PlayWatchService.scala:126)
at play.runsupport.JNotifyPlayWatchService$$anon$4$$anonfun$stop$1.apply(PlayWatchService.scala:126)
at play.runsupport.JNotifyPlayWatchService$$anon$4$$anonfun$stop$1.apply(PlayWatchService.scala:126)
at scala.collection.immutable.List.foreach(List.scala:318)
at play.runsupport.JNotifyPlayWatchService$$anon$4.stop(PlayWatchService.scala:126)
at play.runsupport.Reloader.close(Reloader.scala:354)
at play.runsupport.Reloader$$anon$4.close(Reloader.scala:213)
at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:123)
at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:54)
at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
at sbt.std.Transform$$anon$4.work(System.scala:64)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
at sbt.Execute.work(Execute.scala:244)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:701)

[success] Total time: 10 s, completed May 5, 2015 11:22:41 PM

**Comment by jroper** [comment]
Hi @ranaraj, the issue tracker isn't a place for debugging or getting help, it's a place to discuss bugs. I see you've already seen other similar bug reports with explanations such as filename length limits being the problem. Please ask for help on the [Play mailing list](https://groups.google.com/forum/#!forum/play-framework).
