### ISSUE TITLE
[2.4.0] mocha errors at end of test runs

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#4416]
Since 2.4.0 (RC1/RC2) I get the following error in the console when doing a 
sbt test

java.lang.NoSuchMethodError: spray.json.StandardFormats$class.optionFormat(Lspray/json/StandardFormats;Lspray/json/JsonFormat;)Lspray/json/StandardFormats$OptionFormat;
	at com.typesafe.sbt.mocha.MochaTestReporting$MochaJsonProtocol$.optionFormat(MochaTestReporting.scala:278)
	at com.typesafe.sbt.mocha.MochaTestReporting$MochaJsonProtocol$.<init>(MochaTestReporting.scala:279)
	at com.typesafe.sbt.mocha.MochaTestReporting.MochaJsonProtocol$lzycompute(MochaTestReporting.scala:278)
	at com.typesafe.sbt.mocha.MochaTestReporting.MochaJsonProtocol(MochaTestReporting.scala:278)
	at com.typesafe.sbt.mocha.MochaTestReporting.logTestResults(MochaTestReporting.scala:53)
	at com.typesafe.sbt.mocha.SbtMocha$$anonfun$4$$anonfun$apply$6$$anonfun$apply$7.apply(SbtMocha.scala:168)
	at com.typesafe.sbt.mocha.SbtMocha$$anonfun$4$$anonfun$apply$6$$anonfun$apply$7.apply(SbtMocha.scala:167)
	at scala.Option.map(Option.scala:145)
	at com.typesafe.sbt.mocha.SbtMocha$$anonfun$4$$anonfun$apply$6.apply(SbtMocha.scala:167)
	at com.typesafe.sbt.mocha.SbtMocha$$anonfun$4$$anonfun$apply$6.apply(SbtMocha.scala:135)
	at com.typesafe.sbt.mocha.SbtMocha$$anonfun$projectSettings$8.apply(SbtMocha.scala:80)
	at com.typesafe.sbt.mocha.SbtMocha$$anonfun$projectSettings$8.apply(SbtMocha.scala:80)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (root/*:mochaExecuteTests) java.lang.NoSuchMethodError: spray.json.StandardFormats$class.optionFormat(Lspray/json/StandardFormats;Lspray/json/JsonFormat;)Lspray/json/StandardFormats$OptionFormat;
[error] Total time: 39 s, completed May 8, 2015 4:13:30 PM

I tried to upgrade to 
addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.0.2")
but it did not change anything.

**Comment by marcospereira** [comment]
You have to upgrade to sbt-mocha 1.1.0. I will let this issue open so that we can submit a pr to document that in our migration guide.

**Comment by marcospereira** [comment]
Hi, @domdorn, did you had time to test with sbt-mocha 1.1.0?

**Comment by domdorn** [comment]
yes, this error is gone after upgrading. 
The error I'm still facing is yet unresolved ( https://groups.google.com/forum/#!topic/play-framework-dev/iGVW2vdSmfE )... I first thought it was a problem with the content-type being wrong, but actually something with the parsers or the way the FakeRequest gets assembled seems broken. Haven't had enough time to debug into it yet. If you'd like you can close this issue, as the mocha error is resolved.

**Comment by marcospereira** [comment]
Ok. I will close this issue and we can discuss the other problem at the mail list.
