### ISSUE TITLE
2.4.0-RC2 BoneCP exception: No configuration setting found for key 'defaultCatalog'

### ISSUE THREAD

**Issue by shkhln** [playframework/playframework#4448]
Changing jdbc connection pool back to BoneCP with `play.db.pool = bonecp` setting as suggested by the migration guide doesn't work properly right now.

```
play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.configError(Configuration.scala:178) ~[play_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.Configuration.reportError(Configuration.scala:829) ~[play_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DBApi.scala:74) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DBApi.scala:68) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.6.jar:na]
	at play.api.db.DefaultDBApi.connect(DBApi.scala:68) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.db.DBApiProvider.get$lzycompute(DBModule.scala:72) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.db.DBApiProvider.get(DBModule.scala:62) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.db.DBApiProvider.get(DBModule.scala:58) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81) ~[guice-4.0.jar:na]
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'defaultCatalog'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152) ~[config-1.3.0-M3.jar:na]
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170) ~[config-1.3.0-M3.jar:na]
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:193) ~[config-1.3.0-M3.jar:na]
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:198) ~[config-1.3.0-M3.jar:na]
	at com.typesafe.config.impl.SimpleConfig.getIsNull(SimpleConfig.java:208) ~[config-1.3.0-M3.jar:na]
	at play.api.PlayConfig.getOptional(Configuration.scala:951) ~[play_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.PlayConfig.getOptionalDeprecated(Configuration.scala:996) ~[play_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.db.BoneConnectionPool.create(BoneCPModule.scala:67) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.db.PooledDatabase.createDataSource(Database.scala:276) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
	at play.api.db.DefaultDatabase.dataSource$lzycompute(Database.scala:201) ~[play-jdbc_2.11-2.4.0-RC2.jar:2.4.0-RC2]
```

**Comment by marcospereira** [comment]
@shkhln could you please share your configuration here?

**Comment by shkhln** [comment]
That should be reproducible with the play-scala activator template: make it use 2.4.0-RC2 instead of 2.3.9, uncomment h2 db section and add `play.db.pool = bonecp`.

**Comment by marcospereira** [comment]
Ok. I was able to reproduce it and will take a look as soon as possible. Thanks, @shkhln.

**Comment by marcospereira** [comment]
To anyone interest, the code below could be a good path to investigating what is happening:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/Configuration.scala#L982-L998

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/Configuration.scala#L942-L952

https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc/src/main/resources/reference.conf#L126-L127

**Comment by jroper** [comment]
BoneCPModule is looking up `defaultCatalog` instead of `bonecp.defaultCatalog`, easy fix, but a bigger concern is why this isn't tested (that would be my fault).

**Comment by marcospereira** [comment]
@jroper I don't think that this is the case:

https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc/src/main/scala/play/api/db/BoneCPModule.scala#L67

It is looking for the deprecated `defaultCatalog` and then `bonecp.defaultCatalog`.

**Comment by marcospereira** [comment]
@jroper you are right. The order of the parameters are inverted.
