### ISSUE TITLE
Automatic app recompilation fails in dev mode after any changes on Windows

### ISSUE THREAD

**Issue by MipH** [playframework/playframework#4525]
Got compilation error only on Windows machine. In Linux environment my apps works fine.
Dev mode.
I have a very common CRUD app (MVC + Ebean) running on Windows 7. Play 2.3.0 (same error I have on 2.3.9 and sbt 2.11.6). Java project.

There are such deps in build.sbt:
```
libraryDependencies ++= Seq(
  javaJdbc,
  javaEbean,
  javaCore,
  "org.apache.poi" % "poi" % "3.11",
  "org.apache.poi" % "poi-ooxml" % "3.11",
  "com.innoq.liqid" % "ldap-connector" % "1.4",
  "org.mindrot" % "jbcrypt" % "0.3m",
  "commons-io" % "commons-io" % "2.4"
)
```

App works fine until I change some code and do refresh in a browser. Recompilation starts and I receive errors:
```
[info] Compiling 1 Java source to D:\1\angular-seed-play\target\scala-2.10\classes...
[info] Packaging D:\1\angular-seed-play\target\scala-2.10\app_2.10-2.0.7.jar ...
[info] Done packaging.

...

2015-05-21 15:29:55,062 - [ERROR] - from application in New I/O worker #7 


! @6m866coah - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[NullPointerException: null]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:151) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:115) ~[play_2.10-2.3.0.jar:2.3.0]
	at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:115) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:113) ~[play_2.10-2.3.0.jar:2.3.0]
	at scala.util.Success.flatMap(Try.scala:200) ~[scala-library.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:113) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:105) ~[play_2.10-2.3.0.jar:2.3.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library.jar:na]
Caused by: java.lang.NullPointerException: null
	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:567) ~[na:1.8.0_20]
	at java.util.zip.ZipFile.access$900(ZipFile.java:61) ~[na:1.8.0_20]
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:525) ~[na:1.8.0_20]
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:500) ~[na:1.8.0_20]
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:481) ~[na:1.8.0_20]
	at java.util.jar.JarFile$JarEntryIterator.next(JarFile.java:257) ~[na:1.8.0_20]
	at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:266) ~[na:1.8.0_20]
	at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:247) ~[na:1.8.0_20]
	at org.reflections.vfs.ZipDir$1$1.computeNext(ZipDir.java:35) ~[reflections-0.9.8.jar:na]
	at org.reflections.vfs.ZipDir$1$1.computeNext(ZipDir.java:33) ~[reflections-0.9.8.jar:na]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-16.0.1.jar:na]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-16.0.1.jar:na]
	at org.reflections.Reflections.scan(Reflections.java:165) ~[reflections-0.9.8.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:94) ~[reflections-0.9.8.jar:na]
	at play.libs.Classpath.getReflections(Classpath.java:51) ~[play-java_2.10-2.3.0.jar:2.3.0]
	at play.libs.Classpath.getTypes(Classpath.java:28) ~[play-java_2.10-2.3.0.jar:2.3.0]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:72) ~[play-java-ebean_2.10-2.3.0.jar:2.3.0]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.10-2.3.0.jar:2.3.0]
	at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.api.Play$.start(Play.scala:90) ~[play_2.10-2.3.0.jar:2.3.0]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:142) ~[play_2.10-2.3.0.jar:2.3.0]
	... 14 common frames omitted
```

If I stop the app and run it again (activator run) then it works fine (I see last changes, no compilations error).

I tried on another Windows machine and get the same error. I tried to remove all controllers and models except the main one (Application.java). I left only one action and route path in the route file. There was no error in that case. But after I began to add some actions and routes I see error again. And I couldn't find out any logic how to reproduce this situation on basic play-java activator template.

**Comment by MipH** [comment]
And I found the reason.
In build.sbt I have options:

```
// SECTION: Build package configuration
serverLoading in Debian  := SystemV
maintainer in Debian  := "me"
packageSummary in Debian  := "App"
packageDescription := "App"
exportJars := true
defaultLinuxInstallLocation := "/var"
// /SECTION: Build package configuration
```

If I remove exportJars  param my app feel good on Windows.
But using this option I cant recompile changes...

**Comment by jroper** [comment]
Why do you have `exportJars` set to true?  I'm not sure what's causing this, but I do know Windows has some very weird errors when you try to modify files and read them at the same time.

`exportJars` only really affects inter project dependencies, it shouldn't have any impact on your packaging configuration, because it's got nothing to do with packaging, it only impacts how classpaths are built internally in sbt and by Play.

**Comment by MipH** [comment]
ok
I can't reproduce this error on an empty play template like `play-java`.
But I spent several hours to find out the cause of error on my project (unfortunately I can't show the sources). The only thing I should do to get rid of error is to switch off `exportJars`.

Maybe the problem is in some dependencies I'm using or sequence of them.
Maybe it is *very weird Windows errors* you've mentioned.

I think we should close this issue. Thank you.
