### ISSUE TITLE
[2.4.0] Docker image packages Java 7 - needs Java 8

### ISSUE THREAD

**Issue by haebler** [playframework/playframework#4579]
Just started working with play 2.4.0 and I am trying to package a Java project as docker.

It seems that the Java 8 requirement for 2.4.0 hasn't been translated to the docker build configuration. The docker image I get includes Java 7 - not Java 8:

```
$ docker run -p 9000:9000 myapp:0.8
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:81)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:42)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

```
$ docker inspect myapp:0.8 | grep -i java
            "JAVA_VERSION=7u79",
            "JAVA_DEBIAN_VERSION=7u79-2.5.5-1~deb8u1"
            "JAVA_VERSION=7u79",
            "JAVA_DEBIAN_VERSION=7u79-2.5.5-1~deb8u1"
```

Is there a way to change the defaults to force a JDK/JRE 8?

**Comment by cchantep** [comment]
Hi @haebler , please first ask such question on the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework). If then an issue is confirmed about Play itself a detailed ticket can be filed on this issue tracker. Best regards.
