### ISSUE TITLE
OutOfMemoryError: Metaspace

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#4617]
It happens quite often during compilation (Play 2.4.0)

```
[info] Compiling 51 Scala sources and 46 Java sources to D:\workspaces\XXX\target\scala-2.11\classes...
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
        at sbt.Execute.next$1(Execute.scala:83)
        at sbt.Execute.processAll(Execute.scala:86)
        at sbt.Execute.runKeep(Execute.scala:66)
        at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:342)
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:341)
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:361)
        at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:64)
        at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:62)
        at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:293)
        at sbt.Aggregation$.timedRun(Aggregation.scala:62)
        at sbt.Aggregation$.runTasks(Aggregation.scala:71)
        at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:32)
        at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:31)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:153)
        at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:152)
        at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:244)
        at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:241)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.OutOfMemoryError: Metaspace
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at xsbt.CompilerInterface.newCompiler(CompilerInterface.scala:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
        at sbt.compiler.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:56)
        at sbt.compiler.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:51)
        at sbt.compiler.CompilerCache$$anon$2.apply(CompilerCache.scala:47)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:39)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
        at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
        at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
        at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
        at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
        at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
        at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace
[error] Use 'last' for the full log.
```

**Comment by eximius313** [comment]
or:
```
! @6md18h2id - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.OutOfMemoryError: Metaspace
  at plugins.ElasticSearchPlugin.<init>(ElasticSearchPlugin.java:39)
  at plugins.ElasticSearchPlugin.class(ElasticSearchPlugin.java:35)
  while locating plugins.ElasticSearchPlugin
    for field at controllers.Offers.searchPlugin(Offers.java:48)
  while locating controllers.Offers
    for parameter 2 at router.Routes.<init>(Routes.scala:56)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.11-2.4.0.jar:2.4.0]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.0.jar:2.4.0]
        at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.0.jar:2.4.0]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.0.j
ar:2.4.0]
        at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.6.jar:na]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.0.jar:2.4.0]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.0.jar:2.4.0]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.6.jar:na]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[na:1.8.0_31]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_31]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902) ~[na:1.8.0_31]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689) ~[na:1.8.0_31]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644) ~[na:1.8.0_31]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_31]
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.OutOfMemoryError: Metaspace
  at plugins.ElasticSearchPlugin.<init>(ElasticSearchPlugin.java:39)
  at plugins.ElasticSearchPlugin.class(ElasticSearchPlugin.java:35)
  while locating plugins.ElasticSearchPlugin
    for field at controllers.Offers.searchPlugin(Offers.java:48)
  while locating controllers.Offers
    for parameter 2 at router.Routes.<init>(Routes.scala:56)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.Application$class.routes(Application.scala:111) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.DefaultApplication.routes(Application.scala:240) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.Play$.start(Play.scala:89) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:156) ~[play-server_2.11-2.4.0.jar:2.4.0]
        ... 15 common frames omitted
Caused by: java.lang.OutOfMemoryError: Metaspace
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_31]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_31]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_31]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[na:1.8.0_31]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_31]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[na:1.8.0_31]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_31]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_31]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_31]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_31]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_31]
        at org.elasticsearch.action.ActionModule.configure(ActionModule.java:228) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:203) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159) ~[elasticsearch-1.5.2.jar:na]
        at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166) ~[elasticsearch-1.5.2.jar:na]
        at plugins.ElasticSearchPlugin.<init>(ElasticSearchPlugin.java:40) ~[na:na]
        at plugins.ElasticSearchPlugin$$FastClassByGuice$$12470702.newInstance(<generated>) ~[na:na]
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[guice-4.0.jar:na]
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) ~[guice-4.0.jar:na]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105) ~[guice-4.0.jar:na]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:na]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) ~[guice-4.0.jar:na]
```

**Comment by benmccann** [comment]
This is more likely a bug in your app than in Play. For tips on how to debug, see https://github.com/playframework/playframework/issues/4469

**Comment by eximius313** [comment]
but it almost always happens during compilation and it didn't happen in Play 2.3.8

**Comment by benmccann** [comment]
It doesn't happen to most users. It happens just to a handful that have memory or thread leaks in their app such as not closing an elasticsearch connection when the app is shut down

**Comment by marcospereira** [comment]
If it is happening when compiling the code, then it is more a sbt or activator problem. You can configure `SBT_OPTS` to set `Xms`, `Xmx`, `Xss` e `XX:MaxPermSize` and see if it fixes the problem.

**Comment by benmccann** [comment]
Does this happen each time the code is compiled or only sometimes?

**Comment by eximius313** [comment]
once every 4-10 compilations

**Comment by benmccann** [comment]
Yeah, then you definitely have the problem I was referring to. The issue is that when you reload the page and recompile the code it reloads the application. There's some cleanup that should happen when you shutdown an application that you're not doing. After you reload the app enough time, you have all these old objects around still that eventually cause the server to run out of memory. I had the same problem and in my case it turned out that I needed to close my connection to MongoDB and ElasticSearch. You should look at https://github.com/playframework/playframework/issues/4469 for tips on how to debug

**Comment by marcospereira** [comment]
@eximius313 and @benmccann we should probably close this issue, right?

**Comment by benmccann** [comment]
Yeah, I think it's fine to close this. Probably better discussed on the mailing list since it's a problem in @eximius313's app and not with Play. Though we need to add a documentation page to help users debug these types of problems, which is what the other bug I linked to is for

(There is some chance there's a bug in Play here as there have been in the past. However, I think those problems are all fixed and we should assume the bug isn't in Play unless someone follows the directions in https://github.com/playframework/playframework/issues/4469 and then posts that output showing that the problem is in Play)

**Comment by Hamsterkiller** [comment]
resolved for me by relaunching sbt console

**Comment by eximius313** [comment]
"resolved"... you just delayed it ;)
it keeps returning all the time :(
