### ISSUE TITLE
play WS (via Ning) is not compatible with Netty 3.10.X

### ISSUE THREAD

**Issue by vsabella** [playframework/playframework#4652]
We are currently using Netty 3.10.X with Play (2.3.7 and 2.3.9 last tested) and it appears that Ning is attempting to call an unavailable method.

Could we perhaps get a newer version of Ning that is compatible?

java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.setHeader(Ljava/lang/String;Ljava/lang/Object;)V
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.construct(NettyAsyncHttpProvider.java:702) ~[com.ning.async-http-client-1.8.14.jar:na]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.buildRequest(NettyAsyncHttpProvider.java:655) ~[com.ning.async-http-client-1.8.14.jar:na]
        at com.ning.http.client.providers.netty.NettyConnectListener$Builder.build(NettyConnectListener.java:145) ~[com.ning.async-http-client-1.8.14.jar:na]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1069) ~[com.ning.async-http-client-1.8.14.jar:na]
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:938) ~[com.ning.async-http-client-1.8.14.jar:na]
        at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:499) ~[com.ning.async-http-client-1.8.14.jar:na]
        at play.api.libs.ws.ning.NingWSClient.executeRequest(NingWS.scala:42) ~[com.typesafe.play.play-ws_2.11-2.3.7.jar:2.3.7]
        at play.api.libs.ws.ning.NingWSRequest.executeStream(NingWS.scala:275) ~[com.typesafe.play.play-ws_2.11-2.3.7.jar:2.3.7]
        at play.api.libs.ws.ning.NingWSRequestHolder.stream(NingWS.scala:409) ~[com.typesafe.play.play-ws_2.11-2.3.7.jar:2.3.7]
        at play.api.libs.ws.WSRequestHolder$class.getStream(WS.scala:502) ~[com.typesafe.play.play-ws_2.11-2.3.7.jar:2.3.7]
        at play.api.libs.ws.ning.NingWSRequestHolder.getStream(NingWS.scala:361) ~[com.typesafe.play.play-ws_2.11-2.3.7.jar:2.3.7]
        at controllers.Reports$$anonfun$downloadReport$1$$anonfun$apply$11$$anonfun$apply$12.apply(Reports.scala:142) ~[com.evidence.evidence-webserver-master-62.jar:master-62]

**Comment by wsargent** [comment]
Play 2.4 uses AHC 1.9.x under the hood.

Sent from Outlook

    _____________________________

**Comment by marcospereira** [comment]
Hello @vsabella, do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue.

Thanks.

**Comment by ubourdon** [comment]
I have the same issue when using play.api.libs.ws.Ws with 2.3.10.
It seems that play-2.3.10 use netty 3.10.4.Final & play-ws-2.3.10 use async-http-client 1.8.15 which use method 'org.jboss.netty.handler.codec.http.HttpRequest.setHeader' that do not exist in 3.10.4.Final version of netty.

**Comment by marcospereira** [comment]
@ubourdon, 

I've checked that and looks like Play 2.3.10 uses Netty 3.9.9.Final instead:

https://github.com/playframework/playframework/blob/2.3.10/framework/project/Dependencies.scala#L79

And version 3.9.9.Final of Netty still have the `setHeader` method:

https://github.com/netty/netty/blob/netty-3.9.9.Final/src/main/java/org/jboss/netty/handler/codec/http/HttpMessage.java#L99-L109

(`HttpRequest` extends `HttpMessage`) Are you manually adding Netty 3.10.4.Final? Moreover, I suggest that you use our [mailing list](https://groups.google.com/forum/m/#!forum/play-framework) to discuss these kind of doubts.

**Comment by ubourdon** [comment]
@marcospereira 
Yes sorry,

I find my issu. It's because of reactive-mongo upgrade version. I talk with maintainer of lib & they said playframework 2.3.9 embed Netty 3.10.4.Final but in fact, as you said, no.

So it is an issue for the lib and not for you.

Sorry for the disturb.

**Comment by dmassart** [comment]
upgrading to reactivemongo 0.11.13-play23 seems to fix the problem.
