### ISSUE TITLE
compile error when using play sub routes on play 2.4 with 'routesGenerator := InjectedRoutesGenerator'

### ISSUE THREAD

**Issue by bkkoo** [playframework/playframework#4671]
When enable InjectedRoutesGenerator in build.sbt ('routesGenerator := InjectedRoutesGenerator) and change the Application controller from object to class and config route with sub route as following

->      /room/chat        controllers.Application.chat

when run cause following compile error...

play.sbt.PlayExceptions$CompilationException: Compilation error[object Application is not a member of package controllers
Note: class Application exists, but it has no companion object.]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.10.5.jar:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.10.5.jar:na]
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
[info] Compiling 9 Scala sources and 1 Java source to /home/bkkoo/Projects/play/play2-sockjs/samples/sockjs-chat/target/scala-2.10/classes...
[error] /home/bkkoo/Projects/play/play2-sockjs/samples/sockjs-chat/conf/routes:8: object Application is not a member of package controllers
[error] Note: class Application exists, but it has no companion object.
[error] ->      /room/chat                  controllers.Application.chat
[error] /home/bkkoo/Projects/play/play2-sockjs/samples/sockjs-chat/conf/routes:8: object Application is not a member of package controllers
[error] Note: class Application exists, but it has no companion object.
[error] ->      /room/chat                  controllers.Application.chat
[error] /home/bkkoo/Projects/play/play2-sockjs/samples/sockjs-chat/conf/routes:8: object Application is not a member of package controllers
[error] Note: class Application exists, but it has no companion object.
[error] ->      /room/chat                  controllers.Application.chat
[error] three errors found
[error] (compile:compileIncremental) Compilation failed
[error] application -

**Comment by jroper** [comment]
Hi @bkkoo, please ask questions like this on the mailing list.

`controllers.Application.chat` is a controller, not a router, so you can't include it as a router.

**Comment by tenstriker** [comment]
Shouldn't error message be bit more clearer in this case? "class Application exists, but it has no companion object" doesn't help to troubleshoot anything.
