### ISSUE TITLE
Evolutions does not tolerate no db connection

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#4675]
Evolutions does not tolerate not being able to resolve a connection to a database.

With some data sources, a database connection may not be available immediately. In this case the application of evolutions fails. Here is the stack trace:

```
Oops, cannot start the server.
java.sql.SQLTimeoutException: Timeout after 1004ms of waiting for a connection.
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227)
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93)
	at slick.jdbc.HikariCPJdbcDataSource.createConnection(JdbcDataSource.scala:131)
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:394)
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:394)
	at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:54)
	at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:56)
	at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:119)
	at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:97)
	at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:112)
	at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:77)
	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:50)
	at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:98)
	at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
	at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
	at scala.collection.immutable.Stream.foreach(Stream.scala:594)
	at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
	at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:149)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:44)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at com.typesafe.conductr.bundlelib.play.ConductRApplicationLoader.load(ConductRApplicationLoader.scala:20)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: org.postgresql.util.PSQLException: Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:239)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:41)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:414)
	at org.postgresql.Driver.connect(Driver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at slick.jdbc.ProxyDataSource.getConnection(ProxyDataSource.scala:106)
	at slick.jdbc.ProxyDataSource.getConnection(ProxyDataSource.scala:72)
	at slick.jdbc.ProxyDataSource.getConnection(ProxyDataSource.scala:60)
	at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:438)
	at com.zaxxer.hikari.pool.BaseHikariPool$1.run(BaseHikariPool.java:413)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:121)
	... 20 more
```

**Comment by jroper** [comment]
Is there anything though that evolutions can do about this?  I mean, if you fail to apply the evolutions, you don't want your application to run.  Evolutions are, by design, meant to prevent the app from starting if there's a problem.  Unless evolutions blocks the entire app from running when there's no database, I don't see any other way of addressing this.

**Comment by huntc** [comment]
Thanks for the response. Perhaps evolutions and resiliency i.e. being able to continue in the face of failure, do not mix. I shall abandon evolutions then.

**Comment by PhilAndrew** [comment]
Although you closed the issue, I think the problem is that if there is a timeout, everything seems to "give up" after that until I restart the app.

**Comment by smiller171** [comment]
how can this timeout be adjusted, or add in retries?

**Comment by vrcod** [comment]
Is there any progress on this issue? This situation basically makes it impossible to use evolutions with Slick, so should that be not clearly stated in the documentation (https://www.playframework.com/documentation/2.4.x/PlaySlick)?

**Comment by dotta** [comment]
@vrcod That is FUD. As *stated* in the [play-slick documentation](https://www.playframework.com/documentation/2.4.x/PlaySlick), play-slick supports Play evolutions.

**Comment by vrcod** [comment]
@dotta FUD was never and intention - just after reading all the comments that seemed like an obvious conclusion. I have followed the documentation to the letter and it doesn't work. I cannot find a single working example, if there is one - please link me to it. Thanks, I appreciate all the work you guys are doing here.

**Comment by dotta** [comment]
@vrcod Quite simply, I think the discussion started on the wrong foot, but there is no bad feeling on my side. In fact, I've just answered your question in the mailing list, hopefully that will set you on the right track and you'll be able to enjoy play-slick with evolutions support ;-)

**Comment by vrcod** [comment]
@dotta Thanks, but it's still not working. Also, your example contradicts the documentation: https://www.playframework.com/documentation/2.4.x/PlaySlick#Database-Configuration

**Comment by dotta** [comment]
> Thanks, but it's still not working. 

Ok. Let's keep discussing in the mailing list.

> Also, your example contradicts the documentation: https://www.playframework.com/documentation/2.4.x/PlaySlick#Database-Configuration

I don't see how, so please clarify this point as well in the mailing list.

**Comment by dsounded** [comment]
Any updates with this ?
it still doesn't work with `mysql` adapter and `play/slick/evolutions`

**Comment by dsounded** [comment]
@dotta I am using last version of `Scala/Play/Slick` with `mysql` and getting the same error, could you please help me out with this ?

**Comment by dsounded** [comment]
@dotta Sorry, seems it doesn't work only of wrong credentials have been provided, so it's ok for now.

**Comment by matthewdooler** [comment]
Is there scope for this to ever be added to evolutions? e.g., by allowing retries?

I can think of a number of use cases:
- Starting up a whole application and database for a few small integration tests, in which the database may take a few seconds longer to start up
- General resiliency on startup (e.g., if there was temporary network problem when deploying, another redeploy would need to be done)
