### ISSUE TITLE
Hibernate ClassCastException

### ISSUE THREAD

**Issue by ScreaD** [playframework/playframework#4679]
At every request to my web application I have this log in console.
```
13:49:45,119 ERROR ~ Why the driver complains here?
java.lang.ClassCastException: org.hibernate.internal.SessionImpl cannot be cast to org.hibernate.impl.SessionImpl
	at play.db.DB.getConnection(DB.java:59)
	at play.db.jpa.JPAPlugin.closeTx(JPAPlugin.java:395)
	at play.db.jpa.JPAPlugin.afterInvocation(JPAPlugin.java:350)
	at play.plugins.PluginCollection.afterInvocation(PluginCollection.java:479)
	at play.Invoker$Invocation.after(Invoker.java:225)
	at play.Invoker$Invocation.run(Invoker.java:279)
	at Invocation.HTTP Request(Play!)
```

What I'm doing wrong?

**Comment by marcospereira** [comment]
Hello @ScreaD, do you mind discuss that first on the [user mailing list](https://groups.google.com/forum/m/#!forum/play-framework)? If we confirm that there is an error with Play, than we can open an issue.

Thanks.
