### ISSUE TITLE
Serializing via an array doesn't seem to work.

### ISSUE THREAD

**Issue by ddispaltro** [playframework/playframework#4744]
This example should work, the read side works fine, but this throws an error.  It seems writes assume a JsObject, do you have any suggestions?

```scala 

case class Foo(i: String, l: Long)
  implicit val fooFormat = (__(0).write[String] and __(1).write[Long])(unlift(Foo.unapply))

  test("simple json") {
    Json.toJson(Foo("hell0", 12))
  }
```

Exception:
```
expected KeyPathNode
java.lang.RuntimeException: expected KeyPathNode
	at play.api.libs.json.JsPath$.step$1(JsPath.scala:138)
	at play.api.libs.json.JsPath$.play$api$libs$json$JsPath$$buildSubPath$1(JsPath.scala:147)
	at play.api.libs.json.JsPath$$anonfun$createObj$1.apply(JsPath.scala:152)
	at play.api.libs.json.JsPath$$anonfun$createObj$1.apply(JsPath.scala:150)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at play.api.libs.json.JsPath$.createObj(JsPath.scala:150)
	at play.api.libs.json.PathWrites$$anonfun$at$2.apply(JsConstraints.scala:161)
	at play.api.libs.json.PathWrites$$anonfun$at$2.apply(JsConstraints.scala:161)
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76)
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65)
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65)
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76)
	at play.api.libs.json.OWrites$$anon$1$$anonfun$contramap$1.apply(Writes.scala:71)
	at play.api.libs.json.OWrites$$anon$1$$anonfun$contramap$1.apply(Writes.scala:71)
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76)
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:75)
	at play.api.libs.json.Json$.toJson(Json.scala:118)
	...

```

**Comment by jroper** [comment]
That's true.  This kind of indexed based array serialisation isn't supported.  To explain why, let's say you tried this:

```scala
val writes: Writes[String] = __(1).write[String]
val json: JsValue = writes.writes("foo")
```

What's `json` going to be?  A `JsArray`?  If it was `JsArray`, the only thing you could output would be `["foo"]`.  The fact that the `foo` should be in the second position is lost, and there's no way to carry that information.  So when you combine it with another writes, there's no way to merge it.  Contrast this with objects:

```scala
val writes: Writes[String] = (__ \ "key").write[String]
val json: JsValue = writes.writes("foo")
```

Now that's going to output `{"key": "foo"}`, so when you merge that with the output of another writes, it's fine, because the path is part of the object, and so is carried through.

**Comment by ddispaltro** [comment]
I guess I am looking to serialize and deserialize tuples., looks like https://github.com/cvogt/play-json-extensions is the way to do that.  Surprised this isn't in play-json though.
