### ISSUE TITLE
Can't use Java controller with Scala app in Play 2.4?

### ISSUE THREAD

**Issue by brikis98** [playframework/playframework#4779]
I'm trying to upgrade the [ping-play](https://github.com/brikis98/ping-play) app to Play 2.4 and to use [Scala Compile Time Dependency Injection](https://playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection). My `ApplicationLoader` looks something like this:

```scala
class PingApplicationLoader extends ApplicationLoader {
  override def load(context: Context): Application = {
    new PingComponents(context).application
  }
}

class PingComponents(context: Context) extends BuiltInComponentsFromContext(context)  {
  lazy val scalaController = new ScalaController()
  lazy val javaController = new JavaController()

  lazy val router: Router = new Routes(httpErrorHandler, scalaController, javaController)
}
```

When I go to the URL for the `scalaController`, it works fine. When I go to the URL for the `javaController`, I get the following error:

```
[error] p.c.s.n.PlayDefaultUpstreamHandler - Exception caught in Netty
scala.MatchError: Right((play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3@43355ebf,play.api.DefaultApplication@2ac109ad)) (of class scala.util.Right)
	at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:150) ~[play-netty-server_2.11-2.4.0.jar:2.4.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
	at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [netty-http-pipelining-1.1.4.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
```

Any ideas?

**Comment by cchantep** [comment]
Hi, to get more help for such question, please ask it on the [user Mailing List](https://groups.google.com/forum/m/#!forum/play-framework). If then an issue is confirmed, a ticket can be filed on this tracker. Best regards.

**Comment by brikis98** [comment]
Posted here: https://groups.google.com/forum/#!topic/play-framework/A0rCbXVX_Gw

**Comment by dwijnand** [comment]
Hit this as well. I think this should be re-opened given @jroper confirmed it as a bug (see the ML thread above).

**Comment by brikis98** [comment]
Oh yea, I totally lost track of this, but +1 to @dwijnand's comment :)
