### ISSUE TITLE
Intellij 14.1.4 does not recognize configured JDK on mac

### ISSUE THREAD

**Issue by kumarsk9** [playframework/playframework#4824]
I get this below error after i have upgraded to Intellij 14.1.4
This is sample Play2 scala application created using default template.
![screen shot 2015-07-08 at 1 30 46 pm](https://cloud.githubusercontent.com/assets/13243807/8581453/ac1d71ca-2575-11e5-8c47-bd033259f455.png)

Error:Internal error: (java.io.IOException) Cannot run program "/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java" (in directory "/Users/kumarkothapalli/Google+Drive/PlayExamples/Play2"): error=2, No such file or directory
java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java" (in directory "/Users/kumarkothapalli/Google+Drive/PlayExamples/Play2"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.intellij.scala.play.jpsSupport.Play2TemplateJpsBuilder$$anonfun$build$1.apply(Play2TemplateJpsBuilder.scala:193)
	at com.intellij.scala.play.jpsSupport.Play2TemplateJpsBuilder$$anonfun$build$1.apply(Play2TemplateJpsBuilder.scala:133)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at com.intellij.scala.play.jpsSupport.Play2TemplateJpsBuilder.build(Play2TemplateJpsBuilder.scala:133)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1196)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:877)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:945)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:840)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:663)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:370)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:191)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:293)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:124)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:242)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 22 more

**Comment by wsargent** [comment]
This is not a Play problem.  You don't have Java installed at that path.
