### ISSUE TITLE
[Play 2.4 Scala] Compile time DI MessagesApi InstantiationException

### ISSUE THREAD

**Issue by danielnixon** [playframework/playframework#4836]
Compile time DI using ApplicationLoader and a MessagesApi dependency, controller actions that take an implicit request explode at runtime. (Those that don't take an implicit request work as expected).

```
class SimpleApplicationLoader extends ApplicationLoader {
  def load(context: Context) = {
    new ApplicationComponents(context).application
  }
}

class ApplicationComponents(context: Context) extends BuiltInComponentsFromContext(context) with I18nComponents {
  lazy val applicationController = new controllers.Application(messagesApi)
  lazy val assets = new controllers.Assets(httpErrorHandler)
  override lazy val router = new Routes(httpErrorHandler, applicationController, assets)
}
```

```
class Application(val messagesApi: MessagesApi) extends Controller with I18nSupport {

  // Works.
  def foo = Action { request =>
    Ok(views.html.index(messagesApi("foo")))
  }

  // Throws InstantiationException.
  def bar = Action { implicit request =>
    Ok(views.html.index(messagesApi("bar")))
  }

}
```

Example project: https://github.com/danielnixon/play24SimpleDI

**Comment by julienrf** [comment]
Hi, I don't have this problem in my projects. Can you please post the stack trace?

**Comment by danielnixon** [comment]
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[InstantiationException: play.api.i18n.MessagesApi]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.7.jar:na]
Caused by: java.lang.InstantiationException: play.api.i18n.MessagesApi
	at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_45]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.2.jar:2.4.2]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.7.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[play_2.11-2.4.2.jar:2.4.2]
Caused by: java.lang.NoSuchMethodException: play.api.i18n.MessagesApi.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_45]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_45]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.2.jar:2.4.2]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.7.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.2.jar:2.4.2]
```

**Comment by julienrf** [comment]
You should use the [`Messages`](https://www.playframework.com/documentation/2.4.x/api/scala/play/api/i18n/Messages$.html) object to translate your messages instead of calling the `MessagesApi`.

I think the problem comes from the fact that `MessagesApi` has an [`apply`](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.i18n.MessagesApi@apply(keys:Seq[String],args:Any*)(implicitlang:play.api.i18n.Lang):String) method that takes an implicit `Lang` as parameter. This implicit lang is retrieved using a legacy way that relies on a runtime dependency injector.

I wonder if we should deprecate this `apply` method.

**Comment by danielnixon** [comment]
Ah I see. I followed [ScalaCompileTimeDependencyInjection#Using-other-components](https://www.playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection#Using-other-components), which looks like:

```
import play.api.i18n._

class MyComponents(context: Context) extends BuiltInComponentsFromContext(context)
                                     with I18nComponents {
  lazy val router = Router.empty

  lazy val myComponent = new MyComponent(messagesApi)
}

class MyComponent(messages: MessagesApi) {
  // ...
}
```

The `// ...` tricked me into using the `messages` param as a replacement for the `Messages` object. Thanks for you help. Happy to close this.

**Comment by godenji** [comment]
> I wonder if we should deprecate this apply method.

A resounding yes, lest others like myself waste a couple of hours trying to sort out what on earth is causing the exception ;-)

Thanks for creating this issue @danielnixon !
