### ISSUE TITLE
playframework2.4(slick 3.0) doesn't work in rasberry pi2

### ISSUE THREAD

**Issue by jijoungsoo** [playframework/playframework#4850]
playframework2.4(slick 3.0) doesn't work in rasberry pi2.
------------------------------------------------------------------------------
[info] - play.api.libs.concurrent.ActorSystemProvider - Starting application default Akka system: application
[info] - play.api.Play - Application started (Dev)
[error] - application - 

! @6mnackb89 - Internal server error, for (GET) [/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[SQLTimeoutException: Timeout after 1002ms of waiting for a connection.]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library-2.11.6.jar:na]
	at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.6.jar:na]
	at scala.util.Failure.recover(Try.scala:215) [scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.6.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.6.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.2.jar:2.4.2]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [scala-library-2.11.6.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [scala-library-2.11.6.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [scala-library-2.11.6.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
Caused by: java.sql.SQLTimeoutException: Timeout after 1002ms of waiting for a connection.
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182) ~[HikariCP-2.3.7.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93) ~[HikariCP-2.3.7.jar:na]
	at slick.jdbc.HikariCPJdbcDataSource.createConnection(JdbcDataSource.scala:131) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:394) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:394) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:252) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:386) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:69) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:198) ~[slick_2.11-3.0.0.jar:na]
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:198) ~[slick_2.11-3.0.0.jar:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:231) ~[slick_2.11-3.0.0.jar:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:231) ~[slick_2.11-3.0.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_33]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_33]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_33]
---------------------------------------------------------------------------------------------------------------
but
playframework2.4(jdbc)  work in rasberry pi2.

and 
play fork is not work.(jdbc)
-----------------------------------------------------------------------------------------------------------------
in my pc everything is ok.

**Comment by marcospereira** [comment]
Hello @jijoungsoo, do you mind discuss that first on the user mailing list? If we confirm that there is an error with Play, than we can open an issue.

Thanks.

**Comment by jijoungsoo** [comment]
I understood.  what is user mailing list?  Is this google group? or do you have other mailing list? I didnt understand exactly the user mailing list.

**Comment by adis-me** [comment]
@jijoungsoo 
[Play! Mailing List](https://groups.google.com/forum/#!forum/play-framework)
See links on the top left part of the [Play! Website](https://playframework.com)

**Comment by jijoungsoo** [comment]
thank you. I am gointo write there

**Comment by jijoungsoo** [comment]
i wrote mailing list.
they didnt reply.
help me.
https://groups.google.com/forum/m/#!topic/play-framework/00-eEoiraQ4

**Comment by jroper** [comment]
@jijoungsoo if you need help, and aren't satisfied with waiting for people to help you for free, then you should consider purchasing a subscription from Typesafe:

http://www.typesafe.com/subscription
