### ISSUE TITLE
Activator over satellite connection

### ISSUE THREAD

**Issue by BobbyWalker** [playframework/playframework#4866]
When running the activator to create a new project (I hadn't used the framework in a couple of months so it had plenty of updates to take), I had to run the command several times to get it to update, which had the following output (I was incrementally getting farther with every run of the command).    Finally I gave up and turned my phone's hotspot on, then the command ran fine and finished updating as expected.   I have a high latency connection averaging around 850ms, but I have great download speeds once the connection is established (up to 15mbs), but since it seems like each item in the update list initiates a new connection, that latency is what is killing the activator command.

[info] Loading project definition from /Users/bobbywalker/Dropbox/Play-Framework/consulting-services-inc/project
[info] Set current project to consulting-services-inc (in build file:/Users/bobbywalker/Dropbox/Play-Framework/consulting-services-inc/)
[info] Updating {file:/Users/bobbywalker/Dropbox/Play-Framework/consulting-services-inc/}root...
[info] Resolving com.fasterxml.jackson.datatype#jackson-datatype-jsr310;2.5.4 ..[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-functional_2.11/2.4.2/play-functional_2.11-2.4.2.jar ...
[info] 	[SUCCESSFUL ] com.typesafe.play#play-functional_2.11;2.4.2!play-functional_2.11.jar (4210ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-omnidoc_2.11/2.4.2/play-omnidoc_2.11-2.4.2.jar ...
[warn] 	[FAILED     ] com.typesafe.play#play-omnidoc_2.11;2.4.2!play-omnidoc_2.11.jar: Tag mismatch! (3641ms)
[warn] 	[FAILED     ] com.typesafe.play#play-omnidoc_2.11;2.4.2!play-omnidoc_2.11.jar:  (0ms)
[warn] ==== local: tried
[warn]   /Users/bobbywalker/.ivy2/local/com.typesafe.play/play-omnidoc_2.11/2.4.2/jars/play-omnidoc_2.11.jar
[warn] ==== activator-local: tried
[warn]   /users/bobbywalker/activator/repository/com.typesafe.play/play-omnidoc_2.11/2.4.2/jars/play-omnidoc_2.11.jar
[warn] ==== activator-launcher-local: tried
[warn]   /users/bobbywalker/activator/repository/com.typesafe.play/play-omnidoc_2.11/2.4.2/jars/play-omnidoc_2.11.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/play-omnidoc_2.11/2.4.2/play-omnidoc_2.11-2.4.2.jar
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/typesafe/play/play-omnidoc_2.11/2.4.2/play-omnidoc_2.11-2.4.2.jar
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/play-omnidoc_2.11/2.4.2/jars/play-omnidoc_2.11.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#play-omnidoc_2.11;2.4.2!play-omnidoc_2.11.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: com.typesafe.play#play-omnidoc_2.11;2.4.2!play-omnidoc_2.11.jar
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: download failed: com.typesafe.play#play-omnidoc_2.11;2.4.2!play-omnidoc_2.11.jar
[error] Total time: 22 s, completed Jul 19, 2015 4:29:33 AM

**Comment by cchantep** [comment]
Please first use the [user MailingList](https://groups.google.com/forum/#!forum/play-framework) for such discussion. Best regards.

**Comment by jroper** [comment]
This discussion is relevant:

https://github.com/sbt/sbt/issues/590

I don't know that it will fix the tag mismatch error you see, but it should make resolution much faster.  If you want to raise an issue for the tag mismatch error, the best place to raise that would be on sbt.
