### ISSUE TITLE
HikariCP - JPAApi leaking connections

### ISSUE THREAD

**Issue by johdah** [playframework/playframework#4916]
After a while of troubleshooting my problems with QueryTimeoutException I activated the debug logging in HikariCP. After 2 hours, no connections in HikariCP is released and the leak detection in HikariCP has been triggered for all the connections. 

Leak detection error:
```
2015-07-30 15:53:15,421 - [warn] c.z.h.p.LeakTask - Connection leak detection triggered for connection com.mysql.jdbc.JDBC4Connection@53b6a428, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:380) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:228) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:171) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:63) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
```

UserDAO:
```java
public class UserDAO extends AbstractDAO<User, User_> {
    JedisPool jedisPool;

    @Inject
    public UserDAO(final JPAApi jpaApi, JedisPool jedisPool) {
        super(jpaApi, User.class, User_.class);
        this.jedisPool = jedisPool;
    }

    ...
}
```

AbstractDAO:
```java
public abstract class AbstractDAO<T extends AbstractModel, M extends AbstractModel_> {
    protected final Class<T> classType;
    protected final EntityManager em;
    protected final CriteriaBuilder cb;

    public AbstractDAO(final JPAApi jpaApi, Class<T> classType, Class<M> metaType) {
        this.em = jpaApi.em("default");
        this.cb = em.getCriteriaBuilder();
        this.classType = classType;
    }

    ...
}
```

persistence.xml:
```xml
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd"
             version="2.1">

    <persistence-unit name="defaultPersistenceUnit" transaction-type="RESOURCE_LOCAL">
        <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
        <non-jta-data-source>DefaultDS</non-jta-data-source>
        <properties>
            <property name="hibernate.dialect" value="org.hibernate.dialect.MySQL5Dialect"/>

            <property name="hibernate.enable_lazy_load_no_trans" value="true" />
            <property name="hibernate.format_sql" value="true" />
            <property name="hibernate.hbm2ddl.auto" value="validate"/>
            <property name="hibernate.max_fetch_depth" value="5" />
            <property name="hibernate.show_sql" value="false" />
        </properties>
    </persistence-unit>

</persistence>
```

application.conf:
```
db {
  default {
    driver=com.mysql.jdbc.Driver
    url="jdbc:mysql://localhost/dbname?tinyInt1isBit=false"
    username="root"
    password="secret"
    jndiName=DefaultDS

    hikaricp {
      connectionTimeout=30 seconds #2 minutes
      idleTimeout = 2 minutes
      leakDetectionThreshold=8 minutes
      maxLifetime = 5 minutes
      maximumPoolSize = 100
    }
  }
}
```

**Comment by jroper** [comment]
An `EntityManager` gets tied to a connection.  Your `AbstractDAO` is creating an `EntityManager`, and keeping it, never cleaning it up.  That's the leak.  You should not create and cache `EntityManager`, you should either request it each time you need it, and be sure to close it in a finally block, or you should use Play's `JPAApi.withTransaction` helpers, which do this for you.

**Comment by johdah** [comment]
Do you mean something like this? Because I still get the leak. Maybe I misunderstod you.

AbstractDAO
```java
public abstract class AbstractDAO<T extends AbstractModel, M extends AbstractModel_> {
    protected final Class<T> classType;
    public final JPAApi jpaApi;

    public AbstractDAO(final JPAApi jpaApi, Class<T> classType, Class<M> metaType) {
        this.jpaApi = jpaApi;
    }
}
```

UserDAO:
```java
public class UserDAO extends AbstractDAO<User, User_> {
    JedisPool jedisPool;

    @Inject
    public UserDAO(final JPAApi jpaApi) {
        super(jpaApi, User.class, User_.class);
    }

    @SuppressWarnings("unchecked")
    public Optional<User> findByEmail(String email) {
        try {
            return (Optional<User>) jpaApi.withTransaction(() -> {
                EntityManager entityManager = jpaApi.em("default");
                Query q = entityManager.createQuery("FROM User WHERE email=?1")
                        .setParameter(1, email);
                try {
                    return Optional.ofNullable((User) q.getSingleResult());
                } catch(NoResultException ex) {
                    return Optional.empty();
                }
            });
        } catch (Throwable throwable) {
            throwable.printStackTrace();
            return Optional.empty();
        }
    }
}
```
