### ISSUE TITLE
application.ini incorrect line ending => application can't start

### ISSUE THREAD

**Issue by giabao** [playframework/playframework#4921]
1. build.sbt

    ```scala
javaOptions in Universal += "-Dlogger.file=conf/logback-prod.xml"
```

2. `sbt dist` from a Windows machine.

3. run in linux => error: 
   ```
Error encountered while configuring logback:
ch.qos.logback.core.joran.spi.JoranException: Could not open URL [file:/var/www/api-3.20-SNAPSHOT/conf/logback-prod.xml%0D].
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at play.api.Logger$.configure(Logger.scala:278)
        at play.api.Logger$.configure(Logger.scala:232)
        at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:73)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
 (No such file or directory)undException: /var/www/api-3.20-SNAPSHOT/conf/logback-prod.xml
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:48)
        ... 9 more
```
4. if before run the app, I run the following command to remove `\r`:
```bash
sed -i.bak 's/\r$//' conf/application.ini
```
=> OK

**Comment by giabao** [comment]
I run play 2.4.2

**Comment by nafg** [comment]
Doesn't sound like a play issue, either it's a logback issue or it's just
different platforms are incompatible.
But who created this file with such line endings?
And since when does play use .ini?

**Comment by giabao** [comment]
This is a bug of [sbt-native-packager](https://github.com/sbt/sbt-native-packager) which is used by Play.

See https://github.com/giabao/native-packager-test
