### ISSUE TITLE
Error while creating Akka actor

### ISSUE THREAD

**Issue by osek666** [playframework/playframework#4950]
Hi!

According to the documentation I'm trying to eliminate Global class from my application.
I moved creating of Akka actor to singleton constructor.
Unfortunately I get error: 

```
[error] - application - 

! @6n3ig93lk - Internal server error, for (GET) [/] ->
 
play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.RuntimeException: There is no started application
  at test.SomeSingleton.<init>(SomeSingleton.java:13)
  at modules.HelloModule.configure(HelloModule.java:10) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.HelloModule)
  while locating test.SomeSingleton
```

My code:

```java
@Singleton
public class SomeSingleton {

    public SomeSingleton() {
        Akka.system().actorOf(Props.create(SomeActor.class), "SomeActorName");
    }

}

public class HelloModule extends AbstractModule {

    @Override
    protected void configure() {
        bind(SomeSingleton.class)
                .asEagerSingleton();
    }

}
```

Any ideas, how to solve it?

**Comment by dotta** [comment]
Hi @osek666, please use the [user MailingList](https://groups.google.com/forum/#!forum/play-framework) for asking questions about Play.
