### ISSUE TITLE
Scala random crash on compilation

### ISSUE THREAD

**Issue by pycloux** [playframework/playframework#4999]
Hi All,

I am experiencing (randomly) some crash during the compilation.
(using JDK1.8 from Oracle and Play 2.4.2 with Scala 11 on CentOs).
It's a scala crash which looks like the stakoverflow reported issues:
https://stackoverflow.com/questions/28510867/scala-2-11-5-compiler-crash-with-type-aliases-and-manifests

The solution seems to increase the memory allocated to SBT with :
```
export SBT_OPTS="-Xmx4G –Xss4M”  for instance.
```
Since we are in continuous integration we'll see if it improves the situation.

However I suspect this is related to a recursive pattern in the generated code (scala templates or routes since we are using Play java).

See below the stacktrace (I cut most of it because it is obviously a recursive pattern):
```
[info] Compiling 326 Scala sources and 366 Java sources to /var/lib/jenkins/jobs/com.agifac.maf.desktop.maf-desktop-app/workspace/target/scala-2.11/classes...
java.lang.StackOverflowError
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5004)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:696)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5472)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5480)
	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:642)
	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:696)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
[error] (compile:compileIncremental) java.lang.StackOverflowError
[error] Total time: 42 s, completed Aug 16, 2015 11:31:17 PM
```

**Comment by dotta** [comment]
Hi @pycloux, thanks for the feedback. However, it would be better if this kind of problems could be discussed first in the [play mailing list](https://groups.google.com/forum/#!forum/play-framework). The reason is that this is likely a scalac bug, and from the ticket it is not possible to say what can be done in Play to work around it (also, note there is no evidence that the problem originates from a Play route/template source in the provided stacktrace).
