### ISSUE TITLE
Error occurs when opening the documentation when integrating the pegdown into a Play Application

### ISSUE THREAD

**Issue by ThunderKeg** [playframework/playframework#5072]
I'm developing an web application using the Play Framework. I'm quite new to the framework, so I want to read the document while I'm developing it. And my application needs to involve the pegdown project to convert a markdown file to html as Play does for its documentation. But when I add the pegdown into the libraryDependencies into the build.sbt, the documentation page will give an exception.
![image](https://cloud.githubusercontent.com/assets/8939125/9699265/ee561458-540e-11e5-86e1-8f84b0263f17.png)

If I remove the pegdown from libraryDependencies, the documentation will be fine. 

My playframework is built from sources. And the playframework code is from the tag 2.4.2 and scala version is 2.11.4

My build.sbt is as follows:

```sbt
name := """my-first-application"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.4"

libraryDependencies ++= Seq(
  "org.pegdown" % "pegdown" % "1.4.0",
  jdbc,
  cache,
  ws,
  specs2 % Test
)

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"
//  
// Play provides two styles of routers, one expects its actions to be injected, the
// other, legacy style, accesses its actions statically.
routesGenerator := InjectedRoutesGenerator
```

The stack trace in application.log is as follows:

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: Error creating extended parser class: Error at instruction 28: Error loading class 'play.doc.CodeReferenceParser' for rule method analysis]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11.jar:2.4.2]
	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50) [play-server_2.11.jar:2.4.2]
	at play.core.server.Server$$anonfun$getHandlerFor$2.apply(Server.scala:56) [play-server_2.11.jar:2.4.2]
	at play.core.server.Server$$anonfun$getHandlerFor$2.apply(Server.scala:56) [play-server_2.11.jar:2.4.2]
	at scala.util.Either$LeftProjection.map(Either.scala:376) [scala-library-2.11.6.jar:na]
	at play.core.server.Server$class.getHandlerFor(Server.scala:56) [play-server_2.11.jar:2.4.2]
	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:33) [play-netty-server_2.11.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139) [play-netty-server_2.11.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$8.apply(PlayDefaultUpstreamHandler.scala:139) [play-netty-server_2.11.jar:2.4.2]
	at scala.util.Either.fold(Either.scala:99) [scala-library-2.11.6.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:127) [play-netty-server_2.11.jar:2.4.2]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
	at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [netty-http-pipelining-1.1.4.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.3.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.3.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: java.lang.RuntimeException: Error creating extended parser class: Error at instruction 28: Error loading class 'play.doc.CodeReferenceParser' for rule method analysis
	at org.parboiled.Parboiled.createParser(Parboiled.java:58) ~[parboiled-java-1.1.5.jar:na]
	at org.pegdown.plugins.PegDownPlugins$Builder.withPlugin(PegDownPlugins.java:99) ~[pegdown-1.4.0.jar:1.4.0]
	at play.doc.PlayDoc.play$doc$PlayDoc$$withRenderer(PlayDoc.scala:169) ~[na:na]
	at play.doc.PlayDoc$$anonfun$renderPage$2$$anonfun$apply$1.apply(PlayDoc.scala:58) ~[na:na]
	at play.doc.PlayDoc$$anonfun$renderPage$2$$anonfun$apply$1.apply(PlayDoc.scala:57) ~[na:na]
	at scala.Option.flatMap(Option.scala:171) ~[scala-library-2.11.6.jar:na]
	at play.doc.PlayDoc$$anonfun$renderPage$2.apply(PlayDoc.scala:57) ~[na:na]
	at play.doc.PlayDoc$$anonfun$renderPage$2.apply(PlayDoc.scala:56) ~[na:na]
	at scala.Option.fold(Option.scala:158) ~[scala-library-2.11.6.jar:na]
	at play.doc.PlayDoc.renderPage(PlayDoc.scala:56) ~[na:na]
	at play.docs.DocumentationHandler.maybeHandleDocRequest(DocumentationHandler.scala:79) ~[na:na]
	at play.docs.DocumentationHandler.maybeHandleDocRequest(DocumentationHandler.scala:38) ~[na:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1.handleWebCommand(DevServerStart.scala:187) ~[play-server_2.11.jar:2.4.2]
	at play.core.server.Server$$anonfun$getHandlerFor$1.apply(Server.scala:55) ~[play-server_2.11.jar:2.4.2]
	at play.core.server.Server$$anonfun$getHandlerFor$1.apply(Server.scala:55) ~[play-server_2.11.jar:2.4.2]
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125) ~[scala-library-2.11.6.jar:na]
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125) ~[scala-library-2.11.6.jar:na]
	at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.6.jar:na]
	at scala.util.control.Exception$Catch.either(Exception.scala:125) ~[scala-library-2.11.6.jar:na]
	at play.core.server.Server$class.getHandlerFor(Server.scala:55) [play-server_2.11.jar:2.4.2]
	... 35 common frames omitted
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 28: Error loading class 'play.doc.CodeReferenceParser' for rule method analysis
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Unknown Source) ~[asm-analysis-4.1.jar:4.1]
	at org.parboiled.transform.InstructionGraphCreator.process(InstructionGraphCreator.java:43) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.ParserTransformer.runMethodTransformers(ParserTransformer.java:62) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:45) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.Parboiled.createParser(Parboiled.java:54) ~[parboiled-java-1.1.5.jar:na]
	... 54 common frames omitted
Caused by: java.lang.RuntimeException: Error loading class 'play.doc.CodeReferenceParser' for rule method analysis
	at org.parboiled.transform.AsmUtils.getClassForInternalName(AsmUtils.java:82) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.AsmUtils.isAssignableTo(AsmUtils.java:294) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.AsmUtils.isCallOnContextAware(AsmUtils.java:344) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.InstructionGraphNode.<init>(InstructionGraphNode.java:57) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.RuleMethod.setGraphNode(RuleMethod.java:198) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.RuleMethodInterpreter.createNode(RuleMethodInterpreter.java:100) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.RuleMethodInterpreter.naryOperation(RuleMethodInterpreter.java:87) ~[parboiled-java-1.1.5.jar:na]
	at org.parboiled.transform.RuleMethodInterpreter.naryOperation(RuleMethodInterpreter.java:37) ~[parboiled-java-1.1.5.jar:na]
	at org.objectweb.asm.tree.analysis.Frame.execute(Unknown Source) ~[asm-analysis-4.1.jar:4.1]
	... 60 common frames omitted
Caused by: java.lang.ClassNotFoundException: play.doc.CodeReferenceParser
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_25]
	at org.parboiled.transform.AsmUtils.getClassForInternalName(AsmUtils.java:80) ~[parboiled-java-1.1.5.jar:na]
	... 68 common frames omitted

**Comment by cchantep** [comment]
Hi, please use the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask for help. This github tracker is for confirmed issue. Best regards.
