### ISSUE TITLE
Compile-time DI causes evolutions to not auto-apply

### ISSUE THREAD

**Issue by khy** [playframework/playframework#5093]
I pushed a repository exhibiting this issue here: https://github.com/khy/play-evolutions-issue

When using compile-time DI, Play does not auto-apply evolutions, despite being configured to do so. Switching to runtime DI fixes the problem.

With the linked app running and the configured database freshly created, `curl -XPOST http://localhost:9000/people/kevin` causes the following error:
```
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
org.postgresql.util.PSQLException: ERROR: relation "people" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365) ~[postgresql-9.3-1102-jdbc4.jar:na]
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[HikariCP-java6-2.3.7.jar:na]
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java) ~[HikariCP-java6-2.3.7.jar:na]
	at slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$internalInsert$1.apply(JdbcInsertInvokerComponent.scala:190) ~[slick_2.11-3.0.1.jar:na]
	at slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$internalInsert$1.apply(JdbcInsertInvokerComponent.scala:187) ~[slick_2.11-3.0.1.jar:na]
```
By commenting out the following line in `conf/application.conf`,
```
play.application.loader = init.ApplicationLoader
```
 the evolution runs and the endpoint behaves as expected.

I think it's worth noting that I needed to make the following change in order to avoid `InstantiationException`s when Play loads the configuration or the Slick API: https://github.com/khy/play-evolutions-issue/commit/fb983857215ec2c7d3114d830291d059f8edbc16. Maybe I did something wrong there?

**Comment by jroper** [comment]
The reason for this is that it's the responsibility of the application loader to execute the evolutions.  When using Guice, Play configures Guice to eagerly instantiate the evolutions component, and this triggers the evolutions to start whenever the application is loaded.  But when you're using compile time DI, there is no framework that instantiates anything for you - it's your responsibility to instantiate and start everything that you need, and that includes evolutions.  Typically, this means in your `ApplicationLoader`, you instantiate the `play.api.db.evolutions.ApplicationEvolutions` component, possibly by simply referencing it (if using `play.api.db.evolutions.EvolutionsComponents`, it's a `lazy val`, and so you should simply reference it to trigger eager instantiation, eg:

```scala
components.applicationEvolutions
```

when you want to start it.  A better option might be to override the `DbApi` definition, such that you provide your own that delegates to the actual one. This can also be responsible for invoking the application evolutions.  By doing this, you ensure that nothing can access the `DbApi` until the evolutions have been run.
