### ISSUE TITLE
Play 2.4 - acceptAnyCertificate doesn't work

### ISSUE THREAD

**Issue by doula78** [playframework/playframework#5105]
Hi,

I want to use the WS functionnality without check certificates.
In my application.conf file, I have :
play.ws.ssl.loose.acceptAnyCertificate = true

But when I execute the code, I have this error :
```
[info] play.api.Play$ - Application started (Dev)
[info] application - [/getGroups] call
[warn] p.a.l.w.n.NingAsyncHttpClientConfigBuilder - buildHostnameVerifier: disabling hostname verification
[error] application -

! @6nf7cp88g - Internal server error, for (GET) [/test] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ConnectException: General SSLEngine problem]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:254) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[play_2.11-2.4.0.jar:2.4.0]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.0.jar:2.4.0]
        at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-
.4.0.jar:2.4.0]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.0.jar:2.4.0]
        at play.core.j.JavaGlobalSettingsAdapter$$anonfun$onError$2.apply(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.0.jar:2.4.0]
        at scala.Option.getOrElse(Option.scala:121) [scala-library-2.11.6.jar:na]
        at play.core.j.JavaGlobalSettingsAdapter.onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.0.jar:2.4.0]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.0.jar:2.4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-nett
-server_2.11-2.4.0.jar:2.4.0]
Caused by: java.net.ConnectException: General SSLEngine problem
        at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.2
.jar:na]
        at com.ning.http.client.providers.netty.request.NettyConnectListener.access$200(NettyConnectListener.java:37) ~[async-http-client-1.9.21.jar:
a]
        at com.ning.http.client.providers.netty.request.NettyConnectListener$1.operationComplete(NettyConnectListener.java:101) ~[async-http-client-1
9.21.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1460) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1314) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3.10.3.Final.jar:na]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1421) ~[na:1.8.0_40]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[na:1.8.0_40]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[na:1.8.0_40]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[na:1.8.0_40]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_40]
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310) ~[netty-3.10.3.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.3.Final.jar:na]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_40]
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728) ~[na:1.8.0_40]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304) ~[na:1.8.0_40]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_40]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478) ~[na:1.8.0_40]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[na:1.8.0_40]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969) ~[na:1.8.0_40]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:909) ~[na:1.8.0_40]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:906) ~[na:1.8.0_40]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_40]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable t
 find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[na:1.8.0_40]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.8.0_40]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_40]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_40]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[na:1.8.0_40]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[na:1.8.0_40]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1465) ~[na:1.8.0_40]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[na:1.8.0_40]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:969) ~[na:1.8.0_40]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:909) ~[na:1.8.0_40]
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145) ~[na:1.8.0_40]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131) ~[na:1.8.0_40]
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_40]
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[na:1.8.0_40]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.8.0_40]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_40]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_40]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[na:1.8.0_40]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[na:1.8.0_40]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1465) ~[na:1.8.0_40]
```

I use Play 2.4 with Java 1.8.40.

Thanks.

**Comment by chua-mbt** [comment]
The conf flags don't seem to work. We've also attempted to pass an SSLLooseConfig instance to the NingAsyncHttpClientConfigBuilder constructor, and to directly set the loose config on the builder. Both have failed. We get a handshake_failure for a very specific domain that uses TLS 1.2/RSA/RC4_128/HMAC-SHA1.

**Comment by schmitch** [comment]
same issue here tried against multiple servers.

**Comment by chua-mbt** [comment]
It's not a parsing issue in play. The flags are correctly parsed by the time the config is being built in NingAsyncHttpClientConfigBuilder. I overrode the call from within configureSSL finside play's builder and the handshake is still failing.

```scala
def configureSSL(sslConfig: SSLConfig) {
    ...
//    builder.setAcceptAnyCertificate(sslConfig.loose.acceptAnyCertificate)
    builder.setAcceptAnyCertificate(true)
    ...
}
```

Might be a bug from further  upstream (AsyncHttpClient)?

**Comment by wsargent** [comment]
Looks like a dup of https://github.com/playframework/playframework/issues/4796

**Comment by schmitch** [comment]
@jroper or @wsargent I don't know but after investigating #4796 looks differently. Currently accentAnyCertificate just won't work, neither in 2.4 nor in 2.5 even with the https://github.com/playframework/playframework/commit/f35dd0946fb84c8eee623b0e3d3cdee3226118a6
could you further look into it please? a basic test is really simple, have a JDK without any certificate and make a request with the default WS Client.
However the ```NingAsyncHttpClientConfigBuilder``` looks broken, since when setting it manually with NingAsyncHttpClientConfigBuilder it won't work, but if you set the ```AsyncHttpClientConfigBean``` it will starts working immediatly.

**Comment by cpoissonnier** [comment]
I agree with @schmitch, it doesn't seem to be a duplicate of #4796.

I'm currently migrating from 2.2.3 to 2.4.6 and it's impossible for me to connect to a CAS server, even if it was possible in the older version, and I'm following the instructions of the migration guide (ie. ` ws.acceptAnyCertificate = true` -> ` play.ws.ssl.loose.acceptAnyCertificate = true`)

**Comment by mbseid** [comment]
I also ran into this issue while using Play 2.4.6. I was able to work around it by using the following snippet:

```
  val config = new AsyncHttpClientConfigBean()
  config.setAcceptAnyCertificate(true)
  config.setFollowRedirect(true)
  val client = NingWSClient(config)
```

**Comment by schmitch** [comment]
Actually there is a way to rebind the play-ws client (under 2.5) you could do something along these:

```scala
@Singleton
class AcceptAllAhcWSAPI @Inject()(lifecycle: ApplicationLifecycle)(implicit materializer: Materializer) extends WSAPI {
  private val logger = Logger(classOf[AhcWSAPI])

  private val context = SslContextBuilder.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build()
  private val builder = new DefaultAsyncHttpClientConfig.Builder

  private val config = builder.setAcceptAnyCertificate(true).setSslContext(context).build()

  lazy val client = {
    val innerClient = new AhcWSClient(config)

    lifecycle.addStopHook { () =>
      Future.successful(innerClient.close())
    }

    innerClient
  }

  def url(url: String) = client.url(url)

}


class AcceptAllWSClientProvider @Inject()(wsApi: WSAPI) extends Provider[WSClient] {

  override def get(): WSClient = wsApi.client

}

class AcceptAllAhcWSModule extends Module {

  override def bindings(environment: Environment, configuration: Configuration): Seq[Binding[_]] = Seq(
    bind[WSAPI].to[AcceptAllAhcWSAPI],
    bind[WSClient].toProvider[AcceptAllWSClientProvider].in[Singleton]
  )

}
```

And then rebind them with a reference.conf:
```
play.modules.disabled += "play.api.libs.ws.ahc.AhcWSModule"
play.modules.disabled += "play.api.libs.openid.OpenIDModule"
play.modules.enabled += "AcceptAllAhcWSModule"
```

it disables OpenID and actually this is the Scala version, but I have a java version aswell.
```
setAcceptAnyCertificate(true)
```
Just setting this won't work always.

Guessing why play's setAcceptAnyCertificate doesn't work:
Play set's a SslContext (for Netty) and setAcceptAnyCertificate doesn't work with that context.
