### ISSUE TITLE
Really newbie error on Scala Activator play-scala-intro

### ISSUE THREAD

**Issue by ryantheleach** [playframework/playframework#5112]
I'm sorry for the newbie error report, but this is my first time using scala with activator rather then toy workbook projects.

Using IntelliJ's wizard to create a new SBT activator project on windows and using https://github.com/playframework/playframework/tree/master/templates/play-scala-intro

SBT fails to build the project due to missing dependencies.

Error:Error while importing SBT project:
...
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] sbt.ResolveException: unresolved dependency: org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1: configuration not found in org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1: 'master(compile)'. Missing configuration: 'compile'. It was required from com.typesafe.play#play_2.11;2.4.3 compile
[error] unresolved dependency: org.scala-lang.modules#scala-xml_2.11;1.0.2: configuration not found in org.scala-lang.modules#scala-xml_2.11;1.0.2: 'master(compile)'. Missing configuration: 'compile'. It was required from org.scalaz#scalaz-core_2.11;7.1.1 compile
[error] Use 'last' for the full log.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0

See complete log in C:\Users\Ryan\.IntelliJIdea14\system\log\sbt.last.log

Am I using the wrong version of scala or something or is this genuinely an issue.

**Comment by cchantep** [comment]
Hi, please use the [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask question and get help. Best regards.

**Comment by ryantheleach** [comment]
So it's not an issue with the activator config and something my end? ok.
