### ISSUE TITLE
Why having null configuration values?

### ISSUE THREAD

**Issue by pauldijou** [playframework/playframework#5141]
Play set some configuration values to `null` as default value (for example, the `play.http.session.maxAge`, [here](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/resources/reference.conf#L98). Is there any good reason to do that rather than not having any value at all?

When trying to access such key with a Configuration object, not having set this key inside my `application.conf`, I was excepting a `None` but I got a `ConfigException` because the SimpleConfig will throw if `null` is found when trying to read a key.

Wouldn't it be better to remove all keys having a hardcoded `null` value and check for their presence rather than their null value? I don't really know what Play is doing internally but it's rather problematic to have such exceptions popping around rather than just having a `None` returned.

```
Caused by: com.typesafe.config.ConfigException$Null: reference.conf @ jar:file:/home/paul/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.4.3.jar!/reference.conf: 98: Configuration key 'play.http.session.maxAge' is set to null but expected STRING
	at com.typesafe.config.impl.SimpleConfig.throwIfNull(SimpleConfig.java:138) ~[config-1.3.0.jar:na]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184) ~[config-1.3.0.jar:na]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189) ~[config-1.3.0.jar:na]
	at com.typesafe.config.impl.SimpleConfig.getDuration(SimpleConfig.java:305) ~[config-1.3.0.jar:na]
	at play.api.Configuration$$anonfun$getMilliseconds$1.apply$mcJ$sp(Configuration.scala:294) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Configuration$$anonfun$getMilliseconds$1.apply(Configuration.scala:294) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Configuration$$anonfun$getMilliseconds$1.apply(Configuration.scala:294) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Configuration.readValue(Configuration.scala:215) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Configuration.getMilliseconds(Configuration.scala:294) ~[play_2.11-2.4.3.jar:2.4.3]
```

**Comment by jroper** [comment]
See https://github.com/typesafehub/config/issues/282 for a discussion of why things are the way they are.

**Comment by pauldijou** [comment]
Thanks for the link @jroper , didn't know about that.

Ok, so you need `null`, I can understand that, but is it ok for the Play Scala layer to behave like that? It's basically a NullPointerException at runtime, that kind of defeat the point of having an `Option` for all Configuration methods.

I'm really concerned because it means that removing a value from `application.conf` might lead to runtime exception while you would just expect a `None`. If you need to differentiate between missing the key and having a `null` value, shouldn't Configuration methods return `Try[Option[T]]` ? For me, NPE at runtime is a Java world problem, not a Scala one.

My other concern is that I've built a JWT Scala lib to store the session inside a HTTP header and I'm using some configuration values. Does it mean I should wrap all my calls to Configuration methods in a try/catch in case such keys receive a `null` inside a `reference.conf` at some point in the future?

For example, there is an expiration property inside JWT token, but it's optional. So the idea was like "If there is a play.http.session.maxAge inside application.conf, use it as expiration, otherwise don't put any expiration". But if people decide not to have an expiration, so not having the key, Play will set a `null` value, couldn't find a way to undo that, and, obviously, my lib will crash because of the exception.

**Comment by jroper** [comment]
You're right, and we do have a plan for how to address this, it's here:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/Configuration.scala#L933

Our plan is to deprecate `Configuration`, and replace it with `PlayConfig`, which implements the new patterns.  This API is currently private because we wanted to give it some battle testing before committing to a new API.  In Play 2.5 we will open it up, and deprecate `Configuration`.

**Comment by pauldijou** [comment]
Thanks for the info, will add try/catch wrapper until this new API land in Play.
