### ISSUE TITLE
War plugin is not getting download for play 2.1.5 

### ISSUE THREAD

**Issue by kanchu1708** [playframework/playframework#5150]
I have followed this link 
https://github.com/play2war/play2-war-plugin/wiki/Configuration

My file's content:
Plugin.sbt
addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.0.2")

build.sbt:
import com.github.play2war.plugin._
import sbt._
import Keys._
import play.Project._

version := "1.0-SNAPSHOT"

Play2WarPlugin.play2WarSettings

Play2WarKeys.servletVersion := "3.1"

libraryDependencies +={
"commons-codec" % "commons-codec" % "1.10"
}

this is what I am getting in my play server
C:\Users\kancgupt\testDemo>play reload

[info] Loading project definition from C:\Users\kancgupt\testDemo\project
[warn]  module not found: com.github.play2war#play2-war-plugin;1.0.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.play2war/play
2-war-plugin/scala_2.9.2/sbt_0.12/1.0.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.
github.play2war/play2-war-plugin/scala_2.9.2/sbt_0.12/1.0.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Program Files\play-2.1.5\play-2.1.5\repository\local\com.github.play
2war\play2-war-plugin\scala_2.9.2\sbt_0.12\1.0.2\ivys\ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/play2war/play2-wa
r-plugin_2.9.2_0.12/1.0.2/play2-war-plugin-1.0.2.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/play2war/play2-war-plugin_2.9.
2_0.12/1.0.2/play2-war-plugin-1.0.2.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.play2war#play2-war-plugin;1.0.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that th
ese dependencies exist with the requested attributes.
[warn]          com.github.play2war:play2-war-plugin:1.0.2 (sbtVersion=0.12, sca
laVersion=2.9.2)
[warn]
sbt.ResolveException: unresolved dependency: com.github.play2war#play2-war-plugi
n;1.0.2: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
        at sbt.IvySbt.liftedTree1$1(Ivy.scala:49)
        at sbt.IvySbt.action$1(Ivy.scala:49)
        at sbt.IvySbt$$anon$3.call(Ivy.scala:58)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:75)
        at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:
79)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
        at xsbt.boot.Locks$.apply0(Locks.scala:30)
        at xsbt.boot.Locks$.apply(Locks.scala:27)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:58)
        at sbt.IvySbt.withIvy(Ivy.scala:99)
        at sbt.IvySbt.withIvy(Ivy.scala:95)
        at sbt.IvySbt$Module.withModule(Ivy.scala:114)
        at sbt.IvyActions$.update(IvyActions.scala:121)
        at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:951)
        at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:949)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:9
72)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:9
70)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:974)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:969)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:977)
        at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:856)
        at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:853)
        at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
        at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structu
re.scala:311)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structu
re.scala:311)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
        at sbt.std.Transform$$anon$5.work(System.scala:71)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:23
2)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:23
2)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:238)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestric
tions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:47
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.play2
war#play2-war-plugin;1.0.2: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?  quit

can Some one  tell me what I am missing?

**Comment by dotta** [comment]
@kanchu1708 Looks like you are missing a resolver (see the documentation you linked, `resolvers += "Play2war plugins release" at "http://repository-play-war.forge.cloudbees.com/release/"`). In the future (or if you need more help with the play-war-plugin), please ask usage questions in the [play mailing-list](https://groups.google.com/forum/#!forum/play-framework).

**Comment by kanchu1708** [comment]
After adding resolver  also same error I am getting .

**Comment by dotta** [comment]
@kanchu1708 As hinted in my previous message, please follow up in the playframework mailing list. This issue tracker is for keeping track of defects/enhancements, and is not the appropriate place for discussing usage issues. Furthermore, the play2-war-plugin is not maintained by us.
