### ISSUE TITLE
error in using play 2.4.3 with windows7

### ISSUE THREAD

**Issue by kanchu1708** [playframework/playframework#5154]
at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
 at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
 at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
 at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
 at sbt.BuildLoader.apply(BuildLoader.scala:140)
 at sbt.Load$.loadAll(Load.scala:334)
 at sbt.Load$.loadURI(Load.scala:289)
 at sbt.Load$.load(Load.scala:285)
 at sbt.Load$.load(Load.scala:276)
 at sbt.Load$.apply(Load.scala:130)
 at sbt.Load$.defaultLoad(Load.scala:36)
 at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
 at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
 at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
 at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
 at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
 at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
 at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
 at sbt.Command$.process(Command.scala:93)
 at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
 at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
 at sbt.State$$anon$1.process(State.scala:184)
 at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
 at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
 at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
 at sbt.MainLoop$.next(MainLoop.scala:98)
 at sbt.MainLoop$.run(MainLoop.scala:91)
 at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
 at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
 at sbt.Using.apply(Using.scala:24)
 at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
 at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
 at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
 at sbt.MainLoop$.runLogged(MainLoop.scala:24)
 at sbt.StandardMain$.runManaged(Main.scala:53)
 at sbt.xMain.run(Main.scala:28)
 at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
 at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
 at xsbt.boot.Launch$.run(Launch.scala:109)
 at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
 at xsbt.boot.Launch$.launch(Launch.scala:117)
 at xsbt.boot.Launch$.apply(Launch.scala:18)
 at xsbt.boot.Boot$.runImpl(Boot.scala:41)
 at xsbt.boot.Boot$.main(Boot.scala:17)
 at xsbt.boot.Boot.main(Boot.scala)
 java.lang.UnsupportedClassVersionError: org/webjars/WebJarExtractor$Cache : Unsupported major.minor version 51.0
 Use 'last' for the full log.
 loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

after creating project I am doing sbt then I am getting above error 
even in my system only java 1.8 is installed and path is also correct pointing to 1.8 only , don't know why getting this error. can some one tell me what I am doing wrong?

**Comment by dotta** [comment]
@kanchu1708 Please, discuss usage question in the [playframework mailing list](https://groups.google.com/forum/#!forum/play-framework).
