### ISSUE TITLE
java.lang.OutOfMemoryError: Metaspace - play 2.4.3

### ISSUE THREAD

**Issue by hepin1989** [playframework/playframework#5180]
after several ```run``` & ```Ctrl + D```
```
java.lang.OutOfMemoryError: Metaspace
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at scala.runtime.AbstractFunction2.<init>(AbstractFunction2.scala:12)
	at scala.collection.immutable.MapLike$$anonfun$$plus$plus$1.<init>(MapLike.scala:88)
	at scala.collection.immutable.MapLike$class.$plus$plus(MapLike.scala:88)
	at scala.collection.immutable.AbstractMap.$plus$plus(Map.scala:194)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:65)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:61)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:60)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:223)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)

```

**Comment by hepin1989** [comment]
https://github.com/playframework/playframework/issues/4617

**Comment by wsargent** [comment]
You are probably running into a resource leak in your application -- this is very common if you are using resources outside the scope of Play's lifecycle and do not have an ApplicationLifecycle hook that will release the resource when Play restarts (which is what happens in "activator run").

https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection#Stopping/cleaning-up

**Comment by hepin1989** [comment]
@wsargent maybe not,after I run ```clean``` then it works again for awhile.the only resource I am using is the ```svnkit``` but it don't have any specified lifecycle I think.I will try to detect the real cause later.

**Comment by wsargent** [comment]
It's not impossible it could be https://github.com/playframework/playframework/issues/4649 but generally speaking this is application based.

**Comment by nafg** [comment]
I would put some blame on the fact that the sbt script sets a max metaspace
amount, which is unnecessary.
Before java 8, with perm gen, the default was limited, so the sbt script
sets a default so it's not too low. But with java 8 metaspace, the default
is unlimited, and there's no need for the sbt script to change that. I
think it does because someone did a mechanical update to it.

**Comment by hepin1989** [comment]
I found I maybe need to call ```    void dispose();``` on ```SVNClient``` when the actor is ```postStop```

**Comment by jroper** [comment]
@nafg The default is not unlimited unless you have an infinite amount of RAM.  The change in Java 8 is that instead of allocating memory for class meta data out of a pool managed by the JVM, memory is allocated directly using malloc from the system.  What that means is if you have a memory leak, the JVM will continue to allocate more and more memory from the system, eventually it will start allocating out of swap, and your system will slow to a crawl, and then eventually your system will run out of virtual memory, and then random things on your system will start crashing.  Which is better, crashing your entire system because of a memory leak in sbt, or crashing sbt because of a memory leak in sbt?  This is why we configure max metaspace, it means sbt is only capable of crashing itself, not the entire OS.

**Comment by hepin1989** [comment]
that call ```dispose()``` will release the native peer of it,I think that may be a leak when I do the reloading but don't release that .

**Comment by nanothermite** [comment]
Please note that I just got this on play 2.4.6 as well:

Caused by: java.lang.OutOfMemoryError: Metaspace                                                                                
        at java.lang.ClassLoader.defineClass1(Native Method)                                                                    
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)                                                              
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)                                              
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)                                                         
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)                                                           
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)                                                               
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)                                                               
        at java.security.AccessController.doPrivileged(Native Method)                                                           
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)                                                           
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)                                                                
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)                                                                
        at play.api.inject.DefaultApplicationLifecycle$$anonfun$stop$1$$anonfun$apply$3.apply(ApplicationLifecycle.scala:95)    
        at play.api.inject.DefaultApplicationLifecycle$$anonfun$stop$1$$anonfun$apply$3.apply(ApplicationLifecycle.scala:94)    
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)                                                   
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)                                                   
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)                                                         
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)                                             
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)                                            
        at scala.concurrent.impl.Promise$KeptPromise.onComplete(Promise.scala:333)                                              
        at scala.concurrent.Future$class.flatMap(Future.scala:249)                                                              
        at scala.concurrent.impl.Promise$KeptPromise.flatMap(Promise.scala:322)                                                 
        at play.api.inject.DefaultApplicationLifecycle$$anonfun$stop$1.apply(ApplicationLifecycle.scala:94)                     
        at play.api.inject.DefaultApplicationLifecycle$$anonfun$stop$1.apply(ApplicationLifecycle.scala:93)                     
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)                                     
        at scala.collection.immutable.List.foldLeft(List.scala:84)                                                              
        at play.api.inject.DefaultApplicationLifecycle.stop(ApplicationLifecycle.scala:93)                                      
        at play.api.DefaultApplication.stop(Application.scala:256)                                                              
        at play.api.Play$$anonfun$stop$1.apply(Play.scala:111)                                                                  
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)                                                         
        at play.api.Play$.stop(Play.scala:107)                                                                                  
        at play.core.server.NettyServer$$anonfun$stop$1.apply(NettyServer.scala:159)                                            
        at play.core.server.NettyServer$$anonfun$stop$1.apply(NettyServer.scala:159)                                            
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace 

So presumably if I run from the dist, the sbt memory leak would not be an issue?

Thanks,
Henry

**Comment by wsargent** [comment]
> So presumably if I run from the dist, the sbt memory leak would not be an issue?

This is correct.  It's an artifact of hot-reloading.
