### ISSUE TITLE
Raw Body Parser not works correctly for large file

### ISSUE THREAD

**Issue by b0c1** [playframework/playframework#5230]
If the raw body parser exceed the memory limit it will create temporary file, but this not work correctly.
When I run parse.raw in my application for big request I got:
```text
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[InstantiationException: play.api.libs.Files$DefaultTemporaryFileCreator]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [play-netty-server_2.11-2.4.3.jar:2.4.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [play-netty-server_2.11-2.4.3.jar:2.4.3]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.11.7.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [play-iteratees_2.11-2.4.3.jar:2.4.3]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [play-iteratees_2.11-2.4.3.jar:2.4.3]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [scala-library-2.11.7.jar:na]
Caused by: java.lang.InstantiationException: play.api.libs.Files$DefaultTemporaryFileCreator
	at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_60]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.3.jar:2.4.3]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.7.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[play_2.11-2.4.3.jar:2.4.3]
Caused by: java.lang.NoSuchMethodException: play.api.libs.Files$DefaultTemporaryFileCreator.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_60]
	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_60]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.3.jar:2.4.3]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.7.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:234) ~[play_2.11-2.4.3.jar:2.4.3]
```

The error start from  backToTemporaryFile() in RawBuffer push method.

Scala: 2.11
Play version: 2.4.3
OS: Windows
The application using macwire not guice...

**Comment by gmethvin** [comment]
I think this was fixed by #4925 but it wasn't backported to 2.4.

As a workaround, see https://gist.github.com/Timshel/b39f7ca724b16a7eb01e

**Comment by richdougherty** [comment]
I've created a PR to backport the fixes to 2.4: #5248.

**Comment by mkurz** [comment]
@richdougherty This issue can be closed (?)

**Comment by richdougherty** [comment]
Yes this is fixed. A Play 2.4.4 release with the fix should happen today.

**Comment by maxcan** [comment]
I'm still seeing this error on play 2.4.4 and 2.4.6.
