### ISSUE TITLE
[2.4.3 - java] Correction in commented section of plugins.sbt

### ISSUE THREAD

**Issue by harsh00008** [playframework/playframework#5283]
plugins.sbt in the commented section about ebean says the following:
```
// Play Ebean support, to enable, uncomment this line, and enable in your build.sbt using
// enablePlugins(SbtEbean). Note, uncommenting this line will automatically bring in
// Play enhancer, regardless of whether the line above is commented out or not.
```
This should be PlayEbean instead of SbtEbean.Enabling with SbtEbean gives error:
```
lazy val root = (project in file(".")).enablePlugins(PlayJava, SbtEbean)
                                                               ^
sbt.compiler.EvalException: Type error in expression
	at sbt.compiler.Eval.checkError(Eval.scala:384)
	at sbt.compiler.Eval.compileAndLoad(Eval.scala:183)
	at sbt.compiler.Eval.evalCommon(Eval.scala:152)
	at sbt.compiler.Eval.evalDefinitions(Eval.scala:122)
	at sbt.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:271)
	at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:109)
	at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:712)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:717)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:716)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:58)
	at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:716)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Load$.loadFiles$1(Load.scala:723)
	at sbt.Load$.discoverProjects(Load.scala:734)
	at sbt.Load$.discover$1(Load.scala:545)
	at sbt.Load$.loadTransitive(Load.scala:574)
	at sbt.Load$.loadProjects$1(Load.scala:442)
	at sbt.Load$.loadUnit(Load.scala:446)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:334)
	at sbt.Load$.loadURI(Load.scala:289)
	at sbt.Load$.load(Load.scala:285)
	at sbt.Load$.load(Load.scala:276)
	at sbt.Load$.apply(Load.scala:130)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
```

**Comment by wsargent** [comment]
Fixed in #5288
