### ISSUE TITLE
Error in custom provider, @6oa307m58: Configuration error

### ISSUE THREAD

**Issue by liuzhihai520** [playframework/playframework#5318]
play.api.UnexpectedException: Unexpected exception[ProvisionException: Unable to provision, see the following errors:

```
1) Error in custom provider, @6oa307m58: Configuration error
  while locating play.api.libs.CryptoConfigParser
  while locating play.api.libs.CryptoConfig
    for parameter 0 at play.api.libs.Crypto.<init>(Crypto.scala:282)
  at play.api.inject.BuiltinModule.bindings(BuiltinModule.scala:49):
Binding(class play.api.libs.Crypto to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating play.api.libs.Crypto

1 error]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [com.typesafe.play.play-netty-server_2.11-2.4.4.jar:2.4.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [com.typesafe.play.play-netty-server_2.11-2.4.4.jar:2.4.4]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.util.Try$.apply(Try.scala:191) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.util.Failure.recover(Try.scala:215) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.6.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play.play-iteratees_2.11-2.4.4.jar:2.4.4]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play.play-iteratees_2.11-2.4.4.jar:2.4.4]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.11.6.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.6.jar:na]
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, @6oa307m58: Configuration error
  while locating play.api.libs.CryptoConfigParser
  while locating play.api.libs.CryptoConfig
    for parameter 0 at play.api.libs.Crypto.<init>(Crypto.scala:282)
  at play.api.inject.BuiltinModule.bindings(BuiltinModule.scala:49):
Binding(class play.api.libs.Crypto to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating play.api.libs.Crypto

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[com.google.inject.guice-4.0.jar:na]
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.utils.InlineCache.apply(InlineCache.scala:55) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at scala.Option.fold(Option.scala:158) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at play.api.libs.Crypto$.crypto(Crypto.scala:43) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.libs.Crypto$.sign(Crypto.scala:67) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.CookieBaker$class.encode(Http.scala:504) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Session$.encode(Http.scala:653) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.CookieBaker$class.encodeAsCookie(Http.scala:556) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Session$.encodeAsCookie(Http.scala:653) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Result.withSession(Results.scala:170) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at controllers.CaptchaController$$anonfun$getCaptcha$1.apply(CaptchaController.scala:38) ~[trunk.trunk-1.0-SNAPSHOT-sans-externalized.jar:na]
        at controllers.CaptchaController$$anonfun$getCaptcha$1.apply(CaptchaController.scala:31) ~[trunk.trunk-1.0-SNAPSHOT-sans-externalized.jar:na]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at scala.Option.map(Option.scala:146) ~[org.scala-lang.scala-library-2.11.6.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[com.typesafe.play.play-iteratees_2.11-2.4.4.jar:2.4.4]
        at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741) ~[com.typesafe.play.play-iteratees_2.11-2.4.4.jar:2.4.4]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.11.6.jar:na]
        ... 6 common frames omitted
Caused by: play.api.PlayException: Configuration error[Application secret not set]
        at play.api.libs.CryptoConfigParser.get$lzycompute(Crypto.scala:236) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.libs.CryptoConfigParser.get(Crypto.scala:203) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at play.api.libs.CryptoConfigParser.get(Crypto.scala:197) ~[com.typesafe.play.play_2.11-2.4.4.jar:2.4.4]
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[com.google.inject.guice-4.0.jar:na]
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012) ~[com.google.inject.guice-4.0.jar:na]
        ... 40 common frames omitted
```

**Comment by benmccann** [comment]
I've edited your comment to make it more readable. Please see https://help.github.com/articles/github-flavored-markdown/ for tips on formatting

**Comment by benmccann** [comment]
The error says "Application secret not set". Have you actually set it?

I'm going to close this to help keep the issue tracker clean since there's no evidence that it's a bug in Play. If you have questions about usage, please try the mailing list or stackoverflow: https://www.playframework.com/get-involved. If this is indeed a bug in Play, then please feel free to reopen providing more details as to what the bug is
