### ISSUE TITLE
WSRequest doesn't timeout properly when a call hangs on SYN_SENT

### ISSUE THREAD

**Issue by oleg-gr** [playframework/playframework#5387]
WSRequest doesn't timeout properly when a call hangs on SYN_SENT.

I am trying to perform a request:
```
        WSRequest wsRequest = ws.url("http://google.com/")
                .setMethod("GET")
                .setRequestTimeout(3000);
```
Due to internal network set up some of the addresses by design are blocked (possibly on DNS level) so this call cannot go through (connection hangs on SYN_SENT). However, I still expect this request to timeout after 3000ms due to request timeout. Instead the future doesn't complete for more than 5 minutes:
```
[debug] - io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
[debug] - io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
[info] - play.api.Play - Application started (Prod)
[debug] - io.netty.util.internal.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.io.netty.channel.ChannelMatcher
[debug] - io.netty.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0xcebb6f043b7c5edf (took 0 ms)
[debug] - io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
[debug] - io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
[debug] - io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
[debug] - io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 4096
[info] - play.core.server.NettyServer - Listening for HTTP on /0.0.0.0:9555
[debug] - io.netty.util.internal.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.io.netty.handler.codec.http.HttpObjectMatcher
[debug] - io.netty.util.internal.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.io.netty.handler.codec.http.HttpRequestMatcher
[debug] - io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
[debug] - io.netty.util.internal.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.io.netty.handler.codec.http.HttpContentMatcher
[debug] - io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 1ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.pool.DefaultChannelPool - Closed 0 connections out of 0 in 0ms
[debug] - org.asynchttpclient.netty.channel.NettyConnectListener - Trying to recover from failing to connect channel [id: 0xa4228562] with a retry value of true
[debug] - org.asynchttpclient.netty.channel.NettyConnectListener - Failed to recover from connect exception: io.netty.channel.ConnectTimeoutException: connection timed out: google.com/173.194.117.233:80 with channel [id: 0xa4228562]
[warn] - application - External call failed with an exception
java.util.concurrent.CompletionException: java.net.ConnectException: connection timed out: google.com/173.194.117.233:80
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205) ~[na:1.8.0_31]
	at java.util.concurrent.CompletableFuture$AsyncWhenComplete.exec(CompletableFuture.java:653) [na:1.8.0_31]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_31]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902) [na:1.8.0_31]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689) [na:1.8.0_31]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644) [na:1.8.0_31]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [na:1.8.0_31]
Caused by: java.net.ConnectException: connection timed out: google.com/173.194.117.233:80
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133) ~[org.asynchttpclient.async-http-client-2.0.0-alpha14.jar:na]
	at org.asynchttpclient.netty.channel.NettyConnectListener.operationComplete(NettyConnectListener.java:143) ~[org.asynchttpclient.async-http-client-2.0.0-alpha14.jar:na]
	at org.asynchttpclient.netty.channel.NettyConnectListener.operationComplete(NettyConnectListener.java:39) ~[org.asynchttpclient.async-http-client-2.0.0-alpha14.jar:na]
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.operationComplete(NettyChannelConnector.java:53) ~[org.asynchttpclient.async-http-client-2.0.0-alpha14.jar:na]
	at org.asynchttpclient.netty.request.NettyChannelConnector$1.operationComplete(NettyChannelConnector.java:38) ~[org.asynchttpclient.async-http-client-2.0.0-alpha14.jar:na]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:222) ~[io.netty.netty-transport-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[io.netty.netty-transport-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[io.netty.netty-common-4.0.31.Final.jar:4.0.31.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_31]
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: google.com/173.194.117.233:80
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:220) ~[io.netty.netty-transport-4.0.31.Final.jar:4.0.31.Final]
	... 7 common frames omitted
```

**Comment by wsargent** [comment]
Hi @oleg-gr There are three timeout settings, and `withRequestTimeout` only sets one of them.  Can you check the others and confirm that request timeout is responsible?

```
play.ws.timeout.connection: The maximum time to wait when connecting to the remote host (default is 120 seconds).
play.ws.timeout.idle: The maximum time the request can stay idle (connection is established but waiting for more data) (default is 120 seconds).
play.ws.timeout.request: The total time you accept a request to take (it will be interrupted even if the remote host is still sending data) (default is 120 seconds).
```

https://www.playframework.com/documentation/2.4.x/ScalaWS#Configuring-Timeouts

**Comment by oleg-gr** [comment]
@wsargent I am aware of that, but I was under the impression, that setting `.setRequestTimeout(3000)` on each request will mean that this particular request's future will complete in 3000ms no matter what. Am I wrong in thinking this?

I am logging things before and after `wsRequest.execute()` so I can see that `wsRequest.execute()` returns a future and the controller also returns the future fine, it's just that the future returned by `wsRequest.execute()` completes in 5 minutes, and not in 3000ms that I am expecting.

Moreover, the configuration settings in application.conf for the timeouts are the following:
```
play {
  ws {
    timeout {
      connection = 30000
      idle = 30000
      request = 60000
    }
  }
}
```
Hope it makes sense. Is there something I am missing from the picture?

**Comment by slandelle** [comment]
Actually, AHC starts the request timeout timer after connection has been established or fetched from the pool.

**Comment by oleg-gr** [comment]
@slandelle Thanks for the response. In any case "play.ws.timeout.request: The total time you accept a request to take (it will be interrupted even if the remote host is still sending data) (default is 120 seconds)." would mean that every single request finishes in 60000ms which I don't think is the case in this particular case.

Any idea what would be an adequate way to make a request timeout with a specific timeout time no matter what (on a per request basis). Basically I want one request to timeout within 2000ms no mater anything, and another one in 3000ms no matter what happens

**Comment by wsargent** [comment]
Probably the easiest way to do "no matter what" is to use akka.pattern.after: http://doc.akka.io/docs/akka/current/scala/futures.html#After

**Comment by oleg-gr** [comment]
well, shouldn't `play.ws.timeout` setting kill the whole request no matter what though? If it's set at 60000, no request to the play application should ever take more than 1 minute in my understanding. This is clearly not the case in my app....

**Comment by wsargent** [comment]
> Any idea what would be an adequate way to make a request timeout with a specific timeout time no matter what (on a per request basis). Basically I want one request to timeout within 2000ms no mater anything, and another one in 3000ms no matter what happens

> well, shouldn't play.ws.timeout.request setting kill the whole request no matter what though

That's clearly not happening in this case, so "no matter what" involves stomping on the Future as a workaround.

One thing I note is that you have [org.asynchttpclient.async-http-client-2.0.0-alpha14.jar:na] in your stack trace.  If you're using Play 2.4.x, then your AHC version should be 1.9.21:

https://github.com/playframework/playframework/blob/2.4.x/framework/project/Dependencies.scala#L273

So you're using an alpha version of AHC 2.0.x somehow, which I would not have thought was even binary compatible with Play 2.4.x.   Can you install https://github.com/jrudolph/sbt-dependency-graph or https://github.com/gilt/sbt-dependency-graph-sugar and ensure that AHC 2.0.0 is not loaded?

**Comment by oleg-gr** [comment]
@wsargent sorry, I didn't mention it, but I am using 2.5.0-M1

**Comment by oleg-gr** [comment]
> That's clearly not happening in this case, so "no matter what" involves stomping on the Future as a workaround.

Well the question is shouldn't it happen? Is this expected behaviour?

**Comment by wsargent** [comment]
> Well the question is shouldn't it happen? Is this expected behaviour?

You're using a M1 build containing a reference to an alpha AHC -- this is unreleased software and unreleased software has bugs in it.  The expected behavior is that things will not work.  If you're not a contributor or a bug reporter, you should be using 2.4.x.

**Comment by slandelle** [comment]
Making things clear: AHC used to start counting for request timeout after DNS resolution and connect.
This behavior has always been the same since first versions of AHC and nobody complained, as your use case is very specific (I can't say if it's even legit).

Then, [I just changed it today](https://github.com/AsyncHttpClient/async-http-client/issues/1060). So next release candidates of AHC 2 will ship it, and so will the Play 2.1 milestones eventually.

**Comment by oleg-gr** [comment]
Forgot to reply to this.

@wsargent You are right. Sorry I forgot to mention it wasn't 2.4.x so you wasted time trying to reproduce the issue. I actually haven't tried in 2.4.x so I don't know if the problem is present in AHC before version 2. Still thought it would be better to mention this on a milestone build before it gets released and only then reporting it (assuming it goes unfixed/unnoticed). Will provide run down of my env next time I report any issues on milestone builds.

@slandelle Thank you for the response. I agree that the case is very specific. Though I still think starting the timeout timer right away even before the DNS resolution sounds more right (in terms of expected behaviour). Thanks for the fix.
