### ISSUE TITLE
NamedEhCacheProvider doesn't allow explicitly configured cache attributes

### ISSUE THREAD

**Issue by varju** [playframework/playframework#5443]
https://www.playframework.com/documentation/2.4.x/ScalaCache states that additional caches can be configured by creating a custom ehcache.xml.  It also indicates that you should list these caches in play.cache.bindCaches and use the NamedCache qualifier to access these caches.  This doesn't appear to work as documented (tested with Play 2.4.6).

I've defined a custom ehcache.xml:

```
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ehcache.org/ehcache.xsd" updateCheck="false">

  <defaultCache
    maxEntriesLocalHeap="10000"
    eternal="false"
    timeToIdleSeconds="120"
    timeToLiveSeconds="120"
    overflowToDisk="false"
    maxElementsOnDisk="10000000"
    diskPersistent="false"
    diskExpiryThreadIntervalSeconds="120"
    memoryStoreEvictionPolicy="LRU" />

  <cache name="my-cache"
    maxEntriesLocalHeap="10000" />

</ehcache>
```

In application.conf, I've listed this cache:

```
play.cache.bindCaches = ["my-cache"]
```

And from my code I've wired the cache up:

```
class Test @Inject()(@NamedCache("my-cache") cache: CacheApi)
```

If I try to start the application with this configuration, it blows up:

```
Caused by: net.sf.ehcache.ObjectExistsException: Cache my-cache already exists
  at net.sf.ehcache.CacheManager.addCache(CacheManager.java:1171)
  at play.api.cache.NamedEhCacheProvider.get$lzycompute(Cache.scala:208)
```

If I remove the custom cache definitions from ehcache.xml, things work, but this means I cannot set custom attributes on individual caches.

At first glance it seems like the code should be changed to something more like this:

```
diff --git a/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala b/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala
index d55bb23..970a40a 100644
--- a/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala
+++ b/framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala
@@ -205,8 +205,10 @@ class CacheManagerProvider @Inject() (env: Environment, config: Configuration, l
 private[play] class NamedEhCacheProvider(name: String) extends Provider[Ehcache] {
   @Inject private var manager: CacheManager = _
   lazy val get: Ehcache = {
-    manager.addCache(name)
-    manager.getEhcache(name)
+    Option(manager.getEhcache(name)).getOrElse {
+      manager.addCache(name)
+      manager.getEhcache(name)
+    }
   }
 }

```

**Comment by gmethvin** [comment]
@varju Yeah, it looks it should be using the configuration from `ehcache.xml`. That seems unintentional.

In addition to the change you mentioned, I think it would be useful to automatically bind caches defined in `ehcache.xml`. It doesn't make sense to me that you'd have to configure your caches in two places. Similar to how we moved logback configuration to `logback.xml`, I think it should be possible to configure ehcache solely with `ehcache.xml`.

**Comment by marklieberman** [comment]
I'm a Java guy, but I've worked around this issue like so:

```
/**
 * Bind named caches using configuration in ehcache.xml.
 * 
 * <p>Define a named cache in ehcache.xml and Ehcache will automatically instantiate the cache at runtime. However,
 * this cache is unknown to the Play cache plugin and is not accessible using {@code @NamedCache}. You must bind a
 * reference to the named cache using {@link CacheModule#bindCustomCache(String)}.
 * 
 * <p>Do not add the named cache to {@code play.cache.bindCaches} in configuration. Caches bound in this manner are
 * programmatically added by the Play cache plugin at runtime. The cache plugin will always copy settings from the
 * default cache, limiting the usefulness of named caches.
 */
public class CacheModule extends AbstractModule {
	
	@Override
	protected void configure() {
		bindCustomCache("tenants");
		bindCustomCache("user-agent");
		bindCustomCache("geo-ip");
		bindCustomCache("full-contact");
	}
	
	/**
	 * Bind a named cache that is defined in ehcache.xml.
	 * 
	 * @param name The name of the cache.
	 */
	private void bindCustomCache(String name) {
		bind(CacheApi.class)
				.annotatedWith(new NamedCacheImpl(name))
				.toProvider(new Provider<CacheApi>() {

					@Inject
					CacheManager cacheManager;
					
					@Override
					public CacheApi get() {
						Cache cache = cacheManager.getCache(name);
						if (cache == null) {
							throw new RuntimeException("Cache named '" + name + "' must be defined in ehcache.xml");
						}
						return new DefaultCacheApi(new EhCacheApi(cache));
					} 
					
				})
				.asEagerSingleton();
	}
	
}
```

I create my named caches in `ehcache.xml` and just have to add a one line `bindCustomCache()` to the configure method.
