### ISSUE TITLE
[2.4.6] Proxy setting not taken into account with ws

### ISSUE THREAD

**Issue by nojkan** [playframework/playframework#5775]
### Are you looking for help?

Proxy settings are not taken into account : 
as mentionned here : https://groups.google.com/forum/#!searchin/play-framework/proxy/play-framework/kAtn5OEc9ns/MWg54RMHBwAJ
### Play Version (2.5.x / etc)

2.4.6
### API ( Java )

Java 8 compiled version
### Operating System (Ubuntu 14.04 TLS)

Ubuntu 14.04 TLS
Use `uname -a` if on Linux.
Linux ezarb 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
### JDK (OpenJDK 1.8.0) / compiled

java -version : javac 1.8.0-internal
java - full version :+1: openjdk full version "1.8.0-internal-root_2016_02_12_15_01-b00"
### Library Dependencies

N/A
## Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1.play request an external https service www.google.fr through an entreprise proxy 
2.contact the proxy regarding proxy param settings
3.connect the external service
### Actual Behavior

Play application is not able to reach external www service throught the proxy. => exception : no route to host

Play doesn't try to contact the proxy which is configured 
### trying  with application.conf params as

play.ws.useProxyProperties=true
play.ws.http.proxyHost=10.236.240.71
play.ws.http.proxyPort=3128
play.ws.https.proxyHost=10.236.240.71
play.ws.https.proxyPort=3128
### trying  with JVM Args in activator command Line

activator testProd -Dhttp.proxyHost=10.236.240.71 -Dhttp.proxyPort=3128

In the tcpdump we can see that despite the proxy settings, play doesn't try to reach the proxy, there is a dns resolution and trying to contact the final host IP (google) never trying to connect the proxy :
10.236.240.71 at port 3128

Note that a curl command response like a charm
 curl  -v https://www.google.fr
--html response ---
### 1.controller java code

In my controller below I simply try to reache a google http or https web site  pointing by a simple route (/etaxis/https), I access throught the web.

```
@Inject WSClient ws2;
    public Promise<Result> https(){



        WSRequest request = ws2.url("https://www.google.fr").setFollowRedirects(true);
        //request.setHeader("Content-Type", "application/json");


        Promise<WSResponse> jsonPromise = request.get();

        return jsonPromise.map(response -> ok("ok"));
    }
```
### proxy settings

My entreprise Proxy is configured as is in application.conf :

```
play.ws.useProxyProperties=true
#play.http.forwarded.version=x-forwarded|rfc7239
#play.http.forwarded.trustedProxies=["10.236.240.71"]
play.ws.http.proxyHost=10.236.240.71
play.ws.http.proxyPort=3128
play.ws.https.proxyHost=10.236.240.71
play.ws.https.proxyPort=3128
```
### 2. tcpdump

I execute a tcpdump to follow what is happening  with root user 
# tcpdump -s0 -w/tmp/dump6 port not ssh

 please find the dump file attached to see the result

[dump4.zip](https://github.com/playframework/playframework/files/151028/dump4.zip)
### 3. server response

play.api.UnexpectedException: Unexpected exception[ConnectException: No route to host]

[trace_play.txt](https://github.com/playframework/playframework/files/151041/trace_play.txt)

extract  
@6p9i7pho6 - Internal server error, for (GET) [/etaxis/https] ->

play.api.UnexpectedException: Unexpected exception[ConnectException: No route to host]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.util.Try$.apply(Try.scala:191) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.util.Failure.recover(Try.scala:215) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.6.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109) [com.typesafe.play.play-iteratees_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71) [com.typesafe.play.play-iteratees_2.11-2.4.6.jar:2.4.6]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.11.6.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.6.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.6.jar:na]
Caused by: java.net.ConnectException: No route to host

**Comment by Gacko** [comment]
I'm also working right behind an proxy server and WS calls to public target as Google are working fine for me as well as calls to internal targets. 

I might be wrong but `java.net.ConnectException: No route to host` sounds more like your client isn't even able to connect to your proxy server.

Did you try to connect to your proxy using telnet?

```
telnet 10.236.240.71 3128
```

I just unset my proxy environment variables using...

```
unset http_proxy
unset https_proxy
unset no_proxy
```

This is the exception I got:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ConnectException: Connection refused: www.google.de/64.233.166.94:443]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.6.jar:2.4.6]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.6.jar:2.4.6]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.6.jar:2.4.6]
Caused by: java.net.ConnectException: Connection refused: www.google.de/64.233.166.94:443
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128) ~[async-http-client-1.9.21.jar:na]
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:140) ~[async-http-client-1.9.21.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400) ~[netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.4.Final.jar:na]
Caused by: java.net.ConnectException: Connection refused: www.google.de/64.233.166.94:443
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_74]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_74]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.10.4.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.10.4.Final.jar:na]
```

So you would rather get an error like this if Play wasn't using your proxy.

Further the documentation (https://www.playframework.com/documentation/2.4.x/ScalaWS) says:

```
play.ws.useProxyProperties: To use the system http proxy settings(http.proxyHost, http.proxyPort) (default is true).
```

I'd expect Play to use the environment variables instead of the configured proxy if this is set to true.

**Comment by Gacko** [comment]
... ah, never mind. I just tried it myself and the solution is a mix of both - application.conf and system properties.

You need to set `-Dhttp.proxyHost=yourproxyhost -Dhttp.proxyPort=yourproxyport` upon start and `play.ws.useProxyProperties=true` in your application.conf as those `http.proxy*` parameters can not be defined in the application.conf but Play needs to know it should use them by setting `play.ws.useProxyProperties` to true.

**Comment by nojkan** [comment]
Hi, Thank sfor you ranswer , It didn't work neither with system properties let's see below 

##1 System properties
application.conf I only set
   play.ws.useProxyProperties=true
starting play with  
 `  activator testProd -Dhttp.proxyHost=10.236.240.71 -Dhttp.proxyPort=3128`

=> same error , after dns resolution of www.google.fr , google ip is called without proxy => no route to host exception

##2 Play Properties
application.conf I set 
```
play.ws.http.proxyHost=10.236.240.71
play.ws.http.proxyPort=3128
play.ws.https.proxyHost=10.236.240.71
play.ws.https.proxyPort=3128
```
Note : I also try without "play.ws"

Starting play with
 `$activator testProd`

=> same error , after dns resolution of www.google.fr , google ip is called without proxy  => no route to host exception

**Comment by AlmightyOatmeal** [comment]
@nojkan: Have you tried setting the proxy from within the code itself?
```
System.setProperty("http.proxyHost", "10.236.240.71");
System.setPropery("http.proxyPort", "3128");
System.setProperty("https.proxyHost", "10.236.240.71");
System.setPropery("https.proxyPort", "3128");
```

**Comment by wsargent** [comment]
Closing -- don't have a reproducible test case, no other reporters, 2.4.x is EOL, play-ws has moved to another project
