### ISSUE TITLE
[2.3.8] play.api.libs.ws.WS.url on an url with scheme in uppercase call made on the wrong default TCP port

### ISSUE THREAD

**Issue by bmontuelle** [playframework/playframework#5820]
Hi, 

We encountered an issue performing HTTP request with play.api.libs.ws.WS.url API on an url composed only in uppercase, the http call is made on the wrong default port. When passing the same url lowering the scheme part its ok.

### Play Version (2.5.x / etc)
2.3.8

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
RHEL 6.6 -- 2.6.32-504.8.1.el6.x86_64 #1 SMP Fri Dec 19 12:09:25 EST 2014 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### Library Dependencies
com.ning.async-http-client-1.8.15.jar
com.typesafe.play.play-ws_2.11-2.3.8.jar

### Expected Behavior
Please describe the expected behavior of the issue, starting from the first action.

1. Perform a request to an all uppercase URL
```scala
val url = "HTTP://WEBASPHERIA2/COMPOSITION.5/REQUEST.ASP"
val params = "param1=aaa&param2=bbb"
val futureResponse = WS.url(url)
      .withHeaders(("Content-Type", "application/x-www-form-urlencoded"))
      .post(params)
```
2. Get a Future[WSResponse] in value futureResponse
3. Work with, and chain to other calls in my case

### Actual Behavior

1. Perform a request to an all uppercase URL
Same code as above
2. Get a TimeoutException for a connection resolved to 192.168.203.6:443, please note it target the 443 tcp port which is default for https protocol not http.

```
play.api.Application$$anon$1: Execution exception[[ConnectException: Connection timed out: WEBASPHERIA2/192.168.203.6:443 to HTTP://WEBASPHERIA2/COMPOSITION.5/REQUEST.ASP]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.2.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.11-2.3.8.jar:2.3.8]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.2.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.11-2.3.8.jar:2.3.8]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.11.2.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.2.jar:na]
Caused by: java.net.ConnectException: Connection timed out: WEBASPHERIA2/192.168.203.6:443 to HTTP://WEBASPHERIA2/COMPOSITION.5/REQUEST.ASP
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:104) ~[com.ning.async-http-client-1.8.15.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:431) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:422) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:384) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[io.netty.netty-3.9.3.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_45]
Caused by: java.net.ConnectException: Connection timed out: WEBASPHERIA2/192.168.203.6:443
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_45]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_45]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[io.netty.netty-3.9.3.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[io.netty.netty-3.9.3.Final.jar:na]
	... 8 common frames omitted
```

What I can also tell is when using an HTTP proxy (configured via $http_proxy envirnment variable) the problem do not reproduce.

I'm willing to provide test case for this one if needed but I need more time to work on it (and set an HTTP server somewhere so it can reproduce or precise the suspicious behavior)

Thanks,
Benoit

**Comment by gmethvin** [comment]
I'm able to reproduce in 2.3 using the standalone WS client:
```scala
import play.api.libs.ws.ning._
import play.api.libs.ws._
import com.ning.http.client._
import scala.util._
import scala.concurrent.ExecutionContext.Implicits._

val config = new NingAsyncHttpClientConfigBuilder(DefaultWSClientConfig()).build()
val builder = new AsyncHttpClientConfig.Builder(config)
val ws = new NingWSClient(builder.build())

ws.url("HTTP://EXAMPLE.COM").get().andThen {
  case Success(result) => println(result)
  case Failure(e) => e.printStackTrace
}
```
Note that switching to a lowercase protocol results in a successful response.

This is **not reproducible on master**. I used the following code:
```scala
import akka.actor._
import akka.stream._
import play.api.libs.ws.ahc._
import scala.util._
import scala.concurrent.ExecutionContext.Implicits._

implicit val system = ActorSystem()
implicit val materializer = ActorMaterializer()
val ws = AhcWSClient()
  
ws.url("HTTP://EXAMPLE.COM").get().andThen {
  case Success(result) => println(result)
  case Failure(e) => e.printStackTrace
}
```
It's possible this is an issue with AHC that was fixed in a later release.

**Comment by gmethvin** [comment]
This is definitely an issue with asynchttpclient. It seems like it is is fixed in AHC 1.9 (Play 2.4) but it is broken in the version used in Play 2.3 (1.8.15)

**Comment by wsargent** [comment]
Okay -- I have a sample project that shows how to dump state out of AHC / Netty without involving WS.  If we can repo it, we can file an AHC issue and set up a reproducing test case repository.

* https://github.com/wsargent/asynchttpclient-socket-leak/blob/master/src/main/scala/com/typesafe/App.scala#L42
* https://github.com/wsargent/asynchttpclient-socket-leak/blob/master/src/main/resources/logback.xml#L27

**Comment by wsargent** [comment]
This is an AHC issue, closing.
