### ISSUE TITLE
Underscore in the routes file causes runtime error

### ISSUE THREAD

**Issue by tenorviol** [playframework/playframework#5859]
### Play Version (2.5.x / etc)

2.5.0

### API (Scala / Java / Neither / Both)

Neither

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

N/A

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

N/A

### Library Dependencies

N/A

### Expected Behavior

Should run without runtime exception

### Actual Behavior

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoSuchMethodError: play.api.libs.functional.syntax.package$.functionalCanBuildApplicative(Lplay/api/libs/functional/Applicative;)Lplay/api/libs/functional/FunctionalCanBuild;]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
```

### Reproducible Test Case

It seems to happen from the underscore, `_type`:

```scala
GET     /services/:_type            controllers.HomeController.services(_type: String)
```

**Comment by tenorviol** [comment]
Interestingly enough, this code worked just fine when I downgraded to Play version 2.4.6.

**Comment by gmethvin** [comment]
Hi @tenorviol,

I'm unable to reproduce this myself on a new Play 2.5 project, and the error you are getting seems to have nothing to do with the underscore in the routes. Are you able to provide an example project that demonstrates the issue?

**Comment by wsargent** [comment]
@tenorviol can you reproduce with a ";clean ;compile; run" from 2.5.0 with the underscore?  It may have been an SBT incremental compilation bug.

**Comment by tenorviol** [comment]
You're right. This has nothing to do with play 2.5. I think it' a consul issue.
