### ISSUE TITLE
Ok.sendFile logs exception java.util.NoSuchElementException: http-handler-body-subscriber

### ISSUE THREAD

**Issue by cookeem** [playframework/playframework#5866]
### Play Version

2.5.0

### API

Scala and Java.

### JDK

```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

### Expected Behavior

The following code should delivery an existent file without exceptions being logged.

#### Scala:

```scala
def streaming = Action {
  Ok.sendFile(
    content = new java.io.File("/Volumes/Share/Book/AkkaScala2.3.14.pdf"),
    fileName = _ => "termsOfService.pdf",
    inline = true
  )
}
```

#### Java:

```java
public Result streaming() {
    File file = new File("/Volumes/Share/Book/AkkaScala2.3.14.pdf");
    return ok(file, "termsOfService.pdf");
}
```

### Actual Behavior

The file is delivered but the following exception appears at the logs:

```
[warn] i.n.u.c.SingleThreadEventExecutor - A task raised an exception.
java.util.NoSuchElementException: http-handler-body-subscriber
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:971)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:298)
        at com.typesafe.netty.http.HttpStreamsHandler.completeBody(HttpStreamsHandler.java:291)
        at com.typesafe.netty.http.HttpStreamsHandler.access$100(HttpStreamsHandler.java:16)
        at com.typesafe.netty.http.HttpStreamsHandler$2$1.run(HttpStreamsHandler.java:272)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by marcospereira** [comment]
@cookeem I can confirm this is happening. I edited the issue to add more information and made the issue clearer.

-----------

For anyone looking at this issue, this is the `sendFile` method right now:

```scala
import akka.stream.scaladsl.FileIO

def sendFile(content: java.io.File, inline: Boolean = false, fileName: java.io.File => String = _.getName, onClose: () => Unit = () => ()): Result = {
  streamFile(FileIO.fromFile(content), fileName(content), content.length, inline)
}
```

`FileIO.fromFile` creates a `akka.stream.impl.io.FileSource` which is an internal API of Akka Streams. Looks like have the following version of `sendFile` fixes the issue:

```scala
import akka.stream.scaladsl.StreamConverters

def sendFile(content: java.io.File, inline: Boolean = false, fileName: java.io.File => String = _.getName, onClose: () => Unit = () => ()): Result = {
  streamFile(StreamConverters.fromInputStream(() => Files.newInputStream(content.toPath)), fileName(content), content.length, inline)
}
```

`StreamConverters.fromInputStream` creates an `akka.stream.impl.io.InputStreamSource` which is slightly different from `akka.stream.impl.io.FileSource`.

I'm still trying to figure out exactly why `FileIO.fromFile` is not doing the magic without the exception.

**Comment by cookeem** [comment]
Actually not only Ok.sendFile will throw this exception, other function use akka streams to read file will throw the same exception. Example code like this:

@Singleton
class Application @Inject() (db: DBApi, ws: WSClient) extends Controller {
  implicit val system = ActorSystem("system")
  implicit val materializer = ActorMaterializer()

	//Throw exception: java.util.NoSuchElementException: http-handler-body-subscriber
  def streaming1 = Action {
    try {
      val fileName = "/Volumes/Share/Book/AkkaScala2.3.14.pdf"
      val file = new File(fileName)
      val fileContent: Source[ByteString, Future[IOResult]] = FileIO.fromFile(file)
      val contentType = play.api.libs.MimeTypes.forFileName(fileName).orElse(Some(play.api.http.ContentTypes.BINARY))
      Result(
        header = ResponseHeader(200, Map(CONTENT_LENGTH -> file.length.toString)),
        body = HttpEntity.Streamed(fileContent, Some(file.length()), contentType)
      )
    } catch {
      case t: Throwable =>
        InternalServerError("Error in server: " + t.getMessage())
    }
  }

	//Throw exception: java.util.NoSuchElementException: http-handler-body-subscriber
  def streaming2 = Action {
    Ok.sendFile(
      content = new java.io.File("/Volumes/Share/Book/AkkaScala2.3.14.pdf"),
      fileName = _ => "termsOfService.pdf", 
      inline = true
    )
  }

	//It works!
  def streaming3 = Action {
    val file = new File("/Volumes/Share/Book/AkkaScala2.3.14.pdf")
    val in: FileInputStream = new FileInputStream(file)
    val dataContent: Enumerator[Array[Byte]] = Enumerator.fromStream(in, 1024*1024)
    val source: Source[Array[Byte], NotUsed] = Source.fromPublisher(Streams.enumeratorToPublisher(dataContent))
    Ok.chunked(source).as("application/pdf")
  }
}

**Comment by gmethvin** [comment]
So it looks like sending a source created by `FileIO.fromFile` triggers that exception in Netty.

**Comment by marcospereira** [comment]
Yep. I can submit a pull request to fix that.

**Comment by gmethvin** [comment]
@marcospereira It would also be good to figure out if the reason it breaks is our issue or an Akka streams issue.

**Comment by marcospereira** [comment]
@gmethvin Totally agree. I've opened the PR most like a point to discuss what is the root cause and also how to add test to it.

**Comment by cookeem** [comment]
Now when I use play 2.5.0 in production mode, application always log that warning, at first I think it was because I use Singleton, after I deleted Singleton, still have this error, I don't know how to do, maybe I should rollback to Play2.4.6 :(

2016-03-15 10:28:39,988 [WARN] from io.netty.util.concurrent.SingleThreadEventExecutor in netty-event-loop-4 - A task raised an exception.
java.util.NoSuchElementException: http-handler-body-subscriber
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:971)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:298)
        at com.typesafe.netty.http.HttpStreamsHandler.completeBody(HttpStreamsHandler.java:291)
        at com.typesafe.netty.http.HttpStreamsHandler.access$100(HttpStreamsHandler.java:16)
        at com.typesafe.netty.http.HttpStreamsHandler$2$1.run(HttpStreamsHandler.java:272)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
2016-03-15 10:29:50,538 [WARN] from io.netty.util.concurrent.SingleThreadEventExecutor in netty-event-loop-3 - A task raised an exception.
java.util.NoSuchElementException: http-handler-body-subscriber
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:971)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:298)
        at com.typesafe.netty.http.HttpStreamsHandler.completeBody(HttpStreamsHandler.java:291)
        at com.typesafe.netty.http.HttpStreamsHandler.access$100(HttpStreamsHandler.java:16)
        at com.typesafe.netty.http.HttpStreamsHandler$2$1.run(HttpStreamsHandler.java:272)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
2016-03-15 10:34:54,017 [WARN] from io.netty.util.concurrent.SingleThreadEventExecutor in netty-event-loop-4 - A task raised an exception.
java.util.NoSuchElementException: http-handler-body-subscriber
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:971)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:298)
        at com.typesafe.netty.http.HttpStreamsHandler.completeBody(HttpStreamsHandler.java:291)
        at com.typesafe.netty.http.HttpStreamsHandler.access$100(HttpStreamsHandler.java:16)
        at com.typesafe.netty.http.HttpStreamsHandler$2$1.run(HttpStreamsHandler.java:272)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)

**Comment by gmethvin** [comment]
I opened up a new issue for the `FileIO.fromFile` problem: #5883

**Comment by jroper** [comment]
Root cause of this is an Akka streams bug:

https://github.com/akka/akka/issues/20031
