### ISSUE TITLE
[2.5.0][PlayConsole run] (project-name/*:projectDescriptors) java.lang.ClassCastException: java.util.concurrent.atomic.AtomicInteger cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by margussipria** [playframework/playframework#5902]
### Are you looking for help?
Not only help, but maybe report bug?

### Play Version (2.5.x / etc)
2.5.0 (Migrated from 2.4.6)

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Mac OS X 10.9.5

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
$ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

### Library Dependencies

$ dependencyList
[info] aopalliance:aopalliance:1.0
[info] ch.qos.logback:logback-classic:1.1.6
[info] ch.qos.logback:logback-core:1.1.6
[info] com.chuusai:shapeless_2.11:2.3.0
[info] com.fasterxml.jackson.core:jackson-annotations:2.7.1
[info] com.fasterxml.jackson.core:jackson-core:2.7.1
[info] com.fasterxml.jackson.core:jackson-databind:2.7.1
[info] com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.7.1
[info] com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.7.1
[info] com.github.tminglei:slick-pg_2.11:0.12.0
[info] com.github.tminglei:slick-pg_core_2.11:0.12.0
[info] com.github.tminglei:slick-pg_joda-time_2.11:0.12.0
[info] com.google.code.findbugs:jsr305:2.0.1
[info] com.google.guava:guava:19.0
[info] com.google.http-client:google-http-client:1.21.0
[info] com.google.inject:guice:4.0
[info] com.google.inject.extensions:guice-assistedinject:4.0
[info] com.google.inject.extensions:guice-multibindings:4.0
[info] com.jcraft:jsch:0.1.53
[info] com.maxmind.db:maxmind-db:1.2.0
[info] com.maxmind.geoip2:geoip2:2.6.0
[info] com.ning:async-http-client:1.9.36
[info] com.twitter:jsr166e:1.0.0
[info] com.twitter:util-collection_2.11:6.33.0
[info] com.twitter:util-core_2.11:6.33.0
[info] com.twitter:util-function_2.11:6.33.0
[info] com.typesafe:config:1.3.0
[info] com.typesafe:ssl-config-akka_2.11:0.1.3
[info] com.typesafe:ssl-config-core_2.11:0.1.3
[info] com.typesafe.akka:akka-actor_2.11:2.4.2
[info] com.typesafe.akka:akka-slf4j_2.11:2.4.2
[info] com.typesafe.akka:akka-stream_2.11:2.4.2
[info] com.typesafe.netty:netty-reactive-streams:1.0.2
[info] com.typesafe.netty:netty-reactive-streams-http:1.0.2
[info] com.typesafe.play:build-link:2.5.0
[info] com.typesafe.play:play-cache_2.11:2.5.0
[info] com.typesafe.play:play-datacommons_2.11:2.5.0
[info] com.typesafe.play:play-exceptions:2.5.0
[info] com.typesafe.play:play-functional_2.11:2.5.0
[info] com.typesafe.play:play-iteratees_2.11:2.5.0
[info] com.typesafe.play:play-jdbc-api_2.11:2.5.0
[info] com.typesafe.play:play-json_2.11:2.5.0
[info] com.typesafe.play:play-logback_2.11:2.5.0
[info] com.typesafe.play:play-netty-server_2.11:2.5.0
[info] com.typesafe.play:play-netty-utils:2.5.0
[info] com.typesafe.play:play-server_2.11:2.5.0
[info] com.typesafe.play:play-slick_2.11:2.0.0
[info] com.typesafe.play:play-streams_2.11:2.5.0
[info] com.typesafe.play:play_2.11:2.5.0
[info] com.typesafe.play:twirl-api_2.11:1.1.1
[info] com.typesafe.scala-logging:scala-logging_2.11:3.1.0
[info] com.typesafe.slick:slick-hikaricp_2.11:3.1.0
[info] com.typesafe.slick:slick_2.11:3.1.1
[info] com.zaxxer:HikariCP:2.4.4
[info] commons-codec:commons-codec:1.10
[info] commons-collections:commons-collections:3.2.2
[info] commons-io:commons-io:2.4
[info] commons-logging:commons-logging:1.1.1
[info] commons-net:commons-net:3.4
[info] io.netty:netty:3.10.5.Final
[info] io.netty:netty-buffer:4.0.33.Final
[info] io.netty:netty-codec:4.0.33.Final
[info] io.netty:netty-codec-http:4.0.33.Final
[info] io.netty:netty-common:4.0.33.Final
[info] io.netty:netty-handler:4.0.33.Final
[info] io.netty:netty-transport:4.0.33.Final
[info] io.netty:netty-transport-native-epoll:4.0.33.Final
[info] javax.inject:javax.inject:1
[info] javax.transaction:jta:1.1
[info] joda-time:joda-time:2.9.2
[info] net.codingwell:scala-guice_2.11:4.0.1
[info] net.databinder.dispatch:dispatch-core_2.11:0.11.3
[info] net.sf.ehcache:ehcache-core:2.6.11
[info] org.apache.commons:commons-compress:1.9
[info] org.apache.commons:commons-lang3:3.4
[info] org.apache.httpcomponents:httpclient:4.0.1
[info] org.apache.httpcomponents:httpcore:4.0.1
[info] org.bouncycastle:bcpg-jdk15on:1.54
[info] org.bouncycastle:bcprov-jdk15on:1.54
[info] org.codehaus.janino:commons-compiler:2.7.8
[info] org.codehaus.janino:janino:2.7.8
[info] org.flywaydb:flyway-core:4.0
[info] org.flywaydb:flyway-play_2.11:3.0.0
[info] org.joda:joda-convert:1.8.1
[info] org.postgresql:postgresql:9.4.1208
[info] org.reactivestreams:reactive-streams:1.0.0
[info] org.scala-lang:scala-reflect:2.11.8
[info] org.scala-lang.modules:scala-java8-compat_2.11:0.7.0
[info] org.scala-lang.modules:scala-parser-combinators_2.11:1.0.4
[info] org.scala-lang.modules:scala-xml_2.11:1.0.5
[info] org.scala-stm:scala-stm_2.11:0.7
[info] org.slf4j:jcl-over-slf4j:1.7.19
[info] org.slf4j:jul-to-slf4j:1.7.16
[info] org.slf4j:slf4j-api:1.7.19
[info] org.typelevel:macro-compat_2.11:1.1.1
[info] org.webjars:bootstrap:3.3.6
[info] org.webjars:font-awesome:4.5.0
[info] org.webjars:jquery:1.11.3
[info] org.webjars:requirejs:2.1.20
[info] org.webjars:webjars-locator:0.30
[info] org.webjars:webjars-locator-core:0.30
[info] org.webjars:webjars-play_2.11:2.5.0
[info] xerces:xercesImpl:2.11.0
[info] xml-apis:xml-apis:1.4.01

### Expected Behavior

1. sbt run
2. load page
3. make changes
4. load page 

### Actual Behavior

1. sbt run
2. load page
3. make changes
4. throws exception:

! @6pehgjdd8 - Internal server error, for (POST) [/] ->
  
play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[ClassCastException: java.util.concurrent.atomic.AtomicInteger cannot be cast to java.lang.String]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:51)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at scala.util.Either$LeftProjection.map(Either.scala:377)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:17)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PlayRun.scala:61)
	at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:338)
	at play.runsupport.Reloader$$anon$3.run(Reloader.scala:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:39)
	at play.runsupport.Reloader.reload(Reloader.scala:336)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:118)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassCastException: java.util.concurrent.atomic.AtomicInteger cannot be cast to java.lang.String
	at org.apache.ivy.core.settings.IvySettings.addAllVariables(IvySettings.java:589)
	at org.apache.ivy.core.settings.IvySettings.addAllVariables(IvySettings.java:583)
	at org.apache.ivy.core.settings.IvySettings.addSystemProperties(IvySettings.java:303)
	at org.apache.ivy.core.settings.IvySettings.<init>(IvySettings.java:298)
	at org.apache.ivy.core.settings.IvySettings.<init>(IvySettings.java:218)
	at sbt.IvySbt.sbt$IvySbt$$settings$lzycompute(Ivy.scala:71)
	at sbt.IvySbt.sbt$IvySbt$$settings(Ivy.scala:69)
	at sbt.IvySbt.ivyLockFile$lzycompute(Ivy.scala:120)
	at sbt.IvySbt.ivyLockFile(Ivy.scala:120)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvySbt$Module.moduleDescriptor(Ivy.scala:158)
	at sbt.IvySbt$Module.dependencyMapping(Ivy.scala:161)
	at sbt.Classpaths$$anonfun$depMap$3$$anonfun$apply$82.apply(Defaults.scala:1569)
	at sbt.Classpaths$$anonfun$depMap$3$$anonfun$apply$82.apply(Defaults.scala:1569)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Classpaths$$anonfun$depMap$3.apply(Defaults.scala:1569)
	at sbt.Classpaths$$anonfun$depMap$3.apply(Defaults.scala:1568)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### Reproducible Test Case

Don't have pinpointed example for this (yet - maybe somebody does have some clue before I try to make one).

We where using SBT 0.13.11 before trying to migrate to Play Framework 2.5 and it worked.

**Comment by wsargent** [comment]
The really odd bit is

```
Caused by: java.lang.ClassCastException: java.util.concurrent.atomic.AtomicInteger cannot be cast to java.lang.String
at org.apache.ivy.core.settings.IvySettings.addAllVariables(IvySettings.java:589)
at org.apache.ivy.core.settings.IvySettings.addAllVariables(IvySettings.java:583)
at org.apache.ivy.core.settings.IvySettings.addSystemProperties(IvySettings.java:303)
at org.apache.ivy.core.settings.IvySettings.(IvySettings.java:298)
at org.apache.ivy.core.settings.IvySettings.(IvySettings.java:218)
at sbt.IvySbt.sbt$IvySbt$$settings$lzycompute(Ivy.scala:71)
at sbt.IvySbt.sbt$IvySbt$$settings(Ivy.scala:69)
at sbt.IvySbt.ivyLockFile$lzycompute(Ivy.scala:120)
at sbt.IvySbt.ivyLockFile(Ivy.scala:120)
at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
at sbt.IvySbt.withIvy(Ivy.scala:128)
at sbt.IvySbt.withIvy(Ivy.scala:125)
at sbt.IvySbt$Module.withModule(Ivy.scala:156)
at sbt.IvySbt$Module.moduleDescriptor(Ivy.scala:158)
at sbt.IvySbt$Module.dependencyMapping(Ivy.scala:161)
```

**Comment by wsargent** [comment]
This looks like https://github.com/sbt/sbt/issues/1920#issuecomment-195572955 or https://github.com/sbt/sbt/issues/2511

**Comment by shkhln** [comment]
https://github.com/brettwooldridge/HikariCP/issues/594

**Comment by marcospereira** [comment]
@margussipria could you please provide an example to reproduce this problem?

**Comment by margussipria** [comment]
Sorry to take so much time with reply, but had time to test this again and after upgrading from HikariCP version 2.4.4 to 2.4.5 this problem went away. Shouldn't upgrade 2 think at one time :smiley_cat:
