### ISSUE TITLE
Session support not working with Compile Time DI in Play 2.5.0

### ISSUE THREAD

**Issue by rmmeans** [playframework/playframework#5929]
Play 2.5.0
Compile Time DI
Scala

### Expected Behavior
When using `.withSession("some-key" -> "some-value")` on a Result returned from a controller, the session should be added and the result returned regardless if I'm using compile time DI or the standard DI mechanism (i.e. Guice).

### Actual Behavior
The result fails with an exception and stack trace. 
`[InstantiationException: play.api.libs.Crypto]`

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[InstantiationException: play.api.libs.Crypto]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:269)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:195)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:98)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
Caused by: java.lang.InstantiationException: play.api.libs.Crypto
	at java.lang.Class.newInstance(Class.java:427)
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:51)
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:87)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:87)
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:82)
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:214)
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:214)
	at play.utils.InlineCache.fresh(InlineCache.scala:69)
Caused by: java.lang.NoSuchMethodException: play.api.libs.Crypto.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:51)
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:87)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:87)
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:82)
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:214)
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:214)
```
### Reproducible Test Case

I have created an extremely simple demo project that shows this bug. 
https://github.com/rmmeans/PlaySessionBug-CompileTimeDIExample

If you comment out the application loader out of the config file https://github.com/rmmeans/PlaySessionBug-CompileTimeDIExample/blob/master/conf/application.conf#L7 the app will start working again once Compile Time DI is turned off.

Usually, I find that I'm missing a component or likewise from mixing into my loader - this doesn't seem to be the case this time. Am I missing something or the documentation missing something in the migration guide?

**Comment by julienrf** [comment]
Hi, I think it has been fixed in the meanwhile by #5856.

**Comment by julienrf** [comment]
Can you confirm that you still have the problem with the latest snapshots?

**Comment by rmmeans** [comment]
It was fixed by that commit - sorry, when I was searching I didn't look under Crypto - I was looking under session issues.

I couldn't figure out how to pull in the latest 2.5 snapshot release ( I feel a little dumb now, that should be easy - just missing something).

I did however try impl'ing a work around based on the commit that fixed it:

``` scala
package environment

import controllers.DemoController
import play.api.ApplicationLoader.Context
import play.api.inject.{NewInstanceInjector, SimpleInjector}
import play.api.libs.crypto._
import play.api.libs.Crypto
import play.api.routing.Router
import play.api.{Application, ApplicationLoader, BuiltInComponentsFromContext, DefaultApplication}
import router.Routes

class AppLoader extends ApplicationLoader {
  override def load(context: Context): Application = new AppComponents(context).applicationFixed
}

class AppComponents(context: Context) extends BuiltInComponentsFromContext(context) {

  lazy val aesCrypter: AESCrypter = new AESCrypterProvider(cryptoConfig).get
  lazy val crypto: Crypto = new Crypto(cookieSigner, csrfTokenSigner, aesCrypter)

  lazy val inejector2 = injector.asInstanceOf[SimpleInjector] + crypto

  lazy val appController = new DemoController()

  override def router: Router = new Routes(
    httpErrorHandler, appController
  )

  lazy val applicationFixed: Application = new DefaultApplication(environment, applicationLifecycle, inejector2,
    configuration, httpRequestHandler, httpErrorHandler, actorSystem, materializer)
}
```

And was able to confirm this workaround resolves the issue.
Thanks! Looking forward to the Play 2.5.1 release

**Comment by julienrf** [comment]
You can see how I’m using a Play 2.6-SNAPSHOT here:
https://github.com/julienrf/pfe-samples/blob/play-2.5.0/pfe-scala/project/plugins.sbt#L4-L6
https://github.com/julienrf/pfe-samples/blob/play-2.5.0/pfe-scala/build.sbt#L7

**Comment by mkurz** [comment]
@julienrf Are there actually snapshots for the 2.5.x branch (like `2.5.1-2016-03-22-xxxxxxx-SNAPSHOT`)?
I can not find any:
https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-java_2.11/

**Comment by rmmeans** [comment]
Yeah, I'm not seeing latest 2.5 snapshots either for any of the back ported fixes.

Your method of pulling in snapshots works, thanks. I was trying to follow this documentation, which wasn't working:

https://www.playframework.com/documentation/2.5.x/Repositories
