### ISSUE TITLE
[Bug] Logger configurator class not found in dev mode, but works in production stage

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#6039]
This looks like a classloader issue in dev mode. Reproduction is very simple:
Create a fresh play-java project (using Play 2.5.1), then add and configure your own logger configurator (as described in the second half of [this doc section](https://www.playframework.com/documentation/2.5.x/SettingsLogger#Using-a-Custom-Logging-Framework)). To make it very simple just create an empty class that extends from `play.api.libs.logback.LogbackLoggerConfigurator` (which is the default in Play).
[Here is an example.](https://github.com/mkurz/Play-LoggerConfiguratorFail/commit/6c3af5bc6009a3ca37b81f6d0b8b55dd978acf6d)

Run the project with `sbt run`. You will get following error:

```
Play cannot load "logging.CustomLogbackLoggerConfigurator". Please make sure you have logback (or another module
that implements play.api.LoggerConfigurator) in your classpath.

java.lang.ClassNotFoundException: logging.CustomLogbackLoggerConfigurator
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at play.api.LoggerConfigurator$.apply(LoggerConfigurator.scala:45)
    at play.api.LoggerConfigurator$$anonfun$apply$1.apply(LoggerConfigurator.scala:39)
    at play.api.LoggerConfigurator$$anonfun$apply$1.apply(LoggerConfigurator.scala:38)
    at scala.Option.flatMap(Option.scala:171)
    at play.api.LoggerConfigurator$.apply(LoggerConfigurator.scala:38)
    at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:101)
    at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
    at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
    at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:158)
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:155)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:155)
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:126)
    at scala.Option.map(Option.scala:146)
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:126)
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:124)
    at scala.util.Success.flatMap(Try.scala:231)
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:124)
    at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

But if you stage the project and then run it:

```
sbt stage
./target/universal/stage/bin/<startscript>
```

everything works fine and the class will be found and loaded.

Check out my test project to reproduce: https://github.com/mkurz/Play-LoggerConfiguratorFail

**Comment by wsargent** [comment]
@mkurz is this similiar to https://github.com/playframework/playframework/issues/6017 and https://github.com/wsargent/play-2.5-log4j2

**Comment by mkurz** [comment]
@wsargent It looks like the same, except for @el-dom it worked when he moved `logger-configurator.properties` in the `conf` folder. For me this still doesn't work (in dev mode).
Also I am used play-java and #6017 and your example project uses play-scala.

**Comment by mkurz** [comment]
@wsargent You can check out my sample project and give it a go with `activator run`.
The app starts up, but the exception is logged in the console.

**Comment by mkurz** [comment]
A related discussion on the mailing list: https://groups.google.com/d/topic/play-framework/07jhwek2ob4/discussion

**Comment by el-dom** [comment]
@mkurz Regarding #6017: I had to move the properties file to the ´conf´ Folder in order for play to find it at all, but i get the same result as you nevertheless. The Logger entered in the properties cannot be loaded in dev mode.

**Comment by markus1189** [comment]
Has anybody found a solution for this?  We are currently running in prod mode, but this is more inconvenient than running in dev mode...

**Comment by mkurz** [comment]
@markus1189 You can put your LoggerConfigurator in a another (sub-)project (which you then include via `libraryDependencies`). Looks like when it gets packaged in a seperate jar file it works.

**Comment by wsargent** [comment]
Sample project https://github.com/playframework/play-log4j2

**Comment by wsargent** [comment]
@mkurz can you review https://github.com/playframework/play-log4j2 and see if I'm missing a trick or two?

**Comment by rb01usa** [comment]
Since it's been a few weeks -- just to confirm the recommended action is still to include LoggerConfigurator as a subproject?

**Comment by wsargent** [comment]
Hi @rb01usa I haven't really had time to work on this bug, but please checkout https://github.com/playframework/play-log4j2

**Comment by mipe** [comment]
@mkurz I tried the sub-project approach but this only works in prod-mode for me, in dev-mode it does not. I don't get a ClassNotFoundException though, I just get:
```No play.logger.configurator found: logging must be configured entirely by the application.```

Could you please provide more infos about your sub-project? Maybe I got something wrong.

**Comment by timzaak** [comment]
I also have the problem. No matter I put it in conf or resources dir.
 I find in the class LoggerConfigurator.scala:61
```
val in = classLoader.getResourceAsStream("logger-configurator.properties")
//debug in idea : classLoader:PlayDependencyClassLoader{file:...}
```
when i use dev mode, the `in` is always empty. if there is any possible we change the way it find `logger-configurator.properties` file?

(in DevServerStart.scala,we can find the project path(line:67), and then give it to LoggerConfigurator)
@wsargent

**Comment by mkurz** [comment]
I found the bug. We were using the wrong classloader when loading the logger configurator class.
Fix is here #6779

@wsargent I did try the fix also with your project https://github.com/playframework/play-log4j2 and it did resolve the `ClassNotFoundException`. You might want to try it by yourself to confirm.

**Comment by rb01usa** [comment]
Awesome. I'll pull that fix into my project and test it out later this week -- thanks for the heads up.

**Comment by mkurz** [comment]
Just to let you know, Play 2.5.11 with the fix was released a few hours ago.

**Comment by thedevd** [comment]
> Since it's been a few weeks -- just to confirm the recommended action is still to include LoggerConfigurator as a subproject?

Can you share how you did this ?
