### ISSUE TITLE
HttpErrorHandlerExceptions.throwableToUsefulException() cause a java.lang.InternalError: Malformed class name

### ISSUE THREAD

**Issue by leonard-IMBERT** [playframework/playframework#6064]
Play version: 2.5.2
Api: Scala 
Scala version: 2.11.7
Java version: 
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

Hi,
I throw an exception when i cannot get the configuration for a mongo driver:
```
case class MongoConfigurationException(key: String) extends Exception("==== Config.Mongo: Cannot load " + key)
```
And when it throw, this error happend:
```
java.lang.InternalError: Malformed class name
        at java.lang.Class.getSimpleName(Class.java:1330)
        at play.api.http.HttpErrorHandlerExceptions$$anon$1.<init>(HttpErrorHandler.scala:282)
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
        at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
```

The cause is simple: Scala can create class name which does not support the method `getSimpleName()`
Example:
```
object A { class B }
val obj = new A.B
val clas = obj.getClass
clas.getSimpleName() //This produce a Malformed class name error
clas.getName() //This do not produce an error
```
`getSimpleName()` is currently use in [HttpErrorHandler.scala](https://github.com/playframework/playframework/blob/2.5.2/framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala#L282). So if I throw an exception which is in an object, play will crash with a `java.lang.InternalError: Malformed class name`.

One of the solution would be to change `getSimpleName` in `getName`.

**Comment by cchantep** [comment]
Please use the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework) to ask for help. Best regards.
