### ISSUE TITLE
play and spark 1.6 compatibility issues 

### ISSUE THREAD

**Issue by listaction** [playframework/playframework#6177]
### Play Version (2.5.x / etc)

Above 2.2.0 

### API (Scala / Java / Neither / Both)
scala and java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

10.11.3  - OS X

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
ava -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

### Library Dependencies

build.sbt
name := """spark-test-1"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.7"

libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1" % Test,
  "org.apache.spark"  %% "spark-core"              % "1.6.1",
  "com.typesafe.akka" %% "akka-actor"              % "2.2.3", 
  "com.typesafe.akka" %% "akka-slf4j"              % "2.2.3",
  "org.apache.spark"  %% "spark-sql"               % "1.6.1",
  "org.apache.spark"  %% "spark-mllib"             % "1.6.1"
)

The only things that matter here are apache spark version and this uses the latest version of spark. 

### Expected Behavior
App should start and run some of the basic spark queries in just about any example: 

### Actual Behavior
TRACE:
the output if i run this app is: 
I've tried with higher versions of akka  (2.4.4) and they all sadly give the same result..

[info] application - ApplicationTimer demo: Starting application at 2016-05-19T20:51:33.009Z.
[info] play.api.Play - Application started (Dev)
[warn] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
java.lang.VerifyError: class com.fasterxml.jackson.module.scala.ser.ScalaIteratorSerializer overrides final method withResolved.(Lcom/fasterxml/jackson/databind/BeanProperty;Lcom/fasterxml/jackson/databind/jsontype/TypeSerializer;Lcom/fasterxml/jackson/databind/JsonSerializer;)Lcom/fasterxml/jackson/databind/ser/std/AsArraySerializerBase;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.fasterxml.jackson.module.scala.ser.IteratorSerializerModule$class.$init$(IteratorSerializerModule.scala:70)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.<init>(DefaultScalaModule.scala:19)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule$.<init>(DefaultScalaModule.scala:35)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule$.<clinit>(DefaultScalaModule.scala)
	at org.apache.spark.rdd.RDDOperationScope$.<init>(RDDOperationScope.scala:81)
	at org.apache.spark.rdd.RDDOperationScope$.<clinit>(RDDOperationScope.scala)
	at org.apache.spark.SparkContext.withScope(SparkContext.scala:714)
	at org.apache.spark.SparkContext.textFile(SparkContext.scala:830)
	at utils.SparkSQL$.simpleSparkSQLApp(SparkSQL.scala:21)
	at controllers.HomeController$$anonfun$index$1$$anonfun$apply$1.apply$mcV$sp(HomeController.scala:25)
	at controllers.HomeController$$anonfun$index$1$$anonfun$apply$1.apply(HomeController.scala:25)
	at controllers.HomeController$$anonfun$index$1$$anonfun$apply$1.apply(HomeController.scala:25)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

### Reproducible Test Case

https://github.com/listaction/spark-test-1
try to do activator run.

**Comment by gmethvin** [comment]
Hi @listaction,

This is not a bug in Play. Unfortunately we cannot guarantee that our dependencies are compatible with arbitrary versions of other libraries. We can try to help you but let's keep the discussion on the mailing list.

**Comment by listaction** [comment]
I have posted in the new mailing list. Also, spark is not an arbitrary library - its probably one of the most transformative libraries that you should support  - IMO. If you want the framework to be used, it should play well with other libraries which are top of mind of times.

**Comment by wsargent** [comment]
Hi @listaction -- generally, you want Spark running in its own JVM, preferably its own hardware.  It should not be run with Play, as they have very different profiles and use cases.

**Comment by listaction** [comment]
Hi wsargent, 

Thanks for the response: 

I am referring to spark apps - which submit to the separate jvm you refer to (which is how spark is run - if you refer to my repo - and the code, all it does is load the spark lib to create an app - the actual spark cluster will be elsewhere.

In all those cases, it is common practice to run the app inside your app (otherwise I am writing socket layers to just an request from say play and then call into spark (via a spark app) - which runs separately (which will in turn call the spark cluster) and then retrieve the results.

Also, this (whatever Im trying to do with 2.5.X) was working "just fine" with 2.2.3 of play and 1.0.1 of spark library.

https://github.com/knoldus/Play-Spark-Scala

**Comment by gmethvin** [comment]
@listaction I was actually specifically referring to the Jackson (and jackson-module-scala) incompatibility (which appears to be the problem here). We might be able to get it working, but you'll have to manually override a few dependencies.

Before reporting a bug, let's discuss first on the mailing list to figure out if there is a reasonable solution to your problem, and if not, decide what we can do in either Play or Spark to fix it.

**Comment by listaction** [comment]
ok - fair enough - thanks for the clarification - i'll post it in the "dev" list for some help / pointers.
