### ISSUE TITLE
ClassNotFoundException when a library uses reflection to load an application class in development mode

### ISSUE THREAD

**Issue by stefanreich** [playframework/playframework#6207]
Affected Scala Play version 2.5.2 and 2.5.3, others not tested.
Tests have been run on MacOS 10.11, on Oracle JDK 1.8.72 and 92.

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.11

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle JDK

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

### Library Dependencies

No dependencies necessary to reproduce the problem. It was discovered by using Kafka, which uses Class.forName to load classes.

### Expected Behavior

When an application class name is passed as a string to a library which uses Class.forName to load the class, the expectation is that the class can be loaded, both in development and production mode.

### Actual Behavior

The class loading succeeds in production mode, and fails in development mode with a java.lang.ClassNotFoundException. The important data point here is that the library wants to load a class that is loaded by the ReloadableClassLoader, which may indicate that the hierarchy of the class loaders is wrong.

### Reproducible Test Case

Attached is a play 2.5.3 app that reproduces the problem. Start the app via "sbt run", point your browser to http://localhost:9000, and observe the exception below. When the app is built via "sbt dist" and started from the shell script, the class is loaded fine and the usual play greeting shows up.

[bug.zip](https://github.com/playframework/playframework/files/294519/bug.zip)

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ClassNotFoundException: controllers.Dummy]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: java.lang.ClassNotFoundException: controllers.Dummy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at p.Reflection.materialize(Reflection.scala:6)
	at controllers.Application$$anonfun$index$1.apply(Application.scala:16)
	at controllers.Application$$anonfun$index$1.apply(Application.scala:9)
	at play.api.mvc.ActionBuilder$$anonfun$apply$14.apply(Action.scala:403)
	at play.api.mvc.ActionBuilder$$anonfun$apply$14.apply(Action.scala:403)

**Comment by shkhln** [comment]
This is not really considered a bug because there is no reasonable solution or workaround. See https://github.com/playframework/playframework/issues/4159 and https://github.com/playframework/playframework/issues/2847 for explanation.

**Comment by schmitch** [comment]
@stefanreich which version of kafka do you use? Since 0.9.0 they don't use Class.forName, see:
https://issues.apache.org/jira/browse/KAFKA-3218
https://issues.apache.org/jira/browse/KAFKA-2295

**Comment by mkurz** [comment]
@gmethvin Was this closed unintentionally?

**Comment by gmethvin** [comment]
Sorry, forgot to comment. I don't think this is a bug for the reasons mentioned.

**Comment by mdii** [comment]
I have the same problem when ehcache is loading a cached element from the disk in dev mode. I am using Play 2.5.3 and the ehcache version shipped by it (net.sf.ehcache:ehcache-core:2.6.11). Using  ehcache 2.10.2 leads to the same exception.
I have this exception only since I migrated from Play 2.4 to 2.5.
I would consider this as a bug because it comes from a liberary that is provided in Play.

**Comment by gmethvin** [comment]
> I would consider this as a bug because it comes from a liberary that is provided in Play.

The call to `Class.forName` is from Kafka, which is not provided by Play.

**Comment by mdii** [comment]
In my case, the call to Class.forName is from Ehcache, the default cache implementation in Play. Maybe I should have created a separate issue for my problem with Ehcache.

**Comment by schmitch** [comment]
@mdii why did you upgrade to ehcache 2.10?

Actually I guess Play should anyway drop Ehcache2 in the 2.6 release and use ehcache3 the only thing that still is bad in ehcache3 is expiration on the object level.

Still ClassNotFoundException will actually also happen when changing library versions. A stacktrace would be helpful at all with an example especially since ehcache-core doesn't have that many Class.forName calls that would actually trigger a ClassNotFoundException while using the play cache-api.

**Comment by mdii** [comment]
I upgraded to ehcache 2.10 for testing the behavior before finding out that the problem was from the context class loader. Now, I am using again the version that comes with Play 2.5.3.

Here is the exception when ehcache retrieves the cached value from the disk.

```Java
net.sf.ehcache.CacheException: java.lang.ClassNotFoundException: models.AuthInfo
	at net.sf.ehcache.store.disk.DiskStorageFactory.retrieve(DiskStorageFactory.java:916)
	at net.sf.ehcache.store.disk.Segment.decodeHit(Segment.java:183)
	at net.sf.ehcache.store.disk.Segment.get(Segment.java:221)
	at net.sf.ehcache.store.disk.DiskStore.get(DiskStore.java:467)
	at net.sf.ehcache.store.FrontEndCacheTier.get(FrontEndCacheTier.java:201)
	at net.sf.ehcache.Cache.searchInStoreWithoutStats(Cache.java:2070)
	at net.sf.ehcache.Cache.get(Cache.java:1590)
	at net.sf.ehcache.Cache.get(Cache.java:1557)
	at play.api.cache.EhCacheApi.get(Cache.scala:274)
	at controllers.APISecured$$anonfun$checkAccount$2.apply(Authentication.scala:87)
Caused by: java.lang.ClassNotFoundException: models.AuthInfo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.sf.ehcache.util.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:129)
	at net.sf.ehcache.util.PreferTCCLObjectInputStream.resolveClass(PreferTCCLObjectInputStream.java:44)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
```

I used the following workaround to make loading cached values from disk work:

```Scala
...
withClassLoaderHack(environment, () => cache.get[AuthInfo](key))
...

def withClassLoaderHack[E](environment:Environment, f: () => E): E = {
    environment.mode match {
      case Mode.Dev =>
        val old = Thread.currentThread().getContextClassLoader
        try {
          Thread.currentThread().setContextClassLoader(environment.classLoader)
          f()
        } finally {
          Thread.currentThread().setContextClassLoader(old)
        }
      case _ =>
        f()
    }
}
```

**Comment by nafg** [comment]
Please fix

I can't write a custom Logback appender

**Comment by shkhln** [comment]
> Please fix

@nafg This not a straightforward bug and it wasn't simply overlooked due to lack of complaints. You should probably discuss whatever solution you think of on _play-framework-dev_.
