### ISSUE TITLE
Play 2.4.6 UuidWrites throwing NullPointerException when Option[UUID] is None

### ISSUE THREAD

**Issue by prasannata** [playframework/playframework#6244]
### Play Version (2.5.x / etc)

Play Version 2.4.6

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.11

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode

### Expected Behavior

1. Try serializing `Option[UUID]` to Json when it is None using Play's play.api.libs.json.Writes.UuidWrites
2. If it is None, then omit the value from resultant Json

### Actual Behavior

1. Create a case class with `Option[UUID] ` and set it to None
2. Serialize this using Json.writes
3. NullPointerException is thrown
4. On debugging I found out that the value being passed to writes is `Some(null)`

### StackTrace

```
java.lang.NullPointerException: null
	at play.api.libs.json.DefaultWrites$UuidWrites$.writes(Writes.scala:459) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.DefaultWrites$UuidWrites$.writes(Writes.scala:458) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.DefaultFormat$$anon$4.writes(Format.scala:83) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.PathWrites$$anonfun$nullable$2.apply(JsConstraints.scala:171) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.PathWrites$$anonfun$nullable$2.apply(JsConstraints.scala:169) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$5$$anonfun$inmap$2.apply(Format.scala:31) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$5$$anonfun$inmap$2.apply(Format.scala:31) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$1.writes(Format.scala:41) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$1.writes(Format.scala:37) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.PathWrites$$anonfun$at$2.apply(JsConstraints.scala:161) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.PathWrites$$anonfun$at$2.apply(JsConstraints.scala:161) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$4$$anonfun$apply$1.apply(Writes.scala:65) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:76) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$5$$anonfun$inmap$2.apply(Format.scala:31) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$5$$anonfun$inmap$2.apply(Format.scala:31) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$1.writes(Format.scala:41) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.OFormat$$anon$1.writes(Format.scala:37) ~[play-json_2.11-2.4.6.jar:2.4.6]
	at play.api.libs.json.Json$.toJson(Json.scala:118) ~[play-json_2.11-2.4.6.jar:2.4.6]
```

**Comment by wsargent** [comment]
Hi @prasannata -- can you include the stacktrace and a failing test case showing this behavior?  Thanks!

**Comment by gmethvin** [comment]
@prasannata I did a quick test myself and was unable to reproduce (either on 2.4.6 or 2.5.4):
```scala
import play.api.libs.json._
import play.api.libs.json.Writes._
import java.util.UUID

case class Foo(bar: String, baz: Option[UUID])
implicit val fooWrites = Json.writes[Foo]

Json.toJson(Foo("test", None))
```

**Comment by prasannata** [comment]
@wsargent @gmethvin Sorry guys for the delay in response. This is not a big in play, I found some other library which was setting the field to 'Some(null)' instead of 'None' and that was causing play to throw NPE. Closing the issue.
