### ISSUE TITLE
Failed to perform fileUpload using FormData (Java)

### ISSUE THREAD

**Issue by fabiowillian** [playframework/playframework#6278]
Hi

I'm not getting upload files to my server because of this error:

[error] play - Exception caught in RequestBodyHandler
java.nio.channels.ClosedChannelException: null
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779

Is there a way to solve this problem? Changing the SSL configs? Changing the app configs? I'm using AngularJS. I've been watching this problem recurs. Please, somebody help me! Thanks!

**Comment by gmethvin** [comment]
Seems like this is the same as #1842

**Comment by cchantep** [comment]
Closing it for now. If something different from #1842 can be reproduced, an up-to-date ticket could be created.
