### ISSUE TITLE
`activator testOnly` does not work as expected

### ISSUE THREAD

**Issue by ShahBinoy** [playframework/playframework#6322]
As per documentation `activator test` works correctly but `activator testOnly my.controllers.ControllerClassTest` does not work.

It works with `activator "test-only my.controllers.ControllerClassTest"` and there by needs to be fixed in the playframework documentation or activator command

**Play Framework Version**
`2.5.4`

**Play Libraries used**
Java

**OS is Linux:**
```
09:55:47 ~$ uname -rvp
3.19.0-64-generic #72~14.04.1-Ubuntu SMP Fri Jun 24 17:59:48 UTC 2016 x86_64
```

**Java Version:**

```
10:02:37 ~$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

This issue has been reported on other versions also

[Google Group Post](https://groups.google.com/forum/#!searchin/play-framework/testOnly%7Csort:date/play-framework/xGDhQSz5cTs/T_Z_gUpW5eIJ)

**Issue Output** ( trimmed )
```
10:08:39 $ activator testOnly controllers.LoginControllerTest
[info] Loading project definition from /project
[info] Set current project to identity-project (in build file:/home/workspace/identity-projects/identity-project/)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
[debug] c.p.MyController - Credential Validation Failed for user 
[info] http.requests - http_method=POST api_path=/profile/updateByUUID time_taken=317 http_status=400
[debug] c.p.MyController - Missing UUID for profile
[info] http.requests - http_method=POST api_path=/profile/updateByUUID time_taken=12 http_status=400
[DEBUG] [07/14/2016 10:09:29.763] [application-akka.actor.default-dispatcher-4] [EventStream] shutting down: StandardOutLogger started
[debug] c.p.MyController - Credential Validation Failed for user alphaAndrew1.beta2@gmail.com
[info] http.requests - http_method=POST api_path=/profile/updateByUUID time_taken=27 http_status=400
[error] c.p.MyController - Profile Not Found Error
[info] http.requests - http_method=POST api_path=/profile/updateByUUID time_taken=10 http_status=400
[debug] c.p.MyController - Credential Validation Failed for user alpha1.beta2@gmail.com
[info] http.requests - http_method=POST api_path=/profile/updateByUUID time_taken=25 http_status=400
[DEBUG] [07/14/2016 10:09:30.453] [application-akka.actor.default-dispatcher-3] [EventStream] shutting down: StandardOutLogger started
[error] Test controllers.LoginControllerTest.authenticate_WithRepeatedInvalidCreds_ShouldGiveUnauthorizedResponse_AndLockAccount failed: java.lang.NullPointerException: null, took 0.148 sec
[error]     at controllers.auth.LoginController.authenticate(LoginController.java:51)
...
[error]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] http.requests - http_method=POST api_path=/auth/letmein time_taken=538 http_status=401
[info] http.requests - http_method=POST api_path=/auth/letmein time_taken=484 http_status=200
[DEBUG] [07/14/2016 10:09:31.956] [application-akka.actor.default-dispatcher-8] [EventStream] shutting down: StandardOutLogger started
[error] Test controllers.LoginControllerTest.authenticate_WithNullPassword_ShouldGiveUnauthorizedResponse failed: java.lang.NullPointerException: null, took 0.156 sec
[error]     at controllers.auth.LoginController.authenticate(LoginController.java:52)
...
[error]     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] http.requests - http_method=POST api_path=/auth/letmein time_taken=429 http_status=200
[debug] s.Authenticator - Token Header Key X-AUTH-TOKEN and Value fa22d8e9-f87a-41c2-80a3-2079fece3e1d
[info] http.requests - http_method=GET api_path=/auth/adios time_taken=24 http_status=200
[info] http.requests - http_method=POST api_path=/auth/letmein time_taken=12 http_status=401
[info] http.requests - http_method=POST api_path=/auth/letmein time_taken=7 http_status=401
[info] c.p.MyController - Calling New Profile
[info] http.requests - http_method=GET api_path=/profile/new time_taken=218 http_status=200
[error] Test controllers.SecuredMyControllerTest.newProfile_When_Authenticated_ShouldGive_EmptyProfileJson failed: 
[error] Expected: is <401>
[error]      but: was <200>, took 0.321 sec
[info] c.p.MyController - Calling New Profile
[info] http.requests - http_method=GET api_path=/profile/new time_taken=19 http_status=200
[error] Test controllers.SecuredMyControllerTest.newProfile_When_NotAuthenticated_ShouldGive_UnauthorizedResponse failed: 
[error] Expected: is <401>
[error]      but: was <200>, took 0.156 sec
[info] http.requests - http_method=POST api_path=/profile/find/5760bdfc3f12cc1f361c184b time_taken=35 http_status=200
[info] http.requests - http_method=POST api_path=/profile/find/5760bdfc3f12cc1f361c184b time_taken=27 http_status=200
[DEBUG] [07/14/2016 10:09:33.703] [application-akka.actor.default-dispatcher-8] [EventStream] shutting down: StandardOutLogger started
[info] http.requests - http_method=POST api_path=/profile/find/5760bdfc3f12cc1f361c184b time_taken=25 http_status=200
[DEBUG] [07/14/2016 10:09:33.854] [application-akka.actor.default-dispatcher-7] [EventStream] shutting down: StandardOutLogger started
[DEBUG] [07/14/2016 10:09:34.096] [application-akka.actor.default-dispatcher-6] [EventStream] shutting down: StandardOutLogger started
[DEBUG] [07/14/2016 10:09:34.222] [application-akka.actor.default-dispatcher-3] [EventStream] shutting down: StandardOutLogger started
[DEBUG] [07/14/2016 10:09:34.350] [application-akka.actor.default-dispatcher-5] [EventStream] shutting down: StandardOutLogger started
[error] Test controllers.MyControllerUpdatePasswordTest.updatePassword_WithUnknownEmail_ShouldGiveBadRequest2 failed: java.lang.NullPointerException: null, took 0.117 sec
[error]     at controllers.profile.MyController.updatePassword(MyController.java:213)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Test controllers.MyControllerUpdatePasswordTest.updatePassword_WithBadUuid_ShouldGiveBadRequest2 failed: java.lang.NullPointerException: null, took 0.14 sec
[error]     at controllers.profile.MyController.updatePassword(MyController.java:213)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[DEBUG] [07/14/2016 10:09:34.755] [application-akka.actor.default-dispatcher-7] [EventStream] shutting down: StandardOutLogger started
[error] Test controllers.MyControllerUpdatePasswordTest.updatePassword_WithEmptyEmail_ShouldGiveBadRequest2 failed: java.lang.NullPointerException: null, took 0.124 sec
[error]     at controllers.profile.MyController.updatePassword(MyController.java:213)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[DEBUG] [07/14/2016 10:09:34.875] [application-akka.actor.default-dispatcher-6] [EventStream] shutting down: StandardOutLogger started
[error] Test controllers.MyControllerUpdatePasswordTest.update_WithoutUUID_ShouldGiveBadRequest2 failed: java.lang.NullPointerException: null, took 0.12 sec
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Test controllers.MyControllerUpdatePasswordTest.updatePassword_WithEmptyNewPassword_ShouldGiveBadRequest2 failed: java.lang.NullPointerException: null, took 0.12 sec
[error]     at controllers.profile.MyController.updatePassword(MyController.java:213)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Test controllers.MyControllerUpdatePasswordTest.updatePassword_ValidData_ShouldGiveSuccess failed: java.lang.NullPointerException: null, took 0.094 sec
[error]     at controllers.profile.MyController.updatePassword(MyController.java:213)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Test controllers.MyControllerUpdatePasswordTest.updatePassword_WithWrongPassword_ShouldGiveBadRequest2 failed: java.lang.NullPointerException: null, took 0.122 sec
[error]     at controllers.profile.MyController.updatePassword(MyController.java:213)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Test controllers.MyControllerUpdatePasswordTest.updatePassword_WithOldNewPasswordMatch_ShouldGiveBadRequest2 failed: java.lang.NullPointerException: null, took 0.12 sec
[error]     at controllers.profile.MyController.updatePassword(MyController.java:213)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Failed: Total 78, Failed 24, Errors 0, Passed 54
[error] Failed tests:
[error] 	controllers.SecuredMyControllerTest
[error] 	controllers.MyControllerUpdatePasswordTest
[error] 	AllTestsSuite
[error] 	controllers.LoginControllerTest
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 15 s, completed Jul 14, 2016 10:09:39 AM
```

**Working Alternative**

```
10:17:05 $ activator "test-only controllers.LoginControllerTest"
[info] Loading project definition from /home/workspace/identity-projects/identity-project/project
[info] Set current project to identity-project (in build file:/home/workspace/identity-projects/identity-project/)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
[error] Test controllers.LoginControllerTest.authenticate_WithRepeatedInvalidCreds_ShouldGiveUnauthorizedResponse_AndLockAccount failed: java.lang.NullPointerException: null, took 2.999 sec
[error]     at controllers.auth.LoginController.authenticate(LoginController.java:51)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] http.requests - http_method=POST api_path=/log/in time_taken=472 http_status=401
[info] http.requests - http_method=POST api_path=/log/in time_taken=445 http_status=200
[error] Test controllers.LoginControllerTest.authenticate_WithNullPassword_ShouldGiveUnauthorizedResponse failed: java.lang.NullPointerException: null, took 0.17 sec
[error]     at controllers.auth.LoginController.authenticate(LoginController.java:52)
...
[error]     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] http.requests - http_method=POST api_path=/log/in time_taken=422 http_status=200
[debug] s.Authenticator - Token Header Key X-AUTH-TOKEN and Value 773731cb-ea57-47c1-a489-7022df284fb7
[info] http.requests - http_method=GET api_path=/auth/adios time_taken=27 http_status=200
[info] http.requests - http_method=POST api_path=/log/in time_taken=7 http_status=401
[info] http.requests - http_method=POST api_path=/log/in time_taken=17 http_status=401
[error] Failed: Total 7, Failed 2, Errors 0, Passed 5
[error] Failed tests:
[error] 	controllers.LoginControllerTest
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed Jul 14, 2016 10:17:37 AM
```

**Comment by wsargent** [comment]
This is actually a pass through to sbt: http://www.scala-sbt.org/1.0/docs/Testing.html#testOnly

@ShahBinoy how would you like this to be documented?

**Comment by ShahBinoy** [comment]
I was looking only at the documentation on https://www.playframework.com/documentation/2.5.x/JavaTest and mistook it as an argument to activator in the command line. I think adding that distinction, something in the lines of example below can help people who are not using interactive activator/sbt shell

```
$activator
# testOnly controllers.MyController
```
and
```
$activator "test-only controllers.MyController"
```
