### ISSUE TITLE
Remove H2 database reference and functionality

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6352]
### Play Version (2.5.x / etc)

master

### API (Scala / Java / Neither / Both)

Neither

### Library Dependencies

h2

### Actual Behavior

We have removed h2 from the play-jdbc module as a compile time dependency https://github.com/playframework/playframework/pull/6338

But we still have documentation references:

* https://www.playframework.com/documentation/2.5.x/Developing-with-the-H2-Database#H2-database

and there is the "h2-browser" sbt task, which still runs but returns an exception:

``` text
[better-play-logger] $ h2-browser
java.lang.ClassNotFoundException: org.h2.tools.Server
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at play.sbt.PlayCommands$$anonfun$6.apply(PlayCommands.scala:77)
	at play.sbt.PlayCommands$$anonfun$6.apply(PlayCommands.scala:74)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:54)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by schmitch** [comment]
should we maybe have a Sbt Module which adds the h2 task and the dependency? actually that would make it easier to distribute the h2 version over certain projects. I mean H2 is really stable so having a PlayH2 plugin shouldn't be too bad?
