### ISSUE TITLE
CSRFFilter fails with Obigo browser

### ISSUE THREAD

**Issue by sanitas2** [playframework/playframework#6356]
Sorry for submitting issue without too much details but it's kind of hard for me to get them. 

I am using version 2.4.x, some of my pages contain forms which are secured with standard CSRF token mechanism. I think it works fine. But lately I've noticed that sometimes page request end with 500 errors and missing CSRF token exception. I checked the logs and it turns out it were **GET** requests (so why the token was expected?) and they were send from browser with user agent:
`ALCATEL_2012G/1.0 ObigoInternetBrowser/Q03C`

I am guessing that's quite strange internet browser and it causes problems. Still I think Framework should be able to deal better with this. 

The exception I get looks like that:

```
Unexpected exception[RuntimeException: Missing CSRF Token]
@70p199id2: Unexpected exception
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261)
        at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
        at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:169)
        at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:131)
        at play.core.j.JavaHttpErrorHandlerAdapter$$anonfun$onServerError$1.apply(JavaHttpErrorHandlerAdapter.scala:22)
        at play.core.j.JavaHttpErrorHandlerAdapter$$anonfun$onServerError$1.apply(JavaHttpErrorHandlerAdapter.scala:22)
        at play.core.j.JavaHelpers$$anonfun$invokeWithContext$1.apply(JavaHelpers.scala:140)
        at play.core.j.JavaHelpers$$anonfun$invokeWithContext$1.apply(JavaHelpers.scala:139)
        at play.core.j.JavaHelpers$class.withContext(JavaHelpers.scala:151)
        at play.core.j.JavaHelpers$.withContext(JavaHelpers.scala:160)
        at play.core.j.JavaHelpers$class.invokeWithContext(JavaHelpers.scala:139)
        at play.core.j.JavaHelpers$.invokeWithContext(JavaHelpers.scala:160)
        at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:22)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Failure.recover(Try.scala:185)
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Missing CSRF Token
        at scala.sys.package$.error(package.scala:27)
        at play.filters.csrf.CSRF$Token$$anonfun$getToken$1.apply(csrf.scala:119)
        at play.filters.csrf.CSRF$Token$$anonfun$getToken$1.apply(csrf.scala:119)
        at scala.Option.getOrElse(Option.scala:120)
        at play.filters.csrf.CSRF$Token$.getToken(csrf.scala:119)
        at views.[...]
        at x.Controller.details()
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$15$$anonfun$apply$15.apply(Routes.scala:2239)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$15$$anonfun$apply$15.apply(Routes.scala:2239)
        at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
        at play.GlobalSettings$1.call(GlobalSettings.java:67)
        at x.TemplateParams.call(TemplateParams.java:54)
        at play.db.jpa.TransactionalAction.lambda$call$5(TransactionalAction.java:19)
        at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:136)
        at play.db.jpa.JPA.withTransaction(JPA.java:159)
        at play.db.jpa.TransactionalAction.call(TransactionalAction.java:16)
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at scala.concurrent.Future$.apply(Future.scala:485)
        at play.core.j.JavaAction.apply(JavaAction.scala:94)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
        at scala.Option.map(Option.scala:145)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        ... 6 more
```

**Comment by gmethvin** [comment]
The issue is that there is supposed to be a generated token available when the form was rendered (CSRF.getToken is being called in the view). This would either be from a tag on the request (if the request is newly generated) or from the cookie.

Now, knowing the user agent is somewhat useful, but it would be more useful to know which other headers were sent and what your CSRF filter configuration is, so we can know for sure if this is an issue with the filter.

**Comment by sanitas2** [comment]
The  CSRF filter configuration I think is standard (I don't have any keys starting with play.filters.csrf. in application.conf). As for the headers it's quite impossible to get them - I don't have them logged and if I had just started logging them there's slim chance the user with that browser would come back to my site anytime soon.

**Comment by cchantep** [comment]
I would suggest to move that to the MailingList, to confirm whether/where is the issue.

**Comment by sanitas2** [comment]
It's closed because the problem was solved?

**Comment by cchantep** [comment]
As indicated before, this need first a discussion on the MailingList. Best regards.

**Comment by sanitas2** [comment]
Can you point me to the discussion? I can't find it on mailing list.

**Comment by cchantep** [comment]
As indicated before, you need to open a discussion on the [MailingList](https://groups.google.com/forum/#!forum/play-framework) if you want to discuss this so it can be check whether there is an issue on Play side, and if yes how it can be actionable.

> Please have a look at the [issue tracker guide](https://github.com/playframework/playframework/blob/master/.github/ISSUE_TEMPLATE.md#are-you-looking-for-help).

**Comment by sanitas2** [comment]
I am not looking for help, I do not need to discuss things. I am 100% sure that sending GET request which ends with throwing "RuntimeException: Missing CSRF Token" is a bug. Only problem is that I am unable to reproduce this (because problem is caused by some random user). So to me there's nothing more to discuss. But if you fell the topic should be discussed elsewhere, don't hesitate to open the discussion.

But if you want just close the bug, fell free to do so. But please provide proper reason like it cannot be reproduced (but I guess nobody even tried that) or my submission lacks reproducible test case (but I already justified why's that).

Anyway, if that was up to me - I would just ask someone to look for few minutes at the code to guess why that exception might be thrown. If nothing suspicious would be find than I would have closed issue with comment it can't be verified. 

But what you doing now is just hiding the problem under the rug and assume it solves the issue.

**Comment by schmitch** [comment]
Well without Code, Headers and more Info this *Bug* is impossible to catch / reproduce. It may not even be a Bug since the lack of information.
I'm very sorry to say it but without more details nobody could even resolve this. And it's probably also not easy to get a Device with such a Browser.

**Comment by gmethvin** [comment]
@sanitas2 Even if it is a bug, you are much more likely to solve it if you post on the mailing list. GitHub is typically used by major contributors to Play, but the mailing list also includes a lot of users as well, some of whom may have run into this problem before. This is why we generally recommend posting on the mailing list first if you can't easily reproduce a bug.

> I am 100% sure that sending GET request which ends with throwing "RuntimeException: Missing CSRF Token" is a bug.

Not sure I agree. First of all, in your initial post I think you misunderstood what the exception meant. This exception means you're using the template helper to get the *server-generated* CSRF token to display in a form, but for some reason it cannot be retrieved. This could happen for a number of reasons:
 1. You have not applied the CSRF filter, which generates the token.
 2. Somehow the request has been modified by another filter to remove the generated CSRF token.
 3. The client (which could actually be "Obigo browser" or someone else spoofing the user agent) is sending an invalid cookie. This might happen because of a bug in the browser or someone intentionally trying to spoof the token. 

> But what you doing now is just hiding the problem under the rug and assume it solves the issue.

At the very least we would need to see your code for your controller and filters to even start trying to reproduce the issue and then decide what action is warranted. If it's triggered by a bug with some obscure browser or a malicious user, it may not even be worth doing anything, especially if the behavior is already improved in newer versions of Play.
