### ISSUE TITLE
DynamicClassLoadingException for ColoredLevel

### ISSUE THREAD

**Issue by jorkzijlstra** [playframework/playframework#6359]
The tests output unnecessary log statements when using Play as an library dependency and a default logback-test.xml which uses the ColoredLevel class.

Specifying the $coloredLevel in a logback pattern causes a "ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type play.api.libs.logback.ColoredLevel" error.

Play version 2.5.4
Ubuntu 16.10
Openjdk version "1.8.0_91"

### Library Dependencies
"com.typesafe.play" %% "play-test" % "2.5.4" % "test",
"org.scalatestplus.play" %% "scalatestplus-play" % "1.5.0" % "test"

So I use Play as an library, not as a plugin.

### Expected Behavior

No excessive output of logs statement. The ColorLevel class to be loaded

### Actual Behavior

ColoredLevel class isn't loaded. So when using $coloredLevel in fileAppender pattern log statements are outputted

### Work around

In your logback.xml remove #coloredLevel from the pattern

### Reproducible Test Case

[play-library-test.zip](https://github.com/playframework/playframework/files/385557/play-library-test.zip)

Might be somewhat related: https://github.com/playframework/playframework/issues/1717

### Output
`
07:29:04,570 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
07:29:04,570 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [file:/home/jork/development/dev-store-library/target/scala-2.11/test-classes/logback-test.xml]
07:29:04,646 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
07:29:04,647 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word coloredLevel with class [play.api.libs.logback.ColoredLevel]
07:29:04,647 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
07:29:04,650 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
07:29:04,656 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
07:29:04,665 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@21bcd37e - Failed to instantiate converter class [play.api.libs.logback.ColoredLevel] for keyword [coloredLevel] ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type play.api.libs.logback.ColoredLevel
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type play.api.libs.logback.ColoredLevel
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
	at 	at ch.qos.logback.core.pattern.parser.Compiler.createConverter(Compiler.java:104)
	at 	at ch.qos.logback.core.pattern.parser.Compiler.compile(Compiler.java:63)
	at 	at ch.qos.logback.core.pattern.parser.Parser.compile(Parser.java:87)
	at 	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:83)
	at 	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at 	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:161)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:155)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:142)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:103)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at net.sf.ehcache.CacheManager.<clinit>(CacheManager.java:131)
	at 	at play.api.cache.CacheManagerProvider.get$lzycompute(Cache.scala:205)
	at 	at play.api.cache.CacheManagerProvider.get(Cache.scala:202)
	at 	at play.api.cache.CacheManagerProvider.get(Cache.scala:201)
	at 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at 	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at 	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at 	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at 	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at 	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
	at 	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:984)
	at 	at com.google.inject.util.Providers$GuicifiedProviderWithDependencies.initialize(Providers.java:149)
	at 	at com.google.inject.util.Providers$GuicifiedProviderWithDependencies$$FastClassByGuice$$2a7177aa.invoke(<generated>)
	at 	at com.google.inject.internal.cglib.reflect.$FastMethod.invoke(FastMethod.java:53)
	at 	at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:57)
	at 	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:91)
	at 	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at 	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at 	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at 	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:174)
	at 	at com.google.inject.internal.Initializer.injectAll(Initializer.java:108)
	at 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
	at 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at 	at com.google.inject.Guice.createInjector(Guice.java:96)
	at 	at com.google.inject.Guice.createInjector(Guice.java:84)
	at 	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
	at 	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
	at 	at play.api.test.FakeApplication.<init>(Fakes.scala:209)
	at 	at org.scalatestplus.play.OneServerPerSuite$class.app(OneServerPerSuite.scala:153)
	at 	at com.pointlogic.services.VisualGuardSpec.app$lzycompute(VisualGuardSpec.scala:11)
	at 	at com.pointlogic.services.VisualGuardSpec.app(VisualGuardSpec.scala:11)
	at 	at org.scalatestplus.play.OneServerPerSuite$class.run(OneServerPerSuite.scala:174)
	at 	at com.pointlogic.services.VisualGuardSpec.run(VisualGuardSpec.scala:11)
	at 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
	at 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
	at 	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at 	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at 	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: play.api.libs.logback.ColoredLevel
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
	at 	... 73 common frames omitted
07:29:04,666 |-ERROR in ch.qos.logback.core.pattern.parser.Compiler@21bcd37e - [coloredLevel] is not a valid conversion word
07:29:04,678 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [./logs/application.log]
07:29:04,679 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
07:29:04,680 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
07:29:04,680 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
07:29:04,682 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
07:29:04,683 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNCFILE]
07:29:04,683 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to ch.qos.logback.classic.AsyncAppender[ASYNCFILE]
07:29:04,683 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCFILE] - Attaching appender named [FILE] to AsyncAppender.
07:29:04,683 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCFILE] - Setting discardingThreshold to 51
07:29:04,683 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
07:29:04,683 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNCSTDOUT]
07:29:04,683 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT]
07:29:04,683 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT] - Attaching appender named [STDOUT] to AsyncAppender.
07:29:04,683 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT] - Setting discardingThreshold to 51
07:29:04,684 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [play] to INFO
07:29:04,684 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [application] to INFO
07:29:04,684 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.gargoylesoftware.htmlunit.javascript] to OFF
07:29:04,684 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
07:29:04,684 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCFILE] to Logger[ROOT]
07:29:04,684 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCSTDOUT] to Logger[ROOT]
07:29:04,684 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
07:29:04,684 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@31d0f7d6 - Registering current configuration as safe fallback point
`

**Comment by wsargent** [comment]
@jorkzijlstra do you have the play-logback library dependency in your project?

```
// https://mvnrepository.com/artifact/com.typesafe.play/play-logback_2.11
libraryDependencies += "com.typesafe.play" % "play-logback_2.11" % "2.5.4"
```

**Comment by jorkzijlstra** [comment]
This was also one of my first guesses. I did try it before creating this issue.
However I just added it again and now it does seem to fix the problem, maybe I forgot to reload the project last time.

**Comment by jorkzijlstra** [comment]
Adding the library partly solves the problem. I did some more testing and could still trigger the output.
It seems having a single test per suite doesn't trigger the output (which I had in the test case supplied with this issue), but haven multiple does. 

These tests trigger the output
```
import org.specs2.mutable.Specification
import play.api.test.{FakeApplication, WithApplication}

object Tests extends Specification {
   abstract class TestApp extends WithApplication(FakeApplication())

  "the tests" should {

    "have a method that" >> {

      "test1" in new TestApp {
        1 === 1
      }

      "test" in new TestApp {
        1 === 1
      }
    }
  }
}
```

But when adding sequential it seems to work again.
These test don't trigger the output

```
import org.specs2.mutable.Specification
import play.api.test.{FakeApplication, WithApplication}

object Tests extends Specification {
  sequential

  abstract class TestApp extends WithApplication(FakeApplication())

  "the tests" should {

    "have a method that" >> {

      "test1" in new TestApp {
        1 === 1
      }

      "test" in new TestApp {
        1 === 1
      }
    }
  }
}
```

So there seems to be some sort of a concurrency problem somewhere, although at the moment I have no idea of what causes it.

**Comment by wsargent** [comment]
If you're running integration tests, you should be running sequentially -- Play 2.x still has global state that means running in parallel can cause concurrency bugs.  This is one of the drivers for Play 3.x.

Sounds like your case is fixed, so closing.

**Comment by jorkzijlstra** [comment]
That it is a must to run all your test sequentially isn't what I call a fix, it is more like a workaround. 

But It works for me. Looking forward for Play 3

**Comment by schmitch** [comment]
Actually your test case:
```scala
import org.scalatestplus.play._

class TestSpec extends PlaySpec with OneServerPerSuite {

  "test" in {
    assert(1 == 1)
  }
}
```
is running sequential by default. only specs2 needs to be called `sequential`. also there are a lot of cases where you can't run in parallel even in play3 it wouldn't work:

- Database Tests (except H2)
- Running a Real Server (if you reuse the same port)

Also it's preferable to run integration tests in sequence and for others you shouldn't start a whole application.
