### ISSUE TITLE
playUpdateSecret dies when it encounters variable substitution in a HOCON file

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#6411]
```
$ sbt
[mywebapp] $ playUpdateSecret
[trace] Stack trace suppressed: run last *:playUpdateSecret for the full output.
[error] (*:playUpdateSecret) com.typesafe.config.ConfigException$NotResolved: called valueType() on value with unresolved substitutions, need to Config#resolve() first, see API docs
[error] Total time: 0 s, completed Aug 11, 2016 11:32:55 AM

[mywebapp] $ last *:playUpdateSecret 
[info] Updating application secret in /var/work/training/projects/public_code/group_play/course_play_scala_intro_code/webapp1/conf/application.conf
com.typesafe.config.ConfigException$NotResolved: called valueType() on value with unresolved substitutions, need to Config#resolve() first, see API docs
	at com.typesafe.config.impl.ConfigDelayedMerge.valueType(ConfigDelayedMerge.java:46)
	at com.typesafe.config.impl.SimpleConfig.hasPath(SimpleConfig.java:96)
	at play.sbt.ApplicationSecretGenerator$$anonfun$updateSecretTask$1.apply(ApplicationSecretGenerator.scala:47)
	at play.sbt.ApplicationSecretGenerator$$anonfun$updateSecretTask$1.apply(ApplicationSecretGenerator.scala:31)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:playUpdateSecret) com.typesafe.config.ConfigException$NotResolved: called valueType() on value with unresolved substitutions, need to Config#resolve() first, see API docs

```

`conf/application.conf` looks like this:

```
play.crypto.secret = changeme
play.crypto.secret = ${?APP_SECRET}
```

Removing the last line solves the problem, and that makes sense. I am reporting this issue in the hope that:

1. resolve() is invoked when parsing application.conf, to prevent the stack dump
1. The default value gets set and the variable substitution is not modified
1. A message is provided to the user so they know what was done (or not done)

**Comment by 012345789** [comment]
👍 for the resolution
