### ISSUE TITLE
Attempted to call materialize() after the ActorMaterializer has been shut down

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#6510]
### Play Version (2.5.x / etc)
2.5.6

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOs 10.11.6 (15G31) 

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode

### Expected Behavior
No exception

### Actual Behavior
This just popped out of nowhere between requests:
```
19:36:58.735 [netty-event-loop-10] [error] play.core.server.netty.PlayRequestHandler - Exception caught in Netty
java.lang.IllegalStateException: Attempted to call materialize() after the ActorMaterializer has been shut down.
        at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:148)
        at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:138)
        at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:351)
        at play.api.libs.streams.SinkAccumulator.run(Accumulator.scala:125)
        at play.api.libs.streams.SinkAccumulator.run(Accumulator.scala:129)
        at play.core.server.netty.PlayRequestHandler.play$core$server$netty$PlayRequestHandler$$handleAction(PlayRequestHandler.scala:258)
        at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:103)
        at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
        at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by nafg** [comment]
What's the code?

**Comment by eximius313** [comment]
Code doesn't matter as it was working all the time unchanged and after restarting the server everything was fine.
I'm curious what could cause such exception?

**Comment by nafg** [comment]
Something calling materialize() after the ActorMaterializer has been shut
down could cause it, I suppose... :)

But if you want to know what's causing *that*... well it might depend on
your code...

**Comment by gmethvin** [comment]
@eximius313 Does anything happen before you get this error? In the past, when we've seen this error, it is due to a fatal exception or error in your application (in dev mode) that prevents it from starting correctly. So in that case the main problem is in your application.

If you can show us code that should otherwise be normally working that fails in this way, then that suggests the problem is with Play.

If you are just generally looking for help, that's fine, but the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a more appropriate forum than this issue tracker.

**Comment by eximius313** [comment]
@gmethvin Actually I'm not looking for help with this issue, because after server restart everything went back to normal.
I had issued this just for you to know.
Code is irrelevant, because it happend sequentially with different requests.

**Comment by gmethvin** [comment]
> Actually I'm not looking for help with this issue, because after server restart everything went back to normal

So this suggests the issue may be with your application. What happened prior to the error.

> Code is irrelevant, because it happend sequentially with different requests.

I'm assuming you're in dev mode. If so, this could happen after your application has already failed for some other reason. If it just happened randomly in a normally functioning app then it's a much more serious problem. This is why we're asking for more information.

**Comment by almothafar** [comment]
I'm getting same issue sometimes, I still can't really find way to remake it, but i'm using play from version 2.3.x and today i'm using 2.5.6, this is first time I think.

Anyway I want to find something common with @eximius313  , do you enabled any filter, or do you have a Startup hook?

For me I was getting exception while using "mapstruct" and that exception was giving me "Stackoverflow" but in the browser I was getting the "java.lang.IllegalStateException: Attempted to call materialize() after the ActorMaterializer has been shut down." statement, while I have to get the real exception like before (as version 2.5.4).

**Comment by schmitch** [comment]
could you list the public libraries you are using, too? And how do you call mapstruct?

It would be cool if you could create a minimal application on github that reproduces the problem.

**Comment by almothafar** [comment]
Currently this is build.sbt : 

```
lazy val root = (project in file(".")).enablePlugins(PlayJava, PlayEbean, Yeoman, LauncherJarPlugin)
scalaVersion := "2.11.8"
libraryDependencies ++= Seq(
  javaJdbc,
  cache,
  javaWs,
  filters,
  evolutions,
  "mysql" % "mysql-connector-java" % "5.1.39",
  "com.typesafe.play" %% "play-mailer" % "5.0.0",
  "de.svenkubiak" % "jBCrypt" % "0.4",
  "org.mapstruct" % "mapstruct-jdk8" % "1.1.0.Beta2",
  "org.mapstruct" % "mapstruct-processor" % "1.1.0.Beta2",
  "commons-io" % "commons-io" % "2.5",
  "org.apache.poi" % "poi" % "3.14",
  "org.apache.poi" % "poi-ooxml" % "3.14"
)
```

I'll try to create minimal play application with mapstruct and post the link here.

**Comment by shkhln** [comment]
I think there is no need to involve mapstruct, `throw new StackOverflowError()` should be enough.

**Comment by schmitch** [comment]
I still get a `StackOverflowError` then, where did you put the `StackOverflowError`?

**Comment by shkhln** [comment]
With `play-scala` activator template:
```
@Singleton
class HomeController @Inject() extends Controller {

  def index = Action {
    throw new StackOverflowError()
    Ok(views.html.index("Your new application is ready."))
  }
}
```
You need to make at least two http requests of course.

**Comment by schmitch** [comment]
I still get:
```
[ERROR] [09/04/2016 19:24:09.807] [application-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(application)] Uncaught fatal error from thread [application-akka.actor.default-dispatcher-6] shutting down ActorSystem [application]
java.lang.StackOverflowError
```

even after 10 requests.

**Comment by shkhln** [comment]
Interesting. Here is what I am seeing: https://gist.github.com/shkhln/8c767f8be34586cab563ce22882f7fa4.

**Comment by schmitch** [comment]
Actually I reenabled filters and then it happend after some requests while being in a `Failed` state. But that is hardly a bug in play, it's more like that an `Error` should not happen. And the original error is still inside the console.

**Comment by eximius313** [comment]
To me it happened only once.
My libraries:
```
libraryDependencies ++= Seq(
  javaJdbc,
  filters,
  cache,
  javaWs,
  javaJpa,
  "be.objectify" %% "deadbolt-java" % "2.5.0",
  "com.typesafe.play" %% "play-mailer" % "5.0.0-M1",
  "org.apache.commons" % "commons-lang3" % "3.4",
  "org.hibernate" % "hibernate-entitymanager" % "5.1.0.Final",
  "org.jadira.usertype" % "usertype.core" % "5.0.0.GA",
  "org.postgresql" % "postgresql" % "9.4-1206-jdbc42",
  "org.mindrot" % "jbcrypt" % "0.3m",
  "org.elasticsearch" % "elasticsearch" % "1.5.2",
  "org.apache.pdfbox" % "pdfbox" % "1.8.11",
  "com.fasterxml.jackson.datatype" % "jackson-datatype-joda" % "2.5.3",
  "org.apache.tika" % "tika-core" % "1.10",
  "com.github.kenglxn.qrgen" % "javase" % "2.1.0",
  "com.diffplug.durian" % "durian" % "3.3.0",
  "org.jsoup" % "jsoup" % "1.8.3",
  "org.mnode.ical4j" % "ical4j" % "1.0.7",
  "commons-beanutils" % "commons-beanutils" % "1.9.2",
  "com.twelvemonkeys.common" % "common-lang" % "3.2.1",
  "com.twelvemonkeys.imageio" % "imageio-core" % "3.2.1",
  "com.twelvemonkeys.imageio" % "imageio-jpeg" % "3.2.1",
  "com.twelvemonkeys.imageio" % "imageio-tiff" % "3.2.1",
  "com.twelvemonkeys.imageio" % "imageio-bmp" % "3.2.1",
  "org.codehaus.janino" % "janino" % "2.7.8",
  "org.openoffice" % "juh" % "3.2.1",
  "org.openoffice" % "jurt" % "3.2.1",
  "org.openoffice" % "ridl" % "3.2.1",
  "org.openoffice" % "unoil" % "3.2.1",
  "commons-io" % "commons-io" % "2.4",
  "commons-cli" % "commons-cli" % "1.3.1",
  "org.json" % "json" % "20141113",
  "org.webjars" %% "webjars-play" % "2.5.0",
  "org.webjars" % "requirejs" % "2.1.20",
  "org.webjars" % "jquery" % "2.1.4",
  "org.webjars.bower" % "compass-mixins" % "0.12.7",
  "org.webjars.bower" % "bootstrap-sass" % "3.3.6",
  "com.mohiva" %% "play-html-compressor" % "0.6.2",
  "com.edulify" %% "sitemap-module" % "2.1.2",
  "com.github.marcospereira" %% "play-hocon-i18n" % "0.0.2"
)
```

**Comment by shkhln** [comment]
> Probably that's caused since the application in Dev Mode isn't alive anymore. The stop hooks are called already.

No, ActorSystem is dead, but other things are alive.

> Actually I reenabled filters and then it happend after some requests while being in a Failed state. But that is hardly a bug in play, it's more like that an Error should not happen. 

It's primarily a usability issue. From the user perspective Play should either report something in browser, or crash completely and report something on terminal. Anything else would be confusing.

> And the original error is still inside the console.

There is one IllegalStateException per http request. With IllegalStateException exceptions taking several screens it could be quite easy to miss.

**Comment by schmitch** [comment]
> No, ActorSystem is dead, but other things are alive.

Yeah you are right, but it's still a "bug" inside the application. Akka shut's itself down if it see's a `Fatal` error.

> It's primarily a usability issue. From the user perspective Play should either report something in browser, or crash completely and report something on terminal. Anything else would be confusing.

I doubt it's not that easy to catch that error from akka or prevent it from shutdown and then give a useful exception of the original Fatal error.

> There is one IllegalStateException per http request. With multiple IllegalStateException exceptions taking several screens it could be quite easy to miss.

Since that only happens in Dev mode (in Prod mode the application would die) it's barley a problem.

**Comment by shkhln** [comment]
> Yeah you are right, but it's still a "bug" inside the application. Akka shut's itself down if it see's a Fatal error.

Yes, but imo the application should be shut down too.

> in Prod mode the application would die, hopefully

Hopefully. Actually, it is easy to check and it doesn't die for me.

**Comment by schmitch** [comment]
add the following to your `application.conf`:

```
akka {
  jvm-exit-on-fatal-error = true
```

**Comment by schmitch** [comment]
Actually play sets that to false, but I guess that's a bad default. Even in dev mode.

**Comment by shkhln** [comment]
> Actually play sets that to false, but I guess that's a bad default. Even in dev mode.

Oh, I see. It's likely there for a reason but it is totally wrong default for the prod mode.

**Comment by gmethvin** [comment]
@schmitch Yeah, so I would say that in dev mode we should set `jvm-exit-on-fatal-error = true`. This should prevent the issue seen here. I think it makes sense to do the same in prod and test. There was a prior issue regarding the test case: #1807

**Comment by schmitch** [comment]
Actually I guess it's even more important in Prod mode. Keeping the application alive while it can't handle a request is probably a bad idea.

**Comment by gmethvin** [comment]
@schmitch Agreed

**Comment by almothafar** [comment]
Well, i'm not sure If i'm a late or this will make any help, but I was able to re-make the issue here: 
https://github.com/almothafar/play-with-mapstruct

**Comment by gmethvin** [comment]
@almothafar The conclusion we reached here is that this error happens in dev mode following a fatal error occurring in your application. We fixed the issue by killing the JVM when a fatal error happens, by setting `akka.jvm-exit-on-fatal-error = true`. Is that the case in your project as well?

**Comment by schmitch** [comment]
Actually I checked his application and it somehow recieves a `StackOverflowError`:
First it tries to load a class via laodClass:
```
java.lang.StackOverflowError: null
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:1038)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:406)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
That fails of course and then it tries to make:
```
at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.mapstruct.factory.Mappers.doGetMapper(Mappers.java:99)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:87)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:76)
	at mappers.AccountMapperImpl.<init>(AccountMapperImpl.java:37)
```
over and over again

**Comment by almothafar** [comment]
@gmethvin I just promised to give you a project that you can see an issue in my second comment.

And I tried adding `akka.jvm-exit-on-fatal-error = true` and its "solving" the issue toughly with killing the process, I wish if there is a better way, its annoying to restart project each time issue like this happened, specially I'm developing with hot swap.

Is there anyway to "reboot" the akka system instead ?

and do I need to add `akka.jvm-exit-on-fatal-error = false` into production?

**Comment by almothafar** [comment]
I'm not sure really about how to reboot akka, but with google found something like this: https://gist.github.com/Kayrnt/9082178

**Comment by schmitch** [comment]
Actually for 2.6 I maybe have a idea to print the error to the browser window and then have a button that reload's the application, like it is done by evolutions. But I'm not sure.
