### ISSUE TITLE
[2.5.6] play-scala-intro does not run evolutions

### ISSUE THREAD

**Issue by Notalifeform** [playframework/playframework#6537]
### Operating System 

OSX 10.11.6

### JDK 

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. localhost:9000 - Database 'default' needs evolution!
2. user: press 'apply this script now!' 
3. application will start

### Actual Behavior

1. localhost:9000 - Database 'default' needs evolution!
2. user: press 'apply this script now!' 
3. localhost:9000 - Database 'default' needs evolution!
4. user: press 'apply this script now!' 

conclusion: evolution is not executed

reproduction:

`/Users/robert/work/scala/play/activator-1.3.10-minimal/bin/activator new my-first-app1 play-scala-intro   `                               

Fetching the latest list of templates...

OK, application "my-first-app1" is being created using the "play-scala-intro" template.

To run "my-first-app1" from the command line, "cd my-first-app1" then:
/Users/robert/work/scala/play/test/my-first-app1/activator run

To run the test for "my-first-app1" from the command line, "cd my-first-app1" then:
/Users/robert/work/scala/play/test/my-first-app1/activator test

To run the Activator UI for "my-first-app1" from the command line, "cd my-first-app1" then:
/Users/robert/work/scala/play/test/my-first-app1/activator ui

`~/work/scala/play/test % cd my-first-app1    `                                                                                                                      
`~/work/scala/play/test/my-first-app1 % sbt run   `                                                                                                                  
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
[info] Loading project definition from /Users/robert/work/scala/play/test/my-first-app1/project
[info] Updating {file:/Users/robert/work/scala/play/test/my-first-app1/project/}my-first-app1-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to my-first-app1 (in build file:/Users/robert/work/scala/play/test/my-first-app1/)
[info] Updating {file:/Users/robert/work/scala/play/test/my-first-app1/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

`(pointed browser at http://localhost:9000/ )`
 
[info] Compiling 9 Scala sources and 1 Java source to /Users/robert/work/scala/play/test/my-first-app1/target/scala-2.11/classes...
[info] CoffeeScript compiling on 1 source(s)
[info] LESS compiling on 1 source(s)
[error] application - 

! @719ad92g6 - Internal server error, for (GET) [/] ->
 
play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:77)
        at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:99)
        at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
        at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:150)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)
[error] application - 

` (pressed 'Apply this script now!')`

! @719af11hd - Internal server error, for (GET) [/] ->
 
play.api.db.evolutions.InvalidDatabaseRevision: Database 'default' needs evolution![An SQL script need to be run on your database.]
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:77)
        at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:99)
        at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
        at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:150)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)

`

**Comment by cchantep** [comment]
Hi, as mentioned please use the [MailingList]( https://groups.google.com/forum/m/#!topic/play-framework/URcaA1ueS7I). This tracker is for confirmed issue. Best regards.

**Comment by schmitch** [comment]
Actually I can confirm this. Happens only on play-slick-evolutions tough. But since the template is inside this repository...

**Comment by schmitch** [comment]
@Notalifeform actually the database does the evolutions, but they are lost since the database is restarted, but the config did not contain `DB_CLOSE_DELAY=-1`

**Comment by Notalifeform** [comment]
yep. works like a charm.

**Comment by pan5431333** [comment]
I've encountered this issue too using play with slick. Anyone can help?
