### ISSUE TITLE
OutOfMemoryError: Java heap space when running Play 2.5 on EmbeddedBoard

### ISSUE THREAD

**Issue by M-Razavi** [playframework/playframework#6550]
I'm going to run a sample of Play framework on Cubie Board2 ( It's a embedded board, You can see all information about it [here](https://en.wikipedia.org/wiki/Cubieboard#Cubieboard2)) 
But when i copy dist zipped file to the board and run it, Error OutOfMemoryError printed (there is 700MB free ram on this board).

This is output of free command:
> [root@if4_192-168-122-103 bin]# free
                  total           used           free       shared     buffers     cached
Mem:        977196     239324     737872        548       9476     115192
-/+ buffers/cache:       114656     862540
Swap:            0                  0                  0

This is error message:

`
Droot@if4_192-168-122-103 bin]# ./test44
Oops, cannot start the server.
com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: Java heap space
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2205)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4881)
        at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:136)
        at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:547)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:884)
        at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
        at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
        at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
        at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:890)
        at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
        at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:134)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.google.inject.internal.asm.$ClassWriter.b(Unknown Source)
        at com.google.inject.internal.asm.$ClassWriter.a(Unknown Source)
        at com.google.inject.internal.asm.$ClassWriter.newNameType(Unknown Source)
        at com.google.inject.internal.asm.$ClassWriter.a(Unknown Source)
        at com.google.inject.internal.asm.$MethodWriter.visitMethodInsn(Unknown Source)
        at com.google.inject.internal.asm.$MethodVisitor.visitMethodInsn(Unknown Source)
        at com.google.inject.internal.cglib.core.$CodeEmitter.emit_invoke(CodeEmitter.java:500)
        at com.google.inject.internal.cglib.core.$CodeEmitter.invoke_virtual(CodeEmitter.java:511)
        at com.google.inject.internal.cglib.core.$CodeEmitter.invoke(CodeEmitter.java:856)
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter$4.processCase(FastClassEmitter.java:180)
        at com.google.inject.internal.cglib.core.$CodeEmitter.process_switch(CodeEmitter.java:629)
        at com.google.inject.internal.cglib.core.$CodeEmitter.process_switch(CodeEmitter.java:602)
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.invokeSwitchHelper(FastClassEmitter.java:169)
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:91)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
        at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
        at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:54)
        at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:159)
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:90)
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
[root@if4_192-168-122-103 bin]#
`

**Comment by calvinlfer** [comment]
Hey @M-Razavi 
Check out https://github.com/playframework/playframework/issues/6491
An update to Play 2.5.7 will likely fix your problem

**Comment by schmitch** [comment]
Actually this is not a issue with play and more that most Java Apps aren't designed to run on every ARM device. Since most problems are looking like google guice errors you could try running without guice and just use another DI mechanism.

We also don't directly support non x86 based processors, that's why I'm closing this as of know.
