### ISSUE TITLE
Error when using StreamConverters.asOutputStream for a chunked response

### ISSUE THREAD

**Issue by halfninja** [playframework/playframework#6579]
### Play Version

2.5.8

### API

Scala

### Operating System)

Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### Library Dependencies

None (other than the standard included akka-streams)

### Expected Behavior

1. Use StreamConverters.asOutputStream to write a chunked response to an OutputStream
2. Consistently get back that response.

### Actual Behavior  

1. The first request is successful
2. Subsequent requests throw "internal error" from within akka-streams. Nothing in the controller is re-using objects between requests.

### Reproducible Test Case

Clone this and run `bin/activator test` to try two requests, the second of which will fail. HomeController includes alternate Source that is from a Publisher that's converted from an Enumerator, which does work fine.

https://github.com/halfninja/play-outputstream-bug.git

**Comment by halfninja** [comment]
There is also this exception, which we get in production because we use a library that utilities PrintWriter for output. In production it also causes a stuck thread, so after enough requests the app is unresponsive.

If you instead write the data out using a PrintWriter, there is no output - PrintWriter brilliantly swallows the specifics of an IOExceptions during flush, but a breakpoint reveals this:

```
java.io.IOException: java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor
	at java.io.PrintWriter.flush(PrintWriter.java:324)
	at controllers.HomeController.write(HomeController.scala:36)
	at controllers.HomeController$$anonfun$controllers$HomeController$$brokenSource$1.apply(HomeController.scala:22)
	at controllers.HomeController$$anonfun$controllers$HomeController$$brokenSource$1.apply(HomeController.scala:22)
	at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:959)
	at akka.stream.impl.MaterializerSession.resolveMaterialized(StreamLayout.scala:958)
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:936)
	at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:882)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:240)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:138)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:350)
	at akka.stream.scaladsl.Source.runWith(Source.scala:81)
	at play.core.server.netty.NettyModelConversion.play$core$server$netty$NettyModelConversion$$createChunkedResponse(NettyModelConversion.scala:256)
	at play.core.server.netty.NettyModelConversion$$anonfun$convertResult$1.apply(NettyModelConversion.scala:189)
	at play.core.server.netty.NettyModelConversion$$anonfun$convertResult$1.apply(NettyModelConversion.scala:166)
	at play.core.server.common.ServerResultUtils$.resultConversionWithErrorHandling(ServerResultUtils.scala:127)
	at play.core.server.netty.NettyModelConversion.convertResult(NettyModelConversion.scala:235)
	at play.core.server.netty.PlayRequestHandler$$anonfun$play$core$server$netty$PlayRequestHandler$$handleAction$2$$anonfun$apply$3.apply(PlayRequestHandler.scala:273)
	at play.core.server.netty.PlayRequestHandler$$anonfun$play$core$server$netty$PlayRequestHandler$$handleAction$2$$anonfun$apply$3.apply(PlayRequestHandler.scala:267)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$flatMap$1$$anonfun$apply$3.apply(Future.scala:254)
	at scala.concurrent.Future$$anonfun$flatMap$1$$anonfun$apply$3.apply(Future.scala:254)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$KeptPromise.onComplete(Promise.scala:333)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:254)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalStateException: not yet initialized: only setHandler is allowed in GraphStageLogic constructor
	at akka.stream.stage.GraphStageLogic.interpreter(GraphStage.scala:242)
	at akka.stream.stage.GraphStageLogic$$anon$2.invoke(GraphStage.scala:885)
	at akka.stream.impl.io.OutputStreamSourceStage$$anon$1.wakeUp(OutputStreamSourceStage.scala:73)
	at akka.stream.impl.io.OutputStreamSourceStage$$anonfun$createLogicAndMaterializedValue$2.apply(OutputStreamSourceStage.scala:154)
	at akka.stream.impl.io.OutputStreamSourceStage$$anonfun$createLogicAndMaterializedValue$2.apply(OutputStreamSourceStage.scala:154)
	at akka.stream.impl.io.OutputStreamAdapter$$anonfun$sendMessage$1.apply$mcV$sp(OutputStreamSourceStage.scala:193)
	at akka.stream.impl.io.OutputStreamAdapter.send(OutputStreamSourceStage.scala:172)
	at akka.stream.impl.io.OutputStreamAdapter.sendMessage(OutputStreamSourceStage.scala:191)
	at akka.stream.impl.io.OutputStreamAdapter.flush(OutputStreamSourceStage.scala:215)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at java.io.PrintWriter.flush(PrintWriter.java:320)
	... 56 more
```

**Comment by halfninja** [comment]
Doing more debugging, it is the same root exception both times. When using a plain OutputStream, the "internal error" seems to be an error in the error handling, attempting to subscribe to an error publisher. A breakpoint in the `NonFatal` `catch` statement of `StreamLayout.materialize` reveals the exception above.

**Comment by halfninja** [comment]
I may have reproduced this problem with akka-streams alone so hold that thought.

**Comment by schmitch** [comment]
@halfninja that happens since you flush before  the Stage is setup. if you add a 
Future { Thread.sleep(1); /* do your outputstream stuff here */ }
it works, it's probably a akka-stream bug as you've seen.  Also in our Services we used a PipedOutputStream, since the push model actually fits the http chunk model a little bit better. And this is also the reason why I'm against https://github.com/playframework/playframework/pull/6464 without understanding the whole stuff a little bit, they can be quite a pain to use. Especially since their is blocking going on internally.

**Comment by halfninja** [comment]
Hi Schmitt

It works here too using the `Future`, so it seems like mapMaterializedValue is indeed too early to be flushing data. Not really production-safe code though! I reproduced in plain Akka as seen here (run with sbt command `akka-stream-tests/test-only akka.stream.io.OutputStreamSourceSpec`):

https://github.com/halfninja/akka/commit/df560dd640125fb37813b1f02d99894cda4db3be

I can't actually find any documentation that says mapMaterializedValue is the right way to get at the OutputStream. There's one akka-users post which suggests using `.run` to get the `OutputStream` instead, which I don't think is any good as we need to pass the Source to Play, not run it ourselves.

https://groups.google.com/forum/#!topic/akka-user/T9un7z5ieug

In the meantime `Source.fromPublisher(Streams.enumeratorToPublisher(Enumerator.outputStream(writeFunc)))` works in Play without deprecation warnings. Looks a bit clunky but does the job.

**Comment by schmitch** [comment]
@halfninja you can materialize it via `StreamConverters.asOutputStream().toMat(Sink.asPublisher(false)(Keep.both).run()` but I guess that might fail as well, at least when I tried.
If you want to dig deeper and you think that might be related to akka-stream you can also post it to their issue tracker: https://github.com/akka/akka/issues

**Comment by halfninja** [comment]
Opened Akka issue to see if they think this is a bug or just a misuse of mapMaterializedValue.

**Comment by schmitch** [comment]
@halfninja you could also try:
```scala
// out is you outputStream and pub is your publisher
val (out, pub) = StreamConverters.asOutputStream().toMat(Sink.asPublisher(false)(Keep.both).run()
Source.fromPublisher(out)
```

**Comment by halfninja** [comment]
Thanks. Think I tried that and the response never returned. Maybe I left something out. Am happy with using the conversion from Enumeratee to Publisher (which doesn't generate any deprecation warnings) for now until there is some change to Akka.
