### ISSUE TITLE
Compatablility issue between ws and play-test

### ISSUE THREAD

**Issue by jorkzijlstra** [playframework/playframework#6628]
I was using 'ws' and "com.typesafe.play" %% "play-test" % playVersion % "test" in my library dependencies. 
Using playVersion > 2.5.4 causes an exception to occur when running any tests

### Play Version (2.5.x / etc)
Play greater than 2.5.4

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

### Library Dependencies

libraryDependencies ++= Seq(
    ws,
    "com.typesafe.play" %% "play-test" % "2.5.8" % "test",
    "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1" % "test"
  )

### Actual Behavior

Running test throws an exception:

`[info] Exception encountered when attempting to run a suite with class name: controllers.TestSpec *** ABORTED ***
[info]   java.lang.NoSuchFieldError: DEFAULT_MAX_PENDING_TASKS
[info]   at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:135)
[info]   at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)
[info]   at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
[info]   at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
[info]   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)
[info]   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)
[info]   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)
[info]   at play.core.server.NettyServer.<init>(NettyServer.scala:77)
[info]   at play.core.server.NettyServerProvider.createServer(NettyServer.scala:279)
[info]   at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
[info]   ...
[error] Uncaught exception when running controllers.TestSpec: java.lang.NoSuchFieldError: DEFAULT_MAX_PENDING_TASKS
sbt.ForkMain$ForkError: java.lang.NoSuchFieldError: DEFAULT_MAX_PENDING_TASKS
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:135)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)
	at play.core.server.NettyServer.<init>(NettyServer.scala:77)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:279)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
	at play.core.server.ServerProvider$class.createServer(ServerProvider.scala:25)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
	at play.api.test.TestServer$.start(TestServer.scala:80)
	at play.api.test.TestServer.start(TestServer.scala:42)
	at org.scalatestplus.play.OneServerPerSuite$class.run(OneServerPerSuite.scala:177)
	at controllers.TestSpec.run(TestSpec.scala:8)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:357)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:502)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

### Reproducible Test Case

[test.zip](https://github.com/playframework/playframework/files/515686/test.zip)

### Temporary fix
1) Dependency "ws" resolves to Play 2.5.0. Replace it for "com.typesafe.play" %% "play-ws" % "2.5.8"
2) Downgrade play-test dependency to at max Play version 2.5.4 ("com.typesafe.play" %% "play-test" % "2.5.4" % "test")

**Comment by gmethvin** [comment]
@jorkzijlstra Generally we expect you to use the same Play version for all your Play dependencies, including play-test. The problem here is that we upgraded Netty in 2.5.5 and Netty introduced some binary incompatibilities.

If I upgrade the Play plugin to 2.5.8 in your project the tests work fine. If there's another reason you can't upgrade your Play plugin that's another issue.
