### ISSUE TITLE
Configuration error on Windows after SBT Reload

### ISSUE THREAD

**Issue by curreli** [playframework/playframework#6630]
### Play Version (2.5.x / etc)

2.5.8

The project is in a multi-project setup:

```
root
  common
  backend
  frontend -> Play App
```

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Run play App with `sbt "project frontend" run`
2. Browse some pages
3. SBT compiles
4. View page result
5. Make some changes
6. Refresh page, or browse another page
7. SBT detects changes and compiles them (reload)
8. View modified page result

### Actual Behavior

Browsing a page after some changes have been recompiled **(8)** fails with a `Configuration Exception` on Windows. I am working on the same project codebase on two machines. The first one is a Laptop running Ubuntu on which I do not have any problem. When running the exact same project on a Windows 10 desktop, everything works until I make a change and SBT reload and recompile the modified files. If I stop sbt and run `sbt "project frontend" run` again, then it works. Basically, it works the first time it is run and then fails after a change is made.

1. Run play App with `sbt "project frontend" run`
2. Browse some pages
3. SBT compiles
4. View page result
5. Make some changes
6. Refresh page, or browse another page
7. SBT detects changes and compiles them (reload)
8. **Configuration error is returned**

```
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Compiling 1 Scala source to C:\Users\Alexandre\Code\Project\Main\frontend\target\classes...
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Packaging C:\Users\Alexandre\Code\Project\Main\frontend\target\frontend-0.0.1.jar ...
[info] Done packaging.

--- (RELOAD) ---

! @71jj6eeio - Internal server error, for (GET) [/] ->
 
play.api.Configuration$$anon$1: Configuration error[application: application.conf @ jar:file:/C:/Users/Alexandre/Code/Project/Main/frontend/target/frontend-0.0.1.jar!/application.conf: java.io.FileNotFoundException: JAR entry application.conf not found in C:\Users\Alexandre\Code\Project\Main\frontend\target\frontend-0.0.1.jar, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties]
	at play.api.Configuration$.configError(Configuration.scala:154)
	at play.api.Configuration$.load(Configuration.scala:101)
	at play.api.Configuration$.load(Configuration.scala:109)
	at play.api.ApplicationLoader$.createContext(ApplicationLoader.scala:94)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:165)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:164)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:164)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:131)
	at scala.Option.map(Option.scala:146)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:131)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:129)
	at scala.util.Success.flatMap(Try.scala:231)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:129)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:121)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.typesafe.config.ConfigException$IO: application: application.conf @ jar:file:/C:/Users/Alexandre/Code/Project/Main/frontend/target/frontend-0.0.1.jar!/application.conf: java.io.FileNotFoundException: JAR entry application.conf not found in C:\Users\Alexandre\Code\Project\Main\frontend\target\frontend-0.0.1.jar, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:236)
	at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:132)
	at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:1024)
	at com.typesafe.config.ConfigFactory.parseApplicationConfig(ConfigFactory.java:238)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:519)
	at play.api.Configuration$$anonfun$3.apply(Configuration.scala:73)
	at play.api.Configuration$$anonfun$3.apply(Configuration.scala:69)
	at scala.Option.getOrElse(Option.scala:121)
	at play.api.Configuration$.load(Configuration.scala:69)
	... 21 common frames omitted
Caused by: com.typesafe.config.ConfigException$IO: application.conf @ jar:file:/C:/Users/Alexandre/Code/Project/Main/frontend/target/frontend-0.0.1.jar!/application.conf: java.io.FileNotFoundException: JAR entry application.conf not found in C:\Users\Alexandre\Code\Project\Main\frontend\target\frontend-0.0.1.jar
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:307)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:747)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
	... 29 common frames omitted
Caused by: java.io.FileNotFoundException: JAR entry application.conf not found in C:\Users\Alexandre\Code\Project\Main\frontend\target\frontend-0.0.1.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:142)
	at com.typesafe.config.impl.Parseable$ParseableURL.reader(Parseable.java:542)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:231)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	... 37 common frames omitted
```

### Reproducible Test Case

I unfortunately cannot share the code.

**Comment by ddulaney** [comment]
Hi @curreli - Any luck with this? I'm having the same problem. It runs fine on linux, but I get this exception on Windows 7 when I hit `localhost:9000` in a browser:
```
Caused by: java.io.FileNotFoundException: JAR entry application.conf not found in C:\Users\ddulaney\git\chia-core\chia-core\target\scala-2.11\chia-core_2.11-1.0.0.jar
```

I'm using Play 2.5.3 and have tried Oracle JDK 1.8 and OpenJDK 1.8. I've inspected that JAR file in IntelliJ and `application.conf` is in there!

**Comment by jn-se** [comment]
I had the same problem. The solution is given here:
https://github.com/playframework/playframework/issues/7310
