### ISSUE TITLE
Play ScalaErrorHandling not working for filters and action composition

### ISSUE THREAD

**Issue by cricanr** [playframework/playframework#6658]
### Are you looking for help?

We have implemented the play error handling like in the [documentation:](https://www.playframework.com/documentation/2.5.x/ScalaErrorHandling). It works fine whenever the "failure" happens inside the controller logic, but we noticed that it does not kick in at all when the failure happens in any Play Filter or action composition. It always goes in the "base" ```DefaultHttpErrorHandler```, for example in method: ```onServerError```. 
Attached you can find our PublishingErrorHandler class that extends the base DefaultHttpErrorHandler class, an example filter code and how we use the filter in our controller.

### Play Version (2.5.x / etc)
2.5.9

### API (Scala / Java / Neither / Both)
Scala: 2.11.8
Java: JDK 8 Oracle

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS: 10.12 (16A323) (local) and AWS Linux AMI (prod)

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### Expected Behavior

1. An error happens inside any filter => our PublishingErrorHandler is called with the appropriate error handling method.
2. An error happens inside any action composition => our PublishingErrorHandler is called with the appropriate error handling method.
3. The default base error handler is overridden and not called in both cases.

### Actual Behavior
1. Error / failure happens inside the controller logic => custom error handler is called correctly.

2. Error happening in Play filter or action composition => default error handler is called only.

Reproducing test case instructions:
Setting an unknown language in the route file:
 ```GET        /results                                        @com.autoscout24.classifiedlist.controllers.ListController.index(language = "uu")
```
Running locally the play application (using ```./activator run```): [local](http://localhost:9000/results)
Leads to a crash and the custom error handling is not called.
See stack trace, exception: 
```
[error] application -

! @71n22fc1d - Internal server error, for (GET) [/results] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[Exception: Unsupported language in routes file: uu]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:45)
	at play.core.server.Server$class.getHandlerFor(Server.scala:65)
	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:47)
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:82)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
Caused by: java.lang.Exception: Unsupported language in routes file: uu
	at com.autoscout24.classifiedlist.i18n.Localized$$anonfun$toLanguageType$1.apply(Localized.scala:70)
	at com.autoscout24.classifiedlist.i18n.Localized$$anonfun$toLanguageType$1.apply(Localized.scala:70)
	at scala.Option.getOrElse(Option.scala:121)
	at com.autoscout24.classifiedlist.i18n.Localized$.toLanguageType(Localized.scala:69)
	at com.autoscout24.classifiedlist.i18n.Localized.actionAsyncWithLang(Localized.scala:38)
	at com.autoscout24.classifiedlist.controllers.ListController.listPage(ListController.scala:72)
	at com.autoscout24.classifiedlist.controllers.ListController.index(ListController.scala:68)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(Routes.scala:1425)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(Routes.scala:1425)
	at play.core.routing.HandlerInvokerFactory$$anon$12$$anon$13.call(HandlerInvoker.scala:95)

```

### Reproducible Test Case

[Localized.txt](https://github.com/playframework/playframework/files/541177/Localized.txt)

see above test cases and attached code for:
- PublishingErrorHandler
- route conf (see above)
- ListController filter / action composition call:
```package com.autoscout24.classifiedlist.controllers

import javax.inject.Singleton

import akka.actor.ActorSystem
import com.autoscout24.classifiedlist._
import com.autoscout24.classifiedlist.ads.AdTargeting
import com.autoscout24.classifiedlist.app.Configuration
import com.autoscout24.classifiedlist.controllers.ListController.AdTargetingTimeoutException
import com.autoscout24.classifiedlist.controllers.QueryParamExtractions._
import com.autoscout24.classifiedlist.controllers.actions._
import com.autoscout24.classifiedlist.i18n.As24CountryKeys.As24CountryKey
import com.autoscout24.classifiedlist.i18n.Languages.Language
import com.autoscout24.classifiedlist.i18n.Tlds.Tld
import com.autoscout24.classifiedlist.i18n.{Languages, Localized, UrlSupport}
import com.autoscout24.classifiedlist.models.ModelsJsonApi.ModelsResponse
import com.autoscout24.classifiedlist.models.filtersummary.FilterSummary
import com.autoscout24.classifiedlist.models.seo._
import com.autoscout24.classifiedlist.models.tracking.Tracking
import com.autoscout24.classifiedlist.models.{ClientFailure, FiltersModel}
import com.autoscout24.classifiedlist.parameters._
import com.autoscout24.classifiedlist.services.TaxonomyService.MakeInfos
import com.autoscout24.classifiedlist.services.{ClassifiedListBuilder, ClassifiedListService, TaxonomyService}
import com.autoscout24.eventpublisher24.events.TypedEventPublisher
import com.autoscout24.eventpublisher24.request.ScoutRequestMeta
import com.autoscout24.taxonomy.model.Car
import com.google.inject.Inject
import com.kenshoo.play.metrics.Metrics
import featurebee.api.FeatureRegistry
import org.scalactic.{Bad, Good}
import play.api.i18n.{Lang, MessagesApi}
import play.api.libs.concurrent.Execution.Implicits._
import play.api.mvc._

import scala.concurrent.Future
import scala.concurrent.duration._
import scala.language.postfixOps

@Singleton
class ListController @Inject()(classifiedListService: ClassifiedListService,
                               taxonomyService: TaxonomyService,
                               config: Configuration,
                               urlSupport: UrlSupport,
                               val messagesApi: MessagesApi,
                               metrics: Metrics,
                               actorSystem: ActorSystem
                              )(implicit featureRegistry: FeatureRegistry, publisher: TypedEventPublisher) extends Localized(messagesApi, urlSupport) {

  val maybeAdTargetingTimer = Option(metrics.defaultRegistry.timer("ad-targeting")) // not needed in tests

  private def defaultParams(tld: Tld) = {
    val (extractedDefaultsOr, remaining) = extractionChain(tld)(Map())
    UpstreamParameters
      .flatten(extractedDefaultsOr.getOrElse(ExtractedParams()).toUpstreamParamSeq :+ new PassThroughParameters(remaining))
      .toQueryParamMap
  }
  private def extractionChain(tld: Tld) = queryParamsToTupleOfValidatedParamsAndRemainingParams(taxonomyService, tld)

  def untrail(path: String) = Action { implicit request =>
    if (request.rawQueryString.isEmpty) {
      MovedPermanently("/" + path)
    } else {
      MovedPermanently("/" + path + "?" + request.rawQueryString)
    }
  }

  def listElements(language: String) = listPage(language, fullPage = false)
  def index(language: String) = listPage(language, fullPage = true)

  private def listPage(language: String, fullPage: Boolean) =
    Cors { Timing { Tagging { Pricing { Actions.addVisitorCookie {
              actionAsyncWithLang(language) { implicit request => implicit messages =>
   
              // rest of our business logic, not relevant
```

**Comment by alex-voigt** [comment]
We also ran into the same problem...

**Comment by team3** [comment]
Faced with the same problem. Do we have any workaround?

**Comment by wsargent** [comment]
@cricanr There is no PublishingErrorHandler class attached.  @alex-voigt or @team3 can you provide a sample play application on github reproducing the issue?

**Comment by bpaczkowski** [comment]
Experiencing the same problem, only I'm directly implementing `HttpErrorHandler`. I don't have an example, but the `DefaultHttpErrorHandler` is being referenced here: [click](https://github.com/playframework/playframework/blob/145314cbab94d9ffb8abe14c9e4b65a10839b62f/framework/src/play-server/src/main/scala/play/core/server/Server.scala#L114).

**Comment by marcospereira** [comment]
Is it possible to reproduce this error on Play 2.6.10+? I think https://github.com/playframework/playframework/pull/8091 fixed the problem.

**Comment by bpaczkowski** [comment]
I'm using Lagom, which has Play 2.6.11 as a dependency, so yes, I think it is still reproducible. But I will try and test it again this weekend with bare Play and see how it works.

**Comment by rogerzxu** [comment]
Having the same issue, only that it is our custom `onForbidden` error handler that is being bypassed. We are using action composition for authorization and returning forbidden for invalid requests, and this also does not work.

**Comment by Enalmada** [comment]
I am using play 2.6.15 with [silhouette](https://github.com/mohiva/play-silhouette) for authentication and trying to override onDevServerError from DefaultHttpErrorHandler and it isn't working.  The strange thing is that my override of onProdServer and onNotFound is working in production because I see my custom templates in prod but for the life of me I can't get onDevServer error to take in dev mode.  Could that be something to do with this ticket?

**Comment by gmethvin** [comment]
If any of you have an example we can look at that would be ideal. There may be some edge cases that weren't considered before.

The only time the default error handler should be used is when the error happens while the application is being instantiated.

**Comment by adamrabung** [comment]
Here is a small example of statuses generated by Action builders not using the customer error handler. After LoggedIn generates a Forbidden, I was hoping onClientError would be called in CustomerErrorHandler.
HomeController.scala:
```
package controllers

import javax.inject._
import play.api._
import play.api.http.HttpErrorHandler
import play.api.i18n.MessagesApi
import play.api.mvc.Results._
import play.api.mvc._
import scala.concurrent.ExecutionContext
import scala.concurrent.Future

@Singleton
class HomeController @Inject() (LoggedIn: LoggedIn, val controllerComponents: ControllerComponents) extends BaseController {
  def index() = Action.andThen(LoggedIn) { implicit request: Request[AnyContent] =>
    Ok(views.html.index())
  }
}

case class LoggedIn @Inject() (parser: BodyParsers.Default)(implicit val executionContext: ExecutionContext) extends ActionRefiner[Request, Request] {
  override def refine[A](req: Request[A]): Future[Either[Status, Request[A]]] = Future.successful {
    Left(Forbidden)
  }
}

class CustomErrorHandler @Inject() (val messagesApi: MessagesApi) extends HttpErrorHandler {
  override def onClientError(request: RequestHeader, statusCode: Int, message: String) = {
    Future.successful(Ok("Got status " + statusCode)) // <-- this is never called, Play just passes a standard 403 to the browser
  }
  override def onServerError(request: RequestHeader, ex: Throwable) = {
    Future.successful(Ok("Got server error " + ex))
  }
}
```
application.conf:
`play.http.errorHandler="controllers.CustomErrorHandler"`

I verified my custom handler was configured correctly by throwing an error from LoggedIn & noting that onServerError was actually called. So the problem seems limited to `onClientError`

**Comment by gmethvin** [comment]
@adamrabung I think you've misunderstood the purpose of the `HttpErrorHandler`. Its purpose is to provide a mechanism for for you to customize the error responses returned by the framework. For example, if a Play body parser wants to return a 400 for a malformed body, it will call `onClientError`.

If your action code is producing the `Result` instance, then Play will use the result you provided. If you want to use the same error handling logic as in the `HttpErrorHandler`, you can inject it and call `onClientError` or `onServerError` directly in your code.
