### ISSUE TITLE
HttpEntity.Streamed built from OutputStream hangs or throws IllegalStateException

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#6743]
### Setup
Play Version 2.5.9
API Scala
MacOS 10.12.1
JDK Oracle
```
➜  ~ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

### Expected behavior

1. go to http://localhost:9000
2. I expect to get a file download

### Actual Behavior

2 options

- I get an error as posted below (using brokenSource)
- the request hangs forever (using brokenSource2)

_also provided case where using Source.single_ with single byte works

### Reproducible Test Case

just replace index in HomeController.scala for the default  Play Scala Seed 2.5.9 with the below code 

```scala

  def index = Action {

    val source = brokenSource()
    //val source = brokenSource2()
    //val source = okSource()

    val name = "test.bin"

    Result(
      ResponseHeader(OK,
        Map(
          CONTENT_DISPOSITION -> {
            val dispositionType = "attachment"
            s"""$dispositionType; filename="$name"; filename*=utf-8''${UriEncoding.encodePathSegment(name, StandardCharsets.UTF_8)}"""
          }
        )
      ),
      HttpEntity.Streamed(
        source,
        None,
        play.api.libs.MimeTypes.forFileName(name).orElse(Some(play.api.http.ContentTypes.BINARY))
      )
    )

  }

  private def brokenSource(): Source[ByteString, Unit] = {
    StreamConverters.asOutputStream().mapMaterializedValue { outputStream =>
      // just to be sure
      scala.concurrent.blocking {
        (1 to 200).foreach { _ =>
          outputStream.write(1)
        }
        outputStream.flush()
        outputStream.close()
      }
    }
  }

  private def brokenSource2(): Source[ByteString, Unit] = {
    StreamConverters.asOutputStream().mapMaterializedValue { outputStream =>
      outputStream.write(1)
      outputStream.flush()
      outputStream.close()
    }
  }

  private def okSource(): Source[ByteString, NotUsed] = {
    Source.single(ByteString(1))
  }

```

### Remark

Tried to reproduce this in a simple akka streams 2.4.10 project but failed to reproduce it

### Exception trace for the case where a single byte is written

```
! @72518pn5m - Internal server error, for (GET) [/] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ServerResultException: Error converting Play Result for server backend]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.common.ServerResultUtils$.play$core$server$common$ServerResultUtils$$handleConversionError$1(ServerResultUtils.scala:106)
	at play.core.server.common.ServerResultUtils$.resultConversionWithErrorHandling(ServerResultUtils.scala:129)
	at play.core.server.netty.NettyModelConversion.convertResult(NettyModelConversion.scala:235)
	at play.core.server.netty.PlayRequestHandler$$anonfun$play$core$server$netty$PlayRequestHandler$$handleAction$2$$anonfun$apply$3.apply(PlayRequestHandler.scala:273)
	at play.core.server.netty.PlayRequestHandler$$anonfun$play$core$server$netty$PlayRequestHandler$$handleAction$2$$anonfun$apply$3.apply(PlayRequestHandler.scala:267)
Caused by: play.core.server.common.ServerResultException: Error converting Play Result for server backend
	at play.core.server.common.ServerResultUtils$.play$core$server$common$ServerResultUtils$$handleConversionError$1(ServerResultUtils.scala:108)
	at play.core.server.common.ServerResultUtils$.resultConversionWithErrorHandling(ServerResultUtils.scala:129)
	at play.core.server.netty.NettyModelConversion.convertResult(NettyModelConversion.scala:235)
	at play.core.server.netty.PlayRequestHandler$$anonfun$play$core$server$netty$PlayRequestHandler$$handleAction$2$$anonfun$apply$3.apply(PlayRequestHandler.scala:273)
	at play.core.server.netty.PlayRequestHandler$$anonfun$play$core$server$netty$PlayRequestHandler$$handleAction$2$$anonfun$apply$3.apply(PlayRequestHandler.scala:267)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
Caused by: java.lang.IllegalStateException: internal error
	at akka.stream.impl.VirtualPublisher.registerPublisher(StreamLayout.scala:797)
	at akka.stream.impl.MaterializerSession.akka$stream$impl$MaterializerSession$$doSubscribe(StreamLayout.scala:999)
	at akka.stream.impl.MaterializerSession$$anonfun$materialize$3$$anonfun$apply$3.apply(StreamLayout.scala:890)
	at akka.stream.impl.MaterializerSession$$anonfun$materialize$3$$anonfun$apply$3.apply(StreamLayout.scala:889)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at akka.stream.impl.MaterializerSession$$anonfun$materialize$3.apply(StreamLayout.scala:889)
	at akka.stream.impl.MaterializerSession$$anonfun$materialize$3.apply(StreamLayout.scala:889)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:889)
```

**Comment by schmitch** [comment]
Unfortunatly, this is not a Bug in Play!

I actually made a PR against akka, to fix this, but I'm not sure how fast I can get it trough (it's my first there).

https://github.com/akka/akka/pull/21866

You might checkout the PR and do `publishLocal` akka and test it against the snapshot if you want.

**Comment by schmitch** [comment]
Closing due to a duplicate of: https://github.com/playframework/playframework/issues/6621

**Comment by francisdb** [comment]
thanks @schmitch , you might want to also link the akka ticket in #6621
