### ISSUE TITLE
Chunked transfer closes stream with empty string

### ISSUE THREAD

**Issue by vdebergue** [playframework/playframework#6750]
### Play Version (2.5.x / etc)

2.5.9

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOs 10.11

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
```

### Expected Behavior

If an akka `Source` contains an empty `String` the chunked http response should not be closed. It should be closed when the source terminates. 

### Actual Behavior

The connection is closed even if the `Source` is not terminated. The connection is closed as soon as an empty `String` is encountered. 

### Reproducible Test Case

```scala
val source: Source[String, _] = Source.single("hello\n").concat(Source.repeat("")) // send "hello" then connection is closed
val source2 : Source[String, _] = Source.single("").concat(Source.repeat("hello\n")) // connection is closed directly

def chunked = Action {
  Ok.chunked(source)
  // Ok.chunked(source2)
}
```

```bash
% curl -v http://localhost:5000/chunked
*   Trying ::1...
* Connected to localhost (::1) port 5000 (#0)
> GET /chunked HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.43.0
> Accept: */*
> Referer:
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: text/plain; charset=utf-8
< Date: Mon, 21 Nov 2016 14:07:53 GMT
<
hello
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

The behaviour is correct when using a `HttpEntity.Streamed`: 
```scala
val wr = Writeable.wString
Ok.sendEntity(HttpEntity.Streamed(source.map(wr.transform(_)), None, wr.contentType)) // connection stays opened
```

When using the akka-http server, I get the following stacktrace:

```
java.lang.AssertionError: assertion failed: Http chunks must not be empty
	at scala.Predef$.assert(Predef.scala:170)
	at play.api.http.HttpChunk$Chunk.<init>(HttpEntity.scala:141)
	at play.api.mvc.Results$Status$$anonfun$chunked$1.apply(Results.scala:451)
	at play.api.mvc.Results$Status$$anonfun$chunked$1.apply(Results.scala:451)
```

**Comment by schmitch** [comment]
as you might see, a chunked part can't be empty, this is not a bug, the reason why streamed works, is because it isn't a chunked transfer, it just streams the data.

The problem why this does not work is that it would send a `\r\n` response, which actually closes the stream on the remote site anyway.

**Comment by cchantep** [comment]
I would be nice this case was documented and logged, and possibly prevented from the API (not allowing to created an empty chunk).

**Comment by enragedginger** [comment]
I agree with @cchantep. I ran into this same basic issue (except with `Array[Byte]` instances instead of `String` instances). It'd be nice if it was documented somewhere.

**Comment by richdougherty** [comment]
There does appear to be a check for empty chunks in Play, but perhaps the error message doesn't bubble up to the user?

https://github.com/playframework/playframework/blob/7afc0b54d018642f2c1fb4601e4c0475cd31b876/framework/src/play/src/main/scala/play/api/http/HttpEntity.scala#L141

My preference would be for this to be an error that's reported since closing a connection with an empty chunk is probably a mistake.

**Comment by enragedginger** [comment]
@richdougherty Hi, it's been awhile since I was working through this issue. I think my main hangup was just the fact that the behavior was both surprising and undocumented. Simply documenting this in an appropriate place is acceptable IMO. Changing the underlying behavior might not be the best course of action as I'm unsure what existing application behavior would be affected by this.

**Comment by richdougherty** [comment]
OK, thanks. I've tagged this issue as _documentation_ and _help wanted_. Hopefully some docs materialise. :)
