### ISSUE TITLE
NullPointerException if ConfigException has no origin

### ISSUE THREAD

**Issue by ewiner** [playframework/playframework#6817]
### Play Version (2.5.x / etc)

2.5.10, looks to be the same in `master`.

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.11

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

JDK 1.8.0_92

### Expected Behavior

When I pass some invalid data into `Configuration.load()`, I get back a useful exception.

### Actual Behavior

This error: 

```
[info]   java.lang.NullPointerException:
[info]   at play.api.Configuration$.configError(Configuration.scala:151)
[info]   at play.api.Configuration$.load(Configuration.scala:101)
[info]   at play.api.Configuration$.load(Configuration.scala:109)
```

Which I believe is because `ConfigException.origin()` is nullable (according to the Javadoc on that method) but 
https://github.com/playframework/playframework/blob/5bed9745190b51eedab2ccc19279cf1f3fa0100c/framework/src/play/src/main/scala/play/api/Configuration.scala#L146 assumes it's not null.

### Reproducible Test Case

I'm not sure what my actual error is yet, because this exception in the exception handler is obscuring it, so I don't have a small repro yet.

**Comment by gmethvin** [comment]
@ewiner I created a PR to fix this, but it would be nice to find out what the actual error is so we could add a test.

**Comment by ewiner** [comment]
Turns out my original problem was that I was using Scala collections inside the second parameter to `Configuration.load()`:

```
scala> Configuration.load(Environment.simple(), Map("foo" -> "bar"))
res1: play.api.Configuration = Configuration(Config(SimpleConfigObject({"akka":{"actor":{"additional-serialization-bindings":{},"creation-timeout":"20s","debug":{"autoreceive":"off","event-stream":"off","fsm":"off","lifecycle":"off","receive":"off","router-misconfiguration":"off","unhandled":"off"},"default-dispatcher":{"attempt-teamwork":"on","default-executor":{"fallback":"fork-join-executor"},"executor":"default-executor","fork-join-executor":{"parallelism-factor":1,"parallelism-max":24,"parallelism-min":8,"task-peeking-mode":"LIFO"},"mailbox-requirement":"","shutdown-timeout":"1s","thread-pool-executor":{"allow-core-timeout":"on","core-pool-size-factor":3,"core-pool-size-max":64,"core-pool-size-min":8,"fixed-pool-size":"off","keep-alive-time":"60s","max-pool-size-factor":3,"max-pool...

scala> Configuration.load(Environment.simple(), Map("foo" -> Seq("one", "two")))
java.lang.NullPointerException
  at play.api.Configuration$.configError(Configuration.scala:151)
  at play.api.Configuration$.load(Configuration.scala:101)
  at play.api.Configuration$.load(Configuration.scala:109)
  ... 42 elided

scala> Configuration.load(Environment.simple(), Map("foo" -> java.util.Arrays.asList("one", "two")))
res7: play.api.Configuration = Configuration(Config(SimpleConfigObject({"akka":{"actor":{"additional-serialization-bindings":{},"creation-timeout":"20s","debug":{"autoreceive":"off","event-stream":"off","fsm":"off","lifecycle":"off","receive":"off","router-misconfiguration":"off","unhandled":"off"},"default-dispatcher":{"attempt-teamwork":"on","default-executor":{"fallback":"fork-join-executor"},"executor":"default-executor","fork-join-executor":{"parallelism-factor":1,"parallelism-max":24,"parallelism-min":8,"task-peeking-mode":"LIFO"},"mailbox-requirement":"","shutdown-timeout":"1s","thread-pool-executor":{"allow-core-timeout":"on","core-pool-size-factor":3,"core-pool-size-max":64,"core-pool-size-min":8,"fixed-pool-size":"off","keep-alive-time":"60s","max-pool-size-factor":3,"max-pool...
```

I fixed it on my end with something like:
```scala
      def convertToJava(innerConfig: Any): AnyRef = {
        innerConfig match {
          case list: Seq[_]   => list.map(convertToJava).asJava
          case map: Map[_, _] => map.mapValues(convertToJava).asJava
          case other          => other.asInstanceOf[AnyRef]
        }
      }

      Configuration.load(Environment.simple(), config.mapValues(convertToJava))
```

I don't recall having to do something similar for `FakeApplication` back in Play 2.3.

**Comment by gmethvin** [comment]
Thanks @ewiner. I fixed the NPE. I guess we might want to improve the API to work better for Scala collections.
