### ISSUE TITLE
Generated SSL keystore doesn't work in maven-style layout

### ISSUE THREAD

**Issue by ashleymercer** [playframework/playframework#6826]
### Play Version
2.5.3

### API
Scala

### Operating System
MacOS 10.11.6

### JDK
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

### Expected Behavior

1. Create a clean play project, but using maven-style layout
2. Switch to the maven-style layout by disabled `PlayLayoutPlugin`, and moving files into their maven locations (so e.g. `application.conf` lives under `src/main/resources`) - project configuration should look something like this:

```sbt
lazy val play = (project in file("."))
  .enablePlugins(PlayScala)
  .disablePlugins(PlayLayoutPlugin)
```

3. Run play with SSL enabled by adding `-Dhttps.port=9443`
4. Browse with HTTPS (e.g. to `https://localhost:9443`)
5. Website should appear, or browser should generate some warning about a self-signed certificate

### Actual Behavior

Play cannot generate the SSL keystore because there is a [hardcoded path to the `conf` folder](https://github.com/playframework/playframework/blob/5428e7f8ed373efd7672eeeb4ea50d80bffcdea0/framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala#L23), but this doesn't exist in maven-style layout - instead it produces the following error:

```
2016-12-21 13:16:24.343 ERROR [play-dev-mode-akka.actor.default-dispatcher-4] play.core.server.NettyServer - cannot load SSL context
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:96)
	at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:32)
	at play.core.server.NettyServer.liftedTree1$1(NettyServer.scala:91)
	at play.core.server.NettyServer.play$core$server$NettyServer$$sslEngineProvider$lzycompute(NettyServer.scala:90)
	at play.core.server.NettyServer.play$core$server$NettyServer$$sslEngineProvider(NettyServer.scala:89)
	at play.core.server.NettyServer$$anonfun$channelSink$1.apply(NettyServer.scala:158)
	at play.core.server.NettyServer$$anonfun$channelSink$1.apply(NettyServer.scala:149)
	at akka.stream.impl.fusing.Map.onPush(Ops.scala:29)
	at akka.stream.impl.fusing.Map.onPush(Ops.scala:28)
	at akka.stream.stage.AbstractStage$PushPullGraphLogic$$anon$1.onPush(Stage.scala:55)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:587)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:598)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:539)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:469)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:408)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:593)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:604)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:519)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.FileNotFoundException: /Users/ashley/Development/play-ssl-layout-bug/conf/generated.keystore (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at play.core.server.ssl.FakeKeyStore$.keyManagerFactory(FakeKeyStore.scala:72)
	at play.core.server.ssl.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:61)
	at play.core.server.ssl.DefaultSSLEngineProvider.<init>(DefaultSSLEngineProvider.scala:24)
	... 32 common frames omitted
```

I can see a couple of possible fixes, in order from easiest to hardest:

1. just create the `conf` directory if it doesn't already exist
2. get the path to the actual resource directory - although this is knowledge that sbt has (presumably something like `unmanagedResources in Compile`) so not sure how feasible it is to find this at runtime. Or could we find the path to `application.conf` and generate the keystore next to it?
3. there are almost certainly more subtle reasons I'm not aware of why this is a bad idea - but could the keystore just be generated in a temp file somewhere? Why does it have to be generated inside the `conf` directory?

### Reproducible Test Case

https://github.com/ashleymercer/play-ssl-maven-bug

This repo is already set up with maven-style layout. Play run works just fine over HTTP, but if its run with `-Dhttps.port=9443`, browsing to `https://localhost:9443` produces the error as described.

**Comment by marcospereira** [comment]
Hey @ashleymercer, thanks for the detailed report.

Solution 1 looks ok, but it could be a little... strange, considering that we would be mixing the layouts. I would prefer to avoid that.

Solution 2 is the one that makes more sense to me, but, as you said, we need to investigate if it feasible to get the correct classloader here (maybe using `Thread.currentThread.getContextClassLoader`?). If so, I would go for it.

About solution 3, I don't have a strong opinion. One drawback is that, if we are always generating temporary (and thus different) certificates, users will need to accept them (at the browser) each time they are being regenerated. This could be annoying.

Do you want to submit a pull request to fix this?

**Comment by ashleymercer** [comment]
Another possible solution: could the SSL certificate be generated at compile time, probably during `test:compile`? That way the keystore lives under `target` so will not need to be regenerated each time (unless you run `sbt clean` - but then you're going to have to recompile everything anyway).

Is that sensible? If so, I should have time to try making a patch over the next week or two.

**Comment by marcospereira** [comment]
@ashleymercer this sounds like an improvement of solution 2 (use the actual resource directory) and generate it at compile time.

Of course, a pull request would be awesome. :-)

Thanks.

**Comment by evanbennett** [comment]
#3677 contains discussion about this.

For what it is worth, I think it belongs in the project's root folder, as James mentions near the end.

**Comment by timzaak** [comment]
https://github.com/playframework/playframework/blob/0f43b82188583cb63365f33a67b9b487430d187b/framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala#L34

It use `serverConfig` instead of `configuration` when initialize `SSLEngineProvider`, so the application.conf can not be read when   `disablePlugins(PlayLayoutPlugin)` 

so my temp solution is  using -D:
-Dplay.server.https.keyStore.password=xxxxxx -Dplay.server.https.keyStore.path="src/main/resources/keystore.jks"

**Comment by wsargent** [comment]
Brief update: there's ongoing work in lightbend/ssl-config regarding the `FakeKeyStore` and you can also use https://github.com/tersesystems/securitybuilder#x509certificatecreator to generate key stores for integration tests.

**Comment by ignasi35** [comment]
This no longer applies in Play 2.7.x.

Related https://github.com/playframework/playframework/pull/6681, https://github.com/playframework/playframework/pull/8691
