### ISSUE TITLE
NPE attempting to bindFromRequest a Java Form from a Scala App 

### ISSUE THREAD

**Issue by bravegag** [playframework/playframework#6831]
**Play Version**
2.5.10

**API**
Both

**Operating System**
Ubuntu 14.04

**JDK**
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Intro**
I am trying to build a Web App using Scala Play but on top of a Java Play plugin https://github.com/joscha/play-authenticate. So I know very well the ins and outs of  `play.core.j.JavaHelpers`. That framework forces me to have couple of Forms in Java format and thus the issue.

**Expected Behavior**
```
// converting to Java and binding the Java Form to work
val jContext = JavaHelpers.createJavaContext(request)
val filledForm = formFactory.getLoginForm.bindFromRequest(jContext.request())
```

**Actual Behavior**
NPE exception is thrown because indeed the request `play.mvc.Http.RequestImpl#underlying` returned by the jContext has `null` value. I debugged it and it is due to the choice of `RequestImpl` constructor:

```
        /**
         * Constructor only based on a header.
         * @param header the header from a request
         */
        public RequestImpl(play.api.mvc.RequestHeader header) {
            super(header);
            this.underlying = null; // it is indeed null
        }
```

and the NPE point is `play.data.Form` line #182 in the following condition `if(request.body().asFormUrlEncoded() != null) {` body() returns the `RequestImpl#underlying` as null

```
[error] application - 

! @72em09dc4 - Internal server error, for (POST) [/signup] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: java.lang.NullPointerException: null
	at play.data.Form.requestData(Form.java:182)
	at play.data.Form.bindFromRequest(Form.java:270)
	at controllers.Application$$anonfun$8$$anonfun$apply$8.apply(Application.scala:97)
	at controllers.Application$$anonfun$8$$anonfun$apply$8.apply(Application.scala:94)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
```

**Reproducible Test Case**

Clone and run https://github.com/bravegag/play-authenticate-usage-scala and try to sign up (the signup is a Java Form)

**Comment by wsargent** [comment]
```
val jContext = JavaHelpers.createJavaContext(request)
val filledForm = formFactory.getLoginForm.bindFromRequest(jContext.request())
```

IIFC, there is no expectation that the context will be bound directly in situ.   I'd suggest using a custom action annotation: https://www.playframework.com/documentation/2.5.x/JavaActionsComposition

**Comment by bravegag** [comment]
Thank you for your comment! good feedback to use custom annotation ... to avoid all the boilerplate code but still doesn't help me with the OP here or?  do you mean it is not a bug but an intended feature? :)

**Comment by bravegag** [comment]
The issue here is that there are two overloaded methods in `JavaHelpers` namely:

      `def createJavaContext(req: RequestHeader): JContext`
      `def createJavaContext(req: Request[RequestBody]): JContext`

and I need the second one, but no matter what I do it always match the first one which leaves the underlying to `null`. The reason is that `Request` is a subclass of `RequestHeader` and it will always pick the former. If the later would be renamed to e.g. `createJavaContext2` then the problem is over.

**Comment by wsargent** [comment]
`JavaHelpers.createJavaContext` is not part of the public API -- it is not supported and users shouldn't be calling it directly, as it may change without warning without deprecation.

**Comment by bravegag** [comment]
I found a solution that works for now calling `JavaHelpers.createJavaContext(request.asInstanceOf[Request[RequestBody]])` it did the job. I don't like hacks because I will pay the price myself later with migration issues etc but in a twisted kind of way, the current Play top abstract design puts me in this situation. I have to decide between keeping my code in one language Scala and use hacks or to have a mixed Java-Scala code base which anyway has the risk of bumping into the same issues at some point again.

**Comment by gmethvin** [comment]
You should be able to write a regular method that returns a `CompletionStage[play.mvc.Result]` or `play.mvc.Result` in Scala. That involves no undocumented behavior at all, besides writing the code in Scala. You can create an instance of `play.core.j.JavaAction` if you prefer to be explicit.

I think we do need to do a better job identifying the internal APIs though.
