### ISSUE TITLE
Inject error

### ISSUE THREAD

**Issue by dmyersturnbull** [playframework/playframework#6853]
### Play Version (2.5.x / etc)

2.5.10

### API (Scala / Java / Neither / Both)

Scala 2.11.8

### JDK (Oracle 1.8.0_111, OpenJDK 1.8.x)

```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b16)
OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)
```

### Expected Behavior

With Play 2.5.10 and `routesGenerator := InjectedRoutesGenerator`, I have:

#### `config/app.config`:

```
play.crypto.secret = "changeme"
play.i18n.langs = [ "en", "en-US" ]
```

#### `config/routes`:

```
GET     /                           @controllers.Index.index
```

#### `app/controllers/Index.scala`:

```scala
class Index @Inject() (val messagesApi: MessagesApi) extends Controller with I18nSupport {
```

### Actual Behavior

The `@Inject` results in a surprising error.

```
[info] play.api.Play - Application started (Dev)
[error] application - 

! @72i68jd9o - Internal server error, for (GET) [/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.ExceptionInInitializerError
  at controllers.Index.<init>(Index.scala:22)
  while locating controllers.Index

1 error]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:321)
	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:45)
	at play.core.server.Server$class.getHandlerFor(Server.scala:65)
	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:47)
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:82)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.ExceptionInInitializerError
  at controllers.Index.<init>(Index.scala:22)
  while locating controllers.Index

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:94)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(Routes.scala:94)
	at play.core.routing.HandlerInvokerFactory$$anon$12$$anon$13.call(HandlerInvoker.scala:95)
	at play.core.routing.TaggingInvoker.call(HandlerInvoker.scala:39)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(Routes.scala:94)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(Routes.scala:94)
	at play.core.routing.GeneratedRouter.call(GeneratedRouter.scala:93)
	at router.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:93)
	at router.Routes$$anonfun$routes$1.applyOrElse(Routes.scala:89)
Caused by: java.lang.ExceptionInInitializerError: null
	at controllers.Index.<init>(Index.scala:26)
	at controllers.Index$$FastClassByGuice$$37f7585b.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
Caused by: com.typesafe.config.ConfigException$IO: config/app.properties: java.io.FileNotFoundException: config/app.properties (No such file or directory)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:734)
	at kokellab.utils.core.package$.parseConfig(core.scala:17)
	at kokellab.db.core.package$.<init>(package.scala:18)
	at kokellab.db.core.package$.<clinit>(package.scala)
	at controllers.Index.<init>(Index.scala:26)
	at controllers.Index$$FastClassByGuice$$37f7585b.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
Caused by: java.io.FileNotFoundException: config/app.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.typesafe.config.impl.Parseable$ParseableFile.reader(Parseable.java:638)
	at com.typesafe.config.impl.Parseable.reader(Parseable.java:99)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:231)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:734)
```

### Reproducible Test Case

TODO

**Comment by gmethvin** [comment]
@dmyersturnbull With the information provided this doesn't look like a bug in Play. As you can see from the exception, the root cause is that a file called `config/app.properties` (not mentioned in this issue) can't be found. That is originating from your controller code when it's being initialized.

If you need help I'd suggest asking on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

**Comment by dmyersturnbull** [comment]
@gmethvin You're completely right; I should have checked the stack trace more carefully!
