### ISSUE TITLE
My custom exception that extends UsefulException wrapped with CompletionException !

### ISSUE THREAD

**Issue by almothafar** [playframework/playframework#6862]
### Play Version 
2.5.10
### API 
Java
### Operating System 
RedHat and Windows
### JDK 
Oracle 1.8.0_111 and  OpenJDK 1.8.111
### Expected Behavior

Using custom error handler, and custom exception to handle some of the business exceptions inside services, so If that exception returned the error handler must handle it.
1. Inside Controller or Service, I throw a new exception:
`throw new BusinessException(getMessage(MsgKeys.ERR_USER_ALREADY_EXIST));`

2. In my error handler:
```
public class ErrorHandler extends DefaultHttpErrorHandler {
    @Override
    protected CompletionStage<Result> onDevServerError(RequestHeader request, UsefulException exception) {
        Logger.error(AppUtils.concatStrings("Exception: method: ", request.path(), " time:", DateTime.now().toString(),
                " uri=", request.uri(), " remote-address=", request.remoteAddress(), "cause: ", exception.getMessage()));
        if (exception instanceof BusinessException) {
            return CompletableFuture.completedFuture(
                    Results.badRequest(exception.getMessage()));
        } else if (exception instanceof ApplicationException) {
            return CompletableFuture.completedFuture(
                    Results.badRequest(exception.getMessage()));
        }
        return super.onDevServerError(request, exception);
    }
}

```
3. When the exception thrown the result must be `Results.badRequest(exception.getMessage()))` 

### Actual Behavior
 My exception wrapped with `Caused by: java.util.concurrent.CompletionException: @null: null` and it always not match any of if conditions in error handler, and always hit the last line ` return super.onDevServerError(request, exception)` since the exception is always instance of `CompletionException`:

```
[error] - application - 

! @72jc6cp8l - Internal server error, for (PUT) [/api/signup] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: @null: null]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.HttpErrorHandlerExceptions.throwableToUsefulException(HttpErrorHandler.scala)
	at play.http.DefaultHttpErrorHandler.throwableToUsefulException(DefaultHttpErrorHandler.java:169)
	at play.http.DefaultHttpErrorHandler.onServerError(DefaultHttpErrorHandler.java:131)
	at play.core.j.JavaHttpErrorHandlerAdapter$$anonfun$onServerError$1.apply(JavaHttpErrorHandlerAdapter.scala:22)
	at play.core.j.JavaHttpErrorHandlerAdapter$$anonfun$onServerError$1.apply(JavaHttpErrorHandlerAdapter.scala:22)
	at play.core.j.JavaHelpers$$anonfun$invokeWithContext$1.apply(JavaHelpers.scala:142)
	at play.core.j.JavaHelpers$$anonfun$invokeWithContext$1.apply(JavaHelpers.scala:141)
	at play.core.j.JavaHelpers$class.withContext(JavaHelpers.scala:153)
	at play.core.j.JavaHelpers$.withContext(JavaHelpers.scala:162)
	at play.core.j.JavaHelpers$class.invokeWithContext(JavaHelpers.scala:141)
	at play.core.j.JavaHelpers$.invokeWithContext(JavaHelpers.scala:162)
	at play.core.j.JavaHttpErrorHandlerAdapter.onServerError(JavaHttpErrorHandlerAdapter.scala:22)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:346)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.scala$concurrent$impl$Promise$DefaultPromise$$dispatchOrAddCallback(Promise.scala:280)
	at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:270)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.CompletionException: @null: null
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.tryFailure(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:153)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:83)
	at play.api.mvc.Filter$$anon$1$$anonfun$apply$4$$anonfun$apply$1.applyOrElse(Filters.scala:77)
	... 15 common frames omitted
Caused by: exceptions.BusinessException: User already exist
	at controllers.UsersController.signup(UsersController.java:59)
	at prod.Routes$$anonfun$routes$1$$anonfun$applyOrElse$65$$anonfun$apply$65.apply(Routes.scala:1945)
	at prod.Routes$$anonfun$routes$1$$anonfun$applyOrElse$65$$anonfun$apply$65.apply(Routes.scala:1945)
	at play.core.routing.HandlerInvokerFactory$$anon$5.resultCall(HandlerInvoker.scala:160)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:136)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:73)
	at play.http.HttpRequestHandler$1.call(HttpRequestHandler.java:54)
	at play.db.ebean.TransactionalAction.lambda$call$0(TransactionalAction.java:18)
	at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:608)
	at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:602)
	at com.avaje.ebean.Ebean.execute(Ebean.java:1276)
	at play.db.ebean.TransactionalAction.call(TransactionalAction.java:18)
	at handlers.Headers.call(Headers.java:24)
	at play.mvc.Security$AuthenticatedAction.call(Security.java:53)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:494)
	at play.core.j.JavaAction.apply(JavaAction.scala:108)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	... 13 common frames omitted
[error] - application - Exception: method: /api/signup time:2017-01-08T11:33:38.539+02:00 uri=/api/signup remote-address=127.0.0.1cause: Execution exception[[CompletionException: @null: null]]

```
### Reproducible Test Case

Controller with:

```
public Result testSignUp() {
   throw new BusinessException("User already exist");
}
```

And the previous Error handler in the code above .
Simple enough to reproduce my issue here.

**Comment by gmethvin** [comment]
Can you explain why you believe it's Play's (or the DefaultHttpErrorHandler's) responsibility to unwrap the CompletionException? I can see some value to always returning it wrapped; that way it's easier to tell whether the exception came from inside the CompletionStage or in the other logic inside the action.

**Comment by almothafar** [comment]
@gmethvin  Thanks for a reply, First, I was not sure from where this came from, but I was still troubleshooting the issue and seems it is because of my HTTP filter:

```
public class TLSFilter extends Filter {

    @Inject
    public TLSFilter(Materializer mat) {
        super(mat);
    }

    @Override
    public CompletionStage<Result> apply(Function<Http.RequestHeader, CompletionStage<Result>> next, Http.RequestHeader rh) {
        if (Play.current().isProd()) {
            String[] httpsHeader = rh.headers().getOrDefault(Http.HeaderNames.X_FORWARDED_PROTO, new String[]{"http"});
            if (Strings.isNullOrEmpty(httpsHeader[0]) || httpsHeader[0].equalsIgnoreCase("http")) {
                return CompletableFuture.completedFuture(Results.movedPermanently("https://".concat(rh.host().concat(rh.uri()))));
            }
        }
        return next.apply(rh).toCompletableFuture();
    }
}
```

And:

```
public class AppFilters extends DefaultHttpFilters {

    @Inject
    public AppFilters(TLSFilter tlsFilter, GzipFilter gzipFilter) {
        super(tlsFilter, gzipFilter);
    }
}
```

inside my `application.conf`:

`play.http.filters = "filters.AppFilters"`

**Comment by gmethvin** [comment]
@almothafar `CompletionException` just means some other exception happened within a `CompletionStage`. You usually can find the original exception using `getCause` and go from there, or you can use one of the many [getRootCause](https://commons.apache.org/proper/commons-lang/javadocs/api-2.4/org/apache/commons/lang/exception/ExceptionUtils.html#getRootCause(java.lang.Throwable)) utilities to get the original exception. It's hard to see why exactly it happens in your case, but it's pretty common that exceptions are wrapped so I'm not sure if it's something we need to handle by default.

**Comment by gmethvin** [comment]
Also if you have other questions, you can ask on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

**Comment by almothafar** [comment]
@gmethvin I already know what the problem now, actually the problem with this: `next.apply(rh)` the exception happened when the request is being applied while it is not a result but an exception that I throw, so the exception that wrapping my custom one comes from `next.apply(rh)` because there is no `CompletionStage`, the filter sit between my exception and the error handler.

I'm now just looking to make filter skip the exception somehow and continue with the exception to error handler.

**Comment by gmethvin** [comment]
@almothafar Seems like this is more of a question than a bug. Can we move this to the mailing list (where there are a lot more people to help) and close this for now? If after discussion we decide there's a real issue we can open a new bug.

**Comment by almothafar** [comment]
@gmethvin yes sure, thank you.

**Comment by mindas** [comment]
@almothafar have you managed to get to the bottom of this issue? I have the same problem. Thanks.

**Comment by almothafar** [comment]
@mindas yes with tricky way only, anyway I'll post a minified version of the code, so do what you want:

on for `onDevServerError` and `onProdServerError`:

```
@Override
    protected CompletionStage<Result> onProdServerError(RequestHeader request, UsefulException exception) {
        CompletionStage<Result> cause = getHandledErrorCompletionStage(exception);
        if (cause != null) {
            return cause;
        } else {
            return CompletableFuture.completedFuture(Results.internalServerError("A server error occurred: " + getExceptionBody(exception, 500)));
        }
    }
```

for ` getHandledErrorCompletionStage(exception);` this is doing the job here to handle this case with recursive calls if needed:

```
@Nullable
    private CompletionStage<Result> getHandledErrorCompletionStage(UsefulException exception) {
        if (exception instanceof MyCustomException) {
            if (exception instanceof AuthorizationException) {
                // unauthorized :O Call 911 :D 
                return CompletableFuture.completedFuture(Results.unauthorized(getExceptionBody(exception, 911)));
            } else {
                int statusCode = ((MyCustomException) exception).getStatusCode();
                return CompletableFuture.completedFuture(Results.status(statusCode, getExceptionBody(exception, statusCode)));
            }
        } else {
            // TODO remove this condition if filter issue fixed or found another way
            if (exception.getCause() != null && exception.getCause() instanceof CompletionException) {
                Throwable cause = exception.getCause().getCause();
                if (cause != null && cause instanceof UsefulException) {
                    return getHandledErrorCompletionStage((UsefulException) cause);
                }
            }
        }
        return null;
    }
```

For more about `logServerError` it helps to reduce logs:

```
    @Override
    protected void logServerError(RequestHeader request, UsefulException exception) {
        if (exception instanceof MyCustomException) {
            logger.error("\n\n! @{} - {}: for ({}) [{}] remote-address={} -> [{}]",
                    exception.id, exception.getClass().getSimpleName(), request.method(), request.uri(), request.remoteAddress(), exception.getMessage()
            );
        } else {
            if (exception.getCause() != null && exception.getCause() instanceof CompletionException) {
                Throwable cause = exception.getCause().getCause();
                if (cause != null && cause instanceof UsefulException) {
                    logServerError(request, (UsefulException) cause);
                }
            } else {
                super.logServerError(request, exception);
            }
        }
    }
```
