### ISSUE TITLE
Driver not found error [org.mongodb.mongodb-driver]

### ISSUE THREAD

**Issue by abhijeet23rathore** [playframework/playframework#6863]
when I am trying to connect to mongodb in play framework 2.5.10 using java, I am getting this error of Driver not found although I have added the driver in the build path.

I am adding this in the application.conf file
default.driver=org.mongodb.mongodb-driver and passing the rest of the credentials but I get this error

*****************************************************************************************

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
        at play.api.Configuration$.configError(Configuration.scala:154)
        at play.api.Configuration.reportError(Configuration.scala:806)
        at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:48)
        at play.api.db.DefaultDBApi$$anonfun$connect$1.apply(DefaultDBApi.scala:42)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at play.api.db.DefaultDBApi.connect(DefaultDBApi.scala:42)
        at play.api.db.DBApiProvider.get$lzycompute(DBModule.scala:72)
        at play.api.db.DBApiProvider.get(DBModule.scala:62)
        at play.api.db.DBApiProvider.get(DBModule.scala:58)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
Caused by: play.api.Configuration$$anon$1: Configuration error[Driver not found: [org.mongodb.mongodb-driver}]]
        at play.api.Configuration$.configError(Configuration.scala:154)
        at play.api.PlayConfig.reportError(Configuration.scala:996)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:114)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:108)
        at scala.Option.map(Option.scala:146)
        at play.api.db.DefaultDatabase.driver$lzycompute(Databases.scala:108)
        at play.api.db.DefaultDatabase.driver(Databases.scala:107)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:122)
        at play.api.db.DefaultDatabase.dataSource(Databases.scala:121)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:142)
Caused by: play.api.PlayException: Cannot load Driver[Driver [org.mongodb.mongodb-driver] cannot be instantiated.]
        at play.utils.Reflect$.createInstance(Reflect.scala:146)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:110)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:108)
        at scala.Option.map(Option.scala:146)
        at play.api.db.DefaultDatabase.driver$lzycompute(Databases.scala:108)
        at play.api.db.DefaultDatabase.driver(Databases.scala:107)
        at play.api.db.DefaultDatabase.dataSource$lzycompute(Databases.scala:122)
        at play.api.db.DefaultDatabase.dataSource(Databases.scala:121)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:142)
        at play.api.db.DefaultDatabase.getConnection(Databases.scala:138)
Caused by: java.lang.ClassNotFoundException: org.mongodb.mongodb-driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at play.utils.Reflect$.getClass(Reflect.scala:151)
        at play.utils.Reflect$.createInstance(Reflect.scala:140)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:110)
        at play.api.db.DefaultDatabase$$anonfun$driver$1.apply(Databases.scala:108)
        at scala.Option.map(Option.scala:146)

What am I doing wrong?

**Comment by marcospereira** [comment]
Hello @abhijeet23rathore ,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.
