### ISSUE TITLE
Probably play-enchanter not generating getters/setters ?

### ISSUE THREAD

**Issue by 58a36f** [playframework/playframework#6963]
**I am using play version 2.5.11** and IDE I am using Intelij IDEA 2016.3.2

I am getting random errors in biding or when working with model:

Random errors:
`java.lang.NumberFormatException: For input string: ""
 at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
 at java.lang.Long.parseLong(Long.java:601)
 at java.lang.Long.parseLong(Long.java:631)
 at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:230)
 at scala.collection.immutable.StringOps.toLong(StringOps.scala:31)
 at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$bytecodeEnhance$1$$anonfun$apply$2.apply(PlayEnhancer.scala:58)
 at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$bytecodeEnhance$1$$anonfun$apply$2.apply(PlayEnhancer.scala:48)
 at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$scopedSettings$2.apply(PlayEnhancer.scala:38)
 at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$scopedSettings$2.apply(PlayEnhancer.scala:34)
 at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
 at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
 at sbt.std.Transform$$anon$4.work(System.scala:63)
 at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
 at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
 at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
 at sbt.Execute.work(Execute.scala:237)
 at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
 at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
 at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
 at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
[error] (compile:manipulateBytecode) java.lang.NumberFormatException: For input string: ""`

Random binding error:

```
`public class LoginForm{

 @Constraints.Required
 @Constraints.MinLength (5)
 @Constraints.MaxLength(20)
 public String login;

 @Constraints.Required
 @Constraints.MinLength (5)
 @Constraints.MaxLength(20)
 public String password;}`
```

I am binding like this:

```
`@Inject
FormFactory formFactory;

Form<LoginForm> loginForm = formFactory.form(LoginForm.class).bindFromRequest();`
```

And error is:

`play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: java.lang.IllegalStateException: JSR-303 validated property 'password' does not have a corresponding accessor for data binding - check your DataBinder's configuration (bean property versus direct field access)]]
 at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
 at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
 at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
 at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
 at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
 at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
 at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
 at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
 at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
 at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: JSR-303 validated property 'password' does not have a corresponding accessor for data binding - check your DataBinder's configuration (bean property versus direct field access)
 at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
 at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
 at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
 at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
 at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
 at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
 at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)
 at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)
 at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
 at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)`

However sometimes when recompiling it works and binding problem occurs in another class.
Also getting sometimes this error when starting app or doing some compilation while running:
```
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at javassist.bytecode.ClassFile.read(ClassFile.java:777)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:124)
	at javassist.CtClassType.<init>(CtClassType.java:96)
	at javassist.ClassPool.makeClass(ClassPool.java:728)
	at javassist.ClassPool.makeClass(ClassPool.java:706)
	at play.core.enhancers.PropertiesEnhancer.generateAccessors(PropertiesEnhancer.java:64)
	at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$scopedSettings$3.apply(PlayEnhancer.scala:43)
	at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$scopedSettings$3.apply(PlayEnhancer.scala:43)
	at scala.Function2$$anonfun$curried$1$$anonfun$apply$1.apply(Function2.scala:45)
	at scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:264)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:263)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:105)
	at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$bytecodeEnhance$1$$anonfun$apply$2.apply(PlayEnhancer.scala:71)
	at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$bytecodeEnhance$1$$anonfun$apply$2.apply(PlayEnhancer.scala:48)
	at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$scopedSettings$2.apply(PlayEnhancer.scala:38)
	at com.typesafe.play.sbt.enhancer.PlayEnhancer$$anonfun$scopedSettings$2.apply(PlayEnhancer.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:manipulateBytecode) java.io.EOFException
```

My build.sbt:

lazy val root = (project in file(".")).enablePlugins(PlayEbean,PlayJava,SbtTwirl)
scalaVersion := "2.11.8"
TwirlKeys.constructorAnnotations += "@javax.inject.Inject()"
libraryDependencies ++= Seq(
 javaJdbc,
 cache,
 javaWs,
evolutions,
filters,
 "mysql" % "mysql-connector-java" % "5.1.36",
 "com.adrianhurt" %% "play-bootstrap" % "1.1-P25-B3",
 "org.webjars" %% "webjars-play" % "2.5.0",
 "org.webjars" % "bootstrap" % "3.3.7-1",
"org.webjars" % "jquery" % "2.2.3",
 "org.webjars" % "swagger-ui" % "2.2.8",
 "com.nappin" %% "play-recaptcha" % "1.5",
 "com.typesafe.play" %% "play-mailer" % "5.0.0-M1",
 "org.apache.commons" % "commons-lang3" % "3.4",
 "commons-validator" % "commons-validator" % "1.5.1",
 "io.swagger" %% "swagger-play2" % "1.5.3",
 "org.webjars.bower" % "Hover" % "2.0.2",
 "org.webjars.bower" % "react-select" % "1.0.0-rc.1"
)
routesGenerator := InjectedRoutesGenerator
resolvers += Resolver.sonatypeRepo("snapshots")
resolvers += Resolver.sonatypeRepo("public")
JsEngineKeys.engineType := JsEngineKeys.EngineType.Node

plugins:
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.11")
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.2.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.7")
addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.1.0")
addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-enhancer" % "1.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "3.1.0")
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.1.0")

**Comment by marcospereira** [comment]
Hey @58a36f,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

I'm closing this and you can ask the question at the mailing list.

Thanks.
