### ISSUE TITLE
Entity Manager problem on production mode

### ISSUE THREAD

**Issue by arash01** [playframework/playframework#6988]
Please have a look to this closed issue. https://github.com/playframework/playframework/issues/4590

Seems it's still happening:

I had the same issue with Playframework 2.5.12. Now, after adding PlayKeys.externalizeResources := false, I'm getting this error:

play.api.UnexpectedException: Unexpected exception[IllegalStateException: Tried to remove the EntityManager, but none was set.]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
Caused by: java.lang.IllegalStateException: Tried to remove the EntityManager, but none was set.
at play.db.jpa.JPAEntityManagerContext.pop(JPAEntityManagerContext.java:78)
at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:170)
at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:210)
at play.db.jpa.TransactionalAction.call(TransactionalAction.java:25)
at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:108)
at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)

**Comment by marcospereira** [comment]
Hey @arash01, 

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Also, I recommend that you give more information at the mailing list. Per instance, are you adding `@Transactional` annotation to your actions? For now, I'm closing this issue, but if we decide after discussing that it is a bug, then we can reopen it. 

Thanks!
