### ISSUE TITLE
Creating new project for 2.6.0-M using `sbt new` impossible

### ISSUE THREAD

**Issue by mohsenkashi** [playframework/playframework#7018]
### Expected Behavior

creating new project using `sbt new playframework/play-java-seed.g8` as described in [Documentation](https://www.playframework.com/documentation/2.6.x/NewApplication)

my input for this command is:

```
This template generates a Play Java project 

name [play-java-seed]: play26test
organization [com.example]: com.kashi
scala_version [2.11.8]: 
play_version [2.6.0-M1]: 

Template applied in ./play26test
```

### Actual Behavior
`sbt run` command fails because of compile error:

```
mohsen@mohsen-ThinkPad-Edge-E440:~/my-workspace/play26test$ sbt run
[info] Loading global plugins from /home/mohsen/.sbt/0.13/plugins
[info] Loading project definition from /home/mohsen/my-workspace/play26test/project
[info] Set current project to play26test (in build file:/home/mohsen/my-workspace/play26test/)

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] Compiling 6 Scala sources and 4 Java sources to /home/mohsen/my-workspace/play26test/target/scala-2.11/classes...
[error] /home/mohsen/my-workspace/play26test/app/Module.java:1: package com.google.inject does not exist
[error] import com.google.inject.AbstractModule;
[error] /home/mohsen/my-workspace/play26test/app/Module.java:13: cannot find symbol
[error]   symbol: class AbstractModule
[error] public class Module extends AbstractModule {
[error] /home/mohsen/my-workspace/play26test/app/Module.java:15: method does not override or implement a method from a supertype
[error]     @Override
[error] (compile:compileIncremental) javac returned nonzero exit code
[info] Compiling 6 Scala sources and 4 Java sources to /home/mohsen/my-workspace/play26test/target/scala-2.11/classes...
[error] /home/mohsen/my-workspace/play26test/app/Module.java:1: package com.google.inject does not exist
[error] import com.google.inject.AbstractModule;
[error] /home/mohsen/my-workspace/play26test/app/Module.java:13: cannot find symbol
[error]   symbol: class AbstractModule
[error] public class Module extends AbstractModule {
[error] /home/mohsen/my-workspace/play26test/app/Module.java:15: method does not override or implement a method from a supertype
[error]     @Override
[error] (compile:compileIncremental) javac returned nonzero exit code
[info] Compiling 6 Scala sources and 4 Java sources to /home/mohsen/my-workspace/play26test/target/scala-2.11/classes...
[error] /home/mohsen/my-workspace/play26test/app/Module.java:1: package com.google.inject does not exist
[error] import com.google.inject.AbstractModule;
[error] /home/mohsen/my-workspace/play26test/app/Module.java:13: cannot find symbol
[error]   symbol: class AbstractModule
[error] public class Module extends AbstractModule {
[error] /home/mohsen/my-workspace/play26test/app/Module.java:15: method does not override or implement a method from a supertype
[error]     @Override
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] application - 

! @737bdc4k3 - Internal server error, for (GET) [/] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[package com.google.inject does not exist]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49)
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44)
	at scala.Option.map(Option.scala:145)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17)


```

**Comment by wsargent** [comment]
Play 2.6.0 is not out yet, and so using sbt new will not have the desired effect.

**Comment by mohsenkashi** [comment]
@wsargent but it is available in `playframework/play-java-seed.g8` , and also described in [official documentation](https://www.playframework.com/documentation/2.6.x/NewApplication)

**Comment by wsargent** [comment]
@mohsenkashi there's a note on the link you included: "You are viewing the documentation for the 2.6.x development release. The latest stable release series is 2.5.x."

**Comment by mohsenkashi** [comment]
@wsargent how can I create 2.6.0-M1 project?

**Comment by wsargent** [comment]
@mohsenkashi start with a 2.5.x project and upgrade -- if you look at the SNAPSHOT version of the templates it'll work: https://github.com/playframework/play-java/tree/SNAPSHOT

**Comment by mohsenkashi** [comment]
@wsargent thanks, but I expect 2.6.0.-M1 documentation guide me to create new one from scratch

**Comment by wsargent** [comment]
@mohsenkashi the documentation isn't finished, because 2.6.x isn't out yet

**Comment by wsargent** [comment]
BTW, I updated the seeds so that they are hardcoded to 2.5.12 -- filed https://github.com/foundweekends/giter8/issues/272 for the maven properties picking up milestones.
