### ISSUE TITLE
Java play [2.5] WS client no failure callback

### ISSUE THREAD

**Issue by TigranTsat** [playframework/playframework#7211]
WS client swallow errors on timeout and request completes successfully. In my code below, I create a WS request to download the large file and specify small timeout. What I see is that Completion Stage succeed and partial response is returned.
My expectation is that the error should somehow propagate to the top.

I raised question on stackoverflow, but did not get any response. I am not a sure whether this is a bug or not.
http://stackoverflow.com/questions/43288367/play-framework-handle-request-timeout

### Operating System MacOS 10.10
Darwin 14.5.0 Darwin Kernel Version 14.5.0: Thu Jun 16 19:58:21 PDT 2016
### JDK
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
### Library Dependencies

If this is an issue that involves integration with another system, include the exact version and OS of the other system, including any intermediate drivers or APIs i.e. if you connect to a PostgreSQL database, include both the version / OS of PostgreSQL and the JDBC driver version used to connect to the database.

### Reproducible Test Case

```
// Make the request, which should timeout
        CompletionStage<StreamedResponse> futureResponse = ws.url("https://download.docker.com/mac/stable/Docker.dmg")
                .setMethod("GET").setRequestTimeout(1000)
                .stream();
        LOGGER.debug("lskdajld {}", futureResponse);

        CompletionStage<Long> bytesReturned = logStage(logStage(futureResponse.thenCompose(res -> {
            Source<ByteString, ?> responseBody = res.getBody();

            // Count the number of bytes returned
            Sink<ByteString, CompletionStage<Long>> bytesSum = Sink.fold(0L, (total, bytes) -> 
            { 
                long len = bytes.toArray().length;
                return total + len;
            });

            return responseBody.runWith(bytesSum, materializer);
        }), "A").handle((res, err) -> {
            LOGGER.info("Res = {}, err = {}", res, err);
            return 200L;
        }).exceptionally(ex -> {
            LOGGER.error("See exception");
            return 100L;
        }), "B");
        try {
            bytesReturned.toCompletableFuture().get();
            LOGGER.info("Got response");
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (ExecutionException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        LOGGER.error("Step completed");
```
Note: `logStage` is just logging. You can ignore it. The rest of the code was taking from example on play site.
```
    <T> CompletionStage<T> logStage(CompletionStage<T> stage, String extraMessage) {
        LOGGER.debug("Created stage {}. Comment: {}", stage, extraMessage);
        return stage;
    }
```

### Output:

```
2017-04-11 08:04:20,345 [debug] i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.org.asynchttpclient.HttpResponseBodyPartMatcher
2017-04-11 08:04:21,164 [debug] o.a.netty.channel.DefaultChannelPool - Closed 0 connections out of 0 in 0 ms
2017-04-11 08:04:21,164 [debug] o.a.netty.timeout.TimeoutTimerTask - Request timeout to download.docker.com/52.84.239.98:443 after 1000 ms for NettyResponseFuture{currentRetry=0,
	isDone=0,
	isCancelled=0,
	asyncHandler=play.api.libs.ws.ahc.Streamed$DefaultStreamedAsyncHandler@257ab50b,
	nettyRequest=org.asynchttpclient.netty.request.NettyRequest@2bbd5fd4,
	future=java.util.concurrent.CompletableFuture@2f82de7b[Not completed],
	uri=https://download.docker.com/mac/stable/Docker.dmg,
	keepAlive=true,
	redirectCount=0,
	timeoutsHolder=org.asynchttpclient.netty.timeout.TimeoutsHolder@6a8055ef,
	inAuth=0,
	statusReceived=1,
	touch=1491923061158} after 1054 ms
2017-04-11 08:04:21,164 [debug] o.a.netty.channel.ChannelManager - Closing Channel [id: 0x56fd1d70, L:/10.155.124.61:58091 - R:download.docker.com/52.84.239.98:443] 
2017-04-11 08:04:21,164 [debug] o.a.netty.request.NettyRequestSender - Aborting Future NettyResponseFuture{currentRetry=0,
	isDone=0,
	isCancelled=0,
	asyncHandler=play.api.libs.ws.ahc.Streamed$DefaultStreamedAsyncHandler@257ab50b,
	nettyRequest=org.asynchttpclient.netty.request.NettyRequest@2bbd5fd4,
	future=java.util.concurrent.CompletableFuture@2f82de7b[Not completed],
	uri=https://download.docker.com/mac/stable/Docker.dmg,
	keepAlive=true,
	redirectCount=0,
	timeoutsHolder=org.asynchttpclient.netty.timeout.TimeoutsHolder@6a8055ef,
	inAuth=0,
	statusReceived=1,
	touch=1491923061158}

2017-04-11 08:04:21,165 [debug] o.a.netty.request.NettyRequestSender - Request timeout to download.docker.com/52.84.239.98:443 after 1000 ms
java.util.concurrent.TimeoutException: Request timeout to download.docker.com/52.84.239.98:443 after 1000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:48)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)
	at java.lang.Thread.run(Thread.java:745)
2017-04-11 08:04:21,165 [debug] o.a.netty.handler.HttpHandler - Channel Closed: [id: 0x56fd1d70, L:/10.155.124.61:58091 ! R:download.docker.com/52.84.239.98:443] with attribute INSTANCE
2017-04-11 08:04:21,165 [info] controllers.RedirectController - Res = 25902270, err = null
2017-04-11 08:04:21,165 [info] controllers.RedirectController - Got response
2017-04-11 08:04:21,165 [error] controllers.RedirectController - Step completed
```

**Comment by wsargent** [comment]
@TigranTsat wow, apologies for not seeing this earlier.  It sounds like you want a non-blocking timeout here -- you can use https://www.playframework.com/documentation/2.5.x/api/java/play/libs/concurrent/Timeout.html and find when the timeout future completes first.

**Comment by wsargent** [comment]
2.6.x has documentation saying

**Comment by wsargent** [comment]
And it looks like 2.5.x has this as well: https://playframework.com/documentation/2.5.x/JavaWS#Using-WSClient-with-CompletionStage-Timeout so we can close this bug out.
