### ISSUE TITLE
Play 2.6.0-M5 no longer supports HTTP status code 498

### ISSUE THREAD

**Issue by kaesler** [playframework/playframework#7299]
### Play Version (2.5.x / etc)

2.6.0-M5

### API (Scala / Java / Neither / Both)

Scala 2.12.1

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOs 10.12.4

Use `uname -a` if on Linux.

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Paste the output from `java -version` at the command line.

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. I have a controller which creates an Action which returns a Result like this: play.api.mvc.Results.Status(498)

2. The request should return with status 498

### Actual Behavior

An exception is thrown and the request returns with status 500. This is a regression from the pre-
Akka-HTTP version of Play we used.

2017-05-04 12:05:20,594 [application-akka.actor.default-dispatcher-15] ERROR p.c.server.common.ServerResultUtils - Exception occurred while converting Result with headers [<X-API-Version>: <2.0.7>]. Calling HttpErrorHandler to get alternative Result.
java.lang.RuntimeException: Non-standard status codes cannot be created by implicit conversion. Use `StatusCodes.custom` instead.
at akka.http.scaladsl.model.StatusCode$.$anonfun$int2StatusCode$1(StatusCode.scala:28)
at scala.Option.getOrElse(Option.scala:121)
at akka.http.scaladsl.model.StatusCode$.int2StatusCode(StatusCode.scala:27)
at play.core.server.akkahttp.AkkaModelConversion.$anonfun$convertResult$2(AkkaModelConversion.scala:183)
at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:55)
at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
at play.core.server.akkahttp.AkkaModelConversion.$anonfun$convertResult$1(AkkaModelConversion.scala:179)
at play.core.server.common.ServerResultUtils.resultConversionWithErrorHandling(ServerResultUtils.scala:136)
at play.core.server.akkahttp.AkkaModelConversion.convertResult(AkkaModelConversion.scala:192)
at play.core.server.AkkaHttpServer.$anonfun$executeAction$3(AkkaHttpServer.scala:255)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
at scala.concurrent.Promise.complete(Promise.scala:49)
at scala.concurrent.Promise.complete$(Promise.scala:48)
at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:38)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-05-04 12:05:20,813 [application-akka.actor.default-dispatcher-15] ERROR com.mc10inc.play.GlobalErrorHandler - Request Error
play.core.server.common.ServerResultException: Error converting Play Result for server backend
at play.core.server.common.ServerResultUtils.play$core$server$common$ServerResultUtils$$handleConversionError$1(ServerResultUtils.scala:117)
at play.core.server.common.ServerResultUtils$$anonfun$resultConversionWithErrorHandling$9.applyOrElse(ServerResultUtils.scala:136)
at play.core.server.common.ServerResultUtils$$anonfun$resultConversionWithErrorHandling$9.applyOrElse(ServerResultUtils.scala:136)
at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$2(FastFuture.scala:37)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:46)
at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
at akka.http.scaladsl.util.FastFuture$ErrorFuture.transformWith(FastFuture.scala:97)
at scala.concurrent.Future.recoverWith(Future.scala:411)
at scala.concurrent.Future.recoverWith$(Future.scala:410)
at akka.http.scaladsl.util.FastFuture$ErrorFuture.recoverWith(FastFuture.scala:88)
at play.core.server.common.ServerResultUtils.resultConversionWithErrorHandling(ServerResultUtils.scala:136)
at play.core.server.akkahttp.AkkaModelConversion.convertResult(AkkaModelConversion.scala:192)
at play.core.server.AkkaHttpServer.$anonfun$executeAction$3(AkkaHttpServer.scala:255)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
at scala.concurrent.Promise.complete(Promise.scala:49)
at scala.concurrent.Promise.complete$(Promise.scala:48)
at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:38)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Non-standard status codes cannot be created by implicit conversion. Use `StatusCodes.custom` instead.
at akka.http.scaladsl.model.StatusCode$.$anonfun$int2StatusCode$1(StatusCode.scala:28)
at scala.Option.getOrElse(Option.scala:121)
at akka.http.scaladsl.model.StatusCode$.int2StatusCode(StatusCode.scala:27)
at play.core.server.akkahttp.AkkaModelConversion.$anonfun$convertResult$2(AkkaModelConversion.scala:183)
at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:55)
at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
at play.core.server.akkahttp.AkkaModelConversion.$anonfun$convertResult$1(AkkaModelConversion.scala:179)
... 28 common frames omitted`
`

**Comment by wsargent** [comment]
>  Non-standard status codes cannot be created by implicit conversion. Use StatusCodes.custom instead.

Is this unclear?

**Comment by kaesler** [comment]
That clearly explains how to produce an instance of akka.http.scaladsl.model.StatusCode.

I need an instance of play.api.mvc.Result containing the 498.

Looking in the source code to reach the latter from the former...

**Comment by kaesler** [comment]
Looks like this might work:  Result(ResponseHeader(498), HttpEntity.Empty)

Will probably add an "expired token" body.

**Comment by wsargent** [comment]
Okay, then the exception here is due to a leaky abstraction layer, and should say `Result(ResponseHeader(statusCode), HttpEntity.Empty)` instead?

**Comment by kaesler** [comment]
Actually this is what compiles: Result(ResponseHeader(498), HttpEntity.NoEntity)

**Comment by kaesler** [comment]
Yes a leak in the abstraction over Akka-HTTP.

**Comment by kaesler** [comment]
Maybe best to make a method Results.customStatus(n: Int) that translates to the above?

**Comment by kaesler** [comment]
With that workaround above I get the same exception. Looks like a fix internal to Play code is required.

**Comment by kaesler** [comment]
This would fix this bug: On line 183 of AkkaModelConversion.scala,
change this: 

status = validated.header.status,

to

status = StatusCodes.getForKey(validated.header.status).getOrElse(StatusCodes.custom(validated.header.status, ""))

**Comment by gmethvin** [comment]
@kaesler See #7302

**Comment by kaesler** [comment]
Thanks for the quick fix!
