### ISSUE TITLE
Listens to http on an https port if the keystore path is invalid.

### ISSUE THREAD

**Issue by PeterHajdu** [playframework/playframework#7350]
### Expected Behavior
Using the following config parameters from: https://www.playframework.com/documentation/2.6.x/ConfiguringHttps
```sh
-Dhttp.port=disabled -Dhttps.port=9443 -Dplay.server.https.keyStore.path=<invalid keystore path>
```
If the keystore path is invalid.

1. play refuses to start since the configured keystore does not exist or invalid

### Actual Behavior

1. web server starts
2. starts to respond to http requests on the configured https port

### Reproducible Test Case

https://github.com/playframework/play-scala-starter-example

start the application from sbt console:
```sh
[play-scala] $ start -Dhttp.port=disabled -Dhttps.port=9443 -Dplay.server.https.keyStore.path=path/to/invalidkeystore
```

localhost:9443 will respond to http requests

**Comment by richdougherty** [comment]
Thanks for the report @PeterHajdu. Sounds like a bug. If you're able, can you attach the console output when you start the application and also show an HTTP curl request, just so we can verify this? Also if you're able to try with a Play 2.6 milestone release to see if the bug has been fixed that would be helpful.

**Comment by mkurz** [comment]
Seems like this got fixed along the way (the issue was reported when Play 2.5 was the latest major release...)
Now when using the flags
```sh
... -Dhttp.port=disabled -Dhttps.port=9443 -Dplay.server.https.keyStore.path=<invalid keystore path>
```
the app will **not** start up, no matter if the keystore file does not exist or is invalid.

Tested with the [`play-scala-starter-example` from the play-samples repo](https://github.com/playframework/play-samples/tree/3.0.x/play-scala-starter-example):

**If the keyStore file does not exist:**
```sh
play-scala-starter-example (3.0.x)$ sbt stage
...
play-scala-starter-example (3.0.x)$ ./target/universal/stage/bin/play-scala-starter-example -Dhttp.port=disabled -Dhttps.port=9443 -Dplay.server.https.keyStore.path=/tmp/this_file_does_not_exist
INFO  p.a.h.HttpErrorHandlerExceptions - Registering exception handler: guice-provision-exception-handler
INFO  play.api.Play - Application started (Prod) (no global state)
ERROR p.c.s.PekkoHttpServer - Cannot load SSL context
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:122)
        at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:39)
        at play.core.server.PekkoHttpServer.sslContext$lzycompute(PekkoHttpServer.scala:245)
        at play.core.server.PekkoHttpServer.sslContext(PekkoHttpServer.scala:244)
        at play.core.server.PekkoHttpServer.$anonfun$httpsServerBinding$1(PekkoHttpServer.scala:260)
        at play.core.server.PekkoHttpServer.$anonfun$httpsServerBinding$1$adapted(PekkoHttpServer.scala:255)
Caused by: java.lang.Exception: Unable to find HTTPS keystore at "/tmp/this_file_does_not_exist"
        at play.core.server.ssl.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:61)
        at play.core.server.ssl.DefaultSSLEngineProvider.<init>(DefaultSSLEngineProvider.scala:32)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:122)
        at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:39)
        at play.core.server.PekkoHttpServer.sslContext$lzycompute(PekkoHttpServer.scala:245)
        at play.core.server.PekkoHttpServer.sslContext(PekkoHttpServer.scala:244)
INFO  p.c.s.PekkoHttpServer - Listening for HTTPS on /127.0.0.1:9443
Oops, cannot start the server.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:122)
        at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:39)
        at play.core.server.PekkoHttpServer.sslContext$lzycompute(PekkoHttpServer.scala:245)
        at play.core.server.PekkoHttpServer.sslContext(PekkoHttpServer.scala:244)
        at play.core.server.PekkoHttpServer.$anonfun$Http1Encrypted$2(PekkoHttpServer.scala:607)
        at scala.Option.map(Option.scala:242)
        at play.core.server.PekkoHttpServer.Http1Encrypted$lzycompute(PekkoHttpServer.scala:599)
        at play.core.server.PekkoHttpServer.Http1Encrypted(PekkoHttpServer.scala:597)
        at play.core.server.PekkoHttpServer.<init>(PekkoHttpServer.scala:641)
        at play.core.server.PekkoHttpServerProvider.createServer(PekkoHttpServer.scala:742)
        at play.core.server.PekkoHttpServerProvider.createServer(PekkoHttpServer.scala:740)
        at play.core.server.ServerProvider.createServer(ServerProvider.scala:30)
        at play.core.server.ServerProvider.createServer$(ServerProvider.scala:27)
        at play.core.server.PekkoHttpServerProvider.createServer(PekkoHttpServer.scala:740)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:58)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:28)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.Exception: Unable to find HTTPS keystore at "/tmp/this_file_does_not_exist"
        at play.core.server.ssl.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:61)
        at play.core.server.ssl.DefaultSSLEngineProvider.<init>(DefaultSSLEngineProvider.scala:32)
        ... 21 more
```

**If the keyStore file exists but is invalid:**
```sh
play-scala-starter-example (3.0.x)$ touch /tmp/invalidkeystore
play-scala-starter-example (3.0.x)$ ./target/universal/stage/bin/play-scala-starter-example -Dhttp.port=disabled -Dhttps.port=9443 -Dplay.server.https.keyStore.path=/tmp/invalidkeystore
INFO  p.a.h.HttpErrorHandlerExceptions - Registering exception handler: guice-provision-exception-handler
INFO  play.api.Play - Application started (Prod) (no global state)
ERROR p.c.s.PekkoHttpServer - Cannot load SSL context
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:122)
        at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:39)
        at play.core.server.PekkoHttpServer.sslContext$lzycompute(PekkoHttpServer.scala:245)
        at play.core.server.PekkoHttpServer.sslContext(PekkoHttpServer.scala:244)
        at play.core.server.PekkoHttpServer.$anonfun$httpsServerBinding$1(PekkoHttpServer.scala:260)
        at play.core.server.PekkoHttpServer.$anonfun$httpsServerBinding$1$adapted(PekkoHttpServer.scala:255)
Caused by: java.lang.Exception: Error loading HTTPS keystore from /tmp/invalidkeystore
        at play.core.server.ssl.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:56)
        at play.core.server.ssl.DefaultSSLEngineProvider.<init>(DefaultSSLEngineProvider.scala:32)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:122)
        at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:39)
        at play.core.server.PekkoHttpServer.sslContext$lzycompute(PekkoHttpServer.scala:245)
        at play.core.server.PekkoHttpServer.sslContext(PekkoHttpServer.scala:244)
Caused by: java.io.EOFException: null
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:665)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at play.core.server.ssl.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:50)
        at play.core.server.ssl.DefaultSSLEngineProvider.<init>(DefaultSSLEngineProvider.scala:32)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
INFO  p.c.s.PekkoHttpServer - Listening for HTTPS on /127.0.0.1:9443
Oops, cannot start the server.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at play.core.server.ssl.ServerSSLEngine$.createScalaSSLEngineProvider(ServerSSLEngine.scala:122)
        at play.core.server.ssl.ServerSSLEngine$.createSSLEngineProvider(ServerSSLEngine.scala:39)
        at play.core.server.PekkoHttpServer.sslContext$lzycompute(PekkoHttpServer.scala:245)
        at play.core.server.PekkoHttpServer.sslContext(PekkoHttpServer.scala:244)
        at play.core.server.PekkoHttpServer.$anonfun$Http1Encrypted$2(PekkoHttpServer.scala:607)
        at scala.Option.map(Option.scala:242)
        at play.core.server.PekkoHttpServer.Http1Encrypted$lzycompute(PekkoHttpServer.scala:599)
        at play.core.server.PekkoHttpServer.Http1Encrypted(PekkoHttpServer.scala:597)
        at play.core.server.PekkoHttpServer.<init>(PekkoHttpServer.scala:641)
        at play.core.server.PekkoHttpServerProvider.createServer(PekkoHttpServer.scala:742)
        at play.core.server.PekkoHttpServerProvider.createServer(PekkoHttpServer.scala:740)
        at play.core.server.ServerProvider.createServer(ServerProvider.scala:30)
        at play.core.server.ServerProvider.createServer$(ServerProvider.scala:27)
        at play.core.server.PekkoHttpServerProvider.createServer(PekkoHttpServer.scala:740)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:58)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:28)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.Exception: Error loading HTTPS keystore from /tmp/invalidkeystore
        at play.core.server.ssl.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:56)
        at play.core.server.ssl.DefaultSSLEngineProvider.<init>(DefaultSSLEngineProvider.scala:32)
        ... 21 more
Caused by: java.io.EOFException
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:665)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
        at java.base/java.security.KeyStore.load(KeyStore.java:1479)
        at play.core.server.ssl.DefaultSSLEngineProvider.createSSLContext(DefaultSSLEngineProvider.scala:50)
        ... 22 more
```
