### ISSUE TITLE
Using `JPA` helper class stand alone. without injecting `JPAApi`

### ISSUE THREAD

**Issue by mohsenkashi** [playframework/playframework#7535]
### Expected Behavior

Using `JPA` helper class stand alone. without injecting `JPAApi`

### Actual Behavior
**It seems that creating entity manager using DI has some problems in play 2.6**
I have a very very simple database access :
```
@Transactional
public class HomeController extends Controller {

    public Result index() {
        JPA.em().find(Person.class, 1L);
        return ok(views.html.index.render());
    }

}
```

this simple code generates following stack trace and does not works:
```

! @74fhap05p - Internal server error, for (GET) [/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, javax.persistence.PersistenceException: Unable to build entity manager factory
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:40)
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.class(DefaultJPAApi.java:35)
  while locating play.db.jpa.DefaultJPAApi$JPAApiProvider
  while locating play.db.jpa.JPAApi
    for the 1st parameter of play.db.jpa.TransactionalAction.<init>(TransactionalAction.java:20)
  while locating play.db.jpa.TransactionalAction

1 error]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:230)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:229)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, javax.persistence.PersistenceException: Unable to build entity manager factory
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:40)
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.class(DefaultJPAApi.java:35)
  while locating play.db.jpa.DefaultJPAApi$JPAApiProvider
  while locating play.db.jpa.JPAApi
    for the 1st parameter of play.db.jpa.TransactionalAction.<init>(TransactionalAction.java:20)
  while locating play.db.jpa.TransactionalAction

1 error
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:405)
        at play.core.j.DefaultJavaHandlerComponents.getAction(JavaAction.scala:173)
        at play.core.j.JavaAction.$anonfun$apply$1(JavaAction.scala:96)
        at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
        at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
        at scala.collection.mutable.ArraySeq.foldLeft(ArraySeq.scala:46)
        at play.core.j.JavaAction.apply(JavaAction.scala:94)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
Caused by: javax.persistence.PersistenceException: Unable to build entity manager factory
        at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:66)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:39)
        at play.db.jpa.DefaultJPAApi.lambda$start$1(DefaultJPAApi.java:61)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at play.db.jpa.DefaultJPAApi.start(DefaultJPAApi.java:60)
        at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:47)
        at play.db.jpa.DefaultJPAApi$JPAApiProvider$$FastClassByGuice$$dcd4cdbd.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [models.Person]
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:229)
        at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:103)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:147)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:141)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:848)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:876)
        at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
        at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:39)
        at play.db.jpa.DefaultJPAApi.lambda$start$1(DefaultJPAApi.java:61)
Caused by: java.lang.ClassNotFoundException: Could not load requested class : models.Person
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader.findClass(ClassLoaderServiceImpl.java:217)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:226)
        at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:103)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:147)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:141)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:848)


```

while, surprisingly adding unused `JPAApi` inject resolves this problem:
```
@Transactional
public class HomeController extends Controller {
    @Inject
    public HomeController(JPAApi jpaApi) {
    }
    public Result index() {
        JPA.em().find(Person.class, 1L);
        return ok(views.html.index.render());
    }
}
```

I meet this issue when I am try to update my play version from 2.5 to 2.6

**Comment by marcospereira** [comment]
Hi @mohsenkashi, some questions:

1. Is it possible to run a `sbt clean` so that we can confirm this is not being caused by previous compilations with another Play version? The root cause here is this:

```Caused by: java.lang.ClassNotFoundException: Could not load requested class : models.Person
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader.findClass(ClassLoaderServiceImpl.java:217)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:226)
        at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.<init>(AnnotationMetadataSourceProcessorImpl.java:103)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.<init>(MetadataBuildingProcess.java:147)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:141)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:848)
```
So, I'm not sure this is related to the use of `JPA` or something else.

2.  If `sbt clean` does not solve the problem, could you please create a small project that shows this problem?

Thanks.

**Comment by mohsenkashi** [comment]
I run sbt clean several times.
 As I said, with removing inject method application stop working.
I dont access my laptop now, I can push my sample project on github tomorrow

**Comment by mohsenkashi** [comment]
I test sbt clean several times.
I push my simple project here:
https://github.com/mohsenkashi/play26di
With commenting unused inject in `HomeController.java` , error will be raise

**Comment by richdougherty** [comment]
I just downloaded your example project and it worked for me with both the `run` and `start` commands. Is there anything else I should do to replicate this?

The only thing I can think of is that class loading issues can sometimes happen when threads don't have the correct context `ClassLoader` set for them. This should be something Play does automatically, but possibly this is somehow behaving differently on your machine than on my one.

**Comment by mohsenkashi** [comment]
Hi @richdougherty 
Did you read my previous comment?
Removing unused inject constructor causes the bug.
See this branch:
https://github.com/mohsenkashi/play26di/tree/bug

**Comment by richdougherty** [comment]
@mohsenkashi, I must have read your bug description a bit too quickly! A fix is now in progress here: #7552.

**Comment by richdougherty** [comment]
Hi @mohsenkashi, this issue is now addressed in Play 2.6.1 if you want to try it out.

**Comment by sripooja** [comment]
Hi @richdougherty am using play 2.8.4. Still I face the same issue by injecting JPAApi

**Comment by afsilvasantos** [comment]
> Hi @richdougherty am using play 2.8.4. Still I face the same issue by injecting JPAApi

Hey, did you manage to overcome this issue?

**Comment by mkurz** [comment]
@afsilvasantos Can you please post which version of Play you are using and the stack trace?
