### ISSUE TITLE
Regression - [2.5.x] Play Json not supporting joda DateTime

### ISSUE THREAD

**Issue by rickeyski** [playframework/playframework#7555]
### API
Scala

### Operating System 
Red Hat 7

### JDK
openjdk version "1.8.0_131"

### Libraries
Silhouette 4.0.0

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Existing case classes containing DateTime objects would continue to produce valid json
2. I would be able to create new case classes containing DateTime values

### Actual Behavior

1. I recently update to Play 2.5.15 from 2.5.14 and I have started receiving 
  java.lang.NoSuchMethodError: Fatal Execution error, caused by play.api.libs.json.Writes$.DefaultJodaDateWrites()Lplay/api/libs/json/DefaultWrites$DefaultJodaDateWrites$; (CookieAuthenticator.scala:91)
  in libraries where I cannot modify the objects
2. I cannot compile any new objects containing DateTime objects that I want to format to Json

### Reproducible Test Case

I created a test case for the compilation failure.

``` scala
case class Test(start:DateTime, finish:DateTime)
object Test {
  implicit val jsonFormatter = Json.format[Test]
}
```
The bigger problem is that the site no longer runs because Silhouette's json writes fail.

**Comment by richdougherty** [comment]
Can you please attach a stacktrace?

**Comment by rickeyski** [comment]
Here you go. Thanks.

```
Exception in thread "ForkJoinPool-5-worker-9" java.lang.NoSuchMethodError: play.api.libs.json.
Writes$.DefaultJodaDateWrites()Lplay/api/libs/json/DefaultWrites$DefaultJodaDateWrites$;
        at com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticator$.<init>(CookieAu
thenticator.scala:91)
        at com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticator$.<clinit>(Cookie
Authenticator.scala)
        at com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticatorService$$anonfun$
retrieve$3.apply(CookieAuthenticator.scala:209)
        at com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticatorService$$anonfun$
retrieve$3.apply(CookieAuthenticator.scala:204)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:140$
)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by cchantep** [comment]
Hi, the code is [available in 2.5](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala#L410). Please check there was is no other Play JSON version pulled by other way.

**Comment by rickeyski** [comment]
This is my dependency list

``` scala
libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play-slick" % "2.1.0",
  "com.typesafe.play" %% "play-slick-evolutions" % "2.1.0",
  "com.typesafe.play" %% "play-mailer" % "5.0.0",
  "com.typesafe.play" %% "play-streams" % _root_.play.core.PlayVersion.current,
  "com.github.tminglei" %% "slick-pg" % "0.15.1",
  "com.github.tminglei" %% "slick-pg_play-json" % "0.15.1",
  "com.mohiva" %% "play-silhouette" % "4.0.0",
  "com.mohiva" %% "play-silhouette-persistence" % "4.0.0",
  "com.mohiva" %% "play-silhouette-password-bcrypt" % "4.0.0",
  "com.mohiva" %% "play-silhouette-crypto-jca" % "4.0.0",
  "net.codingwell" %% "scala-guice" % "4.0.1",
  "com.iheart" %% "ficus" % "1.2.6",
  "com.enragedginger" %% "akka-quartz-scheduler" % "1.5.0-akka-2.4.x",
  "joda-time" % "joda-time" % "2.7",
  "org.joda" % "joda-convert" % "1.8.1",
  "org.postgresql" % "postgresql" % "42.1.1",
  "com.h2database" % "h2" % "1.4.193" % Test,
  "com.codeborne" % "phantomjsdriver" % "1.2.1" % Test,
  "com.mohiva" %% "play-silhouette-testkit" % "4.0.0" % Test,
  specs2 % Test,
  filters,
  cache,
  ws
)
```
I have already tried clean, as well as completely removing the ./target and ./project/target directories manually.

What else can I do to either clean the project or list the dependencies to try to pin this down?

Thanks

**Comment by cchantep** [comment]
I meant check the transitive dependencies (e.g. using `dependencyTree` in sbt)

**Comment by rickeyski** [comment]
Ahh, I think this shows the issue. I need to downgrade slick-pg, or not use it's play-json module

```
+-com.github.tminglei:slick-pg_play-json_2.11:0.15.1
 | +-com.github.tminglei:slick-pg_core_2.11:0.15.1
 | | +-com.typesafe.slick:slick_2.11:3.2.0 [S]
 | | | +-com.typesafe:config:1.2.1 (evicted by: 1.3.1)
 | | | +-com.typesafe:config:1.3.1
 | | | +-org.reactivestreams:reactive-streams:1.0.0
 | | | +-org.slf4j:slf4j-api:1.7.18 (evicted by: 1.7.25)
 | | | +-org.slf4j:slf4j-api:1.7.21 (evicted by: 1.7.25)
 | | | +-org.slf4j:slf4j-api:1.7.25
 | | | 
 | | +-org.postgresql:postgresql:42.1.1
 | | +-org.scala-lang:scala-reflect:2.11.11 [S]
 | | 
 | +-com.typesafe.play:play-json_2.11:2.6.0 [S]
 | | +-com.fasterxml.jackson.core:jackson-annotations:2.8.8
 | | +-com.fasterxml.jackson.core:jackson-core:2.8.8
 | | +-com.fasterxml.jackson.core:jackson-databind:2.8.8
 | | | +-com.fasterxml.jackson.core:jackson-annotations:2.8.0 (evicted by: 2.8.8)
 | | | +-com.fasterxml.jackson.core:jackson-annotations:2.8.8
 | | | +-com.fasterxml.jackson.core:jackson-core:2.8.8
```

**Comment by rickeyski** [comment]
Yup, removing slick-pg_play-json solves it. Thanks for your help.
