### ISSUE TITLE
Overriden HttpConfiguration not applied to AkkaHttpServer

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#7564]
Play 2.6.0
Scala 2.12.2

My application.conf does not contain `play.http.secret.key`
My AppComponents has something like this

```scala
// since we are not using cookies we use a random crypto secret each time
override lazy val httpConfiguration: HttpConfiguration = {
  val randomSecretConfig = Configuration("play.http.secret.key" -> UUID.randomUUID().toString)
  val configWithRandomSecret = configuration ++ randomSecretConfig
  HttpConfiguration.fromConfiguration(configWithRandomSecret, environment)
}
```

### Expected Behavior

1) Production server starts correctly
2) Server handles requests with a random secret

### Actual Behavior

1) Production server starts correctly (does not complain about unconfigured secret)
2) Any request fails (500) with below exception

It seems that the `AkkaHttpServer` somehow builds it's own `HttpConfiguration` from the config instead of using the one provided. I wonder if overriding the `context.initialConfiguration` instead would fix this.

```
2017-07-04T17:54:22,988Z [application-akka.actor.default-dispatcher-269] ERROR akka.actor.ActorSystemImpl - Internal server error, sending 500 response
play.api.Configuration$$anon$1: Configuration error[
The application secret has not been set, and we are in prod mode. Your application is not secure.
To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
          ]
	at play.api.Configuration$.configError(Configuration.scala:155)
	at play.api.Configuration.reportError(Configuration.scala:984)
	at play.api.http.HttpConfiguration$.getSecretConfiguration(HttpConfiguration.scala:237)
	at play.api.http.HttpConfiguration$.fromConfiguration(HttpConfiguration.scala:222)
	at play.core.server.AkkaHttpServer.resultUtils$lzycompute(AkkaHttpServer.scala:151)
	at play.core.server.AkkaHttpServer.resultUtils(AkkaHttpServer.scala:149)
	at play.core.server.AkkaHttpServer.modelConversion$lzycompute(AkkaHttpServer.scala:161)
	at play.core.server.AkkaHttpServer.modelConversion(AkkaHttpServer.scala:157)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:168)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$3(AkkaHttpServer.scala:95)
	at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
	at akka.actor.Actor.aroundReceive(Actor.scala:513)
	at akka.actor.Actor.aroundReceive$(Actor.scala:511)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by marcospereira** [comment]
Hi @francisdb, 

This is happening because we don't have access to `HttpConfiguration` from the application instance then we need to create it from `Configuration`. I don't think we should change the `Application` API to add `HttpConfiguration` access because we will start to pollute the API with something that can be created with the existing methods.

The workaround here is to override `configuration` instead of `httpConfiguration`:

```scala
  override lazy val configuration: Configuration = {
    context.initialConfiguration ++ Configuration("play.http.secret.key" -> UUID.randomUUID().toString)
  }
```
I'm closing this for now. We can reopen it later if necessary.

**Comment by francisdb** [comment]
Thanks for the workaround.
