### ISSUE TITLE
[2.5|6.x] Play doesn't play nice with Akka cluster

### ISSUE THREAD

**Issue by igmar** [playframework/playframework#7726]
### Play Version (2.5.x / etc)

2.5.16, 2.6.2.

### API (Scala / Java / Neither / Both)

Java

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Oracle java version "1.8.0_144"

### Library Dependencies

akka-actor 2.5.3
akka-cluster-tools 2.5.3
akka-persistence 2.5.3
akka-distributed-data 2.5.3

### Expected Behavior

No errors on bootup.

### Actual Behaviour

Exception on bootup : 

```
! @751h4dkk6 - Internal server error, for (GET) [/healthcheck] ->

play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.IllegalArgumentException: pre-creation serialization check failed at [akka://application/user/anactor]
  at play.libs.akka.AkkaGuiceSupport.bindActor(AkkaGuiceSupport.java:53) (via modules: com.google.inject.util.Modules$OverrideModule -> bootstrap.Bootstrap)
  at play.libs.akka.AkkaGuiceSupport.bindActor(AkkaGuiceSupport.java:53) (via modules: com.google.inject.util.Modules$OverrideModule -> bootstrap.Bootstrap)
  while locating akka.actor.ActorRef annotated with @com.google.inject.name.Named(value=anactor)

1 error]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1.reload(DevServerStart.scala:186)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1.get(DevServerStart.scala:124)
	at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$modelConversion(AkkaHttpServer.scala:184)
	at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$handleRequest(AkkaHttpServer.scala:190)
	at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:107)
	at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:107)
	at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.IllegalArgumentException: pre-creation serialization check failed at [akka://application/user/anactor]
  at play.libs.akka.AkkaGuiceSupport.bindActor(AkkaGuiceSupport.java:53) (via modules: com.google.inject.util.Modules$OverrideModule -> bootstrap.Bootstrap)
  at play.libs.akka.AkkaGuiceSupport.bindActor(AkkaGuiceSupport.java:53) (via modules: com.google.inject.util.Modules$OverrideModule -> bootstrap.Bootstrap)
  while locating akka.actor.ActorRef annotated with @com.google.inject.name.Named(value=anactor)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$1.apply(DevServerStart.scala:174)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$1.apply(DevServerStart.scala:171)
Caused by: java.lang.IllegalArgumentException: pre-creation serialization check failed at [akka://application/user/anactor]
	at akka.actor.dungeon.Children$class.makeChild(Children.scala:264)
	at akka.actor.dungeon.Children$class.attachChild(Children.scala:48)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:370)
	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:717)
	at play.api.libs.concurrent.ActorRefProvider.get$lzycompute(Akka.scala:210)
	at play.api.libs.concurrent.ActorRefProvider.get(Akka.scala:208)
	at play.api.libs.concurrent.ActorRefProvider.get(Akka.scala:204)
	at com.google.inject.util.Providers$GuicifiedProvider.get(Providers.java:119)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
Caused by: java.io.NotSerializableException: play.api.libs.concurrent.ActorRefProvider
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply$mcV$sp(Serializer.scala:313)
	at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply(Serializer.scala:313)
	at akka.serialization.JavaSerializer$$anonfun$toBinary$1.apply(Serializer.scala:313)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
```

### Reproducible Test Case

See github repo : https://github.com/igmar/play-GH-7726

**Comment by wsargent** [comment]
You're using an injected child actor, but there is no parent actor defined and you're not calling `bindChildActor`.

You've also got 

```
serialize-messages = on
serialize-creators = on
```

Comment those two settings out and it should work fine.

**Comment by igmar** [comment]
The real application uses DI child actors with assisted inject, so I can't bind them with bindChildActor.

serialize-messages and serialize-creators are set to on according to recommendations in the Akka docs to test for potential serialisation issues.

**Comment by wsargent** [comment]
"We recommend having these config options turned on only when you’re running tests. Turning these options on in production is pointless, as it would negatively impact the performance of local message passing without giving any gain."

http://doc.akka.io/docs/akka/2.5.3/scala/serialization.html#verification

**Comment by wsargent** [comment]
You may want to use something like https://stackoverflow.com/questions/37767024/scala-akka-guice-dynamically-injecting-child-actors

**Comment by wsargent** [comment]
@igmar still don't see this.  There's nothing that says the injected guice actor creator has to be serializable, and I don't think DI and serialization mix very well in general.

**Comment by igmar** [comment]
Agree. But still : If you follow what the Akka docs say, you'll land on this issue. I'm not even sure this is a real issue : It might Just Work (c).
