### ISSUE TITLE
SyncCacheApi.get() fails when used in a POST handler

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7774]
### Play Version (2.6.3), API (Java), (Ubuntu 16.04), OpenJDK 1.8.0_131

`SyncCacheApi.get()` fails when called from within a POST handler, but works when called from within a GET handler.

Please see my example repo here:  https://github.com/rmcloughlin/play-cache-bug in particular https://github.com/rmcloughlin/play-cache-bug/blob/master/app/controllers/HomeController.java

```java
public Result doGet() {
    syncCacheApi.get("abc");
    return ok("ok GET");
}
public Result doPost() {
    syncCacheApi.get("abc");
    return ok("ok POST");
}
```

`sbt run`
`curl http://localhost:9000`
works fine
`curl -X POST http://localhost:9000`
fails with the stacktrace below.

I am running the app in the "highly synchronous" style https://www.playframework.com/documentation/2.6.x/ThreadPools#Highly-synchronous but the problem occurs even if I run it with the default settings (with a blank `application.conf` file).

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.util.concurrent.TimeoutException]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
	at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at play.cache.DefaultSyncCacheApi.blocking(DefaultSyncCacheApi.java:88)
	at play.cache.DefaultSyncCacheApi.get(DefaultSyncCacheApi.java:31)
	at controllers.HomeController.doPost(HomeController.java:21)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$4(Routes.scala:96)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:136)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:135)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:110)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:78)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
	at play.core.j.JavaAction.$anonfun$apply$2(JavaAction.scala:113)
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at play.cache.DefaultSyncCacheApi.blocking(DefaultSyncCacheApi.java:82)
	at play.cache.DefaultSyncCacheApi.get(DefaultSyncCacheApi.java:31)
	at controllers.HomeController.doPost(HomeController.java:21)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$4(Routes.scala:96)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:136)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:135)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:110)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:78)
```

**Comment by rmcloughlin** [comment]
This problem occurs in both dev and prod mode.  It does not occur in Play 2.6.2 (in either mode).

**Comment by mkurz** [comment]
Probably related to #7649 / #7672 - I will have a look later today

**Comment by mkurz** [comment]
I can reproduce. I have no idea why it works for `GET` but fails for `POST`.
First I thougth maybe it has something to do with the filters that are enabled by default, but the problem also occurs when disabling them via `.disablePlugins(PlayFilters)`.

I have to investigate further. Maybe someone else can have a look as well.

**Comment by mkurz** [comment]
I started debugging a bit and I _think_ it has something to do with akka http - how it handles `GET` vs. `POST` requests.
Maybe this is something to look into before releasing Play 2.6.4. It's late here and I am quite tired... :sleeping: 

@gmethvin @marcospereira @richdougherty maybe you can have a look?

**Comment by mkurz** [comment]
OK, when using netty then even the `GET` request fails already:
```
lazy val root = (project in file(".")).enablePlugins(PlayScala, PlayNettyServer).disablePlugins(PlayAkkaHttpServer).disablePlugins(PlayFilters)
```


I think when using the `thread-pool-executor` as default dispatcher you just have to use an own execution context for other blocking operations (like the cache one) by setting `play.cache.dispatcher = "mydispatcher"`. That should work.
But I don't understand why the threads within the default dispatcher block each other... There should be threads available. Anyway... I am tired...

**Comment by gmethvin** [comment]
Not sure of the exact cause here, but I know the default implementation is not very efficient. The EhCache library itself is blocking, so the async implementation actually blocks, then we block another thread waiting on the future.
