### ISSUE TITLE
2.6.x unsafe if-modified-since handling (breaks assets)

### ISSUE THREAD

**Issue by mriehl** [playframework/playframework#7798]
### Play Version (2.5.x / etc)
2.6.3

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux 4.13

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

hotspot 1.8.0_144

### Expected Behavior

On any play application with an assets route (I'm using `GET           /assets/*file                             controllers.Assets.versioned(path="/public/assets", file: Asset)` as route here)

```bash
curl 'http://localhost:9000/assets/test' -H 'If-Modified-Since: Mon, 26 Jul 1997 05:00:00 GMT' 
```

should work.

I found this out the hard way because my firefox browser sends this header for specific assets.
UPDATE: This seems to be some stupid javascript that sets a global if-modified-since header that is not necessarily correct.
Still I would expect play to handle this gracefully (maybe with a 4xx status code but ideally just serve the asset anyway)

### Actual Behavior
The entire play asset stack explodes.
The date parsing code seems to be throwing away the time zone and thus ends up in a illegal state.

```
[error] a.m.f.ErrorHandler - flow_id=7a7b5f52-92d9-11e7-bfcc-9cb6d0d9871d, request_uri=/assets/shapes/germany.geojson - Internal server error GET /assets/shapes/germany.geojson             
java.lang.RuntimeException: Unexpected error while serving shapes/germany.geojson at /public/assets: Text 'Mon, 26 Jul 1997 05:00:00' could not be parsed: Conflict found: Field DayOfWeek 6 differs from DayOfWeek 1 derived from 1997-07-26
        at controllers.AssetsBuilder$$anonfun$assetAt$6.applyOrElse(Assets.scala:760)         
        at controllers.AssetsBuilder$$anonfun$assetAt$6.applyOrElse(Assets.scala:755)         
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)                   
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)           
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)                       
        at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)  
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)            
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)          
        at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:312)                                                                                             
        at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:303)         
Caused by: java.time.format.DateTimeParseException: Text 'Mon, 26 Jul 1997 05:00:00' could not be parsed: Conflict found: Field DayOfWeek 6 differs from DayOfWeek 1 derived from 1997-07-26 
        at java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:1920)        
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1855)              
        at java.time.ZonedDateTime.parse(ZonedDateTime.java:597)                              
        at controllers.Assets$.parseModifiedDate(Assets.scala:575)                            
        at controllers.AssetsBuilder.$anonfun$maybeNotModified$4(Assets.scala:644)            
        at scala.Option.flatMap(Option.scala:171)                                             
        at controllers.AssetsBuilder.maybeNotModified(Assets.scala:643)                       
        at controllers.AssetsBuilder.$anonfun$assetAt$3(Assets.scala:744)                     
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)                       
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)           
Caused by: java.time.DateTimeException: Conflict found: Field DayOfWeek 6 differs from DayOfWeek 1 derived from 1997-07-26                                                                   
        at java.time.format.Parsed.crossCheck(Parsed.java:647)                                
        at java.time.format.Parsed.crossCheck(Parsed.java:624)                                
        at java.time.format.Parsed.resolve(Parsed.java:246)                                   
        at java.time.format.DateTimeParseContext.toResolved(DateTimeParseContext.java:331)    
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1955)     
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)              
        at java.time.ZonedDateTime.parse(ZonedDateTime.java:597)                              
        at controllers.Assets$.parseModifiedDate(Assets.scala:575)                            
        at controllers.AssetsBuilder.$anonfun$maybeNotModified$4(Assets.scala:644)            
        at scala.Option.flatMap(Option.scala:171)
```

### Reproducible Test Case
```bash
curl 'http://localhost:9000/assets/test' -H 'If-Modified-Since: Mon, 26 Jul 1997 05:00:00 GMT' 
```

**Comment by mkurz** [comment]
Yeah, 6 Jul 1997 was a Saturday, not a Monday...

**Comment by mriehl** [comment]
Yes it's a client issue. Still I wouldn't expect the framework to handle this by blowing up. I mean an error code might be a good thing (because silently ignoring it as play 2.5 did will let the issue stagnate) but 500 is pretty rough.

**Comment by gmethvin** [comment]
We should be ignoring the date in this case. See https://tools.ietf.org/html/rfc7232#section-3.3:

> A recipient MUST ignore the If-Modified-Since header field if the received field-value is not a valid HTTP-date, or if the request method is neither GET nor HEAD.

So the fix is just to catch the exception and return `None` from `parseModifiedDate`.
