### ISSUE TITLE
FileNotFoundException thrown after enabling ws cache.

### ISSUE THREAD

**Issue by joymufeng** [playframework/playframework#7863]
### Play Version 
2.6.5

### API 
Scala

### Operating System
Windows 10 & CentOS Linux 7

### JDK 
Oracle 1.8.0_72

### Expected Behavior
WS cache should works normally with the configuration as following:
```
play.ws {
   cache.enabled = true
   cache.cacheManagerURI="file:./conf/ehcache-play-ws-cache.xml"
}
```

### Actual Behavior
It works normally in dev mode on Windows 10, however, FileNotFoundException thrown after deploying to linux server(CentOS 7).
```
Caused by: net.sf.ehcache.CacheException: Error configuring from file:./conf/ehcache-play-ws-cache.xml. Initial cause was ./conf/ehcache-play-ws-cache.xml (No such file or directory)
        at net.sf.ehcache.config.ConfigurationFactory.parseConfiguration(ConfigurationFactory.java:105)
        at org.ehcache.jcache.JCacheCachingProvider.getCacheManager(JCacheCachingProvider.java:97)
        at org.ehcache.jcache.JCacheCachingProvider.getCacheManager(JCacheCachingProvider.java:72)
        at play.api.libs.ws.ahc.OptionalAhcHttpCacheProvider.optionalCache(AhcWSModule.scala:121)
        at play.api.libs.ws.ahc.OptionalAhcHttpCacheProvider.get$lzycompute(AhcWSModule.scala:96)
        at play.api.libs.ws.ahc.OptionalAhcHttpCacheProvider.get(AhcWSModule.scala:95)
        at play.api.libs.ws.ahc.AsyncHttpClientProvider.get$lzycompute(AhcWSModule.scala:49)
        at play.api.libs.ws.ahc.AsyncHttpClientProvider.get(AhcWSModule.scala:45)
        at play.api.libs.ws.ahc.AsyncHttpClientProvider.get(AhcWSModule.scala:39)
...
Caused by: java.io.FileNotFoundException: ./conf/ehcache-play-ws-cache.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at java.net.URL.openStream(URL.java:1045)
        at net.sf.ehcache.config.ConfigurationFactory.parseConfiguration(ConfigurationFactory.java:102)
        ... 81 more
```

**Comment by joymufeng** [comment]
@gmethvin Hi gmethvin, I fix this issue by #7864 , could you please have a check!  I find that the test already exists in play.api.libs.ws.ahc.OptionalAhcHttpCacheProviderSpec.
