### ISSUE TITLE
Useful error message when result is null

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7866]
### Are you looking for help?

No.

### Play Version (2.5.x / etc)

2.6.3

### API (Scala / Java / Neither / Both)

Java

### Behavior

If a controller method returns null (for a `Result`) the error message is not useful.  See below.  The exceptions don't contain any info about my own code.  The web page also just shows "NullPointerException: null"

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:251)
        at play.core.server.AkkaHttpServer$$anonfun$$nestedInanonfun$executeHandler$1$1.applyOrElse(AkkaHttpServer.scala:250)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:412)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:312)
Caused by: java.lang.NullPointerException: null
        at play.core.j.JavaHelpers.createResult(JavaHelpers.scala:134)
        at play.core.j.JavaHelpers.createResult$(JavaHelpers.scala:133)
        at play.core.j.JavaAction.createResult(JavaAction.scala:59)
        at play.core.j.JavaAction.$anonfun$apply$4(JavaAction.scala:115)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
```

![exception](https://user-images.githubusercontent.com/4472381/31046986-82a09042-a5d0-11e7-9bb0-91da31c166a6.png)

**Comment by richdougherty** [comment]
Good idea!

**Comment by DReigada** [comment]
I can take this one!
