### ISSUE TITLE
AkkaHttp on Dev uses play.runsupport.NamedURLClassLoader, produces ClassNotFoundException on reflection

### ISSUE THREAD

**Issue by GeorgiChochov** [playframework/playframework#7957]
### JDK (Oracle 1.8.0_112)

I am upgrading the Play version of a project from 2.5.14 to 2.6.6. I use JsonDoc lib ("org.jsondoc" % "jsondoc-core" % "1.2.10") for API documentation and am running into this issue on Dev. The fault isn't in the lib, but it was what revealed the issue to me.

### Expected Behavior

Using reflection on Dev should not result in a **ClassNotFoundException**. HTTP requests should use **play.runsupport.DelegatedResourcesClassLoader** and run on an **application-akka.actor.default-dispatcher** thread, as was the case in Play 2.5.14.

### Actual Behavior

1. On Dev:
a) AkkaHttp Server - uses **play.runsupport.NamedURLClassLoader** with **play-dev-mode-akka.actor.default-dispatcher** and produces **ClassNotFoundException**
b) Netty Server - uses **play.runsupport.DelegatedResourcesClassLoader** with **application-akka.actor.default-dispatcher** and produces no exceptions
2. On Prod (either server): uses **sun.misc.Launcher$AppClassLoader** with **application-akka.actor.default-dispatcher** and produces no exceptions

### Workaround

1. Temporarily set the correct ClassLoader manually from the play environment.
2. Revert from AkkaHttp to Netty server.

### Stack Trace
```
o.r.Reflections - could not get type for name models.Foo from any class loader
org.reflections.ReflectionsException: could not get type for name models.Foo
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
        at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:409)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:433)
        at org.jsondoc.core.scanner.DefaultJSONDocScanner.jsondocObjects(DefaultJSONDocScanner.java:48)
        at org.jsondoc.core.scanner.AbstractJSONDocScanner.getJSONDoc(AbstractJSONDocScanner.java:96)
        at controllers.JsonDocController.getJsonDocNode(JsonDocController.java:47)
        at controllers.JsonDocController.getJsonDoc(JsonDocController.java:28)
        at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$4(Routes.scala:123)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
Caused by: java.lang.ClassNotFoundException: models.Foo
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
        at org.reflections.ReflectionUtils.forNames(ReflectionUtils.java:409)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:433)
        at org.jsondoc.core.scanner.DefaultJSONDocScanner.jsondocObjects(DefaultJSONDocScanner.java:48)
        at org.jsondoc.core.scanner.AbstractJSONDocScanner.getJSONDoc(AbstractJSONDocScanner.java:96)
        at controllers.JsonDocController.getJsonDocNode(JsonDocController.java:47)
        at controllers.JsonDocController.getJsonDoc(JsonDocController.java:28)
```

### Reproducible Test Case
Demo project reproduces the issue upon calling /doc (GET)
https://github.com/GeorgiChochov/play-2.6.6-classloader-example

**Comment by richdougherty** [comment]
@GeorgiChochov, thanks for the report. This is probably a change because we now run user code on the server threads in dev mode. The "safe" way to do classloading in Play is to use the `Environment` object to get the application `ClassLoader`. Then, when using reflection, always explicitly use that `ClassLoader`. If you use a library that doesn't let you explicitly provide a `ClassLoader` then you need to use `Thread.setContextClassLoader` around the library code.

**Comment by GeorgiChochov** [comment]
@richdougherty, thanks for the reply. I take it this is as intended then. Could I ask why user code runs on the server threads in dev mode now?

**Comment by richdougherty** [comment]
I believe it is for performance reasons - it avoid a thread switch. However, ClassLoader issues have always been a problem in dev mode.
