### ISSUE TITLE
Error when using custom logback appender

### ISSUE THREAD

**Issue by nemoo** [playframework/playframework#8003]
### Expected Behavior

When using logback, I expect to be able to add custom logback appenders to the default appenders in play framework. The additional appender should be initiated correctly and used for logging.

### Actual Behavior

The custom appender is not instantiated and not used. Instead this error is thrown: 
`14:52:28,831 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [utils.logging.GelfAppender]. ch.qos.logback.core.util.DynamicClassLoadingExcep
tion: Failed to instantiate type utils.logging.GelfAppender
        at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type utils.logging.GelfAppender
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:45)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:34)
        at      at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:52)
        at      at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
        at      at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
        at      at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
        at      at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at      at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at      at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:118)
        at      at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:65)
        at      at play.api.inject.guice.GuiceApplicationBuilder.$anonfun$configureLoggerFactory$1(GuiceApplicationBuilder.scala:122)
        at      at scala.Option.map(Option.scala:146)
        at      at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:121)
        at      at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:100)
        at      at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at      at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at      at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at      at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
        at      at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at      at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
        at      at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
        at      at play.core.server.AkkaHttpServer.modelConversion(AkkaHttpServer.scala:183)
        at      at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:189)
        at      at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$3(AkkaHttpServer.scala:106)
        at      at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
        at      at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
        at      at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
        at      at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
        at      at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
        at      at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
        at      at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
        at      at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:728)
        at      at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:743)
        at      at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at      at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at      at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:653)
        at      at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at      at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at      at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at      at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at      at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at      at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at      at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at      at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at      at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: utils.logging.GelfAppender
        at      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:56)
        at      ... 48 common frames omitted`

### Reproducible Test Case

A project in Github that reproduces the problem can be found here: 
https://github.com/nemoo/play-slick3-example/tree/appender

The relevant commit where the appender was added is here: 
https://github.com/nemoo/play-slick3-example/commit/3228dbbc9c334b50be8062d812e11a7140f35782

**Comment by wsargent** [comment]
You probably need a custom log configurator for that -- see https://www.playframework.com/documentation/2.6.x/SettingsLogger#Using-a-Custom-Logging-Framework

**Comment by nemoo** [comment]
The additional (GELF) appender should work on top of the existing appenders. You wrote that I probably need a custom log configurator. So I would have to reimplement standard play logging first with logback with a custom log configurator so that default logging into the console and a log file works? And then I can hopefully add an additional custom appender to logback?

**Comment by marcospereira** [comment]
Hi @nemoo, 

Yes. What @wsargent was suggesting is that you can add a custom appender customizing the way Logback is initialized. The way you do that is by creating a custom LoggerConfigurator. If you want to preserve all the existing behavior of the default logger configurator, then you can extend it or use it just as a start point to create your own.

I'm not sure it is an issue with Play and the [mailing list](https://groups.google.com/forum/#!forum/play-framework) may be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

So I'm closing this issue, but if I'm missing something, let me know and we can reopen it.
