### ISSUE TITLE
[2.6.7] CSRFFilter not setting session cookie when response has Cache-Control header

### ISSUE THREAD

**Issue by petenattress** [playframework/playframework#8026]
### Play Version (2.5.x / etc)

2.6.7

### API (Scala / Java / Neither / Both)

Java (probably also affects Scala but not tested)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

### Library Dependencies

n/a

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Run this version of the Play Java forms example, which sets a `no-cache` cache control header on the form GET response: https://github.com/petenattress/play-java-forms-example/commit/b39c79dcd6b869c31860505c4098b8316ecd4243
2. Clear all browser cookies for `localhost:9000` (or wherever you're running the example)
3. Go to `http://localhost:9000/widgets`, fill in the form and hit submit
4. The application should accept the POST request

### Actual Behavior

The POST request is rejected with a 403 ("You must be authenticated to access this page."). This is because Play is not setting the CSRF token in the session cookie for the initial GET. You can see this in the logs with trace enabled:

```
[trace] p.c.r.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1 - Invoking action with request: GET /widgets
[trace] p.filters.CSRF - [CSRF] Not adding token to cached response
```

This decision is caused by the following function in `CSRFActions.scala`:

```
  def isCached(result: Result): Boolean =
    result.header.headers.get(CACHE_CONTROL).fold(false)(!_.contains("no-cache"))
```

So if `Cache-Control` doesn't explicitly contain `no-cache` the response is considered "cacheable" by the CSRF filter. However the definition of `no-cache` doesn't actually mean "don't cache", it means "revalidate before serving from cache" (e.g. https://stackoverflow.com/questions/866822/why-both-no-cache-and-no-store-should-be-used-in-http-response). 

`no-store` is an explicit "never cache this" instruction. It seems to me it would be more correct for the CSRF filter to check for this value, but checking for either would probably also be fine (I'm no expert on the practicalities of implementing a CSRF check).

We've worked around this by setting `no-cache, no-store` on the relevant responses, which I have no problem with doing as it is still "correct". However this was a nasty one to diagnose so it would be nice to get it fixed in Play if you agree it's a bug.

**Comment by tsuyoshizawa** [comment]
I have met a problem on my project is using custom HttpErrorHandler with i18n.
The custom HttpErrorHandler couldn't get Cookie value.

My project could reproduce the error with Cache-Control header.

I paste the stack trace.

```
2017-11-20 09:32:24,782 [ERROR] play.core.server.netty.PlayRequestHandler netty-event-loop-1 - Exception caught in Netty
java.util.NoSuchElementException: key not found: Cookies
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:59)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:59)
        at play.api.libs.typedmap.DefaultTypedMap.apply(TypedMap.scala:87)
        at play.api.mvc.RequestHeader$class.cookies(RequestHeader.scala:221)
        at play.api.mvc.RequestHeaderImpl.cookies(RequestHeader.scala:368)
        at play.api.i18n.DefaultMessagesApi.preferred(Messages.scala:460)
        at play.api.i18n.I18nSupport$class.request2Messages(I18nSupport.scala:32)
        at CustomHttpErrorHandler.request2Messages(CustomHttpErrorHandler.scala:xx)
        at CustomHttpErrorHandler.onBadRequest(CustomHttpErrorHandler.scala:xx)
        at play.api.http.DefaultHttpErrorHandler.onClientError(HttpErrorHandler.scala:117)
        at play.core.server.netty.PlayRequestHandler.clientError$1(PlayRequestHandler.scala:86)
        at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:95)
        at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:184)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
        at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mirikle** [comment]
Looks like this issue is in 2.6.10 too.

**Comment by gmethvin** [comment]
@petenattress Noticed this issue hasn't been triaged yet. I agree with you we should take into account `no-store`. I think the right thing to do is check for either `no-cache` or `no-store`, because the key thing that the CSRF filter cares about is whether a cached result will be served back to a user in a subsequent request, which `no-cache` and `no-store` would both prevent. This is pretty easy to fix so if you or someone else is interested in submitting a PR that would be great.

**Comment by gmethvin** [comment]
@tsuyoshizawa I don't see how the issue you mentioned is related to this one. I'd suggest you discuss on the mailing list, or open another issue with a reproducer.

**Comment by petenattress** [comment]
Thanks for the feedback @gmethvin, I will try to find some spare time to submit a PR.

**Comment by richdougherty** [comment]
After a dive into some of the caching specs I have a headache!

1. I agree that we can add a CSRF token when `no-store` is present.
2. But maybe our old behaviour is wrong. Perhaps it's unsafe to add a CSRF token when `no-cache` is present since caching can happen. On the other hand apparently caching can happen even without a `Cache-Control` header being present at all! In both cases the cache is supposed revalidate before serving the cached content, but that's not 100% safe since revalidation could succeed if the server isn't aware of the security risks. That could leak a token. Perhaps `isCached` should return `true` in both these cases, but it would probably break a lot of code…

   Maybe we need to update the CSRF filtering to have a proper understanding of caching directives by using a library like https://github.com/playframework/cachecontrol. Or maybe we need to change CSRF so it controls the caching explicitly by overriding thecaching headers when CSRF tokens are present. Or maybe we need to rethink how we do CSRF?

For now lets go ahead with supporting `no-store` properly, since that's a definite improvement. 😄

**Comment by srirachapills** [comment]
@richdougherty I think we would only need a few test setup fixes to correct your second point... most of them should test in context of an explicit `no-cache` policy. I don't see other problems but you guys  know better!
