### ISSUE TITLE
HttpEntity.Streamed swallows stream failure exception

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#8062]
Play `2.6.7`

When a request throws an exception you normally get a `500` response and an exception is logged. This behavior can be modified in the `HttpErrorHandler`. Eg sending the exception to a bug tracking system.

But for streamed responses where the stream fails the exception is just swallowed and the connection is closed. (curl: (56) Recv failure: Connection reset by peer)
I guess that for chunked responses there is no way to change the response code after the streaming starts. However this exception should at least be logged as this is similar to the `500` case.

In our case we have a nginx in front of play and it makes this issue worse because nginx translates the connection reset into a normal request ending. So the consumers of our api just got a `200` with an empty response.

We spent quite some time on finding the source of our "empty" chunked response and a logged exception could have made this much easier to find.

as a workaround we currently do this:

```scala
        val ndJson = jsonMessages.recoverWithRetries(0, {
          case e =>
            log.error("Stream failed", e)
            Source.single(Json.obj("error" -> "error during streaming")).concat(
              Source.failed(e)
            )
        }) via NDJSON.write
        Result(
          header = ResponseHeader(200, Map.empty),
          body = HttpEntity.Streamed(ndJson, None, Some("application/x-ndjson"))
        )
```

**Comment by gmethvin** [comment]
If you have ideas we're happy to accept a PR. This is something I'd really like to improve.

**Comment by francisdb** [comment]
It would be a good start to just log the exception as level error in the default play logs.

**Comment by richdougherty** [comment]
Picking up on @gmethvin's idea, we could have an extra method in `HttpErrorHandler` to handle streaming errors.

We could pass this method the `RequestHeader` and the `ResponseHeader`. We might also be able to pass the number of bytes streamed so far, which would allow the user to handle an empty response differently from a partly streamed response.

This method could log the error by default and return an empty `Source` and a request to close the connection. (From memory I don't think `Source` lets us signal whether to close the connection after it has finished due to an error - that might have to be a separate value.)

The user could override the error handling method to change the logging behaviour or implement some sort of custom failure handling such as sending an "error" in the body of the message even when the headers are 200 OK.

**Comment by francisdb** [comment]
Reproducing is simple:

```scala
def boom = Action{
  Ok.chunked(Source.failed[String](new RuntimeException("BOOM")))
}
```

```
curl http://localhost:9000/boom
curl: (56) Recv failure: Connection reset by peer
```

The server logs contain no exception, this is similar to a 500 error and should be logged

**Comment by mkurz** [comment]
> The server logs contain no exception, this is similar to a 500 error and should be logged

In Play 2.9/3.0 the error **does** get logged in `logs/application.log`, both in dev mode and prod mode (when staging the app and running `./target/universal/stage/bin/play-scala-seed`).
@francisdb can you check if at least the error now gets logged for you as well? Thanks!
```
2024-03-14 14:16:26 ERROR o.apache.pekko.actor.ActorSystemImpl org.apache.pekko.actor.ActorSystemImpl(application) Response stream for [GET /boom] failed with 'BOOM'. Aborting connection.
java.lang.RuntimeException: BOOM
        at controllers.HomeController.$anonfun$boom$1(HomeController.scala:28)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:496)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:494)
        at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:434)
        at play.api.mvc.Action.$anonfun$apply$6(Action.scala:83)
        at play.api.mvc.BodyParser$.$anonfun$runParserThenInvokeAction$1(Action.scala:260)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:167)
        at scala.util.Try$.apply(Try.scala:217)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:167)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:87)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:198)
        at play.core.server.PekkoHttpServer.$anonfun$runAction$3(PekkoHttpServer.scala:467)
        at org.apache.pekko.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:49)
        at org.apache.pekko.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:59)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
        at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
        at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
        at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
        at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by francisdb** [comment]
@mkurz sorry, not longer working on that project so can't verify.

**Comment by iRevive** [comment]
Hey @mkurz. I ran into this issue recently. 

The Play version is `3.0.4`. I can confirm, that the error is logged:
```
Response stream for [POST /......] failed with '[error message]'. Aborting connection.
```
