### ISSUE TITLE
Exception from Filter is not caught by HttpErrorHandler.onServerError

### ISSUE THREAD

**Issue by FranklinYinanDing** [playframework/playframework#8089]
### Play Version (2.5.x / etc)

2.6.x

### API (Scala / Java / Neither / Both)

Both

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. When a `Filter` throws an exception, it should be caught by `HttpErrorHandler.onServerError`.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

Be descriptive: "it doesn't work" does not describe what the behavior actually is -- instead, say "the page renders a 500 error code with no body content."  Copy and paste logs, and include any URLs.  Turn on internal Play logging with `<logger name="play" value="TRACE"/>` if there is no log output.  

1. For Akka HTTP, browser shows 500 error without content. And it logs in the console,
    `[ERROR] [12/11/2017 12:08:11.909] [play-dev-mode-akka.actor.default-dispatcher-6] [akka.actor.ActorSystemImpl(play-dev-mode)] Internal server error, sending 500 response
java.lang.RuntimeException: WRONG
	at filters.ExampleFilter.apply(ExampleFilter.scala:19)
	at play.api.mvc.Filter$$anon$1.apply(Filters.scala:61)
	at play.api.mvc.Filter$$anon$1.apply(Filters.scala:48)
	at play.core.server.AkkaHttpServer.$anonfun$executeHandler$1(AkkaHttpServer.scala:251)
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:48)
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:47)
	at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:285)
	at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:255)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:201)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:107)
	at akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1191)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`
2. For Netty server, browser just waits for response. And it logs in the console,
    `[error] p.c.s.n.PlayRequestHandler - Exception caught in channelRead future
java.lang.RuntimeException: WRONG
	at filters.ExampleFilter.apply(ExampleFilter.scala:19)
	at play.api.mvc.Filter$$anon$1.apply(Filters.scala:61)
	at play.api.mvc.Filter$$anon$1.apply(Filters.scala:48)
	at play.core.server.netty.PlayRequestHandler.$anonfun$handle$3(PlayRequestHandler.scala:114)
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:48)
	at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:47)
	at play.core.server.netty.PlayRequestHandler.$anonfun$handleAction$3(PlayRequestHandler.scala:274)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)`

### Reproducible Test Case

Please provide a PR with a failing test.  

If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

https://github.com/FranklinYinanDing/play-scala-starter-example/tree/2.6.x

**Comment by FranklinYinanDing** [comment]
This behavior was correct in 2.4.x.

For Akka HTTP server, it blows up around [here](https://github.com/playframework/playframework/blob/2.6.x/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L285), when a request is applied to the Filter to get the Accumulator. The Filter tries to call the first `apply` from the second `apply` [here](https://github.com/playframework/playframework/blob/2.6.x/framework/src/play/src/main/scala/play/api/mvc/Filters.scala#L57). Then it throws the exception which is not caught by HttpErrorHandler.

For Netty server, it is slightly different. The error is still result from the Filter's `apply`. But it gets wrapped in a `Future` [here](https://github.com/playframework/playframework/blob/2.6.x/framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala#L274). Then recovered [here](https://github.com/playframework/playframework/blob/2.6.x/framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala#L198).

**Comment by FranklinYinanDing** [comment]
I think it might be fixed by catching the exception [here](https://github.com/playframework/playframework/blob/2.6.x/framework/src/play/src/main/scala/play/api/mvc/Filters.scala#L57).

**Comment by gmethvin** [comment]
The main issue here is that the Play server assumes that your `Future` will include any exceptions that happen during the production of your result. Of course that's not the case if the exception is thrown before the future is even created. The fix you proposed works for `Filter`, but not for `EssentialFilter`. If you create an `EssentialFilter` and your code throws an exception while the new `Accumulator` is being constructed, I would expect to see a similar problem.

It seems like there are two separate bugs in the Akka and Netty implementations both stemming from the fact that we don't handle exceptions called while the future is being generated. Also, in the Akka server we probably should be executing in the default execution context, just as we are with Netty.

**Comment by FranklinYinanDing** [comment]
Thanks @gmethvin for fixing this! I verified all scenarios with 2.6.11.
