### ISSUE TITLE
[2.6.x] Unable to have custom error message for square brackets in url

### ISSUE THREAD

**Issue by papalagichen** [playframework/playframework#8113]
The same question is asked on StackOverflow as well but not got any response yet.

https://stackoverflow.com/questions/47898135/can-play-framework-2-6-x-handle-square-brackets-in-url

Use Play Framework 2.6.9 with akka-http by default. When url contains '[' or ']', HTTP client will receive message:

`Illegal request-target: Invalid input ']', expected pchar, '/', '?' or 'EOI' (line 1, column 32)`

It seems akka-http intercepts the request and returns directly, while Play Framework has no chance to have custom error handler to return custom response.

Is there any way to have custom response for it?

**Comment by wsargent** [comment]
This is the same root as https://github.com/playframework/playframework/issues/1795 -- square brackets are unsafe characters when unencoded in a URL.  

This is an open issue in akka-http at https://github.com/akka/akka-http/issues/210

**Comment by papalagichen** [comment]
Thank you @wsargent!

I try to switch back to use Netty. 

```
lazy val root = (project in file("."))
    .enablePlugins(PlayMinimalJava, PlayNettyServer)
    .disablePlugins(PlayAkkaHttpServer)
```

However, I still encounter an exception:
 
```
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
java.util.NoSuchElementException: key not found: Id
	at scala.collection.immutable.Map$Map2.apply(Map.scala:129)
	at play.api.libs.typedmap.DefaultTypedMap.apply(TypedMap.scala:92)
	at play.api.mvc.RequestHeader.id(RequestHeader.scala:33)
	at play.api.mvc.RequestHeader.id$(RequestHeader.scala:33)
	at play.api.mvc.RequestHeaderImpl.id(RequestHeader.scala:368)
	at play.core.j.JavaHelpers.createJavaContext(JavaHelpers.scala:162)
	at play.core.j.JavaHelpers.createJavaContext$(JavaHelpers.scala:159)
	at play.core.j.JavaHelpers$.createJavaContext(JavaHelpers.scala:293)
	at play.core.j.JavaHelpers.withContext(JavaHelpers.scala:281)
	at play.core.j.JavaHelpers.withContext$(JavaHelpers.scala:280)
```

My testing url is like `/v1/resources/index]`

**Comment by mkurz** [comment]
With akka 10.2.x I think we could make that finally possible: https://github.com/akka/akka-http/pull/3049

**Comment by mkurz** [comment]
This is fixed - probably since a while ago already.
An error caused by having square brackets `[` or `]` in the url will go through the error handler's `onClientError` method in both http backends now (Akka/Pekko HTTP and Netty) - since at least Play 2.9/3.0 - because akka-http 10.2.0+ / pekko changed how it parses urls (see #11667 and #11671). You can also see that in  #13406 Pekko HTTP was used and the error is going through `onClientError` (I can confirm that from local testing).
The error from [this comment above](https://github.com/playframework/playframework/issues/8113#issuecomment-353553056) has now been fixed in 
- #13407

(that error back then showed/confirmed that Netty already passed the error through `onClientError` but only Akka HTTP did not.
