### ISSUE TITLE
Play framework 2.6.x integrating with hibernate orm 5.1.0 mapping error

### ISSUE THREAD

**Issue by shanakaperera** [playframework/playframework#8121]
I am trying to integrate my java play application with hibernate orm and here is my project structure.

[https://i.stack.imgur.com/B4e5g.png](url)

As you can see, I have placed my pojos inside a package named **models**

(In the above picture you can find **hibernate.cfg.xm**l inside **conf**. That is because initially I tried with the configuration xml but I got no luck so I included the configuration properties with the **HibernateUtill** class itself. So you can ignore the hibernate.cfg,xml)

**HibernateUtil class** : (inside services)
```

public class HibernateUtil {

    private static final SessionFactory sessionFactory;

    static {
        try {
            // Create the SessionFactory from standard (hibernate.cfg.xml)
            // config file.

            StandardServiceRegistry serviceRegistry = new StandardServiceRegistryBuilder()
                    .applySetting("hibernate.connection.url", "jdbc:mysql://localhost:3306/database_name")
                    .applySetting("hibernate.connection.driver_class", "com.mysql.jdbc.Driver")
                    .applySetting("hibernate.dialect", "org.hibernate.dialect.MySQLDialect")
                    .applySetting("hibernate.connection.username", "root")
                    .applySetting("hibernate.connection.password", "password")
                    .applySetting("show_sql", "true")
                    .applySetting("format_sql", "true")
                    .applySetting("hibernate.enable_lazy_load_no_trans", "true")
                    .build();

            Thread.currentThread().setContextClassLoader(Coating.class.getClassLoader());

            MetadataSources metadataSources = new MetadataSources();
            metadataSources.addResource("models/Coating.hbm.xml");
            metadataSources.addResource("models/Fitting.hbm.xml");
            metadataSources.addResource("models/Product.hbm.xml");
            metadataSources.addResource("models/Size.hbm.xml");
            metadataSources.addResource("models/ProductHasSize.hbm.xml");
            metadataSources.addResource("models/ProductHasCoating.hbm.xml");
            metadataSources.addResource("models/ProductHasFitting.hbm.xml");


            final MetadataBuilder metadataBuilder = metadataSources.getMetadataBuilder(serviceRegistry);
            MetadataImplementor metadata = (MetadataImplementor) metadataBuilder.build();

            final SessionFactoryBuilder sfb = metadata.getSessionFactoryBuilder();


            sessionFactory = sfb.build();

        } catch (Throwable ex) {
            // Log the exception.
            System.err.println("Initial SessionFactory creation failed." + ex);
            throw new ExceptionInInitializerError(ex);
        }
    }
```

**Controller Class**

```
public class LoginController extends Controller {

    public Result login() throws SQLException {
        Session s = HibernateUtil.getSessionFactory().openSession();
        Criteria c = s.createCriteria(Coating.class);
        c.add(Restrictions.eq("code", "CO3444"));
        Coating co = (Coating) c.uniqueResult();
        String title = co.getTitle();
        s.close();
        return ok(views.html.login_page.login.render(title));
    }
}
```
Everything seems fine for me and once I compile and run the application, It terminates the application server with below error.
```

Initial SessionFactory creation failed.org.hibernate.MappingException: class models.Coating not found while looking for property: id
Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-4]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[play-dev-mode]
java.lang.ExceptionInInitializerError
        at services.HibernateUtil.<clinit>(HibernateUtil.java:61)
        at controllers.LoginController.login(LoginController.java:17)
        at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$2(Routes.scala:164)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:82)
        at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:132)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
        at scala.concurrent.impl.Promise.transform(Promise.scala:29)
        at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
        at scala.concurrent.Future.map(Future.scala:287)
        at scala.concurrent.Future.map$(Future.scala:287)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
        at scala.concurrent.Future$.apply(Future.scala:653)
        at play.core.j.JavaAction.apply(JavaAction.scala:132)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
        at scala.util.Try$.apply(Try.scala:209)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:218)
        at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:217)
        at java.util.function.Function.lambda$andThen$1(Function.java:88)
        at java.util.function.Function.lambda$andThen$1(Function.java:88)
        at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:403)
        at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:400)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
        at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:298)
        at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:255)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:201)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:107)
        at akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1191)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.hibernate.MappingException: class models.Coating not found while looking for property: id
        at org.hibernate.internal.util.ReflectHelper.reflectedPropertyClass(ReflectHelper.java:212)
        at org.hibernate.mapping.SimpleValue.setTypeUsingReflection(SimpleValue.java:437)
        at org.hibernate.boot.model.source.internal.hbm.ModelBinder.bindSimpleEntityIdentifier(ModelBinder.java:719)
        at org.hibernate.boot.model.source.internal.hbm.ModelBinder.bindEntityIdentifier(ModelBinder.java:343)
        at org.hibernate.boot.model.source.internal.hbm.ModelBinder.bindRootEntity(ModelBinder.java:238)
        at org.hibernate.boot.model.source.internal.hbm.ModelBinder.bindEntityHierarchy(ModelBinder.java:185)
        at org.hibernate.boot.model.source.internal.hbm.HbmMetadataSourceProcessorImpl.processEntityHierarchies(HbmMetadataSourceProcessorImpl.java:144)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:218)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:265)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:83)
        at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:418)
        at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:87)
        at services.HibernateUtil.<clinit>(HibernateUtil.java:51)
        ... 71 more
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [models.Coating]
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:229)
        at org.hibernate.internal.util.ReflectHelper.reflectedPropertyClass(ReflectHelper.java:208)
        ... 83 more
Caused by: java.lang.ClassNotFoundException: Could not load requested class : models.Coating
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader.findClass(ClassLoaderServiceImpl.java:217)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:226)
        ... 84 more
[ERROR] [SECURITY][12/26/2017 06:14:10.559] [play-dev-mode-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(play-dev-mode)] Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-4]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play-dev-mode]
java.lang.ExceptionInInitializerError
        at services.HibernateUtil.<clinit>(HibernateUtil.java:61)
        at controllers.LoginController.login(LoginController.java:17)
        at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$2(Routes.scala:164)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:82)
        at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
        at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:132)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
        at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
        at scala.concurrent.impl.Promise.transform(Promise.scala:29)
        at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
        at scala.concurrent.Future.map(Future.scala:287)
        at scala.concurrent.Future.map$(Future.scala:287)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
        at scala.concurrent.Future$.apply(Future.scala:653)
        at play.core.j.JavaAction.apply(JavaAction.scala:132)
        at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
        at scala.util.Try$.apply(Try.scala:209)
        at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:218)
        at play.api.libs.streams.StrictAccumulator$$anon$1.apply(Accumulator.scala:217)
        at java.util.function.Function.lambda$andThen$1(Function.java:88)
        at java.util.function.Function.lambda$andThen$1(Function.java:88)
        at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:403)
        at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:400)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
        at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:298)
        at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:255)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:201)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:107)
        at akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1191)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.hibernate.MappingException: class models.Coating not found while looking for property: id
        at org.hibernate.internal.util.ReflectHelper.reflectedPropertyClass(ReflectHelper.java:212)
        at org.hibernate.mapping.SimpleValue.setTypeUsingReflection(SimpleValue.java:437)
        at org.hibernate.boot.model.source.internal.hbm.ModelBinder.bindSimpleEntityIdentifier(ModelBinder.java:719)
        at org.hibernate.boot.model.source.internal.hbm.ModelBinder.bindEntityIdentifier(ModelBinder.java:343)
        at org.hibernate.boot.model.source.internal.hbm.ModelBinder.bindRootEntity(ModelBinder.java:238)
        at org.hibernate.boot.model.source.internal.hbm.ModelBinder.bindEntityHierarchy(ModelBinder.java:185)
        at org.hibernate.boot.model.source.internal.hbm.HbmMetadataSourceProcessorImpl.processEntityHierarchies(HbmMetadataSourceProcessorImpl.java:144)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:218)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:265)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:83)
        at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:418)
        at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:87)
        at services.HibernateUtil.<clinit>(HibernateUtil.java:51)
        ... 71 more
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [models.Coating]
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:229)
        at org.hibernate.internal.util.ReflectHelper.reflectedPropertyClass(ReflectHelper.java:208)
        ... 83 more
Caused by: java.lang.ClassNotFoundException: Could not load requested class : models.Coating
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl$AggregatedClassLoader.findClass(ClassLoaderServiceImpl.java:217)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:226)
        ... 84 more
```
But once I remove all the mappings from **HibernateUtill** class and change the **LoginController** code to below =>>

 ```
Session s = HibernateUtil.getSessionFactory().openSession();
        Connection c = s.getSessionFactory().getSessionFactoryOptions().getServiceRegistry()
                .getService(ConnectionProvider.class).getConnection();

        //Criteria c = s.createCriteria(Coating.class);
        //c.add(Restrictions.eq("code", "CO3444"));
        //Coating co = (Coating) c.uniqueResult();
        //String title = co.getTitle();
        //s.close();
        String title = c.getMetaData().getDatabaseProductName();
        return ok(views.html.login_page.login.render(title));
```
Application starts and runs fine in the browser with the output of **MySQL** Which means there is no any hibernate configuration errors and no any errors with the **HibernateUtil** class either.

I post this issue with Hibernate community support and they keep on saying that there is no issue with hibernate which means all the hibernate configurations are correct and should be a ClassLoading issue.
So they suggest me to ask the question in play framework forum.

Any help would be appreciable. Thank you.

**Comment by marcospereira** [comment]
Hi @shanakaperera, this looks like a classloader problem. Maybe Hibernate is not using a compatible classloader here. See the discussion here https://github.com/playframework/playframework/issues/6207 (including linked issues). I suggest that you create a small project to reproduce the problem so other people can help you better.

Moreover, we support JPA out-of-the-box, and you can use Hibernate as an implementation.

**Comment by shanakaperera** [comment]
@marcospereira , Sorry I had no time to mention but I could solve the issue by placing hibernate mapping classes inside the conf directory without keeping them inside the same package(models) like I did in the above  project. ([https://i.stack.imgur.com/B4e5g.png](url))

And also I had to put below code line inside HibernateUtill.java
`Thread.currentThread().setContextClassLoader(OneOfYourDynamicallyLoadedModelClass.getClassLoader());  `

Here is my new project structure 👍 

[https://ibb.co/fsrEH6](url)
(HibernateUtill.java class is inside the services package)

**Comment by mkurz** [comment]
Hi @shanakaperera,

when did your project fail to run? When using `sbt run` (development mode) or in production mode?

**Comment by marcospereira** [comment]
If the mapping xml files aren't being found is probably because they aren't be listed as resource files.

A possible solution is to add `app/models` as an [additional resources directory](http://www.scala-sbt.org/1.x/docs/Howto-Customizing-Paths.html#Add+an+additional+resource+directory) and [configure file filters](http://www.scala-sbt.org/1.x/docs/Howto-Customizing-Paths.html#Include%2Fexclude+files+in+the+resource+directory) if necessary.

Moreover, I think that having a project to reproduce the problem is the way to go here.
