### ISSUE TITLE
Logback custom Layout ClassNotFoundException

### ISSUE THREAD

**Issue by Flo354** [playframework/playframework#8125]
### Play Version (2.5.x / etc)
I am using Play 2.6.10

### API (Scala / Java / Neither / Both)
Java 8

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Debian 9.3

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### Library Dependencies
- Logback (version embedded with play)
- de.siegmar:logback-gelf:1.0.4 => https://github.com/osiegmar/logback-gelf

### Expected Behavior
With this part of the configuration file, logback should use my custom layout class (because the one provided by logback-gelf does not completely fit with my needs.

```
<appender name="GELF" class="de.siegmar.logbackgelf.GelfTcpTlsAppender">
  ...
  <layout class="utils.MyGelfLayout"> THIS LINE
    ...
  </layout>
</appender>
```

### Actual Behavior
In prod mode, there is no problem, everything works.

But in dev mode, it seems that there is a classpath problem, since I have a "ClassNotFoundException".

> 15:29:11,839 |-ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [layout] of type [utils.MyGelfLayout] java.lang.ClassNotFoundException: utils.MyGelfLayout
	at java.lang.ClassNotFoundException: utils.MyGelfLayout
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.Loader.loadClass(Loader.java:120)
	at 	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.begin(NestedComplexPropertyIA.java:102)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:118)
	at 	at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:65)
	at 	at play.api.inject.guice.GuiceApplicationBuilder.$anonfun$configureLoggerFactory$1(GuiceApplicationBuilder.scala:122)
	at 	at scala.Option.map(Option.scala:146)
	at 	at play.api.inject.guice.GuiceApplicationBuilder.configureLoggerFactory(GuiceApplicationBuilder.scala:121)
	at 	at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:100)
	at 	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at 	at play.inject.guice.GuiceBuilder.injector(GuiceBuilder.java:221)
	at 	at play.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.java:156)
	at 	at play.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.java:34)
	at 	at play.api.ApplicationLoader$JavaApplicationLoaderAdapter$1.load(ApplicationLoader.scala:87)
	at 	at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
	at 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at 	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
	at 	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
	at 	at play.core.server.AkkaHttpServer.modelConversion(AkkaHttpServer.scala:184)
	at 	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:190)
	at 	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:107)
	at 	at akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1191)
	at 	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
	at 	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
	at 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
	at 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
	at 	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at 	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
	at 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
	at 	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
	at 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
	at 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at 	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

At first, I thought it was related to #6039 but the bug seems to be fixed.

**Comment by mkurz** [comment]
Logback is to blame here. I don't think there is something we can do on Play's side to fix this right now.

The problem boils down to [these lines](https://github.com/qos-ch/logback/blob/v_1.2.3/logback-core/src/main/java/ch/qos/logback/core/util/Loader.java#L119-L120) where the [wrong classloader is used](https://github.com/qos-ch/logback/blob/v_1.2.3/logback-core/src/main/java/ch/qos/logback/core/util/Loader.java#L162-L167).

There have been attempts to make logback use `Thread.currentThread().getContextClassLoader()` however none of these pull requests got merged:
* https://github.com/qos-ch/logback/pull/255
* https://github.com/qos-ch/logback/pull/260

There are two workarounds I can think of:
* If you are using sub-projects put your `utils.MyGelfLayout` class into a sub-project
* If you are not using sub-projects package your `utils.MyGelfLayout` into a `jar` file and put that `jar` file into the [`lib/` directory](https://www.playframework.com/documentation/2.6.x/Anatomy#The-lib/-directory) of your project

**Comment by Flo354** [comment]
Thanks @mkurz for the quick reply.

Actually, it's not a big deal for me since this config is only used in production. But I wanted to test it in dev mode before pushing to my production system and thus, had to manually "sbt stage" and test on my dev environment :(

Honestly, do you think there is chance to see this pull request accepted and merged?

**Comment by mkurz** [comment]
@Flo354 you mean qos-ch/logback#255 / qos-ch/logback#260 ? I have absolutely no idea.

You can go ahead and open a new pull request and address the feedback of the original one. It should be simple - e.g. just use the `Thread.currentThread().getContextClassLoader()` as fallback in case there was a `ClassNotFoundException`. They may accept that.

**Comment by Flo354** [comment]
Ok, I will do that when I have some free time...

Thanks for your help!

**Comment by jsw** [comment]
@Flo354 Any progress on a new PR?

**Comment by Flo354** [comment]
@jsw, I didn't take the time to make a PR, and I don't think I will take some time to make a new one, since at least two PR are already waiting to be merged

**Comment by jsw** [comment]
@Flo354 Can you link them? I assume you're not referring to the ones above that are both marked closed.

**Comment by mkurz** [comment]
I think maybe a new pull request like described [here](https://github.com/qos-ch/logback/pull/255#issuecomment-354163106) or https://github.com/qos-ch/logback/pull/260 would maybe work...?

**Comment by jeantil** [comment]
Just to let you know, I ended up extracting the custom logback stuff I was using to its own jar as a work around. The logback filter I was writing didn't have any dependency on my applcation code and this was it was loaded by the dependency classloader and not by the app class loader and thus was visible to logback. This allowed me to use it both in dev and prod.

**Comment by mkurz** [comment]
@jeantil Thanks for sharing!

**Comment by Flo354** [comment]
@jsw, yes, I talked about those given by @mkurz. 
Honnestly, I don't think any PR addressing this bug will be ever merged...

Look at the last comment from the owner:

> Passing custom class loader or using the TCCL is a rabbit hole I do not wish to descend into. As far as I am concerned, if the class loader that loaded logback cannot find a class, then tough luck. Resources are quite different because they don't have the class loader mismatch issue that classes have.

**Comment by jsw** [comment]
@Flo354 Thanks for trying.

I wonder if @jroper would be helpful here, based on his comments about classloaders here https://github.com/playframework/playframework/issues/2847#issuecomment-44243893

**Comment by jeantil** [comment]
It never hurts to try, just be aware that already mentionned #2847 in my
original pull request...

Le dim. 25 mars 2018 à 00:16, Jeff White <notifications@github.com> a
écrit :

**Comment by thedevd** [comment]
Is there any solution to this except packaging the custom classes in separate jar file ?
