### ISSUE TITLE
[2.6.10] Invalid escape sequence in query String is handled differently in AkkaHttpServer vs NettyHttpServer

### ISSUE THREAD

**Issue by fkoehler** [playframework/playframework#8128]
When an invalid request is being made where the query string parameters are not correctly encoded, i.e:

- localhost:9000?a=someparam%invalidhexvalue
- localhost:9000?a=%
- localhost:9000?a=%_D

when using plugin `PlayNettyServer` play fails with an Internal Server Error with an exception similar to this one:

```
Caused by: java.lang.IllegalArgumentException: unterminated escape sequence at index 3 of: ?a=%
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:334)
	at io.netty.handler.codec.http.QueryStringDecoder.addParam(QueryStringDecoder.java:243)
	at io.netty.handler.codec.http.QueryStringDecoder.decodeParams(QueryStringDecoder.java:230)
	at io.netty.handler.codec.http.QueryStringDecoder.parameters(QueryStringDecoder.java:180)
	at play.core.server.netty.NettyModelConversion$$anon$2.queryMap$lzycompute(NettyModelConversion.scala:113)
	at play.core.server.netty.NettyModelConversion$$anon$2.queryMap(NettyModelConversion.scala:111)
	at play.api.mvc.RequestHeader.queryString(RequestHeader.scala:95)
```

The behaviour in the `PlayAkkaHttpServer` is different though. It just prints a WARNing and continues to process the request using an empty map for the query parameters:

```
WARN  13:36:43.108 | p.c.s.a.AkkaModelConversion | Failed to parse query string; returning empty map.: 
akka.http.scaladsl.model.IllegalUriException: Illegal query: Unexpected end of input, expected HEXDIG (line 1, column 4): a=%
   ^
	at akka.http.scaladsl.model.IllegalUriException$.apply(ErrorInfo.scala:40)
	at akka.http.scaladsl.model.Uri$.fail(Uri.scala:813)
	at akka.http.impl.model.parser.UriParser.fail(UriParser.scala:81)
	at akka.http.impl.model.parser.UriParser.parseQuery(UriParser.scala:70)
	at akka.http.scaladsl.model.Uri.query(Uri.scala:37)
	at play.core.server.akkahttp.AkkaModelConversion$$anon$2.liftedTree2$1(AkkaModelConversion.scala:134)
	at play.core.server.akkahttp.AkkaModelConversion$$anon$2.queryMap$lzycompute(AkkaModelConversion.scala:133)
	at play.core.server.akkahttp.AkkaModelConversion$$anon$2.queryMap(AkkaModelConversion.scala:132)
```

I think there are two issues here: 

1. Both server implementations should behave equally
2. I would prefer it behaves like in the AkkaHttpServer since it is more robust and in this case valid to return an empty map

Here are the problematic source code lines. In the AkkaModelConversion there is a try/catch around the query parsing to make it robust:

https://github.com/playframework/playframework/blob/master/framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala#L132-L140
vs
https://github.com/playframework/playframework/blob/master/framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala#L111-L115

**Comment by gmethvin** [comment]
So it seems like the fix here is to fix the Netty server to map invalid query strings to empty. I agree it's bad to send a 500 error for something like this.

**Comment by ozencem** [comment]
Hi @gmethvin and @fkoehler, can I work on this issue if you or anyone else is not working on it? It seemed like a good candidate for a first pull request.

**Comment by fkoehler** [comment]
I am not working on this. So it's fine from my side.

ozencem <notifications@github.com> schrieb am Mi., 24. Jan. 2018 um
00:35 Uhr:

**Comment by gmethvin** [comment]
Yes. That's why I added the "help wanted" label 👍

**Comment by ozencem** [comment]
Awesome, thanks :) I will try to send a pull request over the weekend 👍

**Comment by mkurz** [comment]
Since akka-http 10.2.0, an incorrect percent-encoded uri character will be immediately handled as 400 bad request by akka-http. It gives us (Play) no chance to handle that, so we never see this error in the Play akka-http backend. That's why in Play 2.9 both akka-http and the netty backend will send 400 bad request instead of returning an empty map in that case (other parsing errors will still be ignored and handled as empty map). See #11671
