### ISSUE TITLE
inMemoryDatabase() uses wrong SQL grammar

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8175]
### Play Version (2.5.x / etc)
2.6.11

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### Library Dependencies
N/A

### Expected Behavior
`fakeApplication(inMemoryDatabase());` should use proper SQL grammar (from H2 database)

### Actual Behavior
I have Play (2.6.10) application configured with JPA and PostgreSQL exactly as [documentation](https://www.playframework.com/documentation/2.6.x/JavaJPA#Running-JPA-transactions) states and it's running just fine.

My persistence.xml file looks like this:
```
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd"
        version="2.1">
        <persistence-unit name="defaultPersistenceUnit" transaction-type="RESOURCE_LOCAL">
                <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
                <non-jta-data-source>DefaultDS</non-jta-data-source>
                <properties>
                        <property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQL94Dialect" />
                        <property name="hibernate.hbm2ddl.auto" value="validate" />
                        <property name="hibernate.show_sql" value="false"></property>
                        <property name="hibernate.format_sql" value="true"></property>
                        <property name="hibernate.connection.autocommit" value="false"/>
                </properties>
        </persistence-unit>
</persistence>
```
and in application.conf:
```
db {
  default {
          driver=org.postgresql.Driver
          url="jdbc:postgresql://localhost/testing"
          username=testing
          password=testing
          jndiName=DefaultDS
  }
}
```

Now I want to setup testing environment with in memmory database (independent from the PostgreSQL) as this [documentation](https://www.playframework.com/documentation/2.6.x/JavaFunctionalTest) states.
So far, so good. My test class looks like this:
```
public class RegisterControllerTest extends WithApplication {
  @Override
  protected Application provideApplication() {
     return fakeApplication(inMemoryDatabase());
  }

    @Test
  public void shouldDisplayPage() {
    //when
    final Result result = new MyController().index();

    //then
    assertThat(result.status()).isEqualTo(OK);
    assertThat(result.contentType().get()).isEqualTo("text/plain");
    assertThat(result.charset().get()).isEqualTo("utf-8");
    assertThat(contentAsString(result)).contains("ok");
  }
}
```

Unfortunately when I run test, an error is thrown:
```
[error] Caused by: org.hibernate.exception.SQLGrammarException: Unable to build DatabaseInformation
[error]     at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
[error]     at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
[error]     at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
[error]     at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
[error]     at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:140)
[error]     at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:61)
[error]     at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:191)
[error]     at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72)
[error]     at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:313)
[error]     at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:452)
[error]     at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)
[error]     ... 127 more
[error] Caused by: org.h2.jdbc.JdbcSQLException: 
[error] Table "PG_CLASS" not found; SQL statement:
[error] select relname from pg_class where relkind='S' [42102-196]
```

So it clearly tries to run PostgreSQL grammar on H2 database instead of taken from `inMemoryDatabase()` configuration.

**Comment by eximius313** [comment]
Maybe that near [this line](https://github.com/playframework/playframework/blob/master/framework/src/play-test/src/main/scala/play/api/test/Helpers.scala#L141) you should add something like this:
`"hibernate.dialect" -> "org.hibernate.dialect.H2Dialect"`
?

**Comment by eximius313** [comment]
I found a workaround... you must add additional element into `persistence.xml` file:
```
        <persistence-unit name="testPersistenceUnit" transaction-type="RESOURCE_LOCAL">
                <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>
                <non-jta-data-source>TestDS</non-jta-data-source>
                <properties>
                        <property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect" />
                        <property name="hibernate.hbm2ddl.auto" value="create" />
                        <property name="hibernate.show_sql" value="false"></property>
                        <property name="hibernate.format_sql" value="true"></property>
                        <property name="hibernate.connection.autocommit" value="false"/>
                </properties>
        </persistence-unit>
```
and then use `fakeApplication` like this:
```
public Map<String, String> getDatabaseConfig() {
    final Map<String, String> map = new HashMap<>(inMemoryDatabase("default"));
    map.put("db.default.jndiName", "TestDS");
    map.put("jpa.default", "testPersistenceUnit");
    return map;
}

@Override
protected Application provideApplication() {
    return fakeApplication(getDatabaseConfig());
}
```
but this is ugly and forces me to override `default` database instead of using `test` so it is definitely not a good solution.

**Comment by gmethvin** [comment]
As far as I can tell, the dialect Hibernate uses is completely disconnected from what the database actually is. So your observation makes sense. What you may want to do is try adding a `test/resources/persistence.xml`, assuming you always want to use the same configuration in tests. I'm not that familiar with Hibernate but there is probably some way to do it programmatically as well.

The documentation does also suggest passing a `MODE` argument. You should be able to set that to `PostgreSQL` to get basic emulation, like described for MySQL here: https://www.playframework.com/documentation/2.6.x/JavaTestingWithDatabases#Using-an-in-memory-database. I'm not sure if the emulation is good enough to allow Hibernate to work though.
