### ISSUE TITLE
Compatibility Issue with google-cloud-vision

### ISSUE THREAD

**Issue by playtowork** [playframework/playframework#8200]
### Play Version (2.5.x / etc)

2.5.9

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux apoorv-ThinkPad-Edge-E530 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

### Library Dependencies

The problem occurs after appending the following in `build.sbt`'s `libraryDependencies`:
"com.google.cloud"        % "google-cloud-vision"      % "1.14.0"

### Expected Behavior

1. Run `sbt clean && sbt "project frontend" run`
2. The app should run, allowing hitting endpoints via localhost:9000.

### Actual Behavior

1. Run `sbt clean && sbt "project frontend" run`
2. The app does not run; it exits with failure. The error is below:

--- (Running the application, auto-reloading is enabled) ---

java.lang.NoSuchFieldError: DEFAULT_MAX_PENDING_TASKS
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at play.core.server.NettyServer.<init>(NettyServer.scala:77)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:279)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:235)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:65)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:64)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:54)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:234)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last frontend/compile:run for the full output.
[error] (frontend/compile:run) java.lang.reflect.InvocationTargetException
[error] Total time: 45 s, completed Jan 28, 2018 12:24:13 PM

### Reproducible Test Case

Just add the google-cloud-vision library as shown above, and you should be unable to `sbt run` the project.

**Comment by gmethvin** [comment]
This is a compatibility issue between Netty 4.0 and 4.1. Play 2.5 uses Netty 4.0 and Play 2.6 uses Netty 4.1. The best solution for you is probably to upgrade to Play 2.6. You can also try using the Akka HTTP server in Play 2.5 and refrain from using play-ws (which also uses Netty 4.0). If you need play-ws you can try the standalone version: https://github.com/playframework/play-ws
