### ISSUE TITLE
errorsAsJson with mocked MessagesApi throws java.util.NoSuchElementException (TestCase provided)

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8318]
### Play Version (2.5.x / etc)
2.6.11

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
JDK 9.0.4

### Library Dependencies
N/A

### Expected Behavior
No exception is thrown

### Actual Behavior
I want my tests to be language independent, thus I want `form.errorsAsJson()` to return error keys instead of translations.
In order to do that I mocked MessagesApi as documentation specifies:
```
public class MyTest extends WithApplication {

  private MessagesApi emptyMessagesApi() {
    return new play.i18n.MessagesApi(new play.api.i18n.DefaultMessagesApi(
        Collections.singletonMap(Lang.defaultLang().code(), Collections.emptyMap()),
        new play.api.i18n.DefaultLangs().asJava()));
  }

  @Override
  protected Application provideApplication() {
    GuiceApplicationBuilder builder = new GuiceApplicationBuilder()
        .in(Environment.simple())
        .overrides(bindings.add(Bindings.bind(MessagesApi.class).toInstance(emptyMessagesApi())));

    Guice.createInjector(builder.applicationModule()).injectMembers(this);
    Application application = builder.build();
    return application;
  }

  public Application getApplication() {
    return app;
  }

//here test making call to controller
}
```

While calls to `messages.at("someKey")` work fine, trying to call `form.errorsAsJson()` throws:
```
[error] Test controllers.MyControllerTest.shouldValidateRequiredFields failed: java.util.NoSuchElementException: null, took 0.881 sec
[error]     at java.util.ArrayList$Itr.next(ArrayList.java:896)
[error]     at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:40)
[error]     at scala.collection.IterableLike.head(IterableLike.scala:106)
[error]     at scala.collection.IterableLike.head$(IterableLike.scala:105)
[error]     at scala.collection.AbstractIterable.head(Iterable.scala:54)
[error]     at scala.collection.TraversableLike.last(TraversableLike.scala:431)
[error]     at scala.collection.TraversableLike.last$(TraversableLike.scala:430)
[error]     at scala.collection.AbstractTraversable.last(Traversable.scala:104)
[error]     at play.api.i18n.DefaultMessagesApi.$anonfun$apply$3(Messages.scala:473)
[error]     at scala.Option.getOrElse(Option.scala:121)
[error]     at play.api.i18n.DefaultMessagesApi.apply(Messages.scala:473)
[error]     at play.i18n.MessagesApi.get(MessagesApi.java:106)
[error]     at play.data.Form.lambda$errorsAsJson$14(Form.java:750)
[error]     at java.util.ArrayList.forEach(ArrayList.java:1380)
[error]     at play.data.Form.errorsAsJson(Form.java:744)
[error]     at play.data.Form.errorsAsJson(Form.java:734)
[error]     at controllers.common.MyController.bindForm(MyController:20)
```

**Comment by eximius313** [comment]
The issue is still there in `Play 2.6.13`, but I prepared the test case: [play-form-exception-showcase.zip](https://github.com/playframework/playframework/files/1910670/play-form-exception-showcase.zip)

Without mocking `MessagesApi`, the error `Invalid value` is normally translated, but when `MessagesApi` is mocked, then:
```
[error] Test FormTest.shouldWork failed: java.util.NoSuchElementException: null, took 5.001 sec
[error]     at java.util.ArrayList$Itr.next(ArrayList.java:896)
[error]     at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:40)
[error]     at scala.collection.IterableLike.head(IterableLike.scala:106)
[error]     at scala.collection.IterableLike.head$(IterableLike.scala:105)
[error]     at scala.collection.AbstractIterable.head(Iterable.scala:54)
[error]     at scala.collection.TraversableLike.last(TraversableLike.scala:431)
[error]     at scala.collection.TraversableLike.last$(TraversableLike.scala:430)
[error]     at scala.collection.AbstractTraversable.last(Traversable.scala:104)
[error]     at play.api.i18n.DefaultMessagesApi.$anonfun$apply$3(Messages.scala:483)
[error]     at scala.Option.getOrElse(Option.scala:121)
[error]     at play.api.i18n.DefaultMessagesApi.apply(Messages.scala:483)
[error]     at play.i18n.MessagesApi.get(MessagesApi.java:106)
[error]     at play.data.Form.lambda$errorsAsJson$14(Form.java:750)
[error]     at java.util.ArrayList.forEach(ArrayList.java:1380)
[error]     at play.data.Form.errorsAsJson(Form.java:744)
[error]     at play.data.Form.errorsAsJson(Form.java:734)
[error]     at controllers.HomeController.testForm(HomeController.java:34)
[error]     at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$2(Routes.scala:93)
[error]     at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
[error]     at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
[error]     at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
[error]     at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:88)
[error]     at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
[error]     at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:138)
[error]     at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
[error]     at scala.util.Success.$anonfun$map$1(Try.scala:251)
[error]     at scala.util.Success.map(Try.scala:209)
[error]     at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
[error]     at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[error]     at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[error]     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error]     at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
[error]     at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
[error]     at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
[error]     at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
[error]     at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:368)
[error]     at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:367)
[error]     at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:375)
[error]     at scala.concurrent.impl.Promise.transform(Promise.scala:29)
[error]     at scala.concurrent.impl.Promise.transform$(Promise.scala:27)
[error]     at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:375)
[error]     at scala.concurrent.Future.map(Future.scala:289)
[error]     at scala.concurrent.Future.map$(Future.scala:289)
[error]     at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:375)
[error]     at scala.concurrent.Future$.apply(Future.scala:655)
[error]     at play.core.j.JavaAction.apply(JavaAction.scala:138)
[error]     at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
[error]     at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
[error]     at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
[error]     at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error]     at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error]     at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
[error]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]     at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
[error]     at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
[error]     at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
[error]     at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
[error]     at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error]     at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error]     at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]     at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] Test run finished: 1 failed, 0 ignored, 1 total, 5.017s
```

is thrown. You can comment `FormTest` Line 74, to get rid of the exception.

You can also comment `FormTest` Line 48, to see that `This field is required` works fine with/without mocked `MessagesApi` (line 74 commented or not)

**Comment by eximius313** [comment]
Moreover - exactly the same thing happens with invalid UUID in form, which is even more problematic:
```
public class UUIDForm {
  @Required
  private UUID uuid;
}
-----------
// given
final String invalidUuid = "foo";
final Map<String, String> params = new HashMap<>();
params.put("uuid", invalidUuid);

//when
final Result result = route(
        fakeRequest(routes.HomeController.updateUUID())
        .method(PUT)
        .bodyForm(params)
);
```

**Comment by eximius313** [comment]
@schmitch Do you need any input from my side in order to verify this bug?

**Comment by schmitch** [comment]
well I removed the `needs-verification` label.

Actually Play even has a Test Helper: `play.test.Helpers.stubMessagesApi()`. That will make your test blow up.
I guess in no case should we have `NoSuchElementException`.

Could you talk more about the second one? 

> Moreover - exactly the same thing happens with invalid UUID in form, which is even more problematic

does this also only happen with a mocked `MessageApi`? Or why is it more 'problematic'?

**Comment by eximius313** [comment]
So:
In tests I want to check the presence of the *key*, not translated message (because I have multilingual site)
In order to have keys in test I must mock MessageApi, to return emptyMap
```
  protected void provideMocks(final List<Binding<?>> bindings){
    bindings.add(Bindings.bind(MessagesApi.class).toInstance(emptyMessagesApi()));
  }

  private MessagesApi emptyMessagesApi() {
    return new play.i18n.MessagesApi(new play.api.i18n.DefaultMessagesApi(
        Collections.singletonMap(Lang.defaultLang().code(), Collections.emptyMap()),
        new play.api.i18n.DefaultLangs().asJava()));
  }

  @Override
  protected Application provideApplication() {
    final List<Binding<?>> bindings = new ArrayList<>();
    provideMocks(bindings);
    GuiceApplicationBuilder builder = new GuiceApplicationBuilder()
        .in(Environment.simple())
        .overrides(bindings.toArray(new Binding<?>[0]));

    Guice.createInjector(builder.applicationModule()).injectMembers(this);
    Application application = builder.build();
    return application;
  }
```
It works in all situations (`@Required`, `@Size` and even custom validation) except when something goes wrong with assigning the field.
So if I have a form that's field is not String (UUID, IBAN) and I make a request like this:
```
// given
final String invalidUuid = "foo";
final Map<String, String> params = new HashMap<>();
params.put("uuid", invalidUuid);

//when
final Result result = route(
        fakeRequest(routes.HomeController.updateUUID())
        .method(PUT)
        .bodyForm(params)
);
```
then the test crashes.
This is rather big problem, because I must disable all tests with corner cases.

**Comment by mkurz** [comment]
The problem here is caused by this code:
https://github.com/playframework/playframework/blob/3935bfa9025cfa071b3658efcecb033021dc2fb1/framework/src/play-java-forms/src/main/java/play/data/Form.java#L473-L480

If you now have an empty `MessagesApi` (meaning "it exists/is present", but actually does not contain any messages) no error keys are added to the builder at all, causing an `ValidationError` instance to be created with no (!) error messages keys. An validation error that does not even tell you what's wrong? Bad.

This will cause `keys.last` to fail with the exception already posted in the bug report. Calling `last` on an empty sequence will fails, [see yourself](https://scastie.scala-lang.org/ATpkVQvOSseWqEtGCEGFlg).  (`keys` is the empty list the builder created above):
https://github.com/playframework/playframework/blob/3935bfa9025cfa071b3658efcecb033021dc2fb1/framework/src/play/src/main/scala/play/api/i18n/Messages.scala#L479-L484

**Comment by mkurz** [comment]
See #8972 and #8973 for fixes.
The fix is that we just have to make sure that we add the default error key (namely `error.invalid`) as validation error key if binding fails and if no error key was found in messages. Easy.

**Comment by mkurz** [comment]
Fixed.
