### ISSUE TITLE
RuntimeException while using Content-Type without subtype

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8325]
### Play Version (2.5.x / etc)
2.6.11

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
JDK 9.0.4

### Library Dependencies
N/A

### Expected Behavior
Content-Type `image` is supported.

### Actual Behavior
If I use just `image` as Content type (which worked fine in Play 2.5) and seems to be correct Content-Type (as far as I understand correctly `Content-Type := type "/" subtype *[";" parameter]` from [RFC](https://tools.ietf.org/html/rfc1341)), Play throws:
```
12:37:56.848 [application-akka.actor.default-dispatcher-8] [error] play.core.server.common.ServerResultUtils - Exception occurred while converting Result with headers []. Calling HttpErrorHandler to get alternative Result.
java.lang.RuntimeException: Error parsing response Content-Type: <image>: List(ErrorInfo(Illegal HTTP header 'Content-Type': Invalid input 'EOI', expected tchar, OWS or '/' (line 1, column 6),image
     ^))
        at play.core.server.akkahttp.AkkaModelConversion.$anonfun$parseContentType$3(AkkaModelConversion.scala:265)
        at scala.util.Either$LeftProjection.map(Either.scala:573)
        at play.core.server.akkahttp.AkkaModelConversion.$anonfun$parseContentType$2(AkkaModelConversion.scala:264)
        at scala.Option.fold(Option.scala:158)
        at play.core.server.akkahttp.AkkaModelConversion.parseContentType(AkkaModelConversion.scala:263)
        at play.core.server.akkahttp.AkkaModelConversion.convertResultBody(AkkaModelConversion.scala:275)
        at play.core.server.akkahttp.AkkaModelConversion.$anonfun$convertResult$2(AkkaModelConversion.scala:233)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:55)
        at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
        at play.core.server.akkahttp.AkkaModelConversion.$anonfun$convertResult$1(AkkaModelConversion.scala:231)
        at play.core.server.common.ServerResultUtils.resultConversionWithErrorHandling(ServerResultUtils.scala:132)
        at play.core.server.akkahttp.AkkaModelConversion.convertResult(AkkaModelConversion.scala:253)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$5(AkkaHttpServer.scala:314)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
12:37:56.851 [application-akka.actor.default-dispatcher-8] [error] application -
```
When I use `image/jpeg` image is being displayed, but I have different types of images, so I don't want to use sub-types of `image`

### Reproducible Test Case
```
   @Transactional(readOnly = false)
   public Result showLogo(String logoId) {
	   return logoRepository.find(logoId)
			   .map(picture -> (Result) ok(picture.getBytes()).as("image"))
			   .orElseGet(() -> notFound());
   }
```

**Comment by eximius313** [comment]
ok, it seems that `*` in `Content-Type := type "/" subtype *[";" parameter]` is about parameters and not, as I thought, about `subtype`
