### ISSUE TITLE
IllegalAccessException in play.shaded.ahc.io.netty.util.internal.PlatformDependent

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8347]
### Play Version (2.5.x / etc)
2.6.13

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
JDK 9.0.4

### Library Dependencies
N/A

### Expected Behavior
No exception is thrown

### Actual Behavior
When I run my application in stage mode Play throws:
```
java.lang.IllegalAccessException: class play.shaded.ahc.io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @2f651f93
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
        at java.base/java.lang.reflect.Method.invoke(Method.java:556)
        at play.shaded.ahc.io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:295)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at play.shaded.ahc.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:286)
        at play.shaded.ahc.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:197)
        at play.shaded.ahc.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:74)
        at play.shaded.ahc.io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:155)
        at play.shaded.ahc.io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:200)
        at play.shaded.ahc.io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:201)
        at play.shaded.ahc.io.netty.util.HashedWheelTimer.<clinit>(HashedWheelTimer.java:88)
        at play.shaded.ahc.org.asynchttpclient.DefaultAsyncHttpClient.newNettyTimer(DefaultAsyncHttpClient.java:91)
        at play.shaded.ahc.org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:83)
        at play.api.libs.ws.ahc.AsyncHttpClientProvider.get$lzycompute(AhcWSModule.scala:47)
        at play.api.libs.ws.ahc.AsyncHttpClientProvider.get(AhcWSModule.scala:44)
        at play.api.libs.ws.ahc.AsyncHttpClientProvider.get(AhcWSModule.scala:38)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:148)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:78)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

**Comment by vortexkd** [comment]
have the same issue here on play 2.6.13 and jdk 9.0.4, any updates?

**Comment by wsargent** [comment]
Please use 1.8

**Comment by mkurz** [comment]
@eximius313 Do you still experience this problem with latest Play 2.8 / latest play-ws?

The origin of the error is the (shaded) netty version that play-ws pulls in via ahc. Given this bug report here

* is about unsupported Play 2.6.13, which
  * [uses outdated play-ws 1.1.7](https://github.com/playframework/playframework/blob/2.6.13/framework/project/Dependencies.scala#L268)
    * which [uses the old ahc version 2.0.36](https://github.com/playframework/play-ws/blob/v1.1.7/project/Dependencies.scala#L45)
      * which is using very outdated [netty version 4.0.51.Final](https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.0.36/pom.xml#L379)

I am going to close this issue for now. I had a look at the netty bug tracker and, besides the fact that play-ws that comes with Play 2.8 is now on Netty 4.1.x (=_many_ new releases since 4.0.51), there are a lot of closed issue in regards to this error message and also latest Netty 4.1 definitely comes with much better Java 11+ support.

If someone still experience issues please (re-)open a new issue, thanks!
