### ISSUE TITLE
Exceptions occured when more than 200 concurrent requests are sent

### ISSUE THREAD

**Issue by Sivabalarajan** [playframework/playframework#8369]
### Play Version (2.5.x / etc)
2.6.x

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 10
Intel i3 with 8GB RAM

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### Library Dependencies
n/a

### Expected Behavior

I created a 'Play Scala Integrated Slick Example' using Intellij IDEA with MariaDB and added a updatePerson method . All these rest APIs are working fine without any issues. However I expect that it should work fine when I sent around ~300 to ~1000 concurrent requests to both update and getPersons rest APIs separately one by one. At least the performance can be slow down but definitely crashes should not happen.

### Actual Behavior
I am getting different exceptions for both updatePerson and getPersons methods separately. So the requests are not executed / handled properly.

I tried the same functionality in ASP.NET core with same database with same method names and it is working fine. The performance is slowing down when the concurrent requests are increased in the .NET version. However I am getting crashes in Play Scala Slick version.
Please refer the below section for steps to reproduce these exceptions

### Reproducible Test Case
1. Create a 'Play Scala Integrated Slick Example' project using Intellij IDEA. Use MariaDB instead of H2 database. 
```
slick.dbs.default.driver = "slick.jdbc.MySQLProfile$" 
slick.dbs.default.db.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.url = "jdbc:mysql://localhost:3306/yourserverdb"
slick.dbs.default.db.user = "root"
slick.dbs.default.db.password = "root pwd"
```

2.  Add a method called updatePerson in PersonController.scala and verify it is working
```
  def updatePerson = Action.async { implicit request =>
    val person = request.body.asJson.get.as[Person]
    repo.update(person) map { res =>
      Ok("Updated the person details. " + res.toString())
    }
  }
```

Add the below method in PersonRepository.scala

```
 def update(person : Person): Future[String] = {
    db.run(people.filter(_.id === person.id).update(person)).map(res => "Person successfully updated").recover {
      case ex : Exception => ex.getCause.getMessage
    }
  }

```
3. Verify getPersons method whether it is working fine. Ensure it is working fine.
4. Create a separate program to test these methods. I used WinForm C# app to send concurrent requests to these rest APIs separately. I tested both methods separately one by one.
5. It is working fine when you send around ~100 concurrent requests. But it is throwing exceptions when it is increased more than 200. Sometimes it is working till 300 concurrent requests. Sometimes crash occurs even less than 100 requests
6. Getting NullPointerException for getPersons method and here is the details...
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:320)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:318)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Caused by: java.lang.NullPointerException: null
at models.PersonRepository$$anonfun$update$3.applyOrElse(PersonRepository.scala:74)
	at models.PersonRepository$$anonfun$update$3.applyOrElse(PersonRepository.scala:73)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recover(Try.scala:230)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:392)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
```

7. Getting HttpErrorHandlerExceptions for updatePerson method. '1165ms' varies each and every time
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[SQLTransientConnectionException: db - Connection is not available, request timed out after 1165ms.]]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:182)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:320)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:318)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Caused by: java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 1165ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
```

8. Here is the c# code for updating person details concurrently. Execute this 'n' times where n refers 100 or 200 or 300 or 1000...
```
async void RunUpdatePerson()
        {
            using (var client = new HttpClient())
            {
                JObject oJsonObject = new JObject();
                oJsonObject.Add("id", 1);
                oJsonObject.Add("name", "admin123CoreNew " + DateTime.Now.ToLongDateString() + " : " + DateTime.Now.ToLongTimeString());
                oJsonObject.Add("age", new Random().Next(2, 80));
                var response = await client.PostAsync(strURL, new StringContent(oJsonObject.ToString(), Encoding.UTF8, "application/json"));
                if (!response.IsSuccessStatusCode)
                    HandleFailure(response);
            }
        }

```
9. Here is the c# code for executing getPersons method concurrently. Execute this 'n' times where n is between 100 and 1000...
```
async void RunGetItems()
        {
            using (var client = new HttpClient())
            {
                var response = await client.GetAsync(strURL);
                if (!response.IsSuccessStatusCode)
                    HandleFailure(response);
            }
        }
```

10.  Here is the build.sbt details.
```
name := """play-scala-slick-example"""

version := "2.6.x"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.12.4"
crossScalaVersions := Seq("2.11.12", "2.12.4")

libraryDependencies += guice

lazy val playSlickVersion = "3.0.1"
libraryDependencies += "com.typesafe.play" %% "play-slick" % playSlickVersion
libraryDependencies += "com.typesafe.play" %% "play-slick-evolutions" % playSlickVersion

lazy val slickVersion = "3.2.3"
libraryDependencies += "com.typesafe.slick" %% "slick" % slickVersion
libraryDependencies += "com.typesafe.slick" %% "slick-hikaricp" % slickVersion

libraryDependencies += specs2 % Test

libraryDependencies += "mysql" % "mysql-connector-java" % "latest.integration"
```

**Comment by schmitch** [comment]
You can actually configure the timeout within slick by raising:

`slick.dbs.default.connectionTimeout` (the default is 1s, however it won't be exactly one second if your server is loaded)
