### ISSUE TITLE
MessagesTest fails if specs2 is upgraded from 4.0.3 to 4.0.4

### ISSUE THREAD

**Issue by SethTisue** [playframework/playframework#8393]
this turned up in the Scala 2.12 community build, but is reproducible outside of dbuild just by bumping the dependency and running `Play/testOnly *MessagesTest*`:

```
[info] Test play.i18n.MessagesTest.testMessageCall started
[error] Test play.i18n.MessagesTest.testMessageCall failed: org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
[error] Invalid use of argument matchers!
[error] 3 matchers expected, 2 recorded:
[error] -> at play.i18n.MessagesTest.testMessageCall(MessagesTest.java:25)
[error] -> at play.i18n.MessagesTest.testMessageCall(MessagesTest.java:25)
[error] 
[error] This exception may occur if matchers are combined with raw values:
[error]     //incorrect:
[error]     someMethod(anyObject(), "raw String");
[error] When using matchers, all arguments have to be provided by matchers.
[error] For example:
[error]     //correct:
[error]     someMethod(anyObject(), eq("String by matcher"));
[error] 
[error] For more info see javadoc for Matchers class.
[error] , took 0.452 sec
[error]     at play.i18n.MessagesTest.testMessageCall(MessagesTest.java:25)
[error]     ...
[info] Test run finished: 1 failed, 0 ignored, 1 total, 0.456s
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	play.i18n.MessagesTest
```

perhaps relevant, perhaps not: https://github.com/playframework/playframework/pull/6676

**Comment by marcospereira** [comment]
#8473 fixes that. It was a Mockito update that broke the test.

**Comment by SethTisue** [comment]
thanks Marcos!
