### ISSUE TITLE
Websockets broken after upgrading from Play 2.6.10 to 2.6.13

### ISSUE THREAD

**Issue by SakulK** [playframework/playframework#8421]
In our application we use `WebSocket.acceptOrResult[JsValue, JsValue] { request =>` and after upgrading Play to 2.6.13 we get this error whenever a browser tries to connect by websocket:

> 05-18 09:04:53,354 ERROR a.a.ActorSystemImpl:69  - Internal server error, sending 500 response
java.lang.RuntimeException: WebSocket returned for non WebSocket request
        at scala.sys.package$.error(package.scala:27)
        at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:297)
        at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$handleRequest(AkkaHttpServer.scala:219)
        at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:117)
        at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:117)
        at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
        at akka.actor.ActorCell.invoke(ActorCell.scala:559)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Did anyone else experienced this error?

**Comment by schmitch** [comment]
actually I tried to run websockets on play and it worked perfectly fine.
could you please try to make a simple reproducer and upload it to github?

**Comment by SakulK** [comment]
Sorry, my bad, I checked and the problem was we had an incompatible version of akka-http as a dependency, everything is fine :)

**Comment by Mogztter** [comment]
@SakulK I'm getting the same error:

```
2018-07-16 15:19:01,421 [ERROR] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-17 - Internal server error, sending 500 response
java.lang.RuntimeException: WebSocket returned for non WebSocket request
        at scala.sys.package$.error(package.scala:27)
        at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:317)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:244)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:137)
        at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
        at akka.actor.ActorCell.invoke(ActorCell.scala:559)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

My dependencies look fine...

**build.sbt**
```
scalaVersion := "2.12.4"

libraryDependencies ++= Seq(
  ws,
  guice,
  "com.googlecode.owasp-java-html-sanitizer" % "owasp-java-html-sanitizer" % "20160827.1",
  "com.typesafe.play" %% "play-json" % "2.6.9",

  "com.amazonaws" % "aws-java-sdk-s3" % "1.11.57",
  "org.apache.commons" % "commons-email" % "1.5",
  "org.apache.commons" % "commons-csv" % "1.5",
  "org.apache.commons" % "commons-text" % "1.3",
  "org.typelevel" %% "cats-core" % "1.1.0",
  "org.apache.tika" % "tika-core" % "1.17",
  "org.apache.poi" % "poi" % "3.17",
  "org.apache.poi" % "poi-ooxml" % "3.17",
  "org.apache.poi" % "openxml4j" % "1.0-beta",

  "org.scalatestplus.play" %% "scalatestplus-play" % "3.1.2" % "test",
  "com.lihaoyi" %% "utest" % "0.6.3" % "test",
  "com.lihaoyi" %% "utest" % "0.6.3" % "test",
  "com.github.tototoshi" %% "scala-csv" % "1.3.5" % "test",
  "org.mockito" % "mockito-core" % "2.19.0" % "test"
)
```

**project/plugins.sbt**
```
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.15")

// Web plugins
addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.4")
addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.2")

// Dependency graph
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
```

Any hint on how you solve this issue ? I can provide the result of `sbt dependencyTree` if needed :wink: 

Thanks!

**Comment by marcospereira** [comment]
Hey @Mogztter,

> Any hint on how you solve this issue ? I can provide the result of sbt dependencyTree if needed 😉

Yes, the dependency tree can help us to confirm if there is a problem or not.

> NOTE: It may be an interaction with my Nginx reverse proxy because I cannot reproduce this issue on a local environment.

By local you mean running in DEV mode (`sbt run`) or even running with PROD mode (`sbt stage` and then running the generated script)? If you cannot reproduce the problem when running in PROD mode locally, then I would suggest starting a new thread at https://discuss.playframework.com. 

It is not the best place to get help regarding nginx, but it is better than to discuss it here. :-)

Best.

**Comment by Mogztter** [comment]
Hello @marcospereira 

It was indeed an issue with Nginx <= 1.13.13 when using WebSocket proxy with SSL enabled:
https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss

Upgrading to Nginx 1.14+ solved this issue but the error message in Play! is a bit misleading. I think that the request received by Play! is invalid because Nginx can't figure it out.

Anyway thanks for your help :wink:

**Comment by ersefuril** [comment]
I've this issue as well with Nginx 1.14 and Play framework 2.6.20. It's really weird because we receive this error from time to time only, the app seems to run without any issue.

**build.sbt**
```
libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play-json" % "2.6.2",
  "com.typesafe.play" %% "play-json-joda" % "2.6.2",
  "com.typesafe.play" %% "play-iteratees" % "2.6.1",
  "com.typesafe.play" %% "play-iteratees-reactive-streams" % "2.6.1",
  "org.reactivemongo" %% "play2-reactivemongo" % "0.12.7-play26",
  "org.reactivemongo" %% "reactivemongo-iteratees" % "0.12.7",
  "org.jsoup" % "jsoup" % "1.10.3",
  "org.quartz-scheduler" % "quartz" % "2.3.0",
  "com.unboundid" % "unboundid-ldapsdk" % "3.1.1",
  "com.github.mumoshu" %% "play2-memcached-play26" % "0.9.2" exclude("net.spy", "spymemcached"),
  "info.folone" %% "poi-scala" % "0.14",
  "com.google.apis" % "google-api-services-analytics" % "v3-rev155-1.23.0",
  "org.specs2" %% "specs2-core" % "3.3.1" % "test",
  "org.specs2" %% "specs2-junit" % "3.6.2" % "test",
  "org.abstractj.kalium" % "kalium" % "0.8.0",                                
  "pl.allegro.tech" % "embedded-elasticsearch" % "2.1.0" % "test",        
  "com.amazonaws" % "aws-java-sdk-sns" % "1.11.26",
  "com.amazonaws" % "aws-java-sdk-s3" % "1.11.37",
  "com.amazonaws" % "aws-java-sdk-cloudfront" % "1.11.559",
  "com.amazonaws" % "elasticache-java-cluster-client" % "1.1.1",
  "com.drewnoakes" % "metadata-extractor" % "2.9.1",
  "com.mohiva" %% "play-html-compressor" % "0.7.1",
  "commons-codec" % "commons-codec" % "1.11",                                 
  "org.apache.commons" % "commons-text" % "1.6",
  specs2 % Test,
  ehcache,
  ws,
  filters,
  guice
)
```

**project/plugins.sbt**
```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.20")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.2.5")
```
