### ISSUE TITLE
Unexpected behaviour with java.library.path added into javaOptions

### ISSUE THREAD

**Issue by nicolasblaye** [playframework/playframework#8445]
### Play Version 
2.6.15
### API 
Scala (not tested on others)
#### System 
MacOS 10.12.6
### JDK
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
### Library Dependencies
Minimal project to reproduce the behaviour: https://github.com/nicolasblaye/sbt-play-fork-issue/tree/master
### Expected Behavior

1. use javaOptions in sbt to add `-Djava.library.path=/opt/libjpeg-turbo/lib64`
2. should link the lib
3. test code:
``` scala
def index = actionBuilder { _ =>
    println(config.getString("test"))
    println(System.getProperty("java.library.path"))
    new TJ
    Ok("Ok")
    }
```

### Actual Behavior
Program fail with 
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.UnsatisfiedLinkError: no turbojpeg in java.library.path]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:251)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:178)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:363)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:361)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: no turbojpeg in java.library.path
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:424)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:96)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:174)
	at scala.util.Try$.apply(Try.scala:209)
	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:174)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
	at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:357)
Caused by: java.lang.UnsatisfiedLinkError: no turbojpeg in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.libjpegturbo.turbojpeg.TJLoader.load(TJLoader.java:33)
	at org.libjpegturbo.turbojpeg.TJ.<clinit>(TJ.java:370)
	at com.powerspace.fork.Application.$anonfun$index$1(Application.scala:20)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
```

### Reproducible Test Case

- checkout https://github.com/nicolasblaye/sbt-play-fork-issue/tree/master
- install turbo-jpeg, check that it's in the right repo
- sbt run in a terminal
- call localhost:9000/
- try changing sbt version to 0.13.x to see if this works for you

**Comment by nicolasblaye** [comment]
I've got this error now.
```
Oops, cannot start the server.
Configuration error: Configuration error[
The application secret has not been set, and we are in prod mode. Your application is not secure.
To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
```

It works with the secret.

Thing is, we have many application, most of them not play.

Is it really impossible to use `run`? What prevents us from doing that?

**Comment by marcospereira** [comment]
See if using play-native-loader can help you:

https://github.com/playframework/play-native-loader/blob/master/src/main/java/play/libs/NativeLoader.java

If so, then we can close this issue.

**Comment by mkurz** [comment]
> If so, then we can close this issue.

I think it's OK now to close the issue.
