### ISSUE TITLE
Evolution surpressed Exception in JDK10 

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8454]
### Play Version (2.5.x / etc)
2.6.15

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
JDK 10.0.1 / 9.0.4

### Library Dependencies
N/A

### Expected Behavior
Exception is shown properly

### Actual Behavior
1) I upgraded Java from 9.0.4 to 10.0.1 and made change to my evolution script and entity in one commit.
2) After launching the application I saw expected "Apply evolutions" screen but after I clicked "Apply" button, evolution didn't run and an exception was thrown instead:
```
13:33:39.804 [play-dev-mode-akka.actor.default-dispatcher-9] [error] akka.actor.ActorSystemImpl - Internal server error, sending 500 response
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2047)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3869)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3873)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4798)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4804)
        at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:71)
        at com.google.inject.internal.Messages.formatInjectionPoint(Messages.java:269)
        at com.google.inject.internal.Messages.formatSource(Messages.java:229)
        at com.google.inject.internal.Messages.formatSource(Messages.java:220)
        at com.google.inject.internal.Messages.formatMessages(Messages.java:90)
        at com.google.inject.CreationException.getMessage(CreationException.java:50)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.$anonfun$new$1(Exceptions.scala:12)
        at scala.Option.map(Option.scala:146)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.apply(Exceptions.scala:12)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.apply(Exceptions.scala:12)
        at scala.Option.getOrElse(Option.scala:121)
        at play.api.UnexpectedException.<init>(Exceptions.scala:12)
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:186)
        at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:222)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:137)
        at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
        at akka.actor.ActorCell.invoke(ActorCell.scala:559)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: null
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:160)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:143)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:418)
        at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:64)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:49)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:45)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3443)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2169)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2128)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2041)
        ... 41 common frames omitted
```
3) I reverted all changes and indeed Play run properly on JDK10.
4) Then I restored changes and downgraded JDK to 9.0.4 and instead of "apply evolutions" I saw hibernate exception instead:
```
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, org.hibernate.AnnotationException: Unable to create unique key constraint (company, city) on table company: database column 'company' not found. Make sure that you use the correct column name which depends on the naming strategy in use (it may not be the same as the property name in the entity, especially for relational types)
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.<init>(DefaultJPAApi.java:44)
  at play.db.jpa.DefaultJPAApi$JPAApiProvider.class(DefaultJPAApi.java:39)
  while locating play.db.jpa.DefaultJPAApi$JPAApiProvider
  while locating play.db.jpa.JPAApi
    for field at security.SecurityHandler.jpaApi(SecurityHandler.java:47)
  while locating security.SecurityHandler
  at lib.ApplicationModule.configure(ApplicationModule.java:106) (via modules: com.google.inject.util.Modules$OverrideModule -> lib.ApplicationModule)
  while locating be.objectify.deadbolt.java.DeadboltHandler annotated with @security.HandlerQualifiers$MainHandler()
    for the 1st parameter of security.SecurityHandlerCache.<init>(SecurityHandlerCache.java:21)
  at security.SecurityHandlerCache.class(SecurityHandlerCache.java:12)
  while locating security.SecurityHandlerCache
  at lib.ApplicationModule.configure(ApplicationModule.java:109) (via modules: com.google.inject.util.Modules$OverrideModule -> lib.ApplicationModule)
  while locating be.objectify.deadbolt.java.cache.HandlerCache

1 error
     com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
     com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
     com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
     com.google.inject.Guice.createInjector(Guice.java:87)
     com.google.inject.Guice.createInjector(Guice.java:78)
     play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
     play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
     play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
     play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
     play.utils.Threads$.withContextClassLoader(Threads.scala:21)
     play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
     play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
     play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:222)
     play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:137)
     akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
     akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
     akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
     akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
     akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
     akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
     akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
     akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
     akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
     akka.actor.Actor.aroundReceive(Actor.scala:517)
     akka.actor.Actor.aroundReceive$(Actor.scala:515)
     akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
     akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
     akka.actor.ActorCell.invoke(ActorCell.scala:559)
     akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
     akka.dispatch.Mailbox.run(Mailbox.scala:224)
     akka.dispatch.Mailbox.exec(Mailbox.scala:234)
     akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
     akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
     akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
     akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
which is obviously my mistake, but in JDK10 it was hidded by evolution screen.
5) I didn't apply the evolution, instead I got back to JDK10, fixed the error and run application. Play applied evolutions without any problems.
6) Then I made this "error" again and Play displayed error properly, so it is directly connected with Evolution screen on JDK10

**Comment by mkurz** [comment]
Most likely that's because Play 2.6 still uses a Guice version that bundles a ASM version that does not yet support Java 10.
Try upgrading to Guice 4.2, see this comment how to: https://github.com/playframework/playframework/pull/8259#issuecomment-370173620

**Comment by eximius313** [comment]
I have Guice 4.2 exactly as in your comment. Without it I wasn't able to run JDK9.
But I have more news - it happened again when I made some changes that failed during initialization.
Again exception on JDK10:
```
14:20:26.334 [play-dev-mode-akka.actor.default-dispatcher-5] [error] akka.actor.ActorSystemImpl - Internal server error, sending 500 response
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2047)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3869)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3873)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4798)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4804)
        at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:71)
        at com.google.inject.internal.Messages.formatSource(Messages.java:241)
        at com.google.inject.internal.Messages.formatSource(Messages.java:220)
        at com.google.inject.internal.Messages.formatInjectionPoint(Messages.java:276)
        at com.google.inject.internal.Messages.formatSource(Messages.java:235)
        at com.google.inject.internal.Messages.formatSource(Messages.java:220)
        at com.google.inject.internal.Messages.formatMessages(Messages.java:90)
        at com.google.inject.ProvisionException.getMessage(ProvisionException.java:61)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.$anonfun$new$1(Exceptions.scala:12)
        at scala.Option.map(Option.scala:146)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.apply(Exceptions.scala:12)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.apply(Exceptions.scala:12)
        at scala.Option.getOrElse(Option.scala:121)
        at play.api.UnexpectedException.<init>(Exceptions.scala:12)
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:186)
        at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:222)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:137)
        at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
        at akka.actor.ActorCell.invoke(ActorCell.scala:559)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: null
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:160)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:143)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:418)
        at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:64)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:49)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:45)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3443)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2169)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2128)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2041)
        ... 43 common frames omitted
14:20:31.264 [play-dev-mode-akka.actor.default-dispatcher-8] [debug] akka.io.TcpListener - New connection accepted
14:20:31.502 [play-dev-mode-akka.actor.default-dispatcher-5] [error] application -
```
When I try to enter to the `/` I get:
```
! @7863jd8f8 - Internal server error, for (GET) [/] ->

play.api.PlayException: Not initialized[?]
        at play.core.server.DevServerStart$$anon$1.<init>(DevServerStart.scala:104)
        at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:97)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:59)
        at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:49)
        at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at play.runsupport.Reloader$.startDevMode(Reloader.scala:229)
        at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:95)
        at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:79)
        at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:102)
        at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:65)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
        at sbt.std.Transform$$anon$4.work(System.scala:66)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:272)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
14:20:31.603 [play-dev-mode-akka.actor.default-dispatcher-7] [error] application -
```

and on JDK9:
```
ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, javax.xml.ws.WebServiceException: Failed to access the WSDL at: file:/home/user/wsdl/MyWsdl.xsd. It failed with: /home/user/wsdl/MyWsdl.xsd (Path not found).
  at lib.ApplicationModule$RegonServiceProvider.<init>(ApplicationModule.java:200)
```

**Comment by mkurz** [comment]
OK I forgot, the ASM version bundled with Guice 4.2 only has support for JDK9, but not for JDK10/11 yet: See https://github.com/google/guice/pull/1169

**Comment by eximius313** [comment]
This could be it! Thanks

**Comment by laguiz** [comment]
I got the same issue with JDK 11 (`Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)` on Windows). I forced guice version to `4.2.2` with `libraryDependencies += "com.google.inject" % "guice" % "4.2.2"`. All back to normal.
