### ISSUE TITLE
Filters/Documentation broken - Cannot load play.http.filters

### ISSUE THREAD

**Issue by philliptaylorpro** [playframework/playframework#8511]
1. Create a new Play Framework scala project:

` sbt new "https://github.com/playframework/play-scala-seed.g8"`

accept the defaults...
```

HOST [10:02: tmp$] sbt new "https://github.com/playframework/play-scala-seed.g8"
[info] Loading global plugins from /home/phill/.sbt/0.13/plugins
[info] Set current project to tmp (in build file:/home/phill/tmp/)

This template generates a Play Scala project 

name [play-scala-seed]: sample
organization [com.example]: 
play_version [2.6.15]: 
sbt_version [1.1.6]: 
scalatestplusplay_version [3.1.2]: 

Template applied in ./sample
```

2. create a directory inside app called filters

```
cd <project-name>
mkdir app/filters
```

3. Copy the first code example of a Filter off the website:

https://www.playframework.com/documentation/2.5.x/ScalaHttpFilters

(incidently this is the code at the time of reporting)

```
import javax.inject.Inject
import akka.stream.Materializer
import play.api.Logger
import play.api.mvc._
import scala.concurrent.{ExecutionContext, Future}

class LoggingFilter @Inject() (implicit val mat: Materializer, ec: ExecutionContext) extends Filter {

  def apply(nextFilter: RequestHeader => Future[Result])
           (requestHeader: RequestHeader): Future[Result] = {

    val startTime = System.currentTimeMillis

    nextFilter(requestHeader).map { result =>

      val endTime = System.currentTimeMillis
      val requestTime = endTime - startTime

      Logger.info(s"${requestHeader.method} ${requestHeader.uri} took ${requestTime}ms and returned ${result.header.status}")

      result.withHeaders("Request-Time" -> requestTime.toString)
    }
  }
}
```

note: I wrote the file to the filename app/filters/LoggingFilter.scala
and I added the line `package filters` to the top of the example too.

4. Add the filter to the `conf/application.conf`, as the page describes:

`play.http.filters     = "filters.LoggingFilter"`

5. Run the application

`sbt run`

6. When you visit the website, the applications fails to compile with the following logged errors:

```
HOST [09:48: play-sample$] sbt run
[info] Loading settings from plugins.sbt ...
[info] Loading global plugins from /home/phill/.sbt/1.0/plugins
[info] Loading settings from scaffold.sbt,plugins.sbt ...
[info] Loading project definition from /home/phill/tmp/play-sample/project
[info] Loading settings from build.sbt ...
[info] Set current project to play-sample (in build file:/home/phill/tmp/play-sample/)

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] Compiling 1 Scala source to /home/phill/tmp/play-sample/target/scala-2.12/classes ...
[info] Done compiling.
[error] application - 

! @78h07d2fp - Internal server error, for (GET) [/] ->
 
play.api.PlayException: Cannot load play.http.filters[play.http.filters [class java.lang.Class}] does not implement interface play.api.http.HttpFilters or interface play.http.HttpFilters.]
        at play.utils.Reflect$.$anonfun$configuredClass$2(Reflect.scala:137)
        at scala.Option.map(Option.scala:146)
        at play.utils.Reflect$.configuredClass(Reflect.scala:127)
        at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:50)
        at play.api.http.HttpFilters$.bindingsFromConfiguration(HttpFilters.scala:46)
        at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.$anonfun$new$3(BuiltinModule.scala:86)
        at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.$anonfun$new$1(BuiltinModule.scala:35)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error] application - 

! @78h07d2fp - Internal server error, for (GET) [/favicon.ico] ->
 
play.api.PlayException: Cannot load play.http.filters[play.http.filters [class java.lang.Class}] does not implement interface play.api.http.HttpFilters or interface play.http.HttpFilters.]
        at play.utils.Reflect$.$anonfun$configuredClass$2(Reflect.scala:137)
        at scala.Option.map(Option.scala:146)
        at play.utils.Reflect$.configuredClass(Reflect.scala:127)
        at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:50)
        at play.api.http.HttpFilters$.bindingsFromConfiguration(HttpFilters.scala:46)
        at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.$anonfun$new$3(BuiltinModule.scala:86)
        at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.$anonfun$new$1(BuiltinModule.scala:35)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error] application - 

! @78h07d2fp - Internal server error, for (GET) [/favicon.ico] ->
 
play.api.PlayException: Cannot load play.http.filters[play.http.filters [class java.lang.Class}] does not implement interface play.api.http.HttpFilters or interface play.http.HttpFilters.]
        at play.utils.Reflect$.$anonfun$configuredClass$2(Reflect.scala:137)
        at scala.Option.map(Option.scala:146)
        at play.utils.Reflect$.configuredClass(Reflect.scala:127)
        at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:50)
        at play.api.http.HttpFilters$.bindingsFromConfiguration(HttpFilters.scala:46)
        at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.$anonfun$new$3(BuiltinModule.scala:86)
        at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.$anonfun$new$1(BuiltinModule.scala:35)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error] application - 

! @78h07d2fp - Internal server error, for (GET) [/assets/images/favicon.png] ->
 
play.api.PlayException: Cannot load play.http.filters[play.http.filters [class java.lang.Class}] does not implement interface play.api.http.HttpFilters or interface play.http.HttpFilters.]
        at play.utils.Reflect$.$anonfun$configuredClass$2(Reflect.scala:137)
        at scala.Option.map(Option.scala:146)
        at play.utils.Reflect$.configuredClass(Reflect.scala:127)
        at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:50)
        at play.api.http.HttpFilters$.bindingsFromConfiguration(HttpFilters.scala:46)
        at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.$anonfun$new$3(BuiltinModule.scala:86)
        at play.api.inject.BuiltinModule$$anonfun$$lessinit$greater$1.$anonfun$new$1(BuiltinModule.scala:35)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[INFO] [07/11/2018 09:49:48.202] [Thread-2] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```

I am unsure of how to resolve this issue.

Sample code base here: [play-sample.tar.gz](https://github.com/playframework/playframework/files/2183761/play-sample.tar.gz)

**Comment by philliptaylorpro** [comment]
Apparently I've misread the config line.

**Comment by jpablo** [comment]
I got bitten by the same issue :/

**Comment by suv1sh** [comment]
How to resolve it?

**Comment by philliptaylorpro** [comment]
https://www.playframework.com/documentation/2.5.x/ScalaHttpFilters#Using-filters

You have to add this bit:
```

class Filters @Inject() (
  gzip: GzipFilter,
  log: LoggingFilter
) extends DefaultHttpFilters(gzip, log)
```

like it says in the documentation and point your config at that class, not at the class name for the first piece of code you copy and pasted.
