### ISSUE TITLE
Possibility to access Session in Java Filter

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#8563]
### Play Version (2.5.x / etc)
2.6.15

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
N/A

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
N/A

### Library Dependencies
N/A

### Expected Behavior
It should be possible to access session in Java filter api. 
```
@Override
public CompletionStage<Result> apply(
          final Function<RequestHeader, CompletionStage<Result>> nextFilter,
          final RequestHeader requestHeader) {
                    final Session session = requestHeader.session();
                    return nextFilter.apply(requestHeader);
}
```

### Actual Behavior
Currently session is available only in Scala API:
`requestHeader.asScala().session()`

Thank you in advance

**Comment by marcospereira** [comment]
Hi @eximius313,

`Http.Context.current().session()` is the API you are looking for. We are moving to deprecate it so you may be interested in #8312.

Best.

**Comment by eximius313** [comment]
1) I'm aware of https://github.com/playframework/playframework/pull/8312 and that was one of the reasons why I opened this issue
2) The second is following exception:
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: There is no HTTP Context available from here.]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:251)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:178)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:363)
        at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:361)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: There is no HTTP Context available from here.
        at play.mvc.Http$Context.current(Http.java:68)
        at controllers.filters.MyFilter.apply(MyContextFilter.java:29)
        at play.mvc.Filter$1.apply(Filter.java:39)
        at play.api.mvc.Filter$$anon$1.apply(Filters.scala:61)
        at play.api.mvc.Filter$$anon$1.apply(Filters.scala:48)
        at play.api.mvc.EssentialAction$$anon$1.apply(Action.scala:37)
        at play.api.mvc.EssentialAction$$anon$1.apply(Action.scala:32)
        at play.filters.hosts.AllowedHostsFilter.$anonfun$apply$1(AllowedHostsFilter.scala:33)
        at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:48)
        at play.api.mvc.EssentialAction$$anon$3.apply(Action.scala:47)
        at play.core.server.AkkaHttpServer.$anonfun$runAction$1(AkkaHttpServer.scala:342)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        ... 12 common frames omitted
```

**Comment by gmethvin** [comment]
I think this is just a matter of adding a `session()` method to the Java `RequestHeader` that looks like the Scala one. When we do that we should also add `flash()` and `cookies()`.

In the meantime, the following should work, since it is possible to access the raw request attributes from Java:

```java
Session session = request.attrs().get(RequestAttrKey.Session().asJava()).value().asJava();
```

I think this would be a good feature to add for Play 2.7.

**Comment by eximius313** [comment]
@gmethvin as adding new methods is backward compatibile - may I ask you for backporting this to 2.6 as well? Thank you in advance

**Comment by marcospereira** [comment]
> I think this is just a matter of adding a session() method to the Java RequestHeader that looks like the Scala one. When we do that we should also add flash() and cookies().

There are some other aspects to consider though: how will this relates to `Http.Context.session`? Should the user expect that adding a value to `Http.Context.session` will reflect in `request.session` (and vice versa)? I haven't tested it, but there are places where Play itself is updating `Http.Context.session`:

https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java#L69

If someone decides to work on this, consider deprecating `Http.Context.session` in favor of `request.session`.

**Comment by marcospereira** [comment]
> I think the ideal API would be an immutable session/withSession similar to the Scala API.

Yes, just like the Scala API: `play.api.mvc.RequestHeader.session` returns an immutable `play.api.mvc.Session` and `play.api.mvc.RequestHeader` is itself immutable. If you want to add something to the session, you need to use a combination of `request.session`, `session.+` and `request.addAttr` and this will all create a new `Session` and a new `RequestHeader`.

We can then add `withSession` to `Result` at the Java APIs. It makes more sense to me to write in the session via the `Result` instead of via the `Request`.

**Comment by eximius313** [comment]
Ok, thanks

**Comment by eximius313** [comment]
@mkurz I looked at https://www.playframework.com/documentation/2.7.0-RC3/Migration27 and https://www.playframework.com/documentation/2.7.0-RC3/JavaHttpContextMigration27 but I don't see anything related to `requestHeader.session()` in `Filter`. Am I missing something?

**Comment by decoded4620** [comment]
> I think this is just a matter of adding a `session()` method to the Java `RequestHeader` that looks like the Scala one. When we do that we should also add `flash()` and `cookies()`.
> 
> In the meantime, the following should work, since it is possible to access the raw request attributes from Java:
> 
> ```java
> Session session = request.attrs().get(RequestAttrKey.Session().asJava()).value().asJava();
> ```
> 
> I think this would be a good feature to add for Play 2.7.

The code above doesn't work for Play 2.6 (asJava method on RequestAttrKey.Session() doesn't exist)

**Comment by mkurz** [comment]
@decoded4620 I just tested with Play 2.6.23 and it worked.

```java
import play.api.mvc.request.RequestAttrKey;
```

```java
//requestHeader being a play.mvc.Http.RequestHeader
requestHeader.attrs().get(RequestAttrKey.Session().asJava()).value().asJava();
```

**Comment by mkurz** [comment]
And yeah, starting with Play 2.7.0 you can just use `requestHeader.session()`

**Comment by decoded4620** [comment]
My app uses the gradle plugin. Last i checked, its not compatible with 2.7. Just waiting until then in the meantime.
