### ISSUE TITLE
Obscure error message, if environment variable not set

### ISSUE THREAD

**Issue by sambokai** [playframework/playframework#8716]
### JDK (Oracle 1.8.0_144)
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### Expected Behavior

1. Require environment variable in `conf/application.conf` using `confKeyName = ${envVarKey}`
2. `sbt clean compile run`
3. `curl localhost:9000`
4. Error message: environment variable $envVarKey not set

If I remember correctly, even compilation used to fail, if the env var was not provided

### Actual Behavior

Step 4:  
```
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:504)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
```

**Comment by wsargent** [comment]
This isn't a bug with the framework -- there would have been an earlier exception showing failure to generate a valid configuration.

**Comment by novakov-alexey** [comment]
Still having this issue, no earlier exception showing failure to generate a valid configuration. :-(

**Comment by Lugghawk** [comment]
I get this issue as well, and no prior exceptions about the configuration. However, after ctrl+c'ing the `sbt run`, the console outputs this before stopping:

```
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
	at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:506)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:376)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:480)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:574)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
[info] p.c.s.AkkaHttpServer - Stopping server...
[warn] a.a.CoordinatedShutdown - Task [shutdown-application-dev-mode] failed in phase [service-stop]: Configuration error[application.conf @ file:/Users/dave/code/hoggit/patreon/target/scala-2.12/classes/application.conf: 9: Could not resolve substitution to a value: ${MY_ENVIRONMENT_VARIABLE}]
```

**Comment by mkurz** [comment]
@novakov-alexey @Lugghawk 
I assume you use the akka-http backend server. Can you switch to netty and tell us what you see then?
https://www.playframework.com/documentation/2.7.x/NettyServer#Netty-Server-Backend

**Comment by marcospereira** [comment]
@mkurz I assume this is the same as #9020.

**Comment by mkurz** [comment]
Based on my findings [here](https://github.com/playframework/playframework/issues/9020#issuecomment-501654091) I guess the swallowed error message is something like `Reserved character '?' is not allowed outside quotes`...

@novakov-alexey @Lugghawk Try to put the config value in quotes:
```
confKeyName = "${envVarKey}"
```
and let us know if that fixes your problem.

**Comment by q-lukasz** [comment]
I also didn't get any earlier exceptions.
@wsargent , would you consider reopening the issue?

**Comment by wsargent** [comment]
@q-lukasz https://github.com/playframework/playframework/issues/9020 is open and has a reproducing test case replicating the issue here, so it's better to continue discussion on that thread.
