### ISSUE TITLE
Custom Server cant 'be loaded in dev mode (sbt run)

### ISSUE THREAD

**Issue by bjaglin** [playframework/playframework#8722]
### Play Version (2.5.x / etc)

2.6.18
2.7.0-M4

### API (Scala / Java / Neither / Both)

Both

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

```
$ uname -a
Linux x1 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

### Library Dependencies

None

### Expected Behavior

1. Follow https://www.playframework.com/documentation/2.6.x/SettingsAkkaHttp#Direct-Akka-HTTP-configuration
2. Run `sbt run`
3. Observe the custom behavior

### Actual Behavior

1. Follow https://www.playframework.com/documentation/2.6.x/SettingsAkkaHttp#Direct-Akka-HTTP-configuration
2. Run `sbt run`
3. ClassNotFoundException

```
[error] play.core.server.ServerStartException: Couldn't find ServerProvider class 'server.CustomAkkaHttpServerProvider'
[error] 	at play.core.server.ServerProvider$.fromConfiguration(ServerProvider.scala:60)
[error] 	at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:232)
[error] 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error] 	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:59)
[error] 	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:49)
[error] 	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:229)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:95)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:79)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:102)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:65)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] Caused by: java.lang.ClassNotFoundException: server.CustomAkkaHttpServerProvider
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at play.core.server.ServerProvider$.fromConfiguration(ServerProvider.scala:59)
[error] 	at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:232)
[error] 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error] 	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:59)
[error] 	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:49)
[error] 	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:229)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:95)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:79)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:102)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:65)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
```

### Reproducible Test Case

Reproduced over a raw `sbt new playframework/play-scala-seed.g8`: https://github.com/bjaglin/play-server-classloader/commit/7ab7270ad726c5d9f59c8496888f4148750e06bc

**Comment by bjaglin** [comment]
To clarify: the dev mode is the only thing from https://github.com/playframework/playframework/pull/8392/files#diff-45b384eb6efcc6beb84ae3458467af95R11 which does not seem to be working - the linked test case works fine when NOT using Play's classpath/reloader mechanism (provided the server is referenced in `application.conf` obviously).

**Comment by patofp** [comment]
I'm also experiencing the same issue as @bjaglin commented with Play 2.7. I was trying to set websockets ping-pong protocol with a custom Akka Http server provider, which already support this protocol, but I got this same error when starting the application in dev mode with ### sbt run.

**Comment by raulsaeztapia** [comment]
+1

**Comment by rafaelgarrote** [comment]
+1

**Comment by mkurz** [comment]
The problem here is that even though [the classloader](https://github.com/playframework/playframework/blob/af43be400c0c11742e16f4ab362e80e35f361640/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala#L59), which is used [to load the class](https://github.com/playframework/playframework/blob/af43be400c0c11742e16f4ab362e80e35f361640/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala#L254) *when the server starts up*, is [the `application(class)Loader`](https://github.com/playframework/playframework/blob/af43be400c0c11742e16f4ab362e80e35f361640/dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala#L283), which doesn't have the application classes on the classpath (yet), because the application is not started yet... Meaning at the time the backend server starts this classloader [only contains the `dependencyClasspath`](https://github.com/playframework/playframework/blob/af43be400c0c11742e16f4ab362e80e35f361640/dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala#L263-L264).

Because we know now that only the `dependencyClasspath` is available you can do following **workaround:**
You need to put a jar on the that `dependencyClasspath` which contains your custom server (provider) class(es). For this you have to create a own project that only contains that class(es) and package it into a jar file. [Here](https://github.com/mkurz/custom-akka-http-server-example) I provide you an example of such a project. Just use this example project and run `package` inside `sbt`. The jar file will be generated and availabe in `target/scala-2.12/custom-server_2.12-1.0.jar`.
Now just copy this jar file into your projects `lib` folder (which you need to create if not there yet) and of course also make sure that `PlayKeys.devSettings += "play.server.provider" -> "server.CustomAkkaHttpServerProvider"` is set in your `build.sbt`.
Now the class will be found in DEV mode as well.
Of course the disadvantage of this workaround is that you have to each time package a new jar file when you make a change to the custom server class and replace the old jar in the `lib` folder.

I hope this helps.

BTW: How about if you guys provide pull requests with the features you need build in into Play's `AkkaHttpServer`, so you don't even need to implement your own custom servers? (I guess the changes would need to go somewhere around [here](https://github.com/playframework/playframework/blob/af43be400c0c11742e16f4ab362e80e35f361640/transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L150)).

**Comment by patofp** [comment]
Thx @mkurz for the awesome explanation and the workaround. When I have a bit of time I will try to provide the features I need to the AkkaHttpServer.

**Comment by bjaglin** [comment]
@mkurz great explanation, makes sense!

Regarding your BTW: my use case for a custom server was actually temporary, to mimic https://github.com/playframework/playframework/pull/8607/files until the PR got merged and released.

IMHO, your workaround is good enough, so maybe [docs](https://www.playframework.com/documentation/2.7.x/SettingsAkkaHttp#Direct-Akka-HTTP-configuration) could be updated to highlight the challenges with a custom server in dev mode, and we can close this? What had bothered me was that the docs explicitly mention the dev mode even though it does not work out of the box.

**Comment by mkurz** [comment]
> IMHO, your workaround is good enough, so maybe [docs](https://www.playframework.com/documentation/2.7.x/SettingsAkkaHttp#Direct-Akka-HTTP-configuration) could be updated to highlight the challenges with a custom server in dev mode, and we can close this?

@bjaglin If you could provide a pull request that would be nice :wink:
