### ISSUE TITLE
Play 2.6.x HQL "select clause" is not work

### ISSUE THREAD

**Issue by jazz321254** [playframework/playframework#8725]
It's well when I used HQL "select clause" statement to create the instance in play 2.5.
currently, I upgrade to Play 2.6.20. it will throw the exception.

the "select clause" is like below
```
SELECT new xxx.com.tw.History(
item.id, item.cat, item.name, item.time
) FROM Item item
```
if anyone can help me it'll be great.

### Play Version (2.5.x / etc)
2.6.20

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Ubuntu 16.04

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
openjdk version "1.8.0_181"

### Library Dependencies
PostgreSQL EnterpriseDB 9.4.4.9 
jdbc com.edb.Driver.edb.16

### Expected Behavior
paste code.
`
public class HistoryDao {
  
  private JPAApi jpaApi;

  @Inject
  public AuditDao(JPAApi api) {
    this.jpaApi = api;
  }
  
  public List<History> findItemHistoryList(String vendNo) { 
    return jpaApi.em()
        .createQuery("SELECT new xxx.yyy.pojo.History("
        + " item.id, "
        + " item.stamp, "
        + " item.vendNo, "
        + " item.editor.name, "
        + " item.record.ip"
        + " ) "
        + " FROM ItemAudit item "
        + " WHERE item.vendNo = :vendNo"
        + " ORDER BY item.stamp DESC", History.class)
        .setParameter("vendNo", vendNo)
        .getResultList();
  }  ...
`

### Actual Behavior
exception stack trace

```
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: Unable to locate class [xxx.yyy.pojo.History] [SELECT new xxx.yyy.pojo.History( item.id,  item.stamp,  item.vendNo,    item.editor.name,  item.record.ip )  FROM xxx.yyy.models.ItemAudit item WHERE item.vendNo = :vendNo ORDER BY item.stamp DESC]
	at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:74)
	at org.hibernate.hql.internal.ast.ErrorTracker.throwQueryException(ErrorTracker.java:93)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.analyze(QueryTranslatorImpl.java:277)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:191)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:143)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:119)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:80)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:597)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:706)
```

**Comment by jazz321254** [comment]
I use hibernate version is 5.3.2.Final.

**Comment by marcospereira** [comment]
Hi @jazz321254,

Is it possible to create a small project that reproduces the problem?

Best.
