### ISSUE TITLE
All requests failing to decode JWT

### ISSUE THREAD

**Issue by timbarclay** [playframework/playframework#8729]
### Play Version (2.5.x / etc)

2.6.6

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

### Expected Behavior

Requests to Play's endpoints and routes should complete without logging warnings about JWT tokens failing to be decoded

### Actual Behavior

On every request to any endpoint on my Play server, the console logs the following:

`[warn] - play.api.mvc.DefaultJWTCookieDataCodec - decode: could not decode JWT: null
java.lang.NullPointerException: null
	at play.api.mvc.JWTCookieDataCodec.$anonfun$decode$7(Cookie.scala:595)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at play.api.mvc.JWTCookieDataCodec.decode(Cookie.scala:595)
	at play.api.mvc.JWTCookieDataCodec.decode$(Cookie.scala:583)
	at play.api.mvc.DefaultJWTCookieDataCodec.decode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.decode(Cookie.scala:754)
	at play.api.mvc.FallbackCookieDataCodec.decode$(Cookie.scala:745)
	at play.api.mvc.DefaultFlashCookieBaker.decode(Flash.scala:91)
	at play.api.mvc.CookieBaker.decodeFromCookie(Cookie.scala:431)
	at play.api.mvc.CookieBaker.decodeFromCookie$(Cookie.scala:428)
	at play.api.mvc.DefaultFlashCookieBaker.decodeFromCookie(Flash.scala:91)
	at play.api.mvc.request.DefaultRequestFactory$$anon$3.create(RequestFactory.scala:119)
	at play.api.mvc.request.DefaultRequestFactory$$anon$3.create(RequestFactory.scala:117)
	at play.api.mvc.request.LazyCell.value(Cell.scala:66)
	at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:225)
	at play.core.server.AkkaHttpServer.$anonfun$executeAction$3(AkkaHttpServer.scala:302)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:55)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
	at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:301)
	at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:254)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:200)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$3(AkkaHttpServer.scala:106)
	at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

The error is being thrown by line 595 of `Cookie.scala`: `data.asScala.map{ case (k, v) => (k, v.toString) }(breakOut)`.

At that point `data` is a map of session values containing only a single `csrfToken` key with a pretty plausible looking string value.

This started happening apparently at random. I had not made any changes to code that would affect session state, cookies or JWT tokens.

I have tried restarting the server, using an incognito browser window and clearing my browser cookies and cache, but it still happens on every request.

**Comment by timbarclay** [comment]
In fact, it looks like it was issue 8114. A previous request _had_ assigned a null value to the flash data.
