### ISSUE TITLE
'application.home' property is not passed to conf/logback.xml in production mode (sbt dist)

### ISSUE THREAD

**Issue by nextdtinc** [playframework/playframework#8759]
### JDK
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

### Expected Behavior

Logging to a file should be possible via `conf/logback.xml` configuration:

    <file>${application.home:-.}/logs/application.log</file>

However, this only works as expected (e.g. logging will be visible in the file path "./logs/application.log", relative to where the Play project is run from) when running the Play project with `sbt run`.

### Actual Behavior

The above configuration does **not** work when the Play project is deployed and run with `sbt dist`. In that case, the `logs/application.log` file is created in the expected location, but no logging occurs, and the `application.log` file remains at zero bytes. In this scenario, logging can still be made to work when skipping the usage of the parameter `application.home`. For example, logging to a file still works even when running with `sbt dist` by simply specifying an absolute path of the file, instead of using `application.home`:

    <file>/tmp/application.log</file>

Therefore, the bug is that `application.home` is not passed to `conf/logback.xml` when using `sbt dist`.

According to the documentation: https://www.playframework.com/documentation/2.6.x/SettingsLogger#Including-Properties

    By default, only the property application.home is exported to the logging framework, meaning that files can be referenced relative to the Play application

### Reproducible Test Case

The minimum reproducible test case has been uploaded here.

[play-test.zip](https://github.com/playframework/playframework/files/2545390/play-test.zip)

**Comment by nextdtinc** [comment]
Relevant: https://github.com/playframework/playframework/issues/5535

`The default value of a variable can reference a another variable. For example, assuming the variable 'id' is unassigned and the variable 'userid' is assigned the value "alice", then the expression "${id:-${userid}}" will return "alice".`

https://logback.qos.ch/manual/configuration.html

**Comment by alvaroc1** [comment]
@nextdtinc So was this a real issue? and was it fixed? how come it was closed?

**Comment by nemoo** [comment]
So currently, the 'application.home' property is still not passed to conf/logback.xml in production mode. Can we reopen the issue?

**Comment by mkurz** [comment]
@nemoo I just tested, this is working in latest Play 2.8 version. No need to re-open.

**Comment by nemoo** [comment]
How to reproduce the problem:

- check out my example project that uses file appender as described in the play documentation with ("application.home:-"): https://github.com/nemoo/play-slick-synchronous-example 
- sbt clean dist

Then: 
 'application.home' is set if the dist shellscript is started from the root directory of the application.
 'application.home' **is not set** if the dist shellscript is started from the myapp/bin directory. Then the startup fails  with:
```
09:48:30,294 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [application.home_IS_UNDEFINED/logs/application.log]
09:48:30,295 |-ERROR in ch.qos.logback.core.FileAppender[FILE] - Failed to create parent directories for [/tmp/myapp/application.home_IS_UNDEFINED/logs/application.log]
09:48:30,295 |-ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(application.home_IS_UNDEFINED/logs/application.log,true) call failed. java.io.FileNotFoundException: application.home_IS_UNDEFINED/logs/application.log (No such file or directory)
	at java.io.FileNotFoundException: application.home_IS_UNDEFINED/logs/application.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
```
Apparently this trips up a lot of people, this issue about it on Stackoverflow has almost 5000 views: https://stackoverflow.com/questions/31486216/in-play-2-4-logback-configurations-where-is-application-home-defined

**Comment by mkurz** [comment]
I had a look. Looks like (if a am not wrong, because I didn't debug, just looking) `application.home` gets initialized from the `environment` whose `rootPath` is initialized with `new File(".")`, which obviously would use the wrong directory if called from within `/bin`.
Note to myself: Interestingly we also have the `play.server.dir` config key and the `user.dir` property, so maybe we want to init `application.home` from one of those values?

Given that there is a workaround (by running the app from the root dir instead from inside the /bin/ folder), I will postpone it for later.

**Comment by mirkosaiu** [comment]
For Play Framework 2.7 I guess I solved this issue passing the 'application.home' through the system properties but I'm looking forward to upgrade the project to Play Framework 2.8 where the issue is allegedly properly solved :)

Here is an example of the solution:

```
/path/to/home/YOUR_APPLICATION_FOLDER/bin/PROJECT_NAME   -Dapplication.home=/path/to/home/YOUR_APPLICATION_FOLDER
```
