### ISSUE TITLE
Netty Native UnsatisfiedLinkError

### ISSUE THREAD

**Issue by abdelrahmanmohamed** [playframework/playframework#8795]
```
play.server {
  netty {
    transport = "native"
  }
}
```

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:79)
	at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:54)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68)
	at play.core.server.NettyServer.<init>(NettyServer.scala:76)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:271)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:270)
	at play.core.server.ServerProvider$class.createServer(ServerProvider.scala:25)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:270)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:57)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.NoSuchMethodError: Method io.netty.channel.epoll.Native.recvFd0(I)I not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:215)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:201)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38)

```

**Comment by abdelrahmanmohamed** [comment]
Play Version 2.6.20

**Comment by mkurz** [comment]
What system are you running your app on? Linux, Windows, Mac?

**Comment by abdelrahmanmohamed** [comment]
Linux

**Comment by pettyjamesm** [comment]
I also saw this issue appear when we upgraded `play-ahc-ws-standalone` from `1.1.10` to `1.1.12`.

**Comment by njovy** [comment]
I'm also having this issue when I try to use ```EpollEventLoopGroup``` on 2.6.21.

**Comment by mkurz** [comment]
Hmm... Maybe one of your dependencies puts another version of netty onto the classpath?
Can you guys post your dependencies defined in `build.sbt` and `project/plugins.sbt`?
Maybe this could related: https://github.com/netty/netty/issues/6665?

**Comment by mkurz** [comment]
And what is the OS architecture? Please run `uname -a`

**Comment by mkurz** [comment]
Alright, I am pretty sure the problem is caused [by the shading](https://github.com/playframework/play-ws#shading) `play-ws` (and it's libs) uses, it puts `shaded-asynchttpclient-*.jar` on the classpath, which comes with it's own netty classes - however they are version 4.0.x and play uses 4.1.x.
Looks like the [shading setup](https://github.com/playframework/play-ws/blob/b002107bba48e39b393216f5a3e668c734d17401/build.sbt#L188-L230) needs some tuning:
If you read through https://github.com/netty/netty/issues/6665, we need to set a system property, for netty 4.0 that is most likely `io.netty.native.epoll.nettyPackagePrefix` (see https://github.com/netty/netty/commit/53323530c1b47e225c28fc4e3a4a4f9de1b7a0e3)
However in Netty 4.1 that system property was removed and instead `io.netty.packagePrefix` was introduced. See the comment(s) [here](https://github.com/netty/netty/issues/4800#issuecomment-178257698) and the according [pull request](https://github.com/netty/netty/commit/075a54af3e607c20eeaf7809a2a08602abd5d735) for Netty 4.1.
Looks like we also need to rename the `*.so` file in play-ws.
(BTW: If you look at the commit description of my last link is clearly says "_...This means EPOLL cannot be used with a shaded Netty._", so we clearly have a bug here)

**Comment by mkurz** [comment]
BTW: This bug probably will fix itself when upgrading to Play 2.7 - because the shaded asynchttpclient version it comes with when using play-ahc-ws-standalone uses Nett 4.1 as well (same like Play uses).

However I still think we should have a look at setting the system property and/or renaming the `*.so` file like (mentioned in my posted links) in Play 2.7 as well.

However, I don't have time to work on this right now.
