### ISSUE TITLE
Application doesn't run if you call configuration from the Global object

### ISSUE THREAD

**Issue by keith-miller** [playframework/playframework#883]
If you have a Global that looks like the following:

import play.api._
import play.api.mvc._
import play.Play

object Global extends GlobalSettings {
  val myvalue = Play.application().configuration().getString("myapp.myvalue")

  override def onRouteRequest(request: RequestHeader): Option[Handler] = {
     super.onRouteRequest(request)
  }
}

The application will fail to run with the error:

play.api.Configuration$$anon$1: Configuration error[Cannot initialize the custom Global object (%s) (perhaps it's a wrong reference?)]
    at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:80) ~[play_2.10.jar:2.1.0]
    at play.api.Configuration.reportError(Configuration.scala:558) ~[play_2.10.jar:2.1.0]
    at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$scalaGlobal(Application.scala:41) ~[play_2.10.jar:2.1.0]
    at play.api.DefaultApplication.play$api$WithDefaultGlobal$$scalaGlobal$lzycompute(Application.scala:383) ~[play_2.10.jar:2.1.0]
    at play.api.DefaultApplication.play$api$WithDefaultGlobal$$scalaGlobal(Application.scala:383) ~[play_2.10.jar:2.1.0]
    at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1$$anonfun$apply$5.apply(Application.scala:52) ~[play_2.10.jar:2.1.0]
Caused by: java.lang.ExceptionInInitializerError: null
    at sun.misc.Unsafe.ensureClassInitialized(Native Method) ~[na:1.6.0_43]
    at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:25) ~[na:1.6.0_43]
    at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:122) ~[na:1.6.0_43]
    at java.lang.reflect.Field.acquireFieldAccessor(Field.java:918) ~[na:1.6.0_43]
    at java.lang.reflect.Field.getFieldAccessor(Field.java:899) ~[na:1.6.0_43]
    at java.lang.reflect.Field.get(Field.java:358) ~[na:1.6.0_43]
Caused by: java.lang.RuntimeException: There is no started application
    at scala.sys.package$.error(package.scala:27) ~[scala-library.jar:na]
    at play.api.Play$$anonfun$current$1.apply(Play.scala:46) ~[play_2.10.jar:2.1.0]
    at play.api.Play$$anonfun$current$1.apply(Play.scala:46) ~[play_2.10.jar:2.1.0]
    at scala.Option.getOrElse(Option.scala:120) ~[scala-library.jar:na]
    at play.api.Play$.current(Play.scala:46) ~[play_2.10.jar:2.1.0]
    at play.api.Play.current(Play.scala) ~[play_2.10.jar:2.1.0]

I'm guessing this is do to the circular nature of what is happening (the conf loads the Global object, the Global object loads the conf). Any ideas on a workaround? Thanks!

**Comment by gkazior** [comment]
A problem when you have:

object Global extends WithFilters(FilterWithConfig) with GlobalSettings {
}

And FilterWithConfig tries to read the application.conf.
One can possibly override onFilter.
