### ISSUE TITLE
Play not installing via sbt run

### ISSUE THREAD

**Issue by AppyCat** [playframework/playframework#9640]
When I generate a new seed java app via:

    sbt new playframework/play-java-seed.g8

Its fine. Once I run sbt run, I get the following errors:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#sbt-plugin;2.7.3: Resolution failed several times for dependency: com.typesafe.play#sbt-plugin;2.7.3 {compile=[default(compile)]}:: 
[warn] 	typesafe-ivy-releases: unable to get resource for com.typesafe.play#sbt-plugin;2.7.3: res=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.3/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	sbt-plugin-releases: unable to get resource for com.typesafe.play#sbt-plugin;2.7.3: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.3/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	:: org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: Resolution failed several times for dependency: org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0 {compile=[default(compile)]}:: 
[warn] 	typesafe-ivy-releases: unable to get resource for org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	sbt-plugin-releases: unable to get resource for org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.play:sbt-plugin:2.7.3 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		org.foundweekends.giter8:sbt-giter8-scaffold:0.11.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.play:sbt-plugin:2.7.3 (scalaVersion=2.12, sbtVersion=1.0) (/Users/laptop/Documents/www/java/play/play-java-seed/project/plugins.sbt#L2-3)
[warn] 		  +- default:play-java-seed-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn] 		org.foundweekends.giter8:sbt-giter8-scaffold:0.11.0 (scalaVersion=2.12, sbtVersion=1.0) (/Users/laptop/Documents/www/java/play/play-java-seed/project/plugins.sbt#L7-8)
[warn] 		  +- default:play-java-seed-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.play#sbt-plugin;2.7.3: Resolution failed several times for dependency: com.typesafe.play#sbt-plugin;2.7.3 {compile=[default(compile)]}:: 
[error] 	typesafe-ivy-releases: unable to get resource for com.typesafe.play#sbt-plugin;2.7.3: res=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.3/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for com.typesafe.play#sbt-plugin;2.7.3: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.3/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 
[error] unresolved dependency: org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: Resolution failed several times for dependency: org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0 {compile=[default(compile)]}:: 
[error] 	typesafe-ivy-releases: unable to get resource for org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvyActions$$$Lambda$2023/1369669580.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module$$Lambda$2024/534625665.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt$$Lambda$2025/1597181494.apply(Unknown Source)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2019/1442220461.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.util.Tracked$$$Lambda$1965/1179548193.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2021/1931069633.apply(Unknown Source)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$$$Lambda$2018/67918933.apply(Unknown Source)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.util.Tracked$$$Lambda$1919/1729096664.apply(Unknown Source)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error] 	at sbt.Classpaths$$$Lambda$1114/748316439.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$1003/2096598149.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$1839/771119702.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.Execute$$Lambda$1856/229234192.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.Execute$$Lambda$1847/1949709901.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$1854/798695894.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.play#sbt-plugin;2.7.3: Resolution failed several times for dependency: com.typesafe.play#sbt-plugin;2.7.3 {compile=[default(compile)]}:: 
[error] 	typesafe-ivy-releases: unable to get resource for com.typesafe.play#sbt-plugin;2.7.3: res=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.3/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for com.typesafe.play#sbt-plugin;2.7.3: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.3/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 
[error] unresolved dependency: org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: Resolution failed several times for dependency: org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0 {compile=[default(compile)]}:: 
[error] 	typesafe-ivy-releases: unable to get resource for org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: res=https://repo.typesafe.com/typesafe/ivy-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[error] 	sbt-plugin-releases: unable to get resource for org.foundweekends.giter8#sbt-giter8-scaffold;0.11.0: res=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.foundweekends.giter8/sbt-giter8-scaffold/scala_2.12/sbt_1.0/0.11.0/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by mkurz** [comment]
@AppyCat Is this still happening? I think this was just a temporary connection problem(?)

**Comment by AppyCat** [comment]
Thank you for checking in. I tried it again and its still giving the same problem, I’ll post some of the output below. Do you think perhaps doing dev in a Docker container might be a better path at the moment?

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#sbt-plugin;2.7.3: Resolution failed several times for dependency: com.typesafe.play#sbt-plugin;2.7.3 {compile=[default(compile)]}::
[warn] 	typesafe-ivy-releases: unable to get resource for com.typesafe.play#sbt-plugin;2.7.3: res=https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.3/ivys/ivy.xml: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by ignasi35** [comment]
@AppyCat I don't think native OS or Docker are the issue here. 

I suspect your `sbt` command is running on a non Java-8 JVM whith different SSL trusted CAs or settings causing the connection to bintray to fail the SSLHandshake.

Can you try again with a JVM version 1.8 or a Java 11 latest?

Thanks,

**Comment by ignasi35** [comment]
PS: please note the file causing the error _exists_ in bintray: https://bintray.com/playframework/sbt-plugin-releases/play-sbt-plugin#files/com.typesafe.play/sbt-plugin/scala_2.12/sbt_1.0/2.7.3/ivys

**Comment by AppyCat** [comment]
Hi, this is my java version info below. It seems to a cert issue and I am not so lear on which cert, where to get it and how and where to add it.

laptops-MacBook-Pro:~ laptop$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by ignasi35** [comment]
@AppyCat you JDK (1.8.0_25) is very old. Please update it to a newer jdk 1.8 since it'll upgrade the list of trusted certificates, supported cryptographic algorythms, etc...

**Comment by mkurz** [comment]
@AppyCat Did upgrading your JDK work?

**Comment by ignasi35** [comment]
hi @AppyCat, please don't use Java 13.

Consider moving away from OSX-provided JDK installers and using [jabba](https://github.com/shyiko/jabba#jabba--) to get a JDK8 installed and setup on you machine.

**Comment by ihostage** [comment]
@AppyCat @ignasi35 or [SDKMAN](https://sdkman.io/) 😄

**Comment by AppyCat** [comment]
Thank you Ignasio and Sergey, finally success with adopt@1.8.0-222  :)

Is there any particular version you would recommend? IAny real difference between Oracle JDK vs Open JDK?

Also what are your thoughts on Graal?

**Comment by marcospereira** [comment]
Hey @AppyCat,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

> Is there any particular version you would recommend? IAny real difference between Oracle JDK vs Open JDK?

We continually test with AdoptOpenJDK 8, and the master branch of Play is tested with AdoptOpenJDK 11 too.

> Also what are your thoughts on Graal?

It is exciting, and we have done some experiments, but right now is official support is not planned.
