### ISSUE TITLE
`scripted` failure on `sbt 0.13` in CRON builds

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9724]
See https://travis-ci.com/playframework/playframework/jobs/244428342#L322

This worked on jobs for `scripted` tests run on `sbt 1.x` but fails when running on `sbt 0.13`:

```
...
[info] Getting Scala 2.10.7 (for sbt)...
[info] downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ...
[info] 	[SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar (58ms)
[info] :: retrieving :: org.scala-sbt#boot-scala
[info] 	confs: [default]
[info] 	5 artifacts copied, 0 already retrieved (24560kB/47ms)
[info] Error during sbt execution: java.lang.NoClassDefFoundError: sbt/AttributeMap$
[error] java.lang.NoClassDefFoundError: sbt/AttributeMap$
[error] 	at sbt.Command$.make(Command.scala:34)
[error] 	at sbt.Command$.command(Command.scala:30)
[error] 	at sbt.BuiltinCommands$.defaults(Main.scala:223)
[error] 	at sbt.xMain.run(Main.scala:33)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.ClassNotFoundException: sbt.AttributeMap$
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	... 13 more
[error] x play-sbt-plugin / akka-fork-join-pool
[error]    {line 1}  Command failed: Remote sbt initialization failed
Running play-sbt-plugin / basic-service
[error] java.lang.NoClassDefFoundError: sbt/AttributeMap$
[error] 	at sbt.Command$.make(Command.scala:34)
[error] 	at sbt.Command$.command(Command.scala:30)
[error] 	at sbt.BuiltinCommands$.defaults(Main.scala:223)
[error] 	at sbt.xMain.run(Main.scala:33)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.ClassNotFoundException: sbt.AttributeMap$
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	... 13 more
[info] Error during sbt execution: java.lang.NoClassDefFoundError: sbt/AttributeMap$
[error] x play-sbt-plugin / basic-service
[error]    {line 2}  Command failed: Remote sbt initialization failed
Running play-sbt-plugin / basic-service-with-routes-file
[error] java.lang.NoClassDefFoundError: sbt/AttributeMap$
[error] 	at sbt.Command$.make(Command.scala:34)
[error] 	at sbt.Command$.command(Command.scala:30)
[error] 	at sbt.BuiltinCommands$.defaults(Main.scala:223)
[error] 	at sbt.xMain.run(Main.scala:33)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
...
```

I can't reproduce that error locally. I tried using:

`$ TRAVIS_EVENT_TYPE=cron sbt -Dakka.version=2.6-20191010-210113 -Dakka.http.version=10.1.10+15-4a5c3c79 ++2.10.7 "Sbt-Plugin/scripted play-sbt-plugin/*1of3"`

_Originally posted by @ignasi35 in https://github.com/playframework/playframework/pull/9717#issuecomment-540993583_

**Comment by ignasi35** [comment]
Hasn't reproduced in latest builds
