### ISSUE TITLE
[2.7.4] Regression using SSL in Java 11

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9896]
Both [Play `2.7.3`](https://github.com/playframework/playframework/blob/2.7.3/project/Dependencies.scala) and [Play `2.7.4`](https://github.com/playframework/playframework/blob/2.7.4/project/Dependencies.scala) explictly depend on `"com.typesafe" %% "ssl-config-core" % "0.3.8"` but in Play `2.7.3` there probably was a transitive dependency to `"ssl-config-core" % "0.4.0"`.

The workaround is to explicitly depend on `"com.typesafe" %% "ssl-config-core" % "0.3.8"`.

<details>
<summary>Sample StackTrace</summary>

```
...
[info] integration.ServerSpec *** ABORTED ***
[info]   java.lang.IllegalStateException: InternalDebug configuration error
[info]   at com.typesafe.sslconfig.ssl.debug.FixInternalDebugLogging.apply(FixInternalDebugLogging.scala:89)
[info]   at com.typesafe.sslconfig.ssl.debug.DebugConfiguration.configureJavaxNetDebug(DebugConfiguration.scala:22)
[info]   at com.typesafe.sslconfig.ssl.debug.DebugConfiguration.configure(DebugConfiguration.scala:15)
[info]   at play.api.libs.ws.ahc.StandaloneAhcWSClient$.apply(StandaloneAhcWSClient.scala:216)
[info]   at play.api.libs.ws.ahc.AhcWSClient$.apply(AhcWSClient.scala:69)
[info]   at integration.ServerSpec.<init>(ServerSpec.scala:29)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[info]   ...
[info]   Cause: java.security.PrivilegedActionException:
[info]   at java.base/java.security.AccessController.doPrivileged(Native Method)
[info]   at com.typesafe.sslconfig.ssl.debug.FixInternalDebugLogging.apply(FixInternalDebugLogging.scala:86)
[info]   at com.typesafe.sslconfig.ssl.debug.DebugConfiguration.configureJavaxNetDebug(DebugConfiguration.scala:22)
[info]   at com.typesafe.sslconfig.ssl.debug.DebugConfiguration.configure(DebugConfiguration.scala:15)
[info]   at play.api.libs.ws.ahc.StandaloneAhcWSClient$.apply(StandaloneAhcWSClient.scala:216)
[info]   at play.api.libs.ws.ahc.AhcWSClient$.apply(AhcWSClient.scala:69)
[info]   at integration.ServerSpec.<init>(ServerSpec.scala:29)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: sun.security.ssl.Debug
[info]   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[info]   at sbt.internal.ManagedClassLoader.findClass(LayeredClassLoaders.scala:376)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[info]   at com.typesafe.sslconfig.ssl.debug.FixInternalDebugLogging$MonkeyPatchInternalSslDebugAction.run(FixInternalDebugLogging.scala:50)
[info]   at com.typesafe.sslconfig.ssl.debug.FixInternalDebugLogging$MonkeyPatchInternalSslDebugAction.run(FixInternalDebugLogging.scala:20)
[info]   at java.base/java.security.AccessController.doPrivileged(Native Method)
[info]   at com.typesafe.sslconfig.ssl.debug.FixInternalDebugLogging.apply(FixInternalDebugLogging.scala:86)
[info]   at com.typesafe.sslconfig.ssl.debug.DebugConfiguration.configureJavaxNetDebug(DebugConfiguration.scala:22)
[info]   at com.typesafe.sslconfig.ssl.debug.DebugConfiguration.configure(DebugConfiguration.scala:15)
[info]   ...
```

</details>

**Comment by mkurz** [comment]
Play 2.7 is EOL and this is not an issue in Play 2.8
