### ISSUE TITLE
Specifying a custom config.resource causes a "resource not found on classpath" in Play 2.8

### ISSUE THREAD

**Issue by henricook** [playframework/playframework#9972]
### Play Version

2.8.0

### API

Scala

### Operating System

Linux bob 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### JDK

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit GraalVM EE 19.1.1 (build 25.221-b11-jvmci-19.1-b01, mixed mode)

### Library Dependencies

N/A

### Expected Behavior

1. I have a file `test.conf` in my `conf/` folder, next to application.conf
2. I specify `-Dconfig.resource=test.conf` when running SBT
3. The application uses `test.conf`

### Actual Behavior

1. I have a file `test.conf` in my `conf/` folder, next to application.conf
2. I specify `-Dconfig.resource=test.conf` when running SBT
3. **The application errors saying test.conf cannot be found on the classpath**

I strongly suspect this to be the cause but would like a second opinion, maybe from @dwijnand ?: https://github.com/playframework/playframework/commit/1b69712bb4df23f7dd6b194e06dbc3c96c2617ed#diff-9c80b5c4ff3925eebc1aa4fab735f97fL73

### Reproducible Test Case

Clone: https://github.com/henricook/play-2.8-bug-config-resource
**Additional information is in the README**

See the regression:
-  `cd play-scala-seed`
- `ls conf` (observe 'test.conf' exists)
- `sbt -Dsbt.version=1.3.5 -Dconfig.resource=test.conf clean run` (observe error)

-----

See it working on 2.7.x:
- `cd ../play-scala-seed-2.7.x`
- `ls conf` (observe 'test.conf' exists)
- `sbt -Dsbt.version=1.3.5 -Dconfig.resource=test.conf clean run` (observe successful start that proves regression)

`sbt.version` included only to ensure a level playing field for this test

### Error dump

```
[error] Configuration error: Configuration error[test.conf: java.io.IOException: resource not found on classpath: test.conf]
[error]         at play.api.Configuration$.configError(Configuration.scala:138)
[error]         at play.api.Configuration$.load(Configuration.scala:81)
[error]         at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:230)
[error]         at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error]         at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:75)
[error]         at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:49)
[error]         at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error]         at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error]         at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] Caused by: com.typesafe.config.ConfigException$IO: test.conf: java.io.IOException: resource not found on classpath: test.conf
[error]         at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:190)
[error]         at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error]         at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
[error]         at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:1058)
[error]         at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:986)
[error]         at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
[error]         at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:529)
[error]         at play.api.Configuration$.load(Configuration.scala:58)
[error]         at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:230)
[error]         at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error]         at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:75)
[error]         at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:49)
[error]         at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error]         at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error]         at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] Caused by: java.io.IOException: resource not found on classpath: test.conf
[error]         at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:726)
[error]         at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:701)
[error]         at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
[error]         at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
[error]         at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
[error]         at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:1058)
[error]         at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:986)
[error]         at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
[error]         at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:529)
[error]         at play.api.Configuration$.load(Configuration.scala:58)
[error]         at play.core.server.DevServerStart$.$anonfun$mainDev$1(DevServerStart.scala:230)
[error]         at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error]         at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:75)
[error]         at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:49)
[error]         at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error]         at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error]         at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.reflect.InvocationTargetException
```

**Comment by dwijnand** [comment]
The ability to redefine the classpath resource to use as the config is built into the config library, so that diff shouldn't impacted this.  But clearly something's up, so I'll triage this today or tomorrow.

**Comment by henricook** [comment]
Thanks @dwijnand  - i thought it might have something to do with this removed `parseResources`:
```scala
{
          setting("config.resource").map(resource => ConfigFactory.parseResources(classLoader, resource.toString))
        }.orElse {
```

But as i say, just a guess

Thanks again

**Comment by dwijnand** [comment]
Fixed in #9978.  Coming in 2.8.1.

**Comment by SJern** [comment]
Is there any way for me to stick with 2.8.0 and being able to specify an alternate config file?
2.8.1 would force me to jump to 2.6.3 - https://github.com/playframework/playframework/milestone/101?closed=1
but the Akka migration guide also states that
`Due to the changed serialization of the Cluster messages in Akka 2.6.2 a rolling update from 2.5.x must first be made to Akka 2.6.2 and then a second rolling update can change to Akka 2.6.3 or later.`
https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html

**Comment by mkurz** [comment]
@SJern Your comment is not related to this issue.
Anyway, I don't think its possible to stick with akka 2.5.x when using Play 2.8.x because I guess from akka 2.5.x to 2.6.x there were api changes which Play makes use of.
