### ISSUE TITLE
JNA error running ~run

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#9999]
### Play Version

A build off of the 2.8.x branch, current HEAD is da4a19d69e8c45a0163fe34df1e6528e52d6eed9.

### Operating System

macOS

### JDK

```
java version "1.8.0_202-ea"
Java(TM) SE Runtime Environment (build 1.8.0_202-ea-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b03, mixed mode)
```

### Library Dependencies

sbt 1.3.6

### Expected Behavior

1. Running `~run`
2. the server is started
3. the code is compiled
4. file watching is started

### Actual Behavior

The execution of the `Compile / run` task fails with:

```
[error] java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
[error] 	at io.methvin.watchservice.jna.CarbonAPI.<clinit>(CarbonAPI.java:19)
[error] 	at io.methvin.watchservice.jna.CFStringRef.toCFString(CFStringRef.java:23)
[error] 	at io.methvin.watchservice.MacOSXListeningWatchService.register(MacOSXListeningWatchService.java:128)
[error] 	at io.methvin.watchservice.WatchablePath.register(WatchablePath.java:50)
[error] 	at io.methvin.watcher.DirectoryWatcher.register(DirectoryWatcher.java:341)
[error] 	at io.methvin.watcher.DirectoryWatcher.registerAll(DirectoryWatcher.java:315)
[error] 	at io.methvin.watcher.DirectoryWatcher.<init>(DirectoryWatcher.java:176)
[error] 	at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:117)
[error] 	at play.dev.filewatch.DefaultFileWatchService.watch(DefaultFileWatchService.scala:38)
[error] 	at play.dev.filewatch.FileWatchService$$anon$1.watch(FileWatchService.scala:87)
[error] 	at play.runsupport.Reloader.<init>(Reloader.scala:443)
[error] 	at play.runsupport.Reloader$.reloader$lzycompute$1(Reloader.scala:283)
[error] 	at play.runsupport.Reloader$.play$runsupport$Reloader$$reloader$1(Reloader.scala:275)
[error] 	at play.runsupport.Reloader$.startDevMode(Reloader.scala:306)
[error] 	at play.sbt.run.PlayRun$.devModeServer$lzycompute$1(PlayRun.scala:98)
[error] 	at play.sbt.run.PlayRun$.devModeServer$1(PlayRun.scala:81)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:105)
[error] 	at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
```

### Reproducible Test Case

1. `publishLocal` Play 2.8.x
2. Take https://github.com/playframework/play-samples/tree/2.8.x/play-scala-hello-world-tutorial (current HEAD https://github.com/playframework/play-samples/commit/da4a19d69e8c45a0163fe34df1e6528e52d6eed9)
3. Update Play to the published version
4. Optional: Update sbt from 1.3.4 to 1.3.6
5. start `sbt`
6. run `~run`

**Comment by dwijnand** [comment]
The problem is that sbt/io uses JNA 4.5.0: https://github.com/sbt/io/blob/v1.3.1/project/Dependencies.scala#L12

So Directory Watcher needs to use JNA 4.x's API, not JNA 5.x API.
